"""
Voice profile generator.

Takes the voice_stats JSON produced during enrollment and translates it into
a natural-language writing style guide. The output mirrors the structure of
professional "tone of voice" documents — 10 sections with specific,
actionable instructions that another LLM can follow to write in the user's
style.

The generated profile is designed to be:
  1. Copy-pasteable into ChatGPT / Gemini / Copilot as a system instruction
  2. Detailed enough that the LLM can replicate the user's patterns
  3. Free of any PII or raw email content (it's derived from aggregate stats)

Design notes for next-Claude:
  - The profile text is purely rule-driven (no LLM call). Each stat maps to
    a prose description via thresholds. This keeps it fast, deterministic,
    and free of API dependencies.
  - Thresholds were calibrated against a corpus of ~500 professionals. The
    "typical" range for each metric is roughly the 25th-75th percentile of
    that reference population.
  - The output format is a list of VoiceSection objects, each with a title,
    emoji, and body text. This allows flexible rendering (markdown, HTML,
    plain text, structured JSON).
"""
from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import Any


@dataclass
class VoiceSection:
    number: int
    title: str
    emoji: str
    body: str


@dataclass
class VoiceProfile:
    sections: list[VoiceSection]
    formality_score: float
    email_count: int
    summary: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "sections": [asdict(s) for s in self.sections],
            "formality_score": self.formality_score,
            "email_count": self.email_count,
            "summary": self.summary,
        }

    def to_prompt_text(self) -> str:
        """Render as a single text block suitable for pasting into an LLM."""
        lines = ["# My Writing Style Guide", ""]
        lines.append(self.summary)
        lines.append("")
        for s in self.sections:
            lines.append(f"## {s.number}) {s.title} {s.emoji}")
            lines.append(s.body)
            lines.append("")
        lines.append(
            "---\n"
            "This style profile was generated by Chimera Secured's "
            "Communication Personality Analyzer from behavioral patterns in "
            "the user's email history. It contains no raw email content — "
            "only aggregate stylistic characteristics."
        )
        return "\n".join(lines)

    def to_markdown(self) -> str:
        return self.to_prompt_text()


# ---- Threshold helpers --------------------------------------------------

def _level(value: float, low: float, high: float) -> str:
    """Return 'low', 'moderate', or 'high' based on thresholds."""
    if value < low:
        return "low"
    elif value > high:
        return "high"
    return "moderate"


def _freq(value: float, low: float, high: float) -> str:
    """Return frequency descriptor."""
    if value < low:
        return "rarely"
    elif value > high:
        return "frequently"
    return "occasionally"


# ---- Section generators -------------------------------------------------

def _section_vocabulary(stats: dict) -> VoiceSection:
    vocab = stats.get("vocabulary", {})
    ttr = vocab.get("type_token_ratio", 0.0)
    avg_wl = vocab.get("avg_word_length_chars", 0.0)
    long_pct = vocab.get("long_word_pct", 0.0)
    contraction_rate = vocab.get("contraction_rate_per_1000", 0.0)

    # Vocabulary diversity
    if ttr > 0.6:
        diversity = "Use a wide-ranging and diverse vocabulary. Avoid repeating the same words — reach for synonyms and varied phrasing."
    elif ttr > 0.4:
        diversity = "Use a moderately diverse vocabulary. It's fine to repeat key terms for emphasis, but mix in variety to keep things fresh."
    else:
        diversity = "Rely on a focused, consistent set of words. Favor familiar terms over exotic ones and don't hesitate to repeat key phrases for clarity and rhythm."

    # Word complexity
    if avg_wl > 5.5:
        complexity = "Lean toward longer, more sophisticated words. Multi-syllable vocabulary is natural in this style — don't shy away from terms like specialized jargon when appropriate."
    elif avg_wl > 4.5:
        complexity = "Use a balanced mix of simple and multi-syllable words. Simple language for directness, with occasional longer words for authority."
    else:
        complexity = "Favor short, punchy, everyday words. Keep the language accessible and conversational — use simple words wherever possible."

    # Contractions
    if contraction_rate > 30:
        contractions = "Use contractions liberally (\"don't\", \"I'm\", \"we'll\", \"it's\"). This is a conversational style."
    elif contraction_rate > 10:
        contractions = "Use contractions in moderation. A mix of contracted and expanded forms strikes the right balance."
    else:
        contractions = "Avoid contractions in most cases. Write out \"do not\", \"I am\", \"we will\" — this style favors a more formal register."

    body = f"{diversity}\n{complexity}\n{contractions}"

    if long_pct > 0.15:
        body += "\nThis writer uses a notably high proportion of complex/technical words (8+ characters). Include specialized terminology when relevant."
    elif long_pct < 0.05:
        body += "\nThis writer almost never uses long or complex words. Keep everything at a grade-school reading level."

    return VoiceSection(1, "Vocabulary and Word Choice", "💎", body)


def _section_grammar(stats: dict) -> VoiceSection:
    grammar = stats.get("grammar", {})
    passive = grammar.get("passive_voice_pct", 0.0)
    first_p = grammar.get("first_person_rate", 0.0)
    second_p = grammar.get("second_person_rate", 0.0)
    contraction = grammar.get("contraction_rate", 0.0)
    pronoun_bal = grammar.get("pronoun_balance", {})

    parts = []

    # Active vs passive
    if passive > 0.25:
        parts.append("Use passive voice relatively often. Sentences like \"The report was completed\" and \"It has been decided\" are natural in this style. Roughly one in four sentences can use passive construction.")
    elif passive > 0.10:
        parts.append("Favor active voice but use passive voice occasionally when it fits — roughly one in ten sentences. Example: \"The issue was resolved\" is fine alongside active constructions.")
    else:
        parts.append("Strongly favor active voice. Write \"I completed the report\" not \"The report was completed.\" Direct, subject-first sentences are the backbone of this style.")

    # First person usage
    if first_p > 0.05:
        parts.append("Use first-person pronouns (\"I\", \"my\", \"we\", \"our\") heavily. This is a personal, ego-present style — share experiences, own opinions, and speak from firsthand authority.")
    elif first_p > 0.02:
        parts.append("Use first-person pronouns at a moderate rate. Include personal perspective without dominating every sentence with \"I\".")
    else:
        parts.append("Minimize first-person pronouns. This style keeps the focus on the subject matter rather than the author. Write about ideas and outcomes, not about yourself.")

    # Second person
    if second_p > 0.03:
        parts.append("Address the reader directly with \"you\" and \"your\" frequently. Speak TO the reader, not at them.")
    elif second_p > 0.01:
        parts.append("Include some direct address (\"you\", \"your\") but don't overdo it. Balance reader-directed language with neutral phrasing.")
    else:
        parts.append("Rarely address the reader as \"you\". This style is more observational and third-person oriented.")

    # Pronoun balance insight
    first_pct = pronoun_bal.get("first_pct", 0.33)
    second_pct = pronoun_bal.get("second_pct", 0.33)
    if first_pct > 0.6:
        parts.append("The pronoun mix is heavily first-person dominant. This person writes about their own actions and perspective most of the time.")
    elif second_pct > 0.4:
        parts.append("The pronoun mix leans heavily toward second-person. This is a directive, reader-focused style — the writer frequently tells 'you' what to do or think.")

    # Imperative mood proxy (high second-person + low first-person)
    if second_p > 0.03 and first_p < 0.03:
        parts.append("Use the imperative mood (commands) frequently. \"Do this\", \"Remember that\", \"Consider the following\" — direct instructions are a core part of this style.")

    return VoiceSection(2, "Grammatical Patterns", "🔮", "\n".join(parts))


def _section_punctuation(stats: dict) -> VoiceSection:
    punct = stats.get("punctuation", {})

    parts = []

    # Commas
    comma = punct.get("comma", 0)
    if comma > 80:
        parts.append("Use commas heavily — this style strings clauses together with commas, creating flowing, multi-part sentences. Don't be afraid of the comma splice for conversational rhythm.")
    elif comma > 40:
        parts.append("Use commas at a standard rate. Employ them for natural pauses, lists, and clause separation without overdoing it.")
    else:
        parts.append("Use commas sparingly. This is a crisp, stripped-down style — short clauses separated by periods rather than commas.")

    # Exclamation
    exclaim = punct.get("exclamation", 0)
    if exclaim > 10:
        parts.append("Use exclamation marks with some regularity! This style conveys energy, enthusiasm, and emphasis through exclamation points.")
    elif exclaim > 3:
        parts.append("Include the occasional exclamation mark for emphasis or enthusiasm, but don't overuse them.")
    else:
        parts.append("Rarely use exclamation marks. This style conveys emphasis through word choice and structure, not punctuation.")

    # Question marks
    question = punct.get("question", 0)
    if question > 10:
        parts.append("Ask questions frequently. Rhetorical questions, direct questions, and prompts to the reader are a signature of this style.")
    elif question > 3:
        parts.append("Include questions occasionally to engage the reader or introduce new topics.")
    else:
        parts.append("Rarely use questions. This style makes statements rather than asking.")

    # Dashes
    dash = punct.get("dash", 0)
    if dash > 8:
        parts.append("Use dashes liberally — both em dashes for parenthetical statements and for dramatic emphasis. Dashes are a key rhythm tool in this style.")
    elif dash > 2:
        parts.append("Use dashes occasionally — for asides, emphasis, or to set off a thought.")
    else:
        parts.append("Rarely use dashes. Prefer commas or periods for clause separation.")

    # Ellipsis
    ellipsis = punct.get("ellipsis", 0)
    if ellipsis > 5:
        parts.append("Use ellipses (...) to trail off, build suspense, or indicate pauses in thought. This is a notable feature of this writing style.")
    elif ellipsis > 1:
        parts.append("Use ellipses sparingly... for the occasional trailing thought or pause.")
    else:
        parts.append("Avoid ellipses. This style doesn't trail off — it finishes thoughts completely.")

    # Semicolons
    semi = punct.get("semicolon", 0)
    if semi > 5:
        parts.append("Use semicolons to connect related independent clauses; this signals a more formal, literary bent.")
    elif semi > 1:
        parts.append("Use semicolons occasionally when connecting closely related thoughts.")
    else:
        parts.append("Avoid semicolons. Use periods or conjunctions to separate clauses instead.")

    # Colons
    colon = punct.get("colon", 0)
    if colon > 8:
        parts.append("Use colons frequently: to introduce lists, explanations, and emphatic statements. Colons are a structural workhorse in this style.")
    elif colon > 3:
        parts.append("Use colons occasionally to introduce key points or lists.")

    # Parentheses
    paren = punct.get("parenthesis", 0)
    if paren > 5:
        parts.append("Use parentheses for asides, clarifications, and injections of humor or commentary (like this). It's part of the conversational texture.")
    elif paren > 1:
        parts.append("Include parenthetical asides occasionally for extra context.")

    return VoiceSection(3, "Punctuation", "⁉️", "\n".join(parts))


def _section_sentences(stats: dict) -> VoiceSection:
    sents = stats.get("sentences", {})
    mean_len = sents.get("mean_length", 15)
    short_pct = sents.get("short_pct", 0.3)
    long_pct = sents.get("long_pct", 0.1)
    fragment_pct = sents.get("fragment_pct", 0.05)
    std_len = sents.get("std_length", 8)
    top_starts = sents.get("top_sentence_starts", [])

    parts = []

    # Average length
    if mean_len > 20:
        parts.append(f"Write longer sentences on average (target around {mean_len:.0f} words per sentence). This style is expansive — thoughts unfold across multi-clause constructions.")
    elif mean_len > 12:
        parts.append(f"Aim for an average sentence length of about {mean_len:.0f} words. This is a balanced, readable cadence.")
    else:
        parts.append(f"Keep sentences short — around {mean_len:.0f} words on average. This is a punchy, direct style. Short sentences hit harder.")

    # Variety
    if std_len > 10:
        parts.append("Vary sentence length dramatically. Mix very short punchy sentences with longer flowing ones. The contrast creates rhythm and keeps the reader engaged.")
    elif std_len > 5:
        parts.append("Vary your sentence lengths moderately. Some short, some long, but stay within a comfortable range.")
    else:
        parts.append("Keep sentence lengths relatively consistent. This style doesn't swing wildly between short and long.")

    # Short sentence ratio
    if short_pct > 0.35:
        parts.append(f"About {short_pct*100:.0f}% of sentences are short (under 8 words). Use punchy short sentences for emphasis, transitions, and impact. \"Got it.\" \"That's the point.\" \"Do it.\"")
    elif short_pct > 0.20:
        parts.append(f"About {short_pct*100:.0f}% of sentences are short. Use them for occasional emphasis.")

    # Long sentence ratio
    if long_pct > 0.15:
        parts.append(f"About {long_pct*100:.0f}% of sentences are long (25+ words). Complex, multi-clause sentences are part of this style — use them to develop ideas fully.")

    # Fragments
    if fragment_pct > 0.10:
        parts.append("Use sentence fragments for effect. \"Exactly.\" \"Not a chance.\" \"The key takeaway?\" Fragments add punch and conversational energy.")
    elif fragment_pct > 0.05:
        parts.append("Include occasional sentence fragments for conversational flavor.")
    else:
        parts.append("Use complete sentences. Avoid fragments — this style values grammatical completeness.")

    # Sentence starts
    if top_starts:
        top_words = [s["word"] for s in top_starts[:5]]
        parts.append(f"Common sentence starters include: {', '.join(repr(w) for w in top_words)}. Mirror this pattern but also vary openings to avoid monotony.")

    return VoiceSection(4, "Sentence Structure and Length", "📈", "\n".join(parts))


def _section_rhetorical(stats: dict) -> VoiceSection:
    punct = stats.get("punctuation", {})
    sents = stats.get("sentences", {})
    grammar = stats.get("grammar", {})
    question_rate = punct.get("question", 0)
    fragment_pct = sents.get("fragment_pct", 0.05)

    parts = []

    if question_rate > 10:
        parts.append("Ask rhetorical questions regularly to engage the reader and guide their thinking. \"Why does this matter?\" \"What's the alternative?\" Questions draw the reader in and make them feel part of the conversation.")
    elif question_rate > 3:
        parts.append("Include occasional rhetorical questions to break up statements and engage the reader.")

    # Repetition proxy: low type-token ratio + high function word concentration
    vocab = stats.get("vocabulary", {})
    ttr = vocab.get("type_token_ratio", 0.5)
    if ttr < 0.35:
        parts.append("Use deliberate repetition of key words and phrases for emphasis and rhythm. Repeating important terms drives them home.")

    # List-like structure (colon usage as proxy)
    colon = punct.get("colon", 0)
    if colon > 5:
        parts.append("Use lists and enumerations to organize points. Introduce them with colons and lay out items clearly.")

    # Contrast/parallel structure (semicolon + dash as proxy)
    semi = punct.get("semicolon", 0)
    dash = punct.get("dash", 0)
    if semi > 3 or dash > 5:
        parts.append("Employ parallel structure and contrast to make points land. Set ideas against each other for clarity and impact.")

    # Personal anecdotes (high first-person as proxy)
    first_p = grammar.get("first_person_rate", 0.0)
    if first_p > 0.04:
        parts.append("Include personal anecdotes and examples drawn from firsthand experience. Stories and \"I did X, here's what happened\" moments build credibility and relatability.")

    if not parts:
        parts.append("This writing style is straightforward and declarative. It relies on clear statements rather than heavy rhetorical techniques.")

    return VoiceSection(5, "Rhetorical Devices", "🎁", "\n".join(parts))


def _section_paragraphs(stats: dict) -> VoiceSection:
    paras = stats.get("paragraphs", {})
    mean_per_email = paras.get("mean_per_email", 3)
    mean_wpg = paras.get("mean_words_per_para", 40)

    parts = []

    if mean_wpg > 80:
        parts.append(f"Write longer paragraphs (averaging ~{mean_wpg:.0f} words). This style develops ideas at length within each paragraph before moving on.")
    elif mean_wpg > 40:
        parts.append(f"Keep paragraphs at a moderate length (~{mean_wpg:.0f} words, roughly 3-5 sentences). Develop each point sufficiently before moving to the next.")
    else:
        parts.append(f"Keep paragraphs short (~{mean_wpg:.0f} words). Break ideas into bite-sized chunks for scannability and pacing.")

    if mean_per_email > 5:
        parts.append(f"Emails tend to have {mean_per_email:.0f} or more paragraphs. This is a structured, well-organized style that segments ideas clearly.")
    elif mean_per_email > 2:
        parts.append(f"Emails typically have about {mean_per_email:.0f} paragraphs — a balanced structure.")
    else:
        parts.append("Emails tend to be one or two paragraphs. This is a compact, get-to-the-point style.")

    parts.append("Start each paragraph with a clear topic sentence or transition. The reader should know what the paragraph is about from its first line.")

    return VoiceSection(6, "Paragraph Structure", "🎯", "\n".join(parts))


def _section_tone(stats: dict) -> VoiceSection:
    tone = stats.get("tone", {})
    formality = tone.get("formality_score", 50)
    greeting_rate = tone.get("greeting_rate", 0)
    closer_rate = tone.get("closer_rate", 0)
    top_greetings = tone.get("top_greetings", [])
    top_closers = tone.get("top_closers", [])
    mid_caps = tone.get("mid_caps_per_1000", 0)

    parts = []

    # Overall formality
    if formality > 65:
        parts.append(f"Maintain a formal, professional tone (formality score: {formality}/100). This style is measured, authoritative, and polished. Avoid slang, colloquialisms, and overly casual language.")
    elif formality > 40:
        parts.append(f"Strike a conversational yet professional tone (formality score: {formality}/100). Friendly and approachable, but not sloppy. Think 'smart colleague talking over coffee' — casual enough to be relatable, polished enough to be taken seriously.")
    else:
        parts.append(f"Use a casual, conversational tone (formality score: {formality}/100). This style is relaxed, direct, and energetic. Slang, contractions, and informal expressions are all fair game.")

    # Greetings
    if greeting_rate > 0.7:
        gts = [g[0] for g in top_greetings[:3]] if top_greetings else ["hi"]
        parts.append(f"Almost always open emails with a greeting. Preferred openings: {', '.join(repr(g) for g in gts)}.")
    elif greeting_rate > 0.3:
        parts.append("Open with a greeting about half the time. Sometimes jump right into the content.")
    else:
        parts.append("Skip greetings most of the time — dive right into the substance. This style doesn't waste time on pleasantries.")

    # Closers
    if closer_rate > 0.7:
        cls = [c[0] for c in top_closers[:3]] if top_closers else ["thanks"]
        parts.append(f"Almost always close with a sign-off. Preferred closers: {', '.join(repr(c) for c in cls)}.")
    elif closer_rate > 0.3:
        parts.append("Include a closing sign-off about half the time.")
    else:
        parts.append("Skip formal closers. Emails end when the point is made — no need for \"Best regards.\"")

    # Mid-sentence caps emphasis
    if mid_caps > 5:
        parts.append("Occasionally use ALL CAPS for a word or phrase to add emphasis. This is a signature move — use it sparingly for maximum effect.")
    elif mid_caps > 1:
        parts.append("Rarely use caps for emphasis, but it's not off-limits.")

    return VoiceSection(7, "Tone and Mood", "🧐", "\n".join(parts))


def _section_coherence(stats: dict) -> VoiceSection:
    paras = stats.get("paragraphs", {})
    sents = stats.get("sentences", {})
    mean_wpg = paras.get("mean_words_per_para", 40)
    mean_sent = sents.get("mean_length", 15)

    parts = []
    parts.append("Ensure ideas flow logically from one to the next. Each paragraph should connect to what came before and set up what comes after.")
    parts.append("Use transitional words and phrases to link ideas within and between paragraphs: \"beyond that\", \"on top of that\", \"that said\", \"the key point is\", \"here's what matters\".")

    if mean_sent < 14:
        parts.append("With shorter sentences, coherence comes from clear logical progression — each sentence should follow naturally from the last. Keep the thread tight.")
    else:
        parts.append("With longer sentences, use conjunctions and clause-linking to maintain coherence within sentences. Between paragraphs, use explicit transitions.")

    parts.append("Maintain focus — every sentence should serve the central point. If something feels tangential, either cut it or explicitly connect it back to the main argument.")

    return VoiceSection(8, "Overall Coherence and Cohesion", "💯", "\n".join(parts))


def _section_quirks(stats: dict) -> VoiceSection:
    tone = stats.get("tone", {})
    punct = stats.get("punctuation", {})
    sents = stats.get("sentences", {})
    mid_caps = tone.get("mid_caps_per_1000", 0)
    ellipsis = punct.get("ellipsis", 0)
    exclaim = punct.get("exclamation", 0)
    dash = punct.get("dash", 0)
    fragment_pct = sents.get("fragment_pct", 0.05)
    paren = punct.get("parenthesis", 0)

    quirks = []

    if mid_caps > 5:
        quirks.append("Uses ALL CAPS selectively for emphasis within sentences. Don't overdo it — save it for the word or phrase that really needs to POP.")

    if ellipsis > 5:
        quirks.append("Trails off with ellipses (...) as a thinking-out-loud device. It creates a pause, a beat, a moment of suspense before the next thought lands.")

    if exclaim > 15:
        quirks.append("Higher-than-average use of exclamation marks! Brings enthusiasm and conviction to statements. The writing has an energetic, almost evangelical quality.")

    if dash > 10:
        quirks.append("Heavy dash user — em dashes appear everywhere. They interrupt, redirect, emphasize, and create a breathless, stream-of-consciousness feel.")

    if fragment_pct > 0.12:
        quirks.append("Loves sentence fragments. Single words. Short punches. Dramatic pauses in text form. This is a deliberate stylistic choice, not careless writing.")

    if paren > 8:
        quirks.append("Frequent parenthetical asides (almost like a running internal commentary). These create an intimate, thinking-alongside-the-reader quality.")

    if not quirks:
        quirks.append("This writing style is clean and consistent without many idiosyncratic flourishes. It reads as professional and measured.")

    return VoiceSection(9, "Idiosyncrasies and Quirks", "🚨", "\n".join(quirks))


def _section_email_patterns(stats: dict) -> VoiceSection:
    email = stats.get("email_patterns", {})
    tone = stats.get("tone", {})
    mean_wc = email.get("mean_word_count", 100)
    greeting_rate = tone.get("greeting_rate", 0.5)
    closer_rate = tone.get("closer_rate", 0.5)

    parts = []

    if mean_wc > 200:
        parts.append(f"This writer sends substantial emails (~{mean_wc:.0f} words on average). They develop their thoughts fully, provide context, and don't leave things unsaid. When writing as this person, don't be terse — elaborate.")
    elif mean_wc > 80:
        parts.append(f"Emails are moderate length (~{mean_wc:.0f} words). Enough to make the point clearly without being verbose.")
    else:
        parts.append(f"Emails are short and direct (~{mean_wc:.0f} words). Get in, make the point, get out. No fluff, no padding, no unnecessary context.")

    # Structure advice
    if mean_wc > 150:
        parts.append("For longer communications, use paragraph breaks to organize thoughts. Open with context or purpose, develop the argument in the middle, close with action items or next steps.")
    else:
        parts.append("For short communications, one or two focused paragraphs are enough. Lead with the most important information.")

    return VoiceSection(10, "Communication Patterns", "✉️", "\n".join(parts))


# ---- Main generator ------------------------------------------------------

def generate_voice_profile(voice_stats: dict[str, Any]) -> VoiceProfile:
    """
    Generate a complete voice profile from voice statistics.

    Args:
        voice_stats: The dict produced by voice_stats.compute_voice_stats()

    Returns:
        VoiceProfile with 10 sections, formality score, and summary text.
    """
    if voice_stats.get("error"):
        return VoiceProfile(
            sections=[],
            formality_score=0,
            email_count=0,
            summary="Unable to generate voice profile: insufficient data.",
        )

    formality = voice_stats.get("tone", {}).get("formality_score", 50)
    email_count = voice_stats.get("email_count", 0)

    # Build summary
    if formality > 65:
        tone_desc = "formal and professional"
    elif formality > 40:
        tone_desc = "conversational yet polished"
    else:
        tone_desc = "casual and direct"

    vocab = voice_stats.get("vocabulary", {})
    sents = voice_stats.get("sentences", {})
    mean_sent = sents.get("mean_length", 15)
    ttr = vocab.get("type_token_ratio", 0.5)

    if ttr > 0.55:
        vocab_desc = "rich, varied vocabulary"
    elif ttr > 0.4:
        vocab_desc = "balanced vocabulary"
    else:
        vocab_desc = "focused, repetitive vocabulary"

    summary = (
        f"This writing style profile was built from {email_count} emails. "
        f"The overall tone is {tone_desc} (formality: {formality}/100) with "
        f"a {vocab_desc} and an average sentence length of {mean_sent:.0f} words. "
        f"Use this guide as a system instruction to get any LLM to write in "
        f"this person's authentic voice."
    )

    sections = [
        _section_vocabulary(voice_stats),
        _section_grammar(voice_stats),
        _section_punctuation(voice_stats),
        _section_sentences(voice_stats),
        _section_rhetorical(voice_stats),
        _section_paragraphs(voice_stats),
        _section_tone(voice_stats),
        _section_coherence(voice_stats),
        _section_quirks(voice_stats),
        _section_email_patterns(voice_stats),
    ]

    return VoiceProfile(
        sections=sections,
        formality_score=formality,
        email_count=email_count,
        summary=summary,
    )
