// dict-tl.js — Filipino/Tagalog phrase dictionary (210+ entries)
// Auto-generated for HowDoISay app
var DICT_TL = {
  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"kumusta", s:[{t:"ku",m:"Coo",h:"like a pigeon's 'coo'"},{t:"mus",m:"Moose",h:"the animal 'moose'"},{t:"ta",m:"Tah",h:"like 'ta-da'"}]},
  "good morning": {t:"magandang umaga", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"gan",m:"Gone",h:"the word 'gone'"},{t:"dang",m:"Dung",h:"the word 'dung'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ga",m:"Gah",h:"like 'gah'"}]},
  "good afternoon": {t:"magandang hapon", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"gan",m:"Gone",h:"the word 'gone'"},{t:"dang",m:"Dung",h:"the word 'dung'"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"pon",m:"Pawn",h:"the word 'pawn'"}]},
  "good evening": {t:"magandang gabi", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"gan",m:"Gone",h:"the word 'gone'"},{t:"dang",m:"Dung",h:"the word 'dung'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"bi",m:"Bee",h:"the word 'bee'"}]},
  "good night": {t:"magandang gabi", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"gan",m:"Gone",h:"the word 'gone'"},{t:"dang",m:"Dung",h:"the word 'dung'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"bi",m:"Bee",h:"the word 'bee'"}]},
  "goodbye": {t:"paalam", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"lam",m:"Lamb",h:"the word 'lamb'"}]},
  "thank you": {t:"salamat", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"mat",m:"Mot",h:"the word 'mot'"}]},
  "thank you very much": {t:"maraming salamat", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ra",m:"Rah",h:"like 'rah rah'"},{t:"ming",m:"Ming",h:"the name 'Ming'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"mat",m:"Mot",h:"the word 'mot'"}]},
  "you're welcome": {t:"walang anuman", s:[{t:"wa",m:"Wah",h:"like 'wah' pedal"},{t:"lang",m:"Lung",h:"the word 'lung'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"nu",m:"Noo",h:"the word 'new'"},{t:"man",m:"Mon",h:"the word 'mon'"}]},
  "excuse me": {t:"paumanhin", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"man",m:"Mon",h:"the word 'mon'"},{t:"hin",m:"Hin",h:"like 'hint' without the T"}]},
  "i'm sorry": {t:"pasensya na", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"sen",m:"Sen",h:"the word 'sen'"},{t:"sya",m:"Shah",h:"like the word 'shah'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "please": {t:"pakiusap", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"sap",m:"Sop",h:"the word 'sop'"}]},
  "nice to meet you": {t:"kinagagalak kitang makilala", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"lak",m:"Luck",h:"the word 'luck'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"tang",m:"Tung",h:"the word 'tongue'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"la",m:"Lah",h:"like a musical note"}]},
  "how are you": {t:"kumusta ka", s:[{t:"ku",m:"Coo",h:"like a pigeon's 'coo'"},{t:"mus",m:"Moose",h:"the animal 'moose'"},{t:"ta",m:"Tah",h:"like 'ta-da'"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "i'm fine": {t:"mabuti naman", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"man",m:"Mon",h:"the word 'mon'"}]},
  "what is your name": {t:"ano ang pangalan mo", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"no",m:"No",h:"the word 'no'"},{t:"ang",m:"Ung",h:"like 'hung' without the H"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"nga",m:"Ngah",h:"like the NG in 'sing' + 'ah'"},{t:"lan",m:"Lahn",h:"like 'lawn'"},{t:"mo",m:"Mo",h:"the name 'Mo'"}]},
  "my name is": {t:"ang pangalan ko ay", s:[{t:"ang",m:"Ung",h:"like 'hung' without the H"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"nga",m:"Ngah",h:"like the NG in 'sing' + 'ah'"},{t:"lan",m:"Lahn",h:"like 'lawn'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"ay",m:"Eye",h:"the word 'eye'"}]},
  "pleased to meet you": {t:"ikinagagalak kong makilala ka", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"lak",m:"Luck",h:"the word 'luck'"},{t:"kong",m:"Kong",h:"like King Kong"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "congratulations": {t:"binabati kita", s:[{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"ta",m:"Tah",h:"like 'ta-da'"}]},
  "happy birthday": {t:"maligayang kaarawan", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"yang",m:"Yung",h:"the word 'young'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ra",m:"Rah",h:"like 'rah rah'"},{t:"wan",m:"Wahn",h:"like 'wand' without the D"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"oo", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"o",m:"Oh",h:"the word 'oh'"}]},
  "no": {t:"hindi", s:[{t:"hin",m:"Hin",h:"like 'hint' without the T"},{t:"di",m:"Dee",h:"the letter 'D'"}]},
  "ok": {t:"sige", s:[{t:"si",m:"See",h:"the word 'see'"},{t:"ge",m:"Geh",h:"like 'get' without the T"}]},
  "i understand": {t:"naiintindihan ko", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"in",m:"In",h:"the word 'in'"},{t:"tin",m:"Tin",h:"the word 'tin'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"han",m:"Hon",h:"the word 'hon'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "i don't understand": {t:"hindi ko naiintindihan", s:[{t:"hin",m:"Hin",h:"like 'hint' without the T"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"in",m:"In",h:"the word 'in'"},{t:"tin",m:"Tin",h:"the word 'tin'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"han",m:"Hon",h:"the word 'hon'"}]},
  "do you speak english": {t:"nagsasalita ka ba ng ingles", s:[{t:"nag",m:"Nug",h:"like 'nag'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"ta",m:"Tah",h:"like 'ta-da'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"ing",m:"Ing",h:"like '-ing' ending"},{t:"les",m:"Les",h:"the name 'Les'"}]},
  "slowly please": {t:"dahan-dahan lang", s:[{t:"da",m:"Dah",h:"like 'duh'"},{t:"han",m:"Hon",h:"the word 'hon'"},{t:"da",m:"Dah",h:"like 'duh'"},{t:"han",m:"Hon",h:"the word 'hon'"},{t:"lang",m:"Lung",h:"the word 'lung'"}]},
  "can you help me": {t:"pwede mo ba akong tulungan", s:[{t:"pwe",m:"Pweh",h:"like 'quest' without 'st'"},{t:"de",m:"Deh",h:"like 'day'"},{t:"mo",m:"Mo",h:"the name 'Mo'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"kong",m:"Kong",h:"like King Kong"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"lu",m:"Loo",h:"the word 'loo'"},{t:"ngan",m:"Ngun",h:"NG + 'un'"}]},
  "where is": {t:"nasaan", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"an",m:"Ahn",h:"like 'on'"}]},
  "how much": {t:"magkano", s:[{t:"mag",m:"Mug",h:"the word 'mug'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"no",m:"No",h:"the word 'no'"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"tulong", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"long",m:"Long",h:"the word 'long'"}]},
  "emergency": {t:"emerhensya", s:[{t:"e",m:"Eh",h:"like 'eh'"},{t:"mer",m:"Mare",h:"the word 'mare'"},{t:"hen",m:"Hen",h:"the word 'hen'"},{t:"sya",m:"Shah",h:"like the word 'shah'"}]},
  "call the police": {t:"tumawag ng pulis", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"wag",m:"Wug",h:"like 'wag'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"pu",m:"Poo",h:"the word 'pooh'"},{t:"lis",m:"Lease",h:"the word 'lease'"}]},
  "call the doctor": {t:"tumawag ng doktor", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"wag",m:"Wug",h:"like 'wag'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"dok",m:"Dock",h:"the word 'dock'"},{t:"tor",m:"Tor",h:"the word 'tore'"}]},
  "hospital": {t:"ospital", s:[{t:"os",m:"Os",h:"like 'boss' without the B"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"tal",m:"Tal",h:"like 'tall'"}]},
  "fire": {t:"sunog", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"nog",m:"Nog",h:"like 'eggnog'"}]},
  "danger": {t:"panganib", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"nga",m:"Ngah",h:"like the NG in 'sing' + 'ah'"},{t:"nib",m:"Nib",h:"the word 'nib'"}]},
  "watch out": {t:"mag-ingat", s:[{t:"mag",m:"Mug",h:"the word 'mug'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"ngat",m:"Ngut",h:"NG + 'ut'"}]},
  "i'm lost": {t:"naliligaw ako", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"gaw",m:"Gow",h:"like 'cow' with G"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "i'm sick": {t:"may sakit ako", s:[{t:"may",m:"My",h:"the word 'my'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"kit",m:"Kit",h:"the word 'kit'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "call an ambulance": {t:"tumawag ng ambulansya", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"wag",m:"Wug",h:"like 'wag'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"am",m:"Am",h:"the word 'am'"},{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"lan",m:"Lahn",h:"like 'lawn'"},{t:"sya",m:"Shah",h:"like the word 'shah'"}]},
  "i need a doctor": {t:"kailangan ko ng doktor", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ngan",m:"Ngun",h:"NG + 'un'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"dok",m:"Dock",h:"the word 'dock'"},{t:"tor",m:"Tor",h:"the word 'tore'"}]},
  "passport": {t:"pasaporte", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"por",m:"Pour",h:"the word 'pour'"},{t:"te",m:"Teh",h:"like 'tech' without the CH"}]},
  "visa": {t:"visa", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "police station": {t:"himpilan ng pulis", s:[{t:"him",m:"Him",h:"the word 'him'"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"lan",m:"Lahn",h:"like 'lawn'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"pu",m:"Poo",h:"the word 'pooh'"},{t:"lis",m:"Lease",h:"the word 'lease'"}]},

  // ===== NUMBERS 0-10, 20, 50, 100, 1000 (15) =====
  "zero": {t:"sero", s:[{t:"se",m:"Seh",h:"like 'set' without the T"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "one": {t:"isa", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "two": {t:"dalawa", s:[{t:"da",m:"Dah",h:"like 'duh'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"wa",m:"Wah",h:"like 'wah' pedal"}]},
  "three": {t:"tatlo", s:[{t:"tat",m:"Tut",h:"like 'tut-tut'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "four": {t:"apat", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"pat",m:"Pot",h:"the word 'pot'"}]},
  "five": {t:"lima", s:[{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"ma",m:"Ma",h:"the word 'ma'"}]},
  "six": {t:"anim", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"nim",m:"Neem",h:"the word 'neem'"}]},
  "seven": {t:"pito", s:[{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "eight": {t:"walo", s:[{t:"wa",m:"Wah",h:"like 'wah' pedal"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "nine": {t:"siyam", s:[{t:"si",m:"See",h:"the word 'see'"},{t:"yam",m:"Yam",h:"the word 'yam'"}]},
  "ten": {t:"sampu", s:[{t:"sam",m:"Sum",h:"the word 'sum'"},{t:"pu",m:"Poo",h:"the word 'pooh'"}]},
  "twenty": {t:"dalawampu", s:[{t:"da",m:"Dah",h:"like 'duh'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"wam",m:"Wom",h:"like 'womb' without the B"},{t:"pu",m:"Poo",h:"the word 'pooh'"}]},
  "fifty": {t:"limampu", s:[{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"mam",m:"Mom",h:"the word 'mom'"},{t:"pu",m:"Poo",h:"the word 'pooh'"}]},
  "one hundred": {t:"isang daan", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"sang",m:"Sung",h:"the word 'sung'"},{t:"da",m:"Dah",h:"like 'duh'"},{t:"an",m:"Ahn",h:"like 'on'"}]},
  "one thousand": {t:"isang libo", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"sang",m:"Sung",h:"the word 'sung'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"bo",m:"Boh",h:"like 'bow'"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"tubig", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"big",m:"Big",h:"the word 'big'"}]},
  "rice": {t:"kanin", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"nin",m:"Neen",h:"like 'keen' with N"}]},
  "chicken": {t:"manok", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"nok",m:"Knock",h:"the word 'knock'"}]},
  "pork": {t:"baboy", s:[{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"boy",m:"Boy",h:"the word 'boy'"}]},
  "beef": {t:"baka", s:[{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "fish": {t:"isda", s:[{t:"is",m:"Is",h:"the word 'is'"},{t:"da",m:"Dah",h:"like 'duh'"}]},
  "egg": {t:"itlog", s:[{t:"it",m:"It",h:"the word 'it'"},{t:"log",m:"Log",h:"the word 'log'"}]},
  "bread": {t:"tinapay", s:[{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"pay",m:"Pie",h:"the word 'pie'"}]},
  "fruit": {t:"prutas", s:[{t:"pru",m:"Proo",h:"like 'prude' without the D"},{t:"tas",m:"Tus",h:"like 'toss'"}]},
  "vegetable": {t:"gulay", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"lay",m:"Lie",h:"the word 'lie'"}]},
  "coffee": {t:"kape", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"pe",m:"Peh",h:"like 'pet' without the T"}]},
  "tea": {t:"tsaa", s:[{t:"tsa",m:"Cha",h:"like 'cha-cha'"},{t:"a",m:"Ah",h:"like 'ah'"}]},
  "beer": {t:"serbesa", s:[{t:"ser",m:"Sair",h:"like 'air' with S"},{t:"be",m:"Beh",h:"like 'bet' without the T"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "juice": {t:"juice", s:[{t:"juice",m:"Juice",h:"the word 'juice'"}]},
  "milk": {t:"gatas", s:[{t:"ga",m:"Gah",h:"like 'gah'"},{t:"tas",m:"Tus",h:"like 'toss'"}]},
  "sugar": {t:"asukal", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"kal",m:"Cull",h:"the word 'cull'"}]},
  "salt": {t:"asin", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"sin",m:"Sin",h:"the word 'sin'"}]},
  "delicious": {t:"masarap", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"rap",m:"Rup",h:"like 'wrap'"}]},
  "spicy": {t:"maanghang", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ang",m:"Ung",h:"like 'hung' without the H"},{t:"hang",m:"Hung",h:"the word 'hung'"}]},
  "sweet": {t:"matamis", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ta",m:"Tah",h:"like 'ta-da'"},{t:"mis",m:"Meese",h:"like 'piece' with M"}]},
  "sour": {t:"maasim", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"sim",m:"Seem",h:"the word 'seem'"}]},
  "bitter": {t:"mapait", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"it",m:"Eat",h:"the word 'eat'"}]},
  "hot food": {t:"mainit", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"nit",m:"Knit",h:"the word 'knit'"}]},
  "cold food": {t:"malamig", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"mig",m:"Meeg",h:"like 'league' with M"}]},
  "i'm hungry": {t:"gutom na ako", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"tom",m:"Tom",h:"the name 'Tom'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "i'm thirsty": {t:"nauuhaw ako", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"haw",m:"How",h:"the word 'how'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "i'm full": {t:"busog na ako", s:[{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"sog",m:"Sog",h:"like 'fog' with S"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},
  "soup": {t:"sabaw", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"baw",m:"Bow",h:"like 'bow' and arrow"}]},
  "noodles": {t:"pansit", s:[{t:"pan",m:"Pun",h:"the word 'pun'"},{t:"sit",m:"Sit",h:"the word 'sit'"}]},
  "ice cream": {t:"sorbetes", s:[{t:"sor",m:"Sore",h:"the word 'sore'"},{t:"be",m:"Beh",h:"like 'bet' without the T"},{t:"tes",m:"Tess",h:"the name 'Tess'"}]},

  // ===== RESTAURANT (15) =====
  "restaurant": {t:"restawran", s:[{t:"res",m:"Ress",h:"like 'rest' without the T"},{t:"taw",m:"Tow",h:"like 'towel'"},{t:"ran",m:"Run",h:"the word 'run'"}]},
  "menu": {t:"menu", s:[{t:"me",m:"Meh",h:"like 'meh'"},{t:"nu",m:"Noo",h:"the word 'new'"}]},
  "i would like": {t:"gusto ko ng", s:[{t:"gus",m:"Goose",h:"the word 'goose'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"}]},
  "the bill please": {t:"pabill na lang po", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"bill",m:"Bill",h:"the word 'bill'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"lang",m:"Lung",h:"the word 'lung'"},{t:"po",m:"Poh",h:"like 'pole' without the LE"}]},
  "more please": {t:"dagdag pa po", s:[{t:"dag",m:"Dug",h:"like 'dug'"},{t:"dag",m:"Dug",h:"like 'dug'"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"po",m:"Poh",h:"like 'pole' without the LE"}]},
  "breakfast": {t:"almusal", s:[{t:"al",m:"Al",h:"the name 'Al'"},{t:"mu",m:"Moo",h:"the word 'moo'"},{t:"sal",m:"Sal",h:"the name 'Sal'"}]},
  "lunch": {t:"tanghalian", s:[{t:"tang",m:"Tung",h:"the word 'tongue'"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"an",m:"Ahn",h:"like 'on'"}]},
  "dinner": {t:"hapunan", s:[{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"pu",m:"Poo",h:"the word 'pooh'"},{t:"nan",m:"Non",h:"the word 'non'"}]},
  "a table for two": {t:"mesa para sa dalawa", s:[{t:"me",m:"Meh",h:"like 'meh'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"ra",m:"Rah",h:"like 'rah rah'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"da",m:"Dah",h:"like 'duh'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"wa",m:"Wah",h:"like 'wah' pedal"}]},
  "very delicious": {t:"napakasarap", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"rap",m:"Rup",h:"like 'wrap'"}]},
  "no ice": {t:"walang yelo", s:[{t:"wa",m:"Wah",h:"like 'wah' pedal"},{t:"lang",m:"Lung",h:"the word 'lung'"},{t:"ye",m:"Yeh",h:"like 'yeah'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "glass of water": {t:"isang baso ng tubig", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"sang",m:"Sung",h:"the word 'sung'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"so",m:"So",h:"the word 'so'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"big",m:"Big",h:"the word 'big'"}]},
  "take away": {t:"pang take out", s:[{t:"pang",m:"Pung",h:"like 'pang'"},{t:"take",m:"Take",h:"the word 'take'"},{t:"out",m:"Out",h:"the word 'out'"}]},
  "eat here": {t:"dito kakain", s:[{t:"di",m:"Dee",h:"the letter 'D'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"in",m:"In",h:"the word 'in'"}]},
  "waiter": {t:"weyter", s:[{t:"wey",m:"Way",h:"the word 'way'"},{t:"ter",m:"Ter",h:"like 'terrace'"}]},

  // ===== SHOPPING & MONEY (20) =====
  "how much is this": {t:"magkano ito", s:[{t:"mag",m:"Mug",h:"the word 'mug'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"no",m:"No",h:"the word 'no'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "too expensive": {t:"masyadong mahal", s:[{t:"mas",m:"Mus",h:"like 'must' without the T"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"dong",m:"Dong",h:"like 'ding dong'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"hal",m:"Hull",h:"the word 'hull'"}]},
  "cheap": {t:"mura", s:[{t:"mu",m:"Moo",h:"the word 'moo'"},{t:"ra",m:"Rah",h:"like 'rah rah'"}]},
  "discount": {t:"diskwento", s:[{t:"dis",m:"Diss",h:"the word 'diss'"},{t:"kwen",m:"Kwen",h:"like 'queen' with W"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "i want to buy": {t:"gusto kong bumili", s:[{t:"gus",m:"Goose",h:"the word 'goose'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"kong",m:"Kong",h:"like King Kong"},{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"li",m:"Lee",h:"the name 'Lee'"}]},
  "money": {t:"pera", s:[{t:"pe",m:"Peh",h:"like 'pet' without the T"},{t:"ra",m:"Rah",h:"like 'rah rah'"}]},
  "cash": {t:"pera", s:[{t:"pe",m:"Peh",h:"like 'pet' without the T"},{t:"ra",m:"Rah",h:"like 'rah rah'"}]},
  "credit card": {t:"credit card", s:[{t:"cre",m:"Creh",h:"like 'credit'"},{t:"dit",m:"Dit",h:"like 'ditto'"},{t:"card",m:"Card",h:"the word 'card'"}]},
  "market": {t:"palengke", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"leng",m:"Leng",h:"like 'length' without the TH"},{t:"ke",m:"Keh",h:"like 'kept' without the PT"}]},
  "store": {t:"tindahan", s:[{t:"tin",m:"Tin",h:"the word 'tin'"},{t:"da",m:"Dah",h:"like 'duh'"},{t:"han",m:"Hon",h:"the word 'hon'"}]},
  "mall": {t:"mall", s:[{t:"mall",m:"Mall",h:"the word 'mall'"}]},
  "receipt": {t:"resibo", s:[{t:"re",m:"Reh",h:"like 'red' without the D"},{t:"si",m:"See",h:"the word 'see'"},{t:"bo",m:"Boh",h:"like 'bow'"}]},
  "bag": {t:"bag", s:[{t:"bag",m:"Bag",h:"the word 'bag'"}]},
  "size": {t:"sukat", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"kat",m:"Cut",h:"the word 'cut'"}]},
  "big": {t:"malaki", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ki",m:"Key",h:"the word 'key'"}]},
  "small": {t:"maliit", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"it",m:"Eat",h:"the word 'eat'"}]},
  "i'm just looking": {t:"nagtitingin lang", s:[{t:"nag",m:"Nug",h:"like 'nag'"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"ngin",m:"Ngin",h:"NG + 'in'"},{t:"lang",m:"Lung",h:"the word 'lung'"}]},
  "do you have": {t:"meron ba kayong", s:[{t:"me",m:"Meh",h:"like 'meh'"},{t:"ron",m:"Ron",h:"the name 'Ron'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"yong",m:"Yong",h:"like 'young'"}]},
  "change": {t:"sukli", s:[{t:"suk",m:"Sook",h:"like 'look' with S"},{t:"li",m:"Lee",h:"the name 'Lee'"}]},
  "pay": {t:"bayad", s:[{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"yad",m:"Yud",h:"like 'yum' without the M + D"}]},

  // ===== DIRECTIONS & TRANSPORTATION (25) =====
  "where": {t:"saan", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"an",m:"Ahn",h:"like 'on'"}]},
  "left": {t:"kaliwa", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"wa",m:"Wah",h:"like 'wah' pedal"}]},
  "right": {t:"kanan", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"nan",m:"Non",h:"the word 'non'"}]},
  "straight ahead": {t:"diretso", s:[{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ret",m:"Ret",h:"like 'red' with T"},{t:"so",m:"So",h:"the word 'so'"}]},
  "near": {t:"malapit", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"pit",m:"Pit",h:"the word 'pit'"}]},
  "far": {t:"malayo", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"yo",m:"Yo",h:"the word 'yo'"}]},
  "stop here": {t:"dito lang po", s:[{t:"di",m:"Dee",h:"the letter 'D'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"lang",m:"Lung",h:"the word 'lung'"},{t:"po",m:"Poh",h:"like 'pole' without the LE"}]},
  "taxi": {t:"taksi", s:[{t:"tak",m:"Tuck",h:"the word 'tuck'"},{t:"si",m:"See",h:"the word 'see'"}]},
  "bus": {t:"bus", s:[{t:"bus",m:"Bus",h:"the word 'bus'"}]},
  "train": {t:"tren", s:[{t:"tren",m:"Tren",h:"like 'trend' without the D"}]},
  "airplane": {t:"eroplano", s:[{t:"e",m:"Eh",h:"like 'eh'"},{t:"ro",m:"Row",h:"the word 'row'"},{t:"pla",m:"Plah",h:"like 'plan' without the N"},{t:"no",m:"No",h:"the word 'no'"}]},
  "boat": {t:"bangka", s:[{t:"bang",m:"Bung",h:"like 'bung'"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "airport": {t:"paliparan", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"ran",m:"Run",h:"the word 'run'"}]},
  "bus station": {t:"istasyon ng bus", s:[{t:"is",m:"Is",h:"the word 'is'"},{t:"tas",m:"Tus",h:"like 'toss'"},{t:"yon",m:"Yon",h:"the word 'yon'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"bus",m:"Bus",h:"the word 'bus'"}]},
  "ticket": {t:"tiket", s:[{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"ket",m:"Ket",h:"like 'kept' without the P"}]},
  "map": {t:"mapa", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"pa",m:"Pa",h:"the word 'pa'"}]},
  "street": {t:"kalye", s:[{t:"kal",m:"Cull",h:"the word 'cull'"},{t:"ye",m:"Yeh",h:"like 'yeah'"}]},
  "bridge": {t:"tulay", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"lay",m:"Lie",h:"the word 'lie'"}]},
  "north": {t:"hilaga", s:[{t:"hi",m:"He",h:"the word 'he'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ga",m:"Gah",h:"like 'gah'"}]},
  "south": {t:"timog", s:[{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"mog",m:"Mog",h:"like 'dog' with M"}]},
  "east": {t:"silangan", s:[{t:"si",m:"See",h:"the word 'see'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ngan",m:"Ngun",h:"NG + 'un'"}]},
  "west": {t:"kanluran", s:[{t:"kan",m:"Con",h:"the word 'con'"},{t:"lu",m:"Loo",h:"the word 'loo'"},{t:"ran",m:"Run",h:"the word 'run'"}]},
  "i want to go to": {t:"gusto kong pumunta sa", s:[{t:"gus",m:"Goose",h:"the word 'goose'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"kong",m:"Kong",h:"like King Kong"},{t:"pu",m:"Poo",h:"the word 'pooh'"},{t:"mun",m:"Moon",h:"the word 'moon'"},{t:"ta",m:"Tah",h:"like 'ta-da'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "how far is it": {t:"gaano kalayo", s:[{t:"ga",m:"Gah",h:"like 'gah'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"no",m:"No",h:"the word 'no'"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"la",m:"Lah",h:"like a musical note"},{t:"yo",m:"Yo",h:"the word 'yo'"}]},
  "is it far": {t:"malayo ba", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"hotel", s:[{t:"ho",m:"Ho",h:"like 'hoe'"},{t:"tel",m:"Tel",h:"the word 'tell'"}]},
  "room": {t:"kuwarto", s:[{t:"ku",m:"Coo",h:"like a pigeon's 'coo'"},{t:"war",m:"War",h:"the word 'war'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "bed": {t:"kama", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"ma",m:"Ma",h:"the word 'ma'"}]},
  "bathroom": {t:"banyo", s:[{t:"ban",m:"Bun",h:"the word 'bun'"},{t:"yo",m:"Yo",h:"the word 'yo'"}]},
  "key": {t:"susi", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"si",m:"See",h:"the word 'see'"}]},
  "air conditioning": {t:"aircon", s:[{t:"air",m:"Air",h:"the word 'air'"},{t:"con",m:"Con",h:"the word 'con'"}]},
  "towel": {t:"tuwalya", s:[{t:"tu",m:"Too",h:"the word 'too'"},{t:"wal",m:"Wall",h:"the word 'wall'"},{t:"ya",m:"Yah",h:"the word 'yah'"}]},
  "check in": {t:"check in", s:[{t:"check",m:"Check",h:"the word 'check'"},{t:"in",m:"In",h:"the word 'in'"}]},
  "check out": {t:"check out", s:[{t:"check",m:"Check",h:"the word 'check'"},{t:"out",m:"Out",h:"the word 'out'"}]},
  "one night": {t:"isang gabi", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"sang",m:"Sung",h:"the word 'sung'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"bi",m:"Bee",h:"the word 'bee'"}]},
  "reservation": {t:"reserbasyon", s:[{t:"re",m:"Reh",h:"like 'red' without the D"},{t:"ser",m:"Sair",h:"like 'air' with S"},{t:"bas",m:"Bus",h:"the word 'bus'"},{t:"yon",m:"Yon",h:"the word 'yon'"}]},
  "do you have a room": {t:"may kuwarto ba kayo", s:[{t:"may",m:"My",h:"the word 'my'"},{t:"ku",m:"Coo",h:"like a pigeon's 'coo'"},{t:"war",m:"War",h:"the word 'war'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"yo",m:"Yo",h:"the word 'yo'"}]},
  "wifi password": {t:"password ng wifi", s:[{t:"pass",m:"Pass",h:"the word 'pass'"},{t:"word",m:"Word",h:"the word 'word'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"wi",m:"Wee",h:"the word 'wee'"},{t:"fi",m:"Fye",h:"like 'five' without the V"}]},
  "hot water": {t:"mainit na tubig", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"nit",m:"Knit",h:"the word 'knit'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"big",m:"Big",h:"the word 'big'"}]},
  "cold water": {t:"malamig na tubig", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"mig",m:"Meeg",h:"like 'league' with M"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"big",m:"Big",h:"the word 'big'"}]},

  // ===== COMMUNICATION (15) =====
  "phone": {t:"telepono", s:[{t:"te",m:"Teh",h:"like 'tech' without the CH"},{t:"le",m:"Leh",h:"like 'let' without the T"},{t:"po",m:"Poh",h:"like 'pole' without the LE"},{t:"no",m:"No",h:"the word 'no'"}]},
  "internet": {t:"internet", s:[{t:"in",m:"In",h:"the word 'in'"},{t:"ter",m:"Ter",h:"like 'terrace'"},{t:"net",m:"Net",h:"the word 'net'"}]},
  "email": {t:"email", s:[{t:"e",m:"Ee",h:"the sound 'ee'"},{t:"mail",m:"Mail",h:"the word 'mail'"}]},
  "i don't know": {t:"hindi ko alam", s:[{t:"hin",m:"Hin",h:"like 'hint' without the T"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"lam",m:"Lamb",h:"the word 'lamb'"}]},
  "wait": {t:"sandali lang", s:[{t:"san",m:"Sun",h:"the word 'sun'"},{t:"da",m:"Dah",h:"like 'duh'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"lang",m:"Lung",h:"the word 'lung'"}]},
  "again": {t:"ulit", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"lit",m:"Lit",h:"the word 'lit'"}]},
  "what": {t:"ano", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "when": {t:"kailan", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"lan",m:"Lahn",h:"like 'lawn'"}]},
  "why": {t:"bakit", s:[{t:"ba",m:"Bah",h:"like 'baa' of a sheep"},{t:"kit",m:"Kit",h:"the word 'kit'"}]},
  "who": {t:"sino", s:[{t:"si",m:"See",h:"the word 'see'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "this": {t:"ito", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "that": {t:"iyan", s:[{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"yan",m:"Yawn",h:"the word 'yawn'"}]},
  "here": {t:"dito", s:[{t:"di",m:"Dee",h:"the letter 'D'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "there": {t:"doon", s:[{t:"do",m:"Doh",h:"the musical note 'doh'"},{t:"on",m:"Own",h:"the word 'own'"}]},
  "i like": {t:"gusto ko", s:[{t:"gus",m:"Goose",h:"the word 'goose'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ko",m:"Co",h:"like 'co-' prefix"}]},

  // ===== HEALTH (10) =====
  "medicine": {t:"gamot", s:[{t:"ga",m:"Gah",h:"like 'gah'"},{t:"mot",m:"Moat",h:"the word 'moat'"}]},
  "pharmacy": {t:"botika", s:[{t:"bo",m:"Boh",h:"like 'bow'"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "headache": {t:"sakit ng ulo", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"kit",m:"Kit",h:"the word 'kit'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "stomach ache": {t:"sakit ng tiyan", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"kit",m:"Kit",h:"the word 'kit'"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"ti",m:"Tee",h:"the word 'tea'"},{t:"yan",m:"Yawn",h:"the word 'yawn'"}]},
  "fever": {t:"lagnat", s:[{t:"lag",m:"Lug",h:"like 'lug'"},{t:"nat",m:"Not",h:"the word 'not'"}]},
  "allergic": {t:"alerdyi", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"ler",m:"Lair",h:"the word 'lair'"},{t:"dyi",m:"Jee",h:"like 'gee'"}]},
  "pain": {t:"sakit", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"kit",m:"Kit",h:"the word 'kit'"}]},
  "dentist": {t:"dentista", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"tis",m:"Tees",h:"like 'tease'"},{t:"ta",m:"Tah",h:"like 'ta-da'"}]},
  "pregnant": {t:"buntis", s:[{t:"bun",m:"Bun",h:"the word 'bun'"},{t:"tis",m:"Tees",h:"like 'tease'"}]},
  "i need medicine": {t:"kailangan ko ng gamot", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"ngan",m:"Ngun",h:"NG + 'un'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"ng",m:"Nang",h:"like the NG in 'sing'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"mot",m:"Moat",h:"the word 'moat'"}]},

  // ===== TIME (10) =====
  "what time is it": {t:"anong oras na", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"nong",m:"Nong",h:"like 'gong' with N"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ras",m:"Ras",h:"like 'rasp' without the P"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "today": {t:"ngayon", s:[{t:"nga",m:"Ngah",h:"like the NG in 'sing' + 'ah'"},{t:"yon",m:"Yon",h:"the word 'yon'"}]},
  "tomorrow": {t:"bukas", s:[{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"kas",m:"Cuss",h:"the word 'cuss'"}]},
  "yesterday": {t:"kahapon", s:[{t:"ka",m:"Kah",h:"like 'car' without the R"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"pon",m:"Pawn",h:"the word 'pawn'"}]},
  "morning": {t:"umaga", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ga",m:"Gah",h:"like 'gah'"}]},
  "afternoon": {t:"hapon", s:[{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"pon",m:"Pawn",h:"the word 'pawn'"}]},
  "evening": {t:"gabi", s:[{t:"ga",m:"Gah",h:"like 'gah'"},{t:"bi",m:"Bee",h:"the word 'bee'"}]},
  "now": {t:"ngayon", s:[{t:"nga",m:"Ngah",h:"like the NG in 'sing' + 'ah'"},{t:"yon",m:"Yon",h:"the word 'yon'"}]},
  "later": {t:"mamaya", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ya",m:"Yah",h:"the word 'yah'"}]},
  "early": {t:"maaga", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ga",m:"Gah",h:"like 'gah'"}]},

  // ===== WEATHER & MISC (10) =====
  "hot weather": {t:"mainit", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"nit",m:"Knit",h:"the word 'knit'"}]},
  "cold weather": {t:"malamig", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"la",m:"Lah",h:"like a musical note"},{t:"mig",m:"Meeg",h:"like 'league' with M"}]},
  "rain": {t:"ulan", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"lan",m:"Lahn",h:"like 'lawn'"}]},
  "sun": {t:"araw", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"raw",m:"Row",h:"the word 'row'"}]},
  "beautiful": {t:"maganda", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"gan",m:"Gone",h:"the word 'gone'"},{t:"da",m:"Dah",h:"like 'duh'"}]},
  "ugly": {t:"pangit", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"ngit",m:"Ngit",h:"NG + 'it'"}]},
  "happy": {t:"masaya", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"ya",m:"Yah",h:"the word 'yah'"}]},
  "tired": {t:"pagod", s:[{t:"pa",m:"Pa",h:"the word 'pa'"},{t:"god",m:"God",h:"the word 'god'"}]},
  "be careful": {t:"mag-ingat ka", s:[{t:"mag",m:"Mug",h:"the word 'mug'"},{t:"i",m:"Ee",h:"the sound 'ee'"},{t:"ngat",m:"Ngut",h:"NG + 'ut'"},{t:"ka",m:"Kah",h:"like 'car' without the R"}]},
  "i love the philippines": {t:"mahal ko ang pilipinas", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"hal",m:"Hull",h:"the word 'hull'"},{t:"ko",m:"Co",h:"like 'co-' prefix"},{t:"ang",m:"Ung",h:"like 'hung' without the H"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"li",m:"Lee",h:"the name 'Lee'"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"nas",m:"Nus",h:"like 'bus' with N"}]}
};
