// dict-de.js — German phrase dictionary (210+ entries)
// Auto-generated for HowDoISay app
// Key sounds: W=V, V=F, Z=TS, ß=SS, ch=ikh/akh, ei=eye, ie=ee, eu/äu=oy, ä=eh, ö=ur, ü=ew
var DICT_DE = {
  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"hallo", s:[{t:"hal",m:"Huh",h:"the word 'huh'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "good morning": {t:"guten Morgen", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"ten",m:"Ten",h:"the number 'ten'"},{t:"Mor",m:"More",h:"the word 'more'"},{t:"gen",m:"Gun",h:"the word 'gun'"}]},
  "good afternoon": {t:"guten Tag", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"ten",m:"Ten",h:"the number 'ten'"},{t:"Tag",m:"Tahk",h:"like 'tock' with an A"}]},
  "good evening": {t:"guten Abend", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"ten",m:"Ten",h:"the number 'ten'"},{t:"A",m:"Ah",h:"the sound 'ah'"},{t:"bend",m:"Bent",h:"the word 'bent'"}]},
  "good night": {t:"gute Nacht", s:[{t:"gu",m:"Goo",h:"like 'goo'"},{t:"te",m:"Tuh",h:"like 'tug' without the G"},{t:"Nacht",m:"Knocked",h:"like 'knocked' — CH is a throaty sound"}]},
  "goodbye": {t:"auf Wiedersehen", s:[{t:"auf",m:"Owf",h:"like 'ouch' + 'F'"},{t:"Wie",m:"Vee",h:"like 'V' — German W sounds like V"},{t:"der",m:"Dare",h:"the word 'dare'"},{t:"se",m:"Say",h:"the word 'say'"},{t:"hen",m:"Hen",h:"the word 'hen'"}]},
  "bye": {t:"tschüss", s:[{t:"tschüss",m:"Juice",h:"like 'juice' — ü sounds like 'ew'"}]},
  "thank you": {t:"danke", s:[{t:"dan",m:"Done",h:"the word 'done'"},{t:"ke",m:"Kuh",h:"like 'cup' without the P"}]},
  "thank you very much": {t:"vielen Dank", s:[{t:"vie",m:"Fee",h:"like 'fee' — German V sounds like F"},{t:"len",m:"Len",h:"the name 'Len'"},{t:"Dank",m:"Donk",h:"like 'donkey' without the EY"}]},
  "you're welcome": {t:"bitte schön", s:[{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without the G"},{t:"schön",m:"Shurn",h:"like 'shirt' without the T — ö sounds like 'ur'"}]},
  "excuse me": {t:"Entschuldigung", s:[{t:"Ent",m:"Ent",h:"like 'enter' without ER"},{t:"schul",m:"Shool",h:"like 'school' with SH"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"gung",m:"Goong",h:"like 'goo' + 'ng'"}]},
  "i'm sorry": {t:"es tut mir leid", s:[{t:"es",m:"Ess",h:"the letter 'S'"},{t:"tut",m:"Toot",h:"the word 'toot'"},{t:"mir",m:"Mere",h:"the word 'mere'"},{t:"leid",m:"Light",h:"like 'light' — EI sounds like 'eye'"}]},
  "please": {t:"bitte", s:[{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without the G"}]},
  "nice to meet you": {t:"freut mich", s:[{t:"freut",m:"Froit",h:"like 'froy' + T — EU sounds like 'oy'"},{t:"mich",m:"Mish",h:"like 'mish' — CH after I is a soft hiss"}]},
  "how are you": {t:"wie geht es Ihnen", s:[{t:"wie",m:"Vee",h:"like 'V' — German W sounds like V"},{t:"geht",m:"Gate",h:"the word 'gate'"},{t:"es",m:"Ess",h:"the letter 'S'"},{t:"Ih",m:"Ee",h:"the sound 'ee'"},{t:"nen",m:"Nen",h:"like 'pen' with N"}]},
  "i'm fine": {t:"mir geht es gut", s:[{t:"mir",m:"Mere",h:"the word 'mere'"},{t:"geht",m:"Gate",h:"the word 'gate'"},{t:"es",m:"Ess",h:"the letter 'S'"},{t:"gut",m:"Goot",h:"like 'good' with a T"}]},
  "what is your name": {t:"wie heißen Sie", s:[{t:"wie",m:"Vee",h:"like 'V' — German W sounds like V"},{t:"hei",m:"High",h:"the word 'high' — EI sounds like 'eye'"},{t:"ßen",m:"Sun",h:"like 'sun' — ß sounds like SS"},{t:"Sie",m:"Zee",h:"like 'zee' — German S before vowel is Z"}]},
  "my name is": {t:"ich heiße", s:[{t:"ich",m:"Ish",h:"like 'ish' — CH after I is a soft hiss"},{t:"hei",m:"High",h:"the word 'high' — EI sounds like 'eye'"},{t:"ße",m:"Suh",h:"like 'sun' without N — ß sounds like SS"}]},
  "congratulations": {t:"herzlichen Glückwunsch", s:[{t:"herz",m:"Hairs",h:"like 'hairs' with a TS"},{t:"li",m:"Lih",h:"like 'lick' without CK"},{t:"chen",m:"Shen",h:"like 'shin' — CH after I is a soft hiss"},{t:"Glück",m:"Glick",h:"like 'click' with G — ü sounds like short I here"},{t:"wunsch",m:"Voonsh",h:"like 'voo' + 'nsh' — W sounds like V"}]},
  "happy birthday": {t:"alles Gute zum Geburtstag", s:[{t:"al",m:"Ahl",h:"like 'all' with AH"},{t:"les",m:"Less",h:"the word 'less'"},{t:"Gu",m:"Goo",h:"like 'goo'"},{t:"te",m:"Tuh",h:"like 'tug' without G"},{t:"zum",m:"Zoom",h:"the word 'zoom'"},{t:"Ge",m:"Guh",h:"like 'gut' without T"},{t:"burts",m:"Boots",h:"like 'boots'"},{t:"tag",m:"Tahk",h:"like 'tock' with an A"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"ja", s:[{t:"ja",m:"Yah",h:"like 'yard' without RD — J sounds like Y"}]},
  "no": {t:"nein", s:[{t:"nein",m:"Nine",h:"the number 'nine' — EI sounds like 'eye'"}]},
  "ok": {t:"in Ordnung", s:[{t:"in",m:"In",h:"the word 'in'"},{t:"Ord",m:"Ort",h:"like 'sort' without S"},{t:"nung",m:"Noong",h:"like 'noon' + 'g'"}]},
  "i understand": {t:"ich verstehe", s:[{t:"ich",m:"Ish",h:"like 'ish' — CH after I is soft"},{t:"ver",m:"Fair",h:"like 'fair' — V sounds like F"},{t:"ste",m:"Shtay",h:"like 'stay' with SH"},{t:"he",m:"Huh",h:"like 'huh'"}]},
  "i don't understand": {t:"ich verstehe nicht", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"ver",m:"Fair",h:"like 'fair' — V sounds like F"},{t:"ste",m:"Shtay",h:"like 'stay' with SH"},{t:"he",m:"Huh",h:"like 'huh'"},{t:"nicht",m:"Nisht",h:"like 'nish' + T — CH after I is soft"}]},
  "do you speak english": {t:"sprechen Sie Englisch", s:[{t:"spre",m:"Shpray",h:"like 'spray' with SH"},{t:"chen",m:"Shen",h:"like 'shin' — CH is soft"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"Eng",m:"Eng",h:"like 'eng' in 'English'"},{t:"lisch",m:"Lish",h:"the word 'lish'"}]},
  "slowly please": {t:"langsam bitte", s:[{t:"lang",m:"Long",h:"the word 'long'"},{t:"sam",m:"Zahm",h:"like 'psalm'"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "can you help me": {t:"können Sie mir helfen", s:[{t:"kön",m:"Kern",h:"like 'kern' — ö sounds like 'ur'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"mir",m:"Mere",h:"the word 'mere'"},{t:"hel",m:"Hell",h:"the word 'hell'"},{t:"fen",m:"Fun",h:"the word 'fun'"}]},
  "where is": {t:"wo ist", s:[{t:"wo",m:"Vo",h:"like 'vote' without TE — W sounds like V"},{t:"ist",m:"Ist",h:"like 'fist' without F"}]},
  "how much": {t:"wie viel", s:[{t:"wie",m:"Vee",h:"like 'V' — W sounds like V"},{t:"viel",m:"Feel",h:"the word 'feel' — V sounds like F"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"Hilfe", s:[{t:"Hil",m:"Hill",h:"the word 'hill'"},{t:"fe",m:"Fuh",h:"like 'fun' without N"}]},
  "emergency": {t:"Notfall", s:[{t:"Not",m:"Note",h:"the word 'note'"},{t:"fall",m:"Fall",h:"the word 'fall'"}]},
  "call the police": {t:"rufen Sie die Polizei", s:[{t:"ru",m:"Roo",h:"like 'rude' without DE"},{t:"fen",m:"Fun",h:"the word 'fun'"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"die",m:"Dee",h:"like 'dee' — IE sounds like 'ee'"},{t:"Po",m:"Po",h:"the name 'Po'"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"zei",m:"Tsye",h:"like 'ts' + 'eye' — Z sounds like TS, EI like 'eye'"}]},
  "call the doctor": {t:"rufen Sie den Arzt", s:[{t:"ru",m:"Roo",h:"like 'rude' without DE"},{t:"fen",m:"Fun",h:"the word 'fun'"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"den",m:"Den",h:"the word 'den'"},{t:"Arzt",m:"Arts",h:"like 'arts' — Z sounds like TS"}]},
  "hospital": {t:"Krankenhaus", s:[{t:"Kran",m:"Kron",h:"like 'cron' in chronic"},{t:"ken",m:"Ken",h:"the name 'Ken'"},{t:"haus",m:"House",h:"the word 'house'"}]},
  "fire": {t:"Feuer", s:[{t:"Feu",m:"Foy",h:"like 'foy' — EU sounds like 'oy'"},{t:"er",m:"Air",h:"the word 'air'"}]},
  "danger": {t:"Gefahr", s:[{t:"Ge",m:"Guh",h:"like 'gut' without T"},{t:"fahr",m:"Far",h:"the word 'far'"}]},
  "watch out": {t:"Vorsicht", s:[{t:"Vor",m:"For",h:"the word 'for' — V sounds like F"},{t:"sicht",m:"Zisht",h:"like 'zish' + T — CH after I is soft"}]},
  "i'm lost": {t:"ich habe mich verirrt", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"be",m:"Buh",h:"like 'but' without T"},{t:"mich",m:"Mish",h:"like 'mish'"},{t:"ver",m:"Fair",h:"like 'fair'"},{t:"irrt",m:"Eert",h:"like 'ear' + T"}]},
  "i'm sick": {t:"ich bin krank", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"bin",m:"Bin",h:"the word 'bin'"},{t:"krank",m:"Kronk",h:"like 'kronk'"}]},
  "call an ambulance": {t:"rufen Sie einen Krankenwagen", s:[{t:"ru",m:"Roo",h:"like 'rude' without DE"},{t:"fen",m:"Fun",h:"the word 'fun'"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"ei",m:"Eye",h:"the word 'eye'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Kran",m:"Kron",h:"like 'cron'"},{t:"ken",m:"Ken",h:"the name 'Ken'"},{t:"wa",m:"Vah",h:"like 'va' — W sounds like V"},{t:"gen",m:"Gun",h:"the word 'gun'"}]},
  "i need a doctor": {t:"ich brauche einen Arzt", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"brau",m:"Brow",h:"the word 'brow'"},{t:"che",m:"Khuh",h:"like a throaty 'huh' — CH after A is throaty"},{t:"ei",m:"Eye",h:"the word 'eye'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Arzt",m:"Arts",h:"like 'arts'"}]},
  "passport": {t:"Reisepass", s:[{t:"Rei",m:"Rye",h:"like 'rye' — EI sounds like 'eye'"},{t:"se",m:"Zuh",h:"like 'zug' without G — S before vowel is Z"},{t:"pass",m:"Pass",h:"the word 'pass'"}]},
  "theft": {t:"Diebstahl", s:[{t:"Dieb",m:"Deep",h:"like 'deep' — IE sounds like 'ee'"},{t:"stahl",m:"Shtahl",h:"like 'stall' with SH"}]},
  "police station": {t:"Polizeiwache", s:[{t:"Po",m:"Po",h:"the name 'Po'"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"zei",m:"Tsye",h:"'ts' + 'eye'"},{t:"wa",m:"Vah",h:"like 'va' — W sounds like V"},{t:"che",m:"Khuh",h:"like a throaty 'huh'"}]},

  // ===== NUMBERS 0-10, 20, 50, 100, 1000 (15) =====
  "zero": {t:"null", s:[{t:"null",m:"Nool",h:"like 'pool' with N"}]},
  "one": {t:"eins", s:[{t:"eins",m:"Eye-ns",h:"like 'eye' + NS — EI sounds like 'eye'"}]},
  "two": {t:"zwei", s:[{t:"zwei",m:"Tsvye",h:"like 'ts' + 'vie' — Z is TS, EI is 'eye'"}]},
  "three": {t:"drei", s:[{t:"drei",m:"Dry",h:"the word 'dry' — EI sounds like 'eye'"}]},
  "four": {t:"vier", s:[{t:"vier",m:"Fear",h:"the word 'fear' — V sounds like F, IE sounds like 'ee'"}]},
  "five": {t:"fünf", s:[{t:"fünf",m:"Fewnf",h:"like 'few' + NF — ü sounds like 'ew'"}]},
  "six": {t:"sechs", s:[{t:"sechs",m:"Zex",h:"like 'sex' with Z — S before vowel is Z, CHS is KS"}]},
  "seven": {t:"sieben", s:[{t:"sie",m:"Zee",h:"like 'zee'"},{t:"ben",m:"Ben",h:"the name 'Ben'"}]},
  "eight": {t:"acht", s:[{t:"acht",m:"Akht",h:"like 'act' with a throaty CH"}]},
  "nine": {t:"neun", s:[{t:"neun",m:"Noyn",h:"like 'noun' with OY — EU sounds like 'oy'"}]},
  "ten": {t:"zehn", s:[{t:"zehn",m:"Tsane",h:"like 'ts' + 'cane' — Z is TS"}]},
  "twenty": {t:"zwanzig", s:[{t:"zwan",m:"Tsvon",h:"like 'ts' + 'von'"},{t:"zig",m:"Tsish",h:"like 'ts' + 'ish' — G at end is soft"}]},
  "fifty": {t:"fünfzig", s:[{t:"fünf",m:"Fewnf",h:"like 'few' + NF"},{t:"zig",m:"Tsish",h:"like 'ts' + 'ish'"}]},
  "one hundred": {t:"hundert", s:[{t:"hun",m:"Hoon",h:"like 'hoon'"},{t:"dert",m:"Dair't",h:"like 'dare' + T"}]},
  "one thousand": {t:"tausend", s:[{t:"tau",m:"Tow",h:"like 'tower' without ER"},{t:"send",m:"Zent",h:"like 'zen' + T — S before vowel is Z"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"Wasser", s:[{t:"Was",m:"Vass",h:"like 'vase' without E — W sounds like V"},{t:"ser",m:"Zer",h:"like 'zur'"}]},
  "beer": {t:"Bier", s:[{t:"Bier",m:"Beer",h:"the word 'beer' — IE sounds like 'ee'"}]},
  "wine": {t:"Wein", s:[{t:"Wein",m:"Vine",h:"the word 'vine' — W is V, EI is 'eye'"}]},
  "red wine": {t:"Rotwein", s:[{t:"Rot",m:"Wrote",h:"like 'wrote'"},{t:"wein",m:"Vine",h:"the word 'vine'"}]},
  "white wine": {t:"Weißwein", s:[{t:"Weiß",m:"Vice",h:"like 'vice' — ß is SS"},{t:"wein",m:"Vine",h:"the word 'vine'"}]},
  "coffee": {t:"Kaffee", s:[{t:"Kaf",m:"Cuff",h:"the word 'cuff'"},{t:"fee",m:"Fay",h:"like 'fay' — stress on second syllable"}]},
  "tea": {t:"Tee", s:[{t:"Tee",m:"Tay",h:"like 'tay' — German EE sounds like 'ay'"}]},
  "milk": {t:"Milch", s:[{t:"Milch",m:"Milsh",h:"like 'milk' with a soft SH — CH after I is soft"}]},
  "juice": {t:"Saft", s:[{t:"Saft",m:"Zoft",h:"like 'soft' with Z — S before vowel is Z"}]},
  "bread": {t:"Brot", s:[{t:"Brot",m:"Brought",h:"like 'brought' without GH"}]},
  "butter": {t:"Butter", s:[{t:"But",m:"Boot",h:"like 'boot'"},{t:"ter",m:"Tare",h:"the word 'tare'"}]},
  "cheese": {t:"Käse", s:[{t:"Kä",m:"Kay",h:"like 'Kay' — ä sounds like 'eh' or 'ay'"},{t:"se",m:"Zuh",h:"like 'zug' without G — S before vowel is Z"}]},
  "egg": {t:"Ei", s:[{t:"Ei",m:"Eye",h:"the word 'eye' — EI sounds like 'eye'"}]},
  "meat": {t:"Fleisch", s:[{t:"Fleisch",m:"Flysh",h:"like 'fly' + 'sh' — EI is 'eye', SCH is SH"}]},
  "chicken": {t:"Hähnchen", s:[{t:"Hähn",m:"Hane",h:"like 'cane' with H — ä is 'ay'"},{t:"chen",m:"Shen",h:"like 'shin' — CH after vowel is soft"}]},
  "fish": {t:"Fisch", s:[{t:"Fisch",m:"Fish",h:"the word 'fish' — SCH sounds like SH"}]},
  "pork": {t:"Schweinefleisch", s:[{t:"Schwein",m:"Shvine",h:"like 'sh' + 'vine' — EI is 'eye'"},{t:"e",m:"Uh",h:"a quick 'uh'"},{t:"fleisch",m:"Flysh",h:"like 'fly' + 'sh'"}]},
  "sausage": {t:"Wurst", s:[{t:"Wurst",m:"Voorst",h:"like 'worst' with OO — W sounds like V"}]},
  "potato": {t:"Kartoffel", s:[{t:"Kar",m:"Car",h:"the word 'car'"},{t:"tof",m:"Toff",h:"like 'toff'"},{t:"fel",m:"Full",h:"the word 'full'"}]},
  "salad": {t:"Salat", s:[{t:"Sa",m:"Zah",h:"like 'zah' — S before vowel is Z"},{t:"lat",m:"Lot",h:"the word 'lot'"}]},
  "soup": {t:"Suppe", s:[{t:"Sup",m:"Zoop",h:"like 'soup' with Z"},{t:"pe",m:"Puh",h:"like 'pup' without final P"}]},
  "rice": {t:"Reis", s:[{t:"Reis",m:"Rice",h:"the word 'rice' — EI sounds like 'eye'"}]},
  "cake": {t:"Kuchen", s:[{t:"Ku",m:"Koo",h:"like 'cool' without L"},{t:"chen",m:"Khen",h:"like a throaty 'hen' — CH after U is throaty"}]},
  "ice cream": {t:"Eis", s:[{t:"Eis",m:"Ice",h:"the word 'ice' — EI sounds like 'eye'"}]},
  "fruit": {t:"Obst", s:[{t:"Obst",m:"Opst",h:"like 'opt' with S before the T"}]},
  "vegetables": {t:"Gemüse", s:[{t:"Ge",m:"Guh",h:"like 'gut' without T"},{t:"mü",m:"Mew",h:"like 'mew' — ü sounds like 'ew'"},{t:"se",m:"Zuh",h:"like 'zug' without G"}]},
  "sugar": {t:"Zucker", s:[{t:"Zu",m:"Tsoo",h:"like 'ts' + 'oo' — Z is TS"},{t:"cker",m:"Ker",h:"like 'cur'"}]},
  "salt": {t:"Salz", s:[{t:"Salz",m:"Zalts",h:"like 'salts' with Z — Z sounds like TS"}]},
  "pepper": {t:"Pfeffer", s:[{t:"Pfef",m:"Feff",h:"like 'feff' — PF is a single sound"},{t:"fer",m:"Fur",h:"the word 'fur'"}]},
  "pretzel": {t:"Brezel", s:[{t:"Bre",m:"Bray",h:"the word 'bray'"},{t:"zel",m:"Tsel",h:"like 'ts' + 'ell' — Z is TS"}]},

  // ===== RESTAURANT (15) =====
  "a table for two please": {t:"einen Tisch für zwei bitte", s:[{t:"ei",m:"Eye",h:"the word 'eye'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Tisch",m:"Tish",h:"like 'tish'"},{t:"für",m:"Few-er",h:"like 'fewer' — ü sounds like 'ew'"},{t:"zwei",m:"Tsvye",h:"like 'ts' + 'vie'"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "the menu please": {t:"die Speisekarte bitte", s:[{t:"die",m:"Dee",h:"like 'dee' — IE is 'ee'"},{t:"Spei",m:"Shpy",h:"like 'sh' + 'pie' — EI is 'eye'"},{t:"se",m:"Zuh",h:"like 'zug' without G"},{t:"kar",m:"Car",h:"the word 'car'"},{t:"te",m:"Tuh",h:"like 'tug' without G"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "i would like": {t:"ich möchte", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"möch",m:"Mursh",h:"like 'mush' with R — ö is 'ur', CH is soft"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "the bill please": {t:"die Rechnung bitte", s:[{t:"die",m:"Dee",h:"like 'dee'"},{t:"Rech",m:"Resh",h:"like 'resh' — CH is soft after E"},{t:"nung",m:"Noong",h:"like 'noon' + G"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "breakfast": {t:"Frühstück", s:[{t:"Früh",m:"Frew",h:"like 'brew' with F — ü is 'ew'"},{t:"stück",m:"Shtick",h:"like 'shtick' — ü is short here"}]},
  "lunch": {t:"Mittagessen", s:[{t:"Mit",m:"Mit",h:"the word 'mitt'"},{t:"tag",m:"Tahk",h:"like 'tock' with A"},{t:"es",m:"Ess",h:"the letter 'S'"},{t:"sen",m:"Zen",h:"the word 'zen'"}]},
  "dinner": {t:"Abendessen", s:[{t:"A",m:"Ah",h:"the sound 'ah'"},{t:"bend",m:"Bent",h:"the word 'bent'"},{t:"es",m:"Ess",h:"the letter 'S'"},{t:"sen",m:"Zen",h:"the word 'zen'"}]},
  "delicious": {t:"lecker", s:[{t:"le",m:"Leh",h:"like 'let' without T"},{t:"cker",m:"Ker",h:"like 'cur'"}]},
  "i am a vegetarian": {t:"ich bin Vegetarier", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"bin",m:"Bin",h:"the word 'bin'"},{t:"Ve",m:"Fay",h:"like 'fay' — V sounds like F"},{t:"ge",m:"Gay",h:"like 'gay'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"ri",m:"Ree",h:"like 'ree'"},{t:"er",m:"Air",h:"the word 'air'"}]},
  "with": {t:"mit", s:[{t:"mit",m:"Mit",h:"the word 'mitt'"}]},
  "without": {t:"ohne", s:[{t:"oh",m:"Oh",h:"the word 'oh'"},{t:"ne",m:"Nuh",h:"like 'nut' without T"}]},
  "i am allergic to": {t:"ich bin allergisch gegen", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"bin",m:"Bin",h:"the word 'bin'"},{t:"al",m:"Ahl",h:"like 'all' with AH"},{t:"ler",m:"Lair",h:"the word 'lair'"},{t:"gisch",m:"Gish",h:"like 'gish'"},{t:"ge",m:"Gay",h:"like 'gay'"},{t:"gen",m:"Gun",h:"the word 'gun'"}]},
  "glass of water": {t:"ein Glas Wasser", s:[{t:"ein",m:"Eye-n",h:"like 'eye' + N"},{t:"Glas",m:"Glass",h:"the word 'glass'"},{t:"Was",m:"Vass",h:"like 'vase' without E"},{t:"ser",m:"Zer",h:"like 'zur'"}]},
  "another one please": {t:"noch eins bitte", s:[{t:"noch",m:"Nokh",h:"like 'knock' without K — CH is throaty"},{t:"eins",m:"Eye-ns",h:"like 'eye' + NS"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "cheers": {t:"Prost", s:[{t:"Prost",m:"Proast",h:"like 'roast' with P"}]},

  // ===== SHOPPING (20) =====
  "how much does this cost": {t:"wie viel kostet das", s:[{t:"wie",m:"Vee",h:"like 'V'"},{t:"viel",m:"Feel",h:"the word 'feel'"},{t:"kos",m:"Cost",h:"the word 'cost'"},{t:"tet",m:"Tet",h:"like 'tet'"},{t:"das",m:"Doss",h:"like 'doss'"}]},
  "too expensive": {t:"zu teuer", s:[{t:"zu",m:"Tsoo",h:"like 'ts' + 'oo' — Z is TS"},{t:"teu",m:"Toy",h:"like 'toy' — EU sounds like 'oy'"},{t:"er",m:"Air",h:"the word 'air'"}]},
  "cheap": {t:"billig", s:[{t:"bil",m:"Bill",h:"the name 'Bill'"},{t:"lig",m:"Lish",h:"like 'lish' — G at end is soft"}]},
  "can i pay by card": {t:"kann ich mit Karte zahlen", s:[{t:"kann",m:"Con",h:"like 'con'"},{t:"ich",m:"Ish",h:"like 'ish'"},{t:"mit",m:"Mit",h:"the word 'mitt'"},{t:"Kar",m:"Car",h:"the word 'car'"},{t:"te",m:"Tuh",h:"like 'tug' without G"},{t:"zah",m:"Tsah",h:"like 'ts' + 'ah' — Z is TS"},{t:"len",m:"Len",h:"the name 'Len'"}]},
  "cash": {t:"Bargeld", s:[{t:"Bar",m:"Bar",h:"the word 'bar'"},{t:"geld",m:"Gelt",h:"like 'felt' with G"}]},
  "receipt": {t:"Quittung", s:[{t:"Quit",m:"Kvit",h:"like 'knit' with KV — QU sounds like KV"},{t:"tung",m:"Toong",h:"like 'tune' + G"}]},
  "i'm just looking": {t:"ich schaue nur", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"schau",m:"Show",h:"like 'shower' without ER"},{t:"e",m:"Uh",h:"a quick 'uh'"},{t:"nur",m:"Noor",h:"like 'nor' with OO"}]},
  "bigger": {t:"größer", s:[{t:"grö",m:"Grur",h:"like 'gr' + 'ur' — ö sounds like 'ur'"},{t:"ßer",m:"Ser",h:"like 'sir' — ß is SS"}]},
  "smaller": {t:"kleiner", s:[{t:"klei",m:"Kline",h:"like 'climb' without B — EI is 'eye'"},{t:"ner",m:"Ner",h:"like 'nur'"}]},
  "open": {t:"geöffnet", s:[{t:"ge",m:"Guh",h:"like 'gut' without T"},{t:"öff",m:"Urf",h:"like 'earth' without TH — ö is 'ur'"},{t:"net",m:"Net",h:"the word 'net'"}]},
  "closed": {t:"geschlossen", s:[{t:"ge",m:"Guh",h:"like 'gut' without T"},{t:"schlos",m:"Shloss",h:"like 'floss' with SHL"},{t:"sen",m:"Zen",h:"the word 'zen'"}]},
  "do you have": {t:"haben Sie", s:[{t:"ha",m:"Hah",h:"like 'ha'"},{t:"ben",m:"Ben",h:"the name 'Ben'"},{t:"Sie",m:"Zee",h:"like 'zee'"}]},
  "bag": {t:"Tüte", s:[{t:"Tü",m:"Tew",h:"like 'stew' without S — ü is 'ew'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "color": {t:"Farbe", s:[{t:"Far",m:"Far",h:"the word 'far'"},{t:"be",m:"Buh",h:"like 'but' without T"}]},
  "size": {t:"Größe", s:[{t:"Grö",m:"Grur",h:"like 'gr' + 'ur' — ö is 'ur'"},{t:"ße",m:"Suh",h:"like 'sun' without N — ß is SS"}]},
  "this one": {t:"dieses", s:[{t:"die",m:"Dee",h:"like 'dee' — IE is 'ee'"},{t:"ses",m:"Zess",h:"like 'zest' without T"}]},
  "that one": {t:"das da", s:[{t:"das",m:"Doss",h:"like 'doss'"},{t:"da",m:"Dah",h:"like 'da'"}]},
  "i'll take it": {t:"ich nehme es", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"neh",m:"Nay",h:"the word 'nay'"},{t:"me",m:"Muh",h:"like 'mud' without D"},{t:"es",m:"Ess",h:"the letter 'S'"}]},
  "entrance": {t:"Eingang", s:[{t:"Ein",m:"Eye-n",h:"like 'eye' + N — EI is 'eye'"},{t:"gang",m:"Gong",h:"the word 'gong'"}]},
  "exit": {t:"Ausgang", s:[{t:"Aus",m:"Ouse",h:"like 'house' without H"},{t:"gang",m:"Gong",h:"the word 'gong'"}]},

  // ===== DIRECTIONS (25) =====
  "where is the bathroom": {t:"wo ist die Toilette", s:[{t:"wo",m:"Vo",h:"like 'vote' without TE"},{t:"ist",m:"Ist",h:"like 'fist' without F"},{t:"die",m:"Dee",h:"like 'dee'"},{t:"Toi",m:"Toy",h:"the word 'toy'"},{t:"let",m:"Let",h:"the word 'let'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "left": {t:"links", s:[{t:"links",m:"Links",h:"the word 'links'"}]},
  "right": {t:"rechts", s:[{t:"rechts",m:"Reshts",h:"like 'rests' with SH — CH after E is soft"}]},
  "straight ahead": {t:"geradeaus", s:[{t:"ge",m:"Guh",h:"like 'gut' without T"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"aus",m:"Ouse",h:"like 'house' without H"}]},
  "north": {t:"Norden", s:[{t:"Nor",m:"Nor",h:"the word 'nor'"},{t:"den",m:"Den",h:"the word 'den'"}]},
  "south": {t:"Süden", s:[{t:"Sü",m:"Zew",h:"like 'zoo' with EW — ü is 'ew'"},{t:"den",m:"Den",h:"the word 'den'"}]},
  "east": {t:"Osten", s:[{t:"Os",m:"Oast",h:"like 'oast'"},{t:"ten",m:"Ten",h:"the number 'ten'"}]},
  "west": {t:"Westen", s:[{t:"Wes",m:"Vest",h:"like 'vest' — W sounds like V"},{t:"ten",m:"Ten",h:"the number 'ten'"}]},
  "near": {t:"nah", s:[{t:"nah",m:"Nah",h:"the word 'nah'"}]},
  "far": {t:"weit", s:[{t:"weit",m:"Vite",h:"like 'invite' without IN — W is V, EI is 'eye'"}]},
  "here": {t:"hier", s:[{t:"hier",m:"Here",h:"the word 'here' — IE is 'ee'"}]},
  "there": {t:"dort", s:[{t:"dort",m:"Dort",h:"like 'door' + T"}]},
  "street": {t:"Straße", s:[{t:"Stra",m:"Shtrah",h:"like 'shtrah' — ST at start is SHT"},{t:"ße",m:"Suh",h:"like 'sun' without N — ß is SS"}]},
  "corner": {t:"Ecke", s:[{t:"Eck",m:"Eck",h:"like 'deck' without D"},{t:"e",m:"Uh",h:"a quick 'uh'"}]},
  "bridge": {t:"Brücke", s:[{t:"Brü",m:"Brew",h:"like 'brew' — ü is 'ew'"},{t:"cke",m:"Kuh",h:"like 'cup' without P"}]},
  "train station": {t:"Bahnhof", s:[{t:"Bahn",m:"Bahn",h:"like 'bon' in French"},{t:"hof",m:"Hoff",h:"like 'off' with H"}]},
  "airport": {t:"Flughafen", s:[{t:"Flug",m:"Floog",h:"like 'flew' + G"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"fen",m:"Fun",h:"the word 'fun'"}]},
  "bus stop": {t:"Bushaltestelle", s:[{t:"Bus",m:"Boos",h:"like 'boost' without T"},{t:"hal",m:"Halt",h:"the word 'halt'"},{t:"te",m:"Tuh",h:"like 'tug' without G"},{t:"stel",m:"Shtel",h:"like 'sh' + 'tell'"},{t:"le",m:"Luh",h:"like 'luck' without CK"}]},
  "taxi": {t:"Taxi", s:[{t:"Tax",m:"Tax",h:"the word 'tax'"},{t:"i",m:"Ee",h:"the sound 'ee'"}]},
  "subway": {t:"U-Bahn", s:[{t:"U",m:"Oo",h:"the sound 'oo'"},{t:"Bahn",m:"Bahn",h:"like 'bon'"}]},
  "how do i get to": {t:"wie komme ich zu", s:[{t:"wie",m:"Vee",h:"like 'V'"},{t:"kom",m:"Come",h:"the word 'come'"},{t:"me",m:"Muh",h:"like 'mud' without D"},{t:"ich",m:"Ish",h:"like 'ish'"},{t:"zu",m:"Tsoo",h:"like 'ts' + 'oo'"}]},
  "is it far": {t:"ist es weit", s:[{t:"ist",m:"Ist",h:"like 'fist' without F"},{t:"es",m:"Ess",h:"the letter 'S'"},{t:"weit",m:"Vite",h:"like 'invite' without IN"}]},
  "map": {t:"Karte", s:[{t:"Kar",m:"Car",h:"the word 'car'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "next to": {t:"neben", s:[{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"ben",m:"Ben",h:"the name 'Ben'"}]},
  "across from": {t:"gegenüber", s:[{t:"ge",m:"Gay",h:"like 'gay'"},{t:"gen",m:"Gun",h:"the word 'gun'"},{t:"ü",m:"Ew",h:"like 'ew' — ü sounds like 'ew'"},{t:"ber",m:"Bare",h:"the word 'bare'"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"Hotel", s:[{t:"Ho",m:"Ho",h:"like 'ho'"},{t:"tel",m:"Tell",h:"the word 'tell'"}]},
  "room": {t:"Zimmer", s:[{t:"Zim",m:"Tsim",h:"like 'ts' + 'him' — Z is TS"},{t:"mer",m:"Mer",h:"like 'mare'"}]},
  "single room": {t:"Einzelzimmer", s:[{t:"Ein",m:"Eye-n",h:"like 'eye' + N"},{t:"zel",m:"Tsel",h:"like 'ts' + 'ell'"},{t:"zim",m:"Tsim",h:"like 'ts' + 'him'"},{t:"mer",m:"Mer",h:"like 'mare'"}]},
  "double room": {t:"Doppelzimmer", s:[{t:"Dop",m:"Dop",h:"like 'drop' without R"},{t:"pel",m:"Pell",h:"like 'spell' without S"},{t:"zim",m:"Tsim",h:"like 'ts' + 'him'"},{t:"mer",m:"Mer",h:"like 'mare'"}]},
  "reservation": {t:"Reservierung", s:[{t:"Re",m:"Ray",h:"the word 'ray'"},{t:"ser",m:"Zer",h:"like 'zur'"},{t:"vie",m:"Fee",h:"like 'fee' — V sounds like F"},{t:"rung",m:"Roong",h:"like 'roo' + NG"}]},
  "i have a reservation": {t:"ich habe eine Reservierung", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"be",m:"Buh",h:"like 'but' without T"},{t:"ei",m:"Eye",h:"the word 'eye'"},{t:"ne",m:"Nuh",h:"like 'nut' without T"},{t:"Re",m:"Ray",h:"the word 'ray'"},{t:"ser",m:"Zer",h:"like 'zur'"},{t:"vie",m:"Fee",h:"like 'fee'"},{t:"rung",m:"Roong",h:"like 'roo' + NG"}]},
  "key": {t:"Schlüssel", s:[{t:"Schlüs",m:"Shlews",h:"like 'sh' + 'loose' — ü is 'ew'"},{t:"sel",m:"Zel",h:"like 'sell' with Z"}]},
  "how much per night": {t:"wie viel pro Nacht", s:[{t:"wie",m:"Vee",h:"like 'V'"},{t:"viel",m:"Feel",h:"the word 'feel'"},{t:"pro",m:"Pro",h:"the word 'pro'"},{t:"Nacht",m:"Knocked",h:"like 'knocked' — CH is throaty"}]},
  "one night": {t:"eine Nacht", s:[{t:"ei",m:"Eye",h:"the word 'eye'"},{t:"ne",m:"Nuh",h:"like 'nut' without T"},{t:"Nacht",m:"Knocked",h:"like 'knocked'"}]},
  "two nights": {t:"zwei Nächte", s:[{t:"zwei",m:"Tsvye",h:"like 'ts' + 'vie'"},{t:"Näch",m:"Nesh",h:"like 'mesh' with N — ä is 'eh', CH is soft"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "check in": {t:"einchecken", s:[{t:"ein",m:"Eye-n",h:"like 'eye' + N"},{t:"check",m:"Check",h:"the word 'check'"},{t:"en",m:"En",h:"like 'end' without D"}]},
  "check out": {t:"auschecken", s:[{t:"aus",m:"Ouse",h:"like 'house' without H"},{t:"check",m:"Check",h:"the word 'check'"},{t:"en",m:"En",h:"like 'end' without D"}]},
  "elevator": {t:"Aufzug", s:[{t:"Auf",m:"Owf",h:"like 'ouch' + F"},{t:"zug",m:"Tsook",h:"like 'ts' + 'ook' — Z is TS"}]},
  "floor": {t:"Stockwerk", s:[{t:"Stock",m:"Shtock",h:"like 'stock' with SH — ST at start is SHT"},{t:"werk",m:"Vairk",h:"like 'work' with V — W is V"}]},
  "wifi password": {t:"WLAN-Passwort", s:[{t:"WLAN",m:"Vay-lon",h:"like 'vay' + 'lawn' — W is V"},{t:"Pass",m:"Pass",h:"the word 'pass'"},{t:"wort",m:"Vort",h:"like 'fort' with V — W is V"}]},

  // ===== COMMUNICATION (15) =====
  "i don't speak german": {t:"ich spreche kein Deutsch", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"spre",m:"Shpray",h:"like 'spray' with SH"},{t:"che",m:"Khuh",h:"like a throaty 'huh'"},{t:"kein",m:"Kine",h:"like 'kind' without D — EI is 'eye'"},{t:"Deutsch",m:"Doytch",h:"like 'boy' + 'ch' — EU is 'oy'"}]},
  "can you repeat that": {t:"können Sie das wiederholen", s:[{t:"kön",m:"Kern",h:"like 'kern' — ö is 'ur'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"das",m:"Doss",h:"like 'doss'"},{t:"wie",m:"Vee",h:"like 'V'"},{t:"der",m:"Dare",h:"the word 'dare'"},{t:"ho",m:"Ho",h:"like 'ho'"},{t:"len",m:"Len",h:"the name 'Len'"}]},
  "what does that mean": {t:"was bedeutet das", s:[{t:"was",m:"Voss",h:"like 'voss' — W is V"},{t:"be",m:"Buh",h:"like 'but' without T"},{t:"deu",m:"Doy",h:"like 'boy' with D — EU is 'oy'"},{t:"tet",m:"Tet",h:"like 'tet'"},{t:"das",m:"Doss",h:"like 'doss'"}]},
  "can you write it down": {t:"können Sie das aufschreiben", s:[{t:"kön",m:"Kern",h:"like 'kern'"},{t:"nen",m:"Nen",h:"like 'pen' with N"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"das",m:"Doss",h:"like 'doss'"},{t:"auf",m:"Owf",h:"like 'ouch' + F"},{t:"schrei",m:"Shry",h:"like 'sh' + 'rye' — EI is 'eye'"},{t:"ben",m:"Ben",h:"the name 'Ben'"}]},
  "telephone": {t:"Telefon", s:[{t:"Te",m:"Tay",h:"like 'tay'"},{t:"le",m:"Luh",h:"like 'luck' without CK"},{t:"fon",m:"Phone",h:"the word 'phone'"}]},
  "internet": {t:"Internet", s:[{t:"In",m:"In",h:"the word 'in'"},{t:"ter",m:"Ter",h:"like 'tare'"},{t:"net",m:"Net",h:"the word 'net'"}]},
  "email": {t:"E-Mail", s:[{t:"E",m:"Ay",h:"the letter 'A'"},{t:"Mail",m:"Mail",h:"the word 'mail'"}]},
  "what time is it": {t:"wie spät ist es", s:[{t:"wie",m:"Vee",h:"like 'V'"},{t:"spät",m:"Shpayt",h:"like 'sh' + 'pate' — ä is 'ay'"},{t:"ist",m:"Ist",h:"like 'fist' without F"},{t:"es",m:"Ess",h:"the letter 'S'"}]},
  "today": {t:"heute", s:[{t:"heu",m:"Hoy",h:"like 'hoy' — EU sounds like 'oy'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "tomorrow": {t:"morgen", s:[{t:"Mor",m:"More",h:"the word 'more'"},{t:"gen",m:"Gun",h:"the word 'gun'"}]},
  "yesterday": {t:"gestern", s:[{t:"ges",m:"Guest",h:"like 'guest' without T"},{t:"tern",m:"Tairn",h:"like 'turn' with AI"}]},
  "do you have wifi": {t:"haben Sie WLAN", s:[{t:"ha",m:"Hah",h:"like 'ha'"},{t:"ben",m:"Ben",h:"the name 'Ben'"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"WLAN",m:"Vay-lon",h:"like 'vay' + 'lawn'"}]},
  "i need help": {t:"ich brauche Hilfe", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"brau",m:"Brow",h:"the word 'brow'"},{t:"che",m:"Khuh",h:"like a throaty 'huh'"},{t:"Hil",m:"Hill",h:"the word 'hill'"},{t:"fe",m:"Fuh",h:"like 'fun' without N"}]},
  "speak more slowly": {t:"sprechen Sie bitte langsamer", s:[{t:"spre",m:"Shpray",h:"like 'spray' with SH"},{t:"chen",m:"Shen",h:"like 'shin'"},{t:"Sie",m:"Zee",h:"like 'zee'"},{t:"bit",m:"Bit",h:"the word 'bit'"},{t:"te",m:"Tuh",h:"like 'tug' without G"},{t:"lang",m:"Long",h:"the word 'long'"},{t:"sa",m:"Zah",h:"like 'zah'"},{t:"mer",m:"Mer",h:"like 'mare'"}]},
  "i speak a little german": {t:"ich spreche ein bisschen Deutsch", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"spre",m:"Shpray",h:"like 'spray' with SH"},{t:"che",m:"Khuh",h:"throaty 'huh'"},{t:"ein",m:"Eye-n",h:"like 'eye' + N"},{t:"biss",m:"Bis",h:"like 'bliss' without L"},{t:"chen",m:"Shen",h:"like 'shin'"},{t:"Deutsch",m:"Doytch",h:"like 'boy' + 'ch'"}]},

  // ===== HEALTH (10) =====
  "pharmacy": {t:"Apotheke", s:[{t:"A",m:"Ah",h:"the sound 'ah'"},{t:"po",m:"Po",h:"the name 'Po'"},{t:"the",m:"Tay",h:"like 'tay'"},{t:"ke",m:"Kuh",h:"like 'cup' without P"}]},
  "i have a headache": {t:"ich habe Kopfschmerzen", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"be",m:"Buh",h:"like 'but' without T"},{t:"Kopf",m:"Copf",h:"like 'cop' + F"},{t:"schmer",m:"Shmair",h:"like 'sh' + 'mare'"},{t:"zen",m:"Tsen",h:"like 'ts' + 'en' — Z is TS"}]},
  "i have a fever": {t:"ich habe Fieber", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"be",m:"Buh",h:"like 'but' without T"},{t:"Fie",m:"Fee",h:"like 'fee' — IE is 'ee'"},{t:"ber",m:"Bare",h:"the word 'bare'"}]},
  "it hurts here": {t:"es tut hier weh", s:[{t:"es",m:"Ess",h:"the letter 'S'"},{t:"tut",m:"Toot",h:"the word 'toot'"},{t:"hier",m:"Here",h:"the word 'here'"},{t:"weh",m:"Vay",h:"like 'vay' — W is V"}]},
  "i need medicine": {t:"ich brauche Medizin", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"brau",m:"Brow",h:"the word 'brow'"},{t:"che",m:"Khuh",h:"throaty 'huh'"},{t:"Me",m:"May",h:"the month 'May'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"zin",m:"Tseen",h:"like 'ts' + 'een' — Z is TS"}]},
  "doctor": {t:"Arzt", s:[{t:"Arzt",m:"Arts",h:"like 'arts' — Z sounds like TS"}]},
  "dentist": {t:"Zahnarzt", s:[{t:"Zahn",m:"Tsahn",h:"like 'ts' + 'on' — Z is TS"},{t:"arzt",m:"Arts",h:"like 'arts'"}]},
  "i am pregnant": {t:"ich bin schwanger", s:[{t:"ich",m:"Ish",h:"like 'ish'"},{t:"bin",m:"Bin",h:"the word 'bin'"},{t:"schwan",m:"Shvon",h:"like 'sh' + 'von' — W is V"},{t:"ger",m:"Ger",h:"like 'gear' without A"}]},
  "pain": {t:"Schmerzen", s:[{t:"Schmer",m:"Shmair",h:"like 'sh' + 'mare'"},{t:"zen",m:"Tsen",h:"like 'ts' + 'en'"}]},
  "hospital emergency": {t:"Notaufnahme", s:[{t:"Not",m:"Note",h:"the word 'note'"},{t:"auf",m:"Owf",h:"like 'ouch' + F"},{t:"nah",m:"Nah",h:"the word 'nah'"},{t:"me",m:"Muh",h:"like 'mud' without D"}]},

  // ===== TIME (10) =====
  "morning": {t:"Morgen", s:[{t:"Mor",m:"More",h:"the word 'more'"},{t:"gen",m:"Gun",h:"the word 'gun'"}]},
  "afternoon": {t:"Nachmittag", s:[{t:"Nach",m:"Nakh",h:"like 'knock' without K — CH is throaty"},{t:"mit",m:"Mit",h:"the word 'mitt'"},{t:"tag",m:"Tahk",h:"like 'tock' with A"}]},
  "evening": {t:"Abend", s:[{t:"A",m:"Ah",h:"the sound 'ah'"},{t:"bend",m:"Bent",h:"the word 'bent'"}]},
  "night": {t:"Nacht", s:[{t:"Nacht",m:"Knocked",h:"like 'knocked' — CH is throaty"}]},
  "now": {t:"jetzt", s:[{t:"jetzt",m:"Yetst",h:"like 'yet' + ST — J is Y, Z is TS"}]},
  "later": {t:"später", s:[{t:"spä",m:"Shpay",h:"like 'sh' + 'pay' — ä is 'ay'"},{t:"ter",m:"Ter",h:"like 'tare'"}]},
  "soon": {t:"bald", s:[{t:"bald",m:"Bolt",h:"like 'bolt'"}]},
  "what day is today": {t:"welcher Tag ist heute", s:[{t:"wel",m:"Vel",h:"like 'velvet' without VET — W is V"},{t:"cher",m:"Sher",h:"like 'shir' — CH is soft after E"},{t:"Tag",m:"Tahk",h:"like 'tock' with A"},{t:"ist",m:"Ist",h:"like 'fist' without F"},{t:"heu",m:"Hoy",h:"like 'hoy' — EU is 'oy'"},{t:"te",m:"Tuh",h:"like 'tug' without G"}]},
  "monday": {t:"Montag", s:[{t:"Mon",m:"Moan",h:"the word 'moan'"},{t:"tag",m:"Tahk",h:"like 'tock' with A"}]},
  "weekend": {t:"Wochenende", s:[{t:"Wo",m:"Vo",h:"like 'vote' without TE"},{t:"chen",m:"Khen",h:"throaty 'hen' — CH after O is throaty"},{t:"en",m:"En",h:"like 'end' without D"},{t:"de",m:"Duh",h:"like 'duh'"}]},

  // ===== WEATHER (10) =====
  "what is the weather like": {t:"wie ist das Wetter", s:[{t:"wie",m:"Vee",h:"like 'V'"},{t:"ist",m:"Ist",h:"like 'fist' without F"},{t:"das",m:"Doss",h:"like 'doss'"},{t:"Wet",m:"Vet",h:"like 'vet' — W is V"},{t:"ter",m:"Ter",h:"like 'tare'"}]},
  "hot": {t:"heiß", s:[{t:"heiß",m:"Hice",h:"like 'heist' without T — EI is 'eye', ß is SS"}]},
  "cold": {t:"kalt", s:[{t:"kalt",m:"Colt",h:"like 'colt'"}]},
  "it's raining": {t:"es regnet", s:[{t:"es",m:"Ess",h:"the letter 'S'"},{t:"reg",m:"Rake",h:"like 'rake' — E sounds like 'ay'"},{t:"net",m:"Net",h:"the word 'net'"}]},
  "it's snowing": {t:"es schneit", s:[{t:"es",m:"Ess",h:"the letter 'S'"},{t:"schneit",m:"Shnite",h:"like 'sh' + 'night' without GH — EI is 'eye'"}]},
  "sunny": {t:"sonnig", s:[{t:"son",m:"Zone",h:"like 'zone'"},{t:"nig",m:"Nish",h:"like 'nish' — G at end is soft"}]},
  "cloudy": {t:"bewölkt", s:[{t:"be",m:"Buh",h:"like 'but' without T"},{t:"wölkt",m:"Vurlkt",h:"like 'V' + 'oolked' — ö is 'ur', W is V"}]},
  "windy": {t:"windig", s:[{t:"win",m:"Vin",h:"like 'vin' — W sounds like V"},{t:"dig",m:"Dish",h:"like 'dish' — G at end is soft"}]},
  "umbrella": {t:"Regenschirm", s:[{t:"Re",m:"Ray",h:"the word 'ray'"},{t:"gen",m:"Gun",h:"the word 'gun'"},{t:"schirm",m:"Sheerm",h:"like 'sheer' + M — SCH is SH"}]},
  "temperature": {t:"Temperatur", s:[{t:"Tem",m:"Tem",h:"like 'temp' without P"},{t:"pe",m:"Puh",h:"like 'pup' without final P"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"tur",m:"Tour",h:"the word 'tour'"}]}
};
