// dict-it.js — Italian phrase dictionary (200+ entries)
// Auto-generated for HowDoISay app
var DICT_IT = {
  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"ciao", s:[{t:"ciao",m:"Chow",h:"like 'chow' mein"}]},
  "good morning": {t:"buongiorno", s:[{t:"buon",m:"Boon",h:"the word 'boon'"},{t:"gior",m:"Jaw",h:"like 'jaw' — Italian GI sounds like English J"},{t:"no",m:"No",h:"the word 'no'"}]},
  "good afternoon": {t:"buon pomeriggio", s:[{t:"buon",m:"Boon",h:"the word 'boon'"},{t:"po",m:"Poe",h:"like the name 'Poe'"},{t:"me",m:"May",h:"the month 'May'"},{t:"rig",m:"Reed",h:"like 'reed' — double G is strong"},{t:"gio",m:"Joe",h:"the name 'Joe'"}]},
  "good evening": {t:"buonasera", s:[{t:"buo",m:"Boo",h:"the word 'boo'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"se",m:"Say",h:"the word 'say'"},{t:"ra",m:"Rah",h:"like 'rah rah'"}]},
  "good night": {t:"buonanotte", s:[{t:"buo",m:"Boo",h:"the word 'boo'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"not",m:"Not",h:"the word 'not'"},{t:"te",m:"Tay",h:"like 'tay' — Italian E is 'ay'"}]},
  "goodbye": {t:"arrivederci", s:[{t:"ar",m:"Are",h:"the word 'are' — roll the R"},{t:"ri",m:"Ree",h:"the word 'ree' — roll the R"},{t:"ve",m:"Vay",h:"'vay' like in 'survey'"},{t:"der",m:"Dare",h:"the word 'dare'"},{t:"ci",m:"Chee",h:"like 'chee' — Italian CI sounds 'chee'"}]},
  "thank you": {t:"grazie", s:[{t:"gra",m:"Grah",h:"'grah' — roll the R"},{t:"zie",m:"Zee-ay",h:"the letter 'Z' + 'ay'"}]},
  "thank you very much": {t:"grazie mille", s:[{t:"gra",m:"Grah",h:"'grah' — roll the R"},{t:"zie",m:"Zee-ay",h:"the letter 'Z' + 'ay'"},{t:"mil",m:"Meal",h:"the word 'meal'"},{t:"le",m:"Lay",h:"the word 'lay'"}]},
  "you're welcome": {t:"prego", s:[{t:"pre",m:"Pray",h:"the word 'pray'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "excuse me": {t:"mi scusi", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"scu",m:"Skoo",h:"like 'school' without the L"},{t:"si",m:"See",h:"the word 'see'"}]},
  "i'm sorry": {t:"mi dispiace", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"spia",m:"Spee-ah",h:"'spee' + 'ah'"},{t:"ce",m:"Chay",h:"like 'chay' — Italian CE sounds 'chay'"}]},
  "please": {t:"per favore", s:[{t:"per",m:"Pair",h:"the word 'pair'"},{t:"fa",m:"Fah",h:"the musical note 'fa'"},{t:"vo",m:"Voh",h:"'voh' like 'vow' without the W"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "nice to meet you": {t:"piacere di conoscerti", s:[{t:"pia",m:"Pee-ah",h:"'pee' + 'ah'"},{t:"ce",m:"Chay",h:"Italian CE sounds 'chay'"},{t:"re",m:"Ray",h:"the word 'ray'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"co",m:"Ko",h:"like 'co' in company"},{t:"no",m:"No",h:"the word 'no'"},{t:"scer",m:"Share",h:"like 'share' — Italian SCE sounds 'shay'"},{t:"ti",m:"Tea",h:"the word 'tea'"}]},
  "how are you": {t:"come stai", s:[{t:"co",m:"Ko",h:"like 'co' in company"},{t:"me",m:"May",h:"the month 'May'"},{t:"stai",m:"Sty",h:"the word 'sty'"}]},
  "i'm fine": {t:"sto bene", s:[{t:"sto",m:"Stow",h:"the word 'stow'"},{t:"be",m:"Bay",h:"the word 'bay'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "what is your name": {t:"come ti chiami", s:[{t:"co",m:"Ko",h:"like 'co' in company"},{t:"me",m:"May",h:"the month 'May'"},{t:"ti",m:"Tea",h:"the word 'tea'"},{t:"chia",m:"Key-ah",h:"'key' + 'ah' — Italian CHI sounds 'key'"},{t:"mi",m:"Me",h:"the word 'me'"}]},
  "my name is": {t:"mi chiamo", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"chia",m:"Key-ah",h:"'key' + 'ah' — Italian CHI sounds 'key'"},{t:"mo",m:"Mo",h:"the name 'Mo'"}]},
  "pleased to meet you": {t:"molto lieto", s:[{t:"mol",m:"Mole",h:"the word 'mole'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"lie",m:"Lee-ay",h:"the word 'lee' + 'ay'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "congratulations": {t:"congratulazioni", s:[{t:"con",m:"Cone",h:"the word 'cone'"},{t:"gra",m:"Grah",h:"'grah' — roll the R"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"zio",m:"Zee-oh",h:"the letter 'Z' + 'oh'"},{t:"ni",m:"Knee",h:"the word 'knee'"}]},
  "happy birthday": {t:"buon compleanno", s:[{t:"buon",m:"Boon",h:"the word 'boon'"},{t:"com",m:"Comb",h:"the word 'comb'"},{t:"ple",m:"Play",h:"the word 'play'"},{t:"an",m:"Ahn",h:"like 'on' with an A"},{t:"no",m:"No",h:"the word 'no' — stress the double N"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"sì", s:[{t:"sì",m:"See",h:"the word 'see'"}]},
  "no": {t:"no", s:[{t:"no",m:"No",h:"the word 'no'"}]},
  "ok": {t:"va bene", s:[{t:"va",m:"Vah",h:"'vah' like 'vat' without the T"},{t:"be",m:"Bay",h:"the word 'bay'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "i understand": {t:"capisco", s:[{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"sco",m:"Sko",h:"like 'scope' without PE"}]},
  "i don't understand": {t:"non capisco", s:[{t:"non",m:"Known",h:"the word 'known'"},{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"pi",m:"Pee",h:"the letter 'P'"},{t:"sco",m:"Sko",h:"like 'scope' without PE"}]},
  "do you speak english": {t:"parla inglese", s:[{t:"par",m:"Par",h:"the word 'par' — roll the R"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"in",m:"Een",h:"like 'keen' without the K"},{t:"gle",m:"Glay",h:"like 'glay'"},{t:"se",m:"Say",h:"the word 'say'"}]},
  "slowly please": {t:"lentamente per favore", s:[{t:"len",m:"Len",h:"the name 'Len'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"men",m:"Men",h:"the word 'men'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"fa",m:"Fah",h:"the musical note 'fa'"},{t:"vo",m:"Voh",h:"'voh'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "can you help me": {t:"può aiutarmi", s:[{t:"può",m:"Poo-oh",h:"'poo' + 'oh'"},{t:"ai",m:"Eye",h:"the word 'eye'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"tar",m:"Tar",h:"the word 'tar' — roll the R"},{t:"mi",m:"Me",h:"the word 'me'"}]},
  "where is": {t:"dov'è", s:[{t:"do",m:"Doe",h:"the word 'doe'"},{t:"v'è",m:"Veh",h:"like 'veh'"}]},
  "how much": {t:"quanto costa", s:[{t:"quan",m:"Kwahn",h:"like 'Juan' with a K"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"co",m:"Ko",h:"like 'co' in company"},{t:"sta",m:"Stah",h:"like 'star' without the R"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"aiuto", s:[{t:"ai",m:"Eye",h:"the word 'eye'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "emergency": {t:"emergenza", s:[{t:"e",m:"Ay",h:"the letter 'A'"},{t:"mer",m:"Mare",h:"the word 'mare'"},{t:"gen",m:"Jen",h:"the name 'Jen' — Italian GE sounds 'jay'"},{t:"za",m:"Tsah",h:"'ts' + 'ah' — Italian Z is 'ts'"}]},
  "call the police": {t:"chiami la polizia", s:[{t:"chia",m:"Key-ah",h:"'key' + 'ah' — Italian CHI sounds 'key'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"zi",m:"Tsee",h:"'ts' + 'ee' — Italian Z is 'ts'"},{t:"a",m:"Ah",h:"the sound 'ah'"}]},
  "call the doctor": {t:"chiami il dottore", s:[{t:"chia",m:"Key-ah",h:"'key' + 'ah'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"il",m:"Eel",h:"the word 'eel'"},{t:"dot",m:"Dot",h:"the word 'dot' — stress the double T"},{t:"to",m:"Toh",h:"like 'toe'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "hospital": {t:"ospedale", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"spe",m:"Spay",h:"like 'spay'"},{t:"da",m:"Dah",h:"like 'dah'"},{t:"le",m:"Lay",h:"the word 'lay'"}]},
  "fire": {t:"fuoco", s:[{t:"fuo",m:"Foo-oh",h:"'foo' + 'oh'"},{t:"co",m:"Ko",h:"like 'co' in company"}]},
  "danger": {t:"pericolo", s:[{t:"pe",m:"Pay",h:"the word 'pay'"},{t:"ri",m:"Ree",h:"like 'ree' — roll the R"},{t:"co",m:"Ko",h:"like 'co' in company"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "watch out": {t:"attenzione", s:[{t:"at",m:"Aht",h:"like 'art' without R — double T is strong"},{t:"ten",m:"Ten",h:"the number 'ten'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "i'm lost": {t:"mi sono perso", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"so",m:"So",h:"the word 'so'"},{t:"no",m:"No",h:"the word 'no'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"so",m:"So",h:"the word 'so'"}]},
  "i'm sick": {t:"mi sento male", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"sen",m:"Sen",h:"like 'send' without D"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"le",m:"Lay",h:"the word 'lay'"}]},
  "call an ambulance": {t:"chiami un'ambulanza", s:[{t:"chia",m:"Key-ah",h:"'key' + 'ah'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"un",m:"Oon",h:"like 'oon'"},{t:"am",m:"Ahm",h:"like 'arm' without R"},{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"lan",m:"Lahn",h:"like 'lawn'"},{t:"za",m:"Tsah",h:"'ts' + 'ah'"}]},
  "i need a doctor": {t:"ho bisogno di un dottore", s:[{t:"ho",m:"Oh",h:"the word 'oh' — H is silent"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"so",m:"So",h:"the word 'so'"},{t:"gno",m:"Nyo",h:"like 'nyo' — Italian GN sounds like NY in 'canyon'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"un",m:"Oon",h:"like 'oon'"},{t:"dot",m:"Dot",h:"the word 'dot'"},{t:"to",m:"Toh",h:"like 'toe'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "passport": {t:"passaporto", s:[{t:"pas",m:"Pahs",h:"like 'pass' — double S is strong"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"por",m:"Poor",h:"the word 'poor'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "theft": {t:"furto", s:[{t:"fur",m:"Foor",h:"like 'foor'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "police station": {t:"stazione di polizia", s:[{t:"sta",m:"Stah",h:"like 'star' without R"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"zi",m:"Tsee",h:"'ts' + 'ee'"},{t:"a",m:"Ah",h:"the sound 'ah'"}]},

  // ===== NUMBERS 0-10, 20, 50, 100, 1000 (15) =====
  "zero": {t:"zero", s:[{t:"ze",m:"Dzay",h:"'dz' + 'ay' — Italian Z is 'dz'"},{t:"ro",m:"Row",h:"the word 'row' — roll the R"}]},
  "one": {t:"uno", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "two": {t:"due", s:[{t:"du",m:"Doo",h:"like 'do'"},{t:"e",m:"Ay",h:"the letter 'A'"}]},
  "three": {t:"tre", s:[{t:"tre",m:"Tray",h:"the word 'tray' — roll the R"}]},
  "four": {t:"quattro", s:[{t:"quat",m:"Kwat",h:"like 'squat' without S"},{t:"tro",m:"Trow",h:"'trow' — double T is strong, roll the R"}]},
  "five": {t:"cinque", s:[{t:"cin",m:"Cheen",h:"like 'chin' — Italian CI sounds 'chee'"},{t:"que",m:"Kway",h:"like 'quay'"}]},
  "six": {t:"sei", s:[{t:"sei",m:"Say",h:"the word 'say'"}]},
  "seven": {t:"sette", s:[{t:"set",m:"Set",h:"the word 'set' — stress the double T"},{t:"te",m:"Tay",h:"like 'tay'"}]},
  "eight": {t:"otto", s:[{t:"ot",m:"Ought",h:"the word 'ought' — stress the double T"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "nine": {t:"nove", s:[{t:"no",m:"No",h:"the word 'no'"},{t:"ve",m:"Vay",h:"like 'vay'"}]},
  "ten": {t:"dieci", s:[{t:"die",m:"Dee-ay",h:"the letter 'D' + 'ay'"},{t:"ci",m:"Chee",h:"like 'chee' — Italian CI sounds 'chee'"}]},
  "twenty": {t:"venti", s:[{t:"ven",m:"Ven",h:"like 'vent' without T"},{t:"ti",m:"Tea",h:"the word 'tea'"}]},
  "fifty": {t:"cinquanta", s:[{t:"cin",m:"Cheen",h:"Italian CI sounds 'cheen'"},{t:"quan",m:"Kwahn",h:"like 'Juan' with K"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "one hundred": {t:"cento", s:[{t:"cen",m:"Chen",h:"like 'Chen' — Italian CE sounds 'chay'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "one thousand": {t:"mille", s:[{t:"mil",m:"Meal",h:"the word 'meal'"},{t:"le",m:"Lay",h:"the word 'lay'"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"acqua", s:[{t:"ac",m:"Ahk",h:"like 'arc' without R"},{t:"qua",m:"Kwah",h:"like 'quad' without D"}]},
  "coffee": {t:"caffè", s:[{t:"caf",m:"Kahf",h:"like 'calf' — double F is strong"},{t:"fè",m:"Feh",h:"like 'feh'"}]},
  "tea": {t:"tè", s:[{t:"tè",m:"Teh",h:"like 'teh' — shorter than English 'tea'"}]},
  "beer": {t:"birra", s:[{t:"bir",m:"Beer",h:"the word 'beer' — roll the double R"},{t:"ra",m:"Rah",h:"like 'rah'"}]},
  "wine": {t:"vino", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "red wine": {t:"vino rosso", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"no",m:"No",h:"the word 'no'"},{t:"ros",m:"Ross",h:"the name 'Ross' — double S is strong"},{t:"so",m:"So",h:"the word 'so'"}]},
  "white wine": {t:"vino bianco", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"no",m:"No",h:"the word 'no'"},{t:"bian",m:"Bee-ahn",h:"'bee' + 'on'"},{t:"co",m:"Ko",h:"like 'co' in company"}]},
  "bread": {t:"pane", s:[{t:"pa",m:"Pah",h:"like 'pa'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "cheese": {t:"formaggio", s:[{t:"for",m:"Four",h:"the number 'four'"},{t:"mag",m:"Mahd",h:"like 'mod' — double G is strong"},{t:"gio",m:"Joe",h:"the name 'Joe' — Italian GI sounds like J"}]},
  "meat": {t:"carne", s:[{t:"car",m:"Car",h:"the word 'car' — roll the R"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "fish": {t:"pesce", s:[{t:"pe",m:"Pay",h:"the word 'pay'"},{t:"sce",m:"Shay",h:"like 'shay' — Italian SCE sounds 'shay'"}]},
  "chicken": {t:"pollo", s:[{t:"pol",m:"Pole",h:"the word 'pole' — double L is strong"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "salad": {t:"insalata", s:[{t:"in",m:"Een",h:"like 'keen' without K"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "soup": {t:"zuppa", s:[{t:"zup",m:"Tsoop",h:"'ts' + 'oop' — double P is strong"},{t:"pa",m:"Pah",h:"like 'pa'"}]},
  "pizza": {t:"pizza", s:[{t:"piz",m:"Peets",h:"'peets' — Italian double Z sounds 'ts'"},{t:"za",m:"Tsah",h:"'ts' + 'ah'"}]},
  "pasta": {t:"pasta", s:[{t:"pa",m:"Pah",h:"like 'pa' — not 'pass'"},{t:"sta",m:"Stah",h:"like 'star' without R"}]},
  "ice cream": {t:"gelato", s:[{t:"ge",m:"Jay",h:"like 'jay' — Italian GE sounds 'jay'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "fruit": {t:"frutta", s:[{t:"frut",m:"Froot",h:"like 'fruit' — double T is strong"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "vegetables": {t:"verdure", s:[{t:"ver",m:"Vair",h:"like 'very' without Y — roll the R"},{t:"du",m:"Doo",h:"like 'do'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "egg": {t:"uovo", s:[{t:"uo",m:"Woe",h:"the word 'woe'"},{t:"vo",m:"Voh",h:"like 'vow' without W"}]},
  "rice": {t:"riso", s:[{t:"ri",m:"Ree",h:"like 'ree' — roll the R"},{t:"so",m:"So",h:"the word 'so'"}]},
  "butter": {t:"burro", s:[{t:"bur",m:"Boor",h:"like 'boor' — roll the double R"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "sugar": {t:"zucchero", s:[{t:"zuc",m:"Tsook",h:"'ts' + 'ook' — double C is strong"},{t:"che",m:"Kay",h:"like 'Kay' — Italian CHE sounds 'kay'"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "milk": {t:"latte", s:[{t:"lat",m:"Lot",h:"like 'lot' — double T is strong"},{t:"te",m:"Tay",h:"like 'tay'"}]},
  "orange juice": {t:"succo d'arancia", s:[{t:"suc",m:"Sook",h:"like 'sook' — double C is strong"},{t:"co",m:"Ko",h:"like 'co' in company"},{t:"da",m:"Dah",h:"like 'dah'"},{t:"ran",m:"Rahn",h:"like 'Ron' — roll the R"},{t:"cia",m:"Chah",h:"like 'cha' — Italian CI sounds 'chee'"}]},
  "i'm hungry": {t:"ho fame", s:[{t:"ho",m:"Oh",h:"the word 'oh' — H is silent"},{t:"fa",m:"Fah",h:"the musical note 'fa'"},{t:"me",m:"May",h:"the month 'May'"}]},
  "i'm thirsty": {t:"ho sete", s:[{t:"ho",m:"Oh",h:"the word 'oh' — H is silent"},{t:"se",m:"Say",h:"the word 'say'"},{t:"te",m:"Tay",h:"like 'tay'"}]},
  "delicious": {t:"delizioso", s:[{t:"de",m:"Day",h:"the word 'day'"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"so",m:"So",h:"the word 'so'"}]},
  "i'm vegetarian": {t:"sono vegetariano", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"no",m:"No",h:"the word 'no'"},{t:"ve",m:"Vay",h:"like 'vay'"},{t:"ge",m:"Jay",h:"Italian GE sounds 'jay'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"ria",m:"Ree-ah",h:"'ree' + 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "i have an allergy": {t:"ho un'allergia", s:[{t:"ho",m:"Oh",h:"the word 'oh'"},{t:"un",m:"Oon",h:"like 'oon'"},{t:"al",m:"Ahl",h:"like 'all' — double L is strong"},{t:"ler",m:"Lair",h:"the word 'lair'"},{t:"gi",m:"Jee",h:"like 'gee' — Italian GI sounds like J"},{t:"a",m:"Ah",h:"the sound 'ah'"}]},

  // ===== RESTAURANT (15) =====
  "a table for two please": {t:"un tavolo per due per favore", s:[{t:"un",m:"Oon",h:"like 'oon'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"vo",m:"Voh",h:"like 'vow' without W"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"du",m:"Doo",h:"like 'do'"},{t:"e",m:"Ay",h:"the letter 'A'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"vo",m:"Voh",h:"'voh'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "the menu please": {t:"il menù per favore", s:[{t:"il",m:"Eel",h:"the word 'eel'"},{t:"me",m:"May",h:"the month 'May'"},{t:"nù",m:"Noo",h:"like 'new'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"vo",m:"Voh",h:"'voh'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "the bill please": {t:"il conto per favore", s:[{t:"il",m:"Eel",h:"the word 'eel'"},{t:"con",m:"Cone",h:"the word 'cone'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"vo",m:"Voh",h:"'voh'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "i would like": {t:"vorrei", s:[{t:"vor",m:"Vor",h:"like 'vor' — roll the double R"},{t:"rei",m:"Ray",h:"the word 'ray'"}]},
  "breakfast": {t:"colazione", s:[{t:"co",m:"Ko",h:"like 'co' in company"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "lunch": {t:"pranzo", s:[{t:"pran",m:"Prahn",h:"like 'prong' without G — roll the R"},{t:"zo",m:"Tso",h:"'ts' + 'oh'"}]},
  "dinner": {t:"cena", s:[{t:"ce",m:"Chay",h:"like 'chay' — Italian CE sounds 'chay'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "waiter": {t:"cameriere", s:[{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"me",m:"May",h:"the month 'May'"},{t:"rie",m:"Ree-ay",h:"'ree' + 'ay' — roll the R"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "a glass of": {t:"un bicchiere di", s:[{t:"un",m:"Oon",h:"like 'oon'"},{t:"bic",m:"Beek",h:"like 'beak' — double C is strong"},{t:"chie",m:"Key-ay",h:"'key' + 'ay' — Italian CHI sounds 'key'"},{t:"re",m:"Ray",h:"the word 'ray'"},{t:"di",m:"Dee",h:"the letter 'D'"}]},
  "a bottle of": {t:"una bottiglia di", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"bot",m:"Boat",h:"the word 'boat' — double T"},{t:"ti",m:"Tee",h:"the word 'tee'"},{t:"glia",m:"Lyah",h:"'ly' + 'ah' — Italian GLI sounds like 'ly'"},{t:"di",m:"Dee",h:"the letter 'D'"}]},
  "with": {t:"con", s:[{t:"con",m:"Cone",h:"the word 'cone'"}]},
  "without": {t:"senza", s:[{t:"sen",m:"Sen",h:"like 'send' without D"},{t:"za",m:"Tsah",h:"'ts' + 'ah'"}]},
  "tip": {t:"mancia", s:[{t:"man",m:"Mahn",h:"like 'mon'"},{t:"cia",m:"Chah",h:"like 'cha' — Italian CI sounds 'ch'"}]},
  "reservation": {t:"prenotazione", s:[{t:"pre",m:"Pray",h:"the word 'pray'"},{t:"no",m:"No",h:"the word 'no'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "is service included": {t:"il servizio è incluso", s:[{t:"il",m:"Eel",h:"the word 'eel'"},{t:"ser",m:"Sair",h:"like 'sair'"},{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"è",m:"Eh",h:"like 'eh'"},{t:"in",m:"Een",h:"like 'keen' without K"},{t:"clu",m:"Kloo",h:"like 'clue'"},{t:"so",m:"So",h:"the word 'so'"}]},

  // ===== SHOPPING (20) =====
  "how much does it cost": {t:"quanto costa", s:[{t:"quan",m:"Kwahn",h:"like 'Juan' with K"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"co",m:"Ko",h:"like 'co' in company"},{t:"sta",m:"Stah",h:"like 'star' without R"}]},
  "too expensive": {t:"troppo caro", s:[{t:"trop",m:"Trop",h:"like 'tropical' start — double P is strong"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "cheap": {t:"economico", s:[{t:"e",m:"Ay",h:"the letter 'A'"},{t:"co",m:"Ko",h:"like 'co'"},{t:"no",m:"No",h:"the word 'no'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"co",m:"Ko",h:"like 'co'"}]},
  "i'm just looking": {t:"sto solo guardando", s:[{t:"sto",m:"Stow",h:"the word 'stow'"},{t:"so",m:"So",h:"the word 'so'"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"guar",m:"Gwahr",h:"like 'guard' without D"},{t:"dan",m:"Dahn",h:"like 'dawn'"},{t:"do",m:"Doe",h:"the word 'doe'"}]},
  "can i try this on": {t:"posso provarlo", s:[{t:"pos",m:"Poss",h:"like 'poss' — double S is strong"},{t:"so",m:"So",h:"the word 'so'"},{t:"pro",m:"Pro",h:"the word 'pro' — roll the R"},{t:"var",m:"Var",h:"like 'var'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "bigger": {t:"più grande", s:[{t:"più",m:"Pew",h:"the word 'pew'"},{t:"gran",m:"Grahn",h:"like 'grand' without D — roll the R"},{t:"de",m:"Day",h:"the word 'day'"}]},
  "smaller": {t:"più piccolo", s:[{t:"più",m:"Pew",h:"the word 'pew'"},{t:"pic",m:"Peek",h:"like 'peek' — double C is strong"},{t:"co",m:"Ko",h:"like 'co'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "this one": {t:"questo", s:[{t:"que",m:"Kway",h:"like 'quay'"},{t:"sto",m:"Stow",h:"the word 'stow'"}]},
  "that one": {t:"quello", s:[{t:"quel",m:"Kwell",h:"the word 'quell' — double L is strong"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "i'll take it": {t:"lo prendo", s:[{t:"lo",m:"Low",h:"the word 'low'"},{t:"pren",m:"Pren",h:"like 'pren' — roll the R"},{t:"do",m:"Doe",h:"the word 'doe'"}]},
  "do you accept credit cards": {t:"accettate carte di credito", s:[{t:"ac",m:"Aht",h:"like 'art' without R"},{t:"cet",m:"Chet",h:"the name 'Chet' — Italian CE sounds 'chay'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"car",m:"Car",h:"the word 'car'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"cre",m:"Kray",h:"like 'cray' — roll the R"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "receipt": {t:"scontrino", s:[{t:"scon",m:"Skon",h:"like 'scone' without E"},{t:"tri",m:"Tree",h:"the word 'tree'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "bag": {t:"borsa", s:[{t:"bor",m:"Bore",h:"the word 'bore'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "open": {t:"aperto", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"per",m:"Pair",h:"the word 'pair'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "closed": {t:"chiuso", s:[{t:"chiu",m:"Key-oo",h:"'key' + 'oo' — Italian CHI sounds 'key'"},{t:"so",m:"So",h:"the word 'so'"}]},
  "sale": {t:"saldi", s:[{t:"sal",m:"Sahl",h:"like 'Sal'"},{t:"di",m:"Dee",h:"the letter 'D'"}]},
  "size": {t:"taglia", s:[{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"glia",m:"Lyah",h:"'ly' + 'ah' — Italian GLI sounds like 'ly' in 'million'"}]},
  "color": {t:"colore", s:[{t:"co",m:"Ko",h:"like 'co'"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "shop": {t:"negozio", s:[{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"}]},
  "market": {t:"mercato", s:[{t:"mer",m:"Mare",h:"the word 'mare'"},{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"to",m:"Toe",h:"the word 'toe'"}]},

  // ===== DIRECTIONS & TRANSPORT (25) =====
  "where is the bathroom": {t:"dov'è il bagno", s:[{t:"do",m:"Doe",h:"the word 'doe'"},{t:"v'è",m:"Veh",h:"like 'veh'"},{t:"il",m:"Eel",h:"the word 'eel'"},{t:"ba",m:"Bah",h:"the word 'bah'"},{t:"gno",m:"Nyo",h:"like 'nyo' — Italian GN sounds like 'ny' in 'canyon'"}]},
  "left": {t:"sinistra", s:[{t:"si",m:"See",h:"the word 'see'"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"stra",m:"Strah",h:"like 'straw' — roll the R"}]},
  "right": {t:"destra", s:[{t:"de",m:"Day",h:"the word 'day'"},{t:"stra",m:"Strah",h:"like 'straw' — roll the R"}]},
  "straight ahead": {t:"dritto", s:[{t:"drit",m:"Dreet",h:"like 'dreet' — roll the R, double T is strong"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "near": {t:"vicino", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"ci",m:"Chee",h:"Italian CI sounds 'chee'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "far": {t:"lontano", s:[{t:"lon",m:"Loan",h:"the word 'loan'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"no",m:"No",h:"the word 'no'"}]},
  "stop": {t:"fermata", s:[{t:"fer",m:"Fair",h:"the word 'fair'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "train station": {t:"stazione dei treni", s:[{t:"sta",m:"Stah",h:"like 'star' without R"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"dei",m:"Day",h:"the word 'day'"},{t:"tre",m:"Tray",h:"the word 'tray' — roll the R"},{t:"ni",m:"Knee",h:"the word 'knee'"}]},
  "bus stop": {t:"fermata dell'autobus", s:[{t:"fer",m:"Fair",h:"the word 'fair'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"del",m:"Dell",h:"the word 'dell'"},{t:"lau",m:"Lah-oo",h:"'la' + 'oo'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"bus",m:"Boos",h:"like 'boos'"}]},
  "airport": {t:"aeroporto", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"e",m:"Ay",h:"the letter 'A'"},{t:"ro",m:"Row",h:"the word 'row' — roll the R"},{t:"por",m:"Poor",h:"the word 'poor'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "taxi": {t:"taxi", s:[{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"xi",m:"Xee",h:"like 'see'"}]},
  "ticket": {t:"biglietto", s:[{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"gliet",m:"Lyet",h:"'ly' + 'et' — Italian GLI sounds like 'ly'"},{t:"to",m:"Toe",h:"the word 'toe' — double T is strong"}]},
  "one way": {t:"solo andata", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"an",m:"Ahn",h:"like 'on' with an A"},{t:"da",m:"Dah",h:"like 'dah'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "round trip": {t:"andata e ritorno", s:[{t:"an",m:"Ahn",h:"like 'on' with A"},{t:"da",m:"Dah",h:"like 'dah'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"e",m:"Ay",h:"the letter 'A'"},{t:"ri",m:"Ree",h:"like 'ree' — roll the R"},{t:"tor",m:"Tore",h:"the word 'tore'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "map": {t:"mappa", s:[{t:"map",m:"Mop",h:"like 'mop' — double P is strong"},{t:"pa",m:"Pah",h:"like 'pa'"}]},
  "street": {t:"via", s:[{t:"vi",m:"Vee",h:"the letter 'V'"},{t:"a",m:"Ah",h:"the sound 'ah'"}]},
  "square": {t:"piazza", s:[{t:"piaz",m:"Pee-ahts",h:"'pee' + 'ahts' — double Z is 'ts'"},{t:"za",m:"Tsah",h:"'ts' + 'ah'"}]},
  "bridge": {t:"ponte", s:[{t:"pon",m:"Pone",h:"the word 'pone'"},{t:"te",m:"Tay",h:"like 'tay'"}]},
  "church": {t:"chiesa", s:[{t:"chie",m:"Key-ay",h:"'key' + 'ay' — Italian CHI sounds 'key'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "museum": {t:"museo", s:[{t:"mu",m:"Moo",h:"the word 'moo'"},{t:"se",m:"Say",h:"the word 'say'"},{t:"o",m:"Oh",h:"the word 'oh'"}]},
  "beach": {t:"spiaggia", s:[{t:"spiag",m:"Spee-ahd",h:"'spee' + 'ahd' — double G is strong"},{t:"gia",m:"Jah",h:"like 'jah' — Italian GI sounds like J"}]},
  "here": {t:"qui", s:[{t:"qui",m:"Kwee",h:"like 'queen' without N"}]},
  "there": {t:"là", s:[{t:"là",m:"Lah",h:"the note 'la'"}]},
  "entrance": {t:"entrata", s:[{t:"en",m:"En",h:"the word 'en'"},{t:"tra",m:"Trah",h:"like 'traw' — roll the R"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "exit": {t:"uscita", s:[{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"sci",m:"Shee",h:"like 'she' — Italian SCI sounds 'shee'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"albergo", s:[{t:"al",m:"Ahl",h:"like 'all'"},{t:"ber",m:"Bear",h:"the word 'bear'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "room": {t:"camera", s:[{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"me",m:"May",h:"the month 'May'"},{t:"ra",m:"Rah",h:"like 'rah' — roll the R"}]},
  "single room": {t:"camera singola", s:[{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"me",m:"May",h:"the month 'May'"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"sin",m:"Seen",h:"like 'seen'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"la",m:"Lah",h:"the note 'la'"}]},
  "double room": {t:"camera doppia", s:[{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"me",m:"May",h:"the month 'May'"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"dop",m:"Dope",h:"the word 'dope' — double P is strong"},{t:"pia",m:"Pee-ah",h:"'pee' + 'ah'"}]},
  "how much per night": {t:"quanto costa a notte", s:[{t:"quan",m:"Kwahn",h:"like 'Juan' with K"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"co",m:"Ko",h:"like 'co'"},{t:"sta",m:"Stah",h:"like 'star' without R"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"not",m:"Not",h:"the word 'not'"},{t:"te",m:"Tay",h:"like 'tay' — double T is strong"}]},
  "key": {t:"chiave", s:[{t:"chia",m:"Key-ah",h:"'key' + 'ah' — Italian CHI sounds 'key'"},{t:"ve",m:"Vay",h:"like 'vay'"}]},
  "shower": {t:"doccia", s:[{t:"doc",m:"Doh-ch",h:"like 'doh' + 'ch' — double C before I sounds 'tch'"},{t:"cia",m:"Chah",h:"like 'cha'"}]},
  "towel": {t:"asciugamano", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"sciu",m:"Shoo",h:"like 'shoe' — Italian SCI sounds 'sh'"},{t:"ga",m:"Gah",h:"like 'gah'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "air conditioning": {t:"aria condizionata", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'ree' — roll the R"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"con",m:"Cone",h:"the word 'cone'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "check in": {t:"check-in", s:[{t:"check",m:"Check",h:"the word 'check'"},{t:"in",m:"Een",h:"like 'keen' without K"}]},
  "check out": {t:"check-out", s:[{t:"check",m:"Check",h:"the word 'check'"},{t:"out",m:"Out",h:"the word 'out'"}]},
  "floor": {t:"piano", s:[{t:"pia",m:"Pee-ah",h:"'pee' + 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "elevator": {t:"ascensore", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"scen",m:"Shen",h:"like 'shen' — Italian SCE sounds 'shay'"},{t:"so",m:"So",h:"the word 'so'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "wifi password": {t:"password del wifi", s:[{t:"pass",m:"Pass",h:"the word 'pass'"},{t:"word",m:"Word",h:"the word 'word'"},{t:"del",m:"Dell",h:"the word 'dell'"},{t:"wi",m:"Wee",h:"the word 'wee'"},{t:"fi",m:"Fee",h:"the word 'fee'"}]},
  "is breakfast included": {t:"la colazione è inclusa", s:[{t:"la",m:"Lah",h:"the note 'la'"},{t:"co",m:"Ko",h:"like 'co'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"zio",m:"Tsee-oh",h:"'ts' + 'ee' + 'oh'"},{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"è",m:"Eh",h:"like 'eh'"},{t:"in",m:"Een",h:"like 'keen' without K"},{t:"clu",m:"Kloo",h:"like 'clue'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},

  // ===== COMMUNICATION (15) =====
  "i don't speak italian": {t:"non parlo italiano", s:[{t:"non",m:"Known",h:"the word 'known'"},{t:"par",m:"Par",h:"the word 'par' — roll the R"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"lia",m:"Lee-ah",h:"'lee' + 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "i speak a little italian": {t:"parlo un po' di italiano", s:[{t:"par",m:"Par",h:"the word 'par'"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"un",m:"Oon",h:"like 'oon'"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ta",m:"Tah",h:"like 'tar' without R"},{t:"lia",m:"Lee-ah",h:"'lee' + 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "can you repeat that": {t:"può ripetere", s:[{t:"può",m:"Poo-oh",h:"'poo' + 'oh'"},{t:"ri",m:"Ree",h:"like 'ree' — roll the R"},{t:"pe",m:"Pay",h:"the word 'pay'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "what does this mean": {t:"cosa significa questo", s:[{t:"co",m:"Ko",h:"like 'co'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"si",m:"See",h:"the word 'see'"},{t:"gni",m:"Nyee",h:"like 'knee' — Italian GN sounds 'ny'"},{t:"fi",m:"Fee",h:"the word 'fee'"},{t:"ca",m:"Kah",h:"like 'car' without R"},{t:"que",m:"Kway",h:"like 'quay'"},{t:"sto",m:"Stow",h:"the word 'stow'"}]},
  "how do you say": {t:"come si dice", s:[{t:"co",m:"Ko",h:"like 'co'"},{t:"me",m:"May",h:"the month 'May'"},{t:"si",m:"See",h:"the word 'see'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ce",m:"Chay",h:"Italian CE sounds 'chay'"}]},
  "telephone": {t:"telefono", s:[{t:"te",m:"Tay",h:"like 'tay'"},{t:"le",m:"Lay",h:"the word 'lay'"},{t:"fo",m:"Foe",h:"the word 'foe'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "internet": {t:"internet", s:[{t:"in",m:"Een",h:"like 'keen' without K"},{t:"ter",m:"Tare",h:"the word 'tare'"},{t:"net",m:"Net",h:"the word 'net'"}]},
  "email": {t:"email", s:[{t:"e",m:"Ay",h:"the letter 'A'"},{t:"mail",m:"Mail",h:"the word 'mail'"}]},
  "can i use your phone": {t:"posso usare il telefono", s:[{t:"pos",m:"Poss",h:"like 'poss' — double S"},{t:"so",m:"So",h:"the word 'so'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"re",m:"Ray",h:"the word 'ray'"},{t:"il",m:"Eel",h:"the word 'eel'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"le",m:"Lay",h:"the word 'lay'"},{t:"fo",m:"Foe",h:"the word 'foe'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "write it down": {t:"lo scriva", s:[{t:"lo",m:"Low",h:"the word 'low'"},{t:"scri",m:"Skree",h:"like 'screen' without N"},{t:"va",m:"Vah",h:"like 'vat' without T"}]},
  "i need help": {t:"ho bisogno di aiuto", s:[{t:"ho",m:"Oh",h:"the word 'oh'"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"so",m:"So",h:"the word 'so'"},{t:"gno",m:"Nyo",h:"Italian GN sounds 'ny' like 'canyon'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ai",m:"Eye",h:"the word 'eye'"},{t:"u",m:"Oo",h:"the sound 'oo'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "i'm a tourist": {t:"sono un turista", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"no",m:"No",h:"the word 'no'"},{t:"un",m:"Oon",h:"like 'oon'"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"ri",m:"Ree",h:"like 'ree'"},{t:"sta",m:"Stah",h:"like 'star' without R"}]},
  "do you have wifi": {t:"avete il wifi", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ve",m:"Vay",h:"like 'vay'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"il",m:"Eel",h:"the word 'eel'"},{t:"wi",m:"Wee",h:"the word 'wee'"},{t:"fi",m:"Fee",h:"the word 'fee'"}]},
  "what time is it": {t:"che ora è", s:[{t:"che",m:"Kay",h:"like 'Kay' — Italian CHE sounds 'kay'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"è",m:"Eh",h:"like 'eh'"}]},
  "today": {t:"oggi", s:[{t:"og",m:"Oh-j",h:"like 'oh' + soft J — double G before I sounds 'dj'"},{t:"gi",m:"Jee",h:"Italian GI sounds like 'jee'"}]},

  // ===== HEALTH (10) =====
  "pharmacy": {t:"farmacia", s:[{t:"far",m:"Far",h:"the word 'far' — roll the R"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ci",m:"Chee",h:"Italian CI sounds 'chee'"},{t:"a",m:"Ah",h:"the sound 'ah'"}]},
  "i have a headache": {t:"ho mal di testa", s:[{t:"ho",m:"Oh",h:"the word 'oh'"},{t:"mal",m:"Mahl",h:"like 'mall'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"te",m:"Tay",h:"like 'tay'"},{t:"sta",m:"Stah",h:"like 'star' without R"}]},
  "i have a fever": {t:"ho la febbre", s:[{t:"ho",m:"Oh",h:"the word 'oh'"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"feb",m:"Feb",h:"like 'Feb' for February — double B is strong"},{t:"bre",m:"Bray",h:"the word 'bray'"}]},
  "medicine": {t:"medicina", s:[{t:"me",m:"May",h:"the month 'May'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ci",m:"Chee",h:"Italian CI sounds 'chee'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "pain": {t:"dolore", s:[{t:"do",m:"Doe",h:"the word 'doe'"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"re",m:"Ray",h:"the word 'ray'"}]},
  "allergic": {t:"allergico", s:[{t:"al",m:"Ahl",h:"like 'all' — double L is strong"},{t:"ler",m:"Lair",h:"the word 'lair'"},{t:"gi",m:"Jee",h:"Italian GI sounds like J"},{t:"co",m:"Ko",h:"like 'co'"}]},
  "i need medicine": {t:"ho bisogno di medicine", s:[{t:"ho",m:"Oh",h:"the word 'oh'"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"so",m:"So",h:"the word 'so'"},{t:"gno",m:"Nyo",h:"Italian GN sounds 'ny'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"me",m:"May",h:"the month 'May'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"ci",m:"Chee",h:"Italian CI sounds 'chee'"},{t:"ne",m:"Nay",h:"the word 'nay'"}]},
  "dentist": {t:"dentista", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"ti",m:"Tea",h:"the word 'tea'"},{t:"sta",m:"Stah",h:"like 'star' without R"}]},
  "stomach ache": {t:"mal di stomaco", s:[{t:"mal",m:"Mahl",h:"like 'mall'"},{t:"di",m:"Dee",h:"the letter 'D'"},{t:"sto",m:"Stow",h:"the word 'stow'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"co",m:"Ko",h:"like 'co'"}]},
  "it hurts here": {t:"mi fa male qui", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"le",m:"Lay",h:"the word 'lay'"},{t:"qui",m:"Kwee",h:"like 'queen' without N"}]},

  // ===== TIME (10) =====
  "now": {t:"adesso", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"des",m:"Des",h:"like 'desk' without K — double S is strong"},{t:"so",m:"So",h:"the word 'so'"}]},
  "later": {t:"più tardi", s:[{t:"più",m:"Pew",h:"the word 'pew'"},{t:"tar",m:"Tar",h:"the word 'tar' — roll the R"},{t:"di",m:"Dee",h:"the letter 'D'"}]},
  "yesterday": {t:"ieri", s:[{t:"ie",m:"Ee-ay",h:"'ee' + 'ay'"},{t:"ri",m:"Ree",h:"like 'ree' — roll the R"}]},
  "tomorrow": {t:"domani", s:[{t:"do",m:"Doe",h:"the word 'doe'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ni",m:"Knee",h:"the word 'knee'"}]},
  "morning": {t:"mattina", s:[{t:"mat",m:"Mot",h:"like 'mot' — double T is strong"},{t:"ti",m:"Tea",h:"the word 'tea'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "afternoon": {t:"pomeriggio", s:[{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"me",m:"May",h:"the month 'May'"},{t:"rig",m:"Reed",h:"like 'reed' — double G"},{t:"gio",m:"Joe",h:"the name 'Joe'"}]},
  "evening": {t:"sera", s:[{t:"se",m:"Say",h:"the word 'say'"},{t:"ra",m:"Rah",h:"like 'rah'"}]},
  "night": {t:"notte", s:[{t:"not",m:"Not",h:"the word 'not' — double T is strong"},{t:"te",m:"Tay",h:"like 'tay'"}]},
  "what time": {t:"a che ora", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"che",m:"Kay",h:"Italian CHE sounds 'kay'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ra",m:"Rah",h:"like 'rah'"}]},
  "minute": {t:"minuto", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"nu",m:"New",h:"the word 'new'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},

  // ===== WEATHER (10) =====
  "what's the weather like": {t:"che tempo fa", s:[{t:"che",m:"Kay",h:"Italian CHE sounds 'kay'"},{t:"tem",m:"Temp",h:"like 'temp' without P"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"fa",m:"Fah",h:"the note 'fa'"}]},
  "it's hot": {t:"fa caldo", s:[{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"cal",m:"Kahl",h:"like 'call'"},{t:"do",m:"Doe",h:"the word 'doe'"}]},
  "it's cold": {t:"fa freddo", s:[{t:"fa",m:"Fah",h:"the note 'fa'"},{t:"fred",m:"Fred",h:"the name 'Fred' — double D is strong"},{t:"do",m:"Doe",h:"the word 'doe'"}]},
  "rain": {t:"pioggia", s:[{t:"piog",m:"Pee-ohd",h:"'pee' + 'ohd' — double G is strong"},{t:"gia",m:"Jah",h:"like 'jah' — Italian GI sounds like J"}]},
  "sun": {t:"sole", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"le",m:"Lay",h:"the word 'lay'"}]},
  "wind": {t:"vento", s:[{t:"ven",m:"Ven",h:"like 'vent' without T"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "snow": {t:"neve", s:[{t:"ne",m:"Nay",h:"the word 'nay'"},{t:"ve",m:"Vay",h:"like 'vay'"}]},
  "cloudy": {t:"nuvoloso", s:[{t:"nu",m:"New",h:"the word 'new'"},{t:"vo",m:"Voh",h:"like 'vow' without W"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"so",m:"So",h:"the word 'so'"}]},
  "beautiful day": {t:"bella giornata", s:[{t:"bel",m:"Bell",h:"the word 'bell' — double L is strong"},{t:"la",m:"Lah",h:"the note 'la'"},{t:"gior",m:"Jaw",h:"like 'jaw' — Italian GI sounds like J"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ta",m:"Tah",h:"like 'tar' without R"}]},
  "umbrella": {t:"ombrello", s:[{t:"om",m:"Ohm",h:"the word 'ohm'"},{t:"brel",m:"Brel",h:"like 'brel' — double L is strong"},{t:"lo",m:"Low",h:"the word 'low'"}]}
};
