var DICT_TH = {

  // ===== 1. GREETINGS & COURTESY (20) =====
  "hello": {t:"สวัสดี", p:"sa-wat-dee", s:[{t:"สวัส",m:"Sa-wat",h:"'suh' + 'what'"},{t:"ดี",m:"Dee",h:"the letter 'D'"}]},
  "hello (polite, male)": {t:"สวัสดีครับ", p:"sa-wat-dee khrap", s:[{t:"สวัส",m:"Sa-wat",h:"'suh' + 'what'"},{t:"ดี",m:"Dee",h:"the letter 'D'"},{t:"ครับ",m:"Khrap",h:"like 'cup' with a 'kr'"}]},
  "hello (polite, female)": {t:"สวัสดีค่ะ", p:"sa-wat-dee kha", s:[{t:"สวัส",m:"Sa-wat",h:"'suh' + 'what'"},{t:"ดี",m:"Dee",h:"the letter 'D'"},{t:"ค่ะ",m:"Kha",h:"like 'car' without the 'r'"}]},
  "how are you?": {t:"สบายดีไหม", p:"sa-baai dee mai", s:[{t:"สบาย",m:"Sa-baai",h:"'suh' + 'buy'"},{t:"ดี",m:"Dee",h:"the letter 'D'"},{t:"ไหม",m:"Mai",h:"the word 'my'"}]},
  "I'm fine": {t:"สบายดี", p:"sa-baai dee", s:[{t:"สบาย",m:"Sa-baai",h:"'suh' + 'buy'"},{t:"ดี",m:"Dee",h:"the letter 'D'"}]},
  "thank you": {t:"ขอบคุณ", p:"khawp khun", s:[{t:"ขอบ",m:"Khawp",h:"like 'cup' with an 'aw' sound"},{t:"คุณ",m:"Khun",h:"like 'coon' but shorter"}]},
  "thank you (polite)": {t:"ขอบคุณครับ", p:"khawp khun khrap", s:[{t:"ขอบ",m:"Khawp",h:"like 'cup' with an 'aw' sound"},{t:"คุณ",m:"Khun",h:"like 'coon' but shorter"},{t:"ครับ",m:"Khrap",h:"like 'cup' with a 'kr'"}]},
  "you're welcome": {t:"ไม่เป็นไร", p:"mai pen rai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"เป็น",m:"Pen",h:"the word 'pen'"},{t:"ไร",m:"Rai",h:"like 'rye' bread"}]},
  "sorry / excuse me": {t:"ขอโทษ", p:"khaw thot", s:[{t:"ขอ",m:"Khaw",h:"like 'core' without the 'r'"},{t:"โทษ",m:"Thot",h:"like 'taught' but shorter"}]},
  "goodbye": {t:"ลาก่อน", p:"laa gawn", s:[{t:"ลา",m:"Laa",h:"the word 'la' as in music"},{t:"ก่อน",m:"Gawn",h:"the word 'gone'"}]},
  "see you later": {t:"แล้วเจอกัน", p:"laew juh gan", s:[{t:"แล้ว",m:"Laew",h:"like 'la' + 'ew'"},{t:"เจอ",m:"Juh",h:"like 'juh' in 'just'"},{t:"กัน",m:"Gan",h:"the word 'gun'"}]},
  "nice to meet you": {t:"ยินดีที่ได้รู้จัก", p:"yin dee tee dai roo jak", s:[{t:"ยินดี",m:"Yin-dee",h:"'yin' like 'yin-yang' + 'D'"},{t:"ที่ได้",m:"Tee-dai",h:"'tea' + 'die'"},{t:"รู้จัก",m:"Roo-jak",h:"'rue' + 'jack'"}]},
  "good morning": {t:"อรุณสวัสดิ์", p:"a-run sa-wat", s:[{t:"อรุณ",m:"A-run",h:"'a' + the word 'run'"},{t:"สวัสดิ์",m:"Sa-wat",h:"'suh' + 'what'"}]},
  "good night": {t:"ราตรีสวัสดิ์", p:"raa-tree sa-wat", s:[{t:"ราตรี",m:"Raa-tree",h:"'ra' + the word 'tree'"},{t:"สวัสดิ์",m:"Sa-wat",h:"'suh' + 'what'"}]},
  "please": {t:"กรุณา", p:"ga-ru-naa", s:[{t:"กรุ",m:"Ga-ru",h:"'guh' + 'rue'"},{t:"ณา",m:"Naa",h:"the word 'nah'"}]},
  "no problem": {t:"ไม่มีปัญหา", p:"mai mee pan-haa", s:[{t:"ไม่มี",m:"Mai-mee",h:"'my' + 'me'"},{t:"ปัญหา",m:"Pan-haa",h:"'pun' + 'ha'"}]},
  "have a good day": {t:"ขอให้เป็นวันที่ดี", p:"khaw hai pen wan tee dee", s:[{t:"ขอให้",m:"Khaw-hai",h:"'core' + 'hi'"},{t:"เป็นวัน",m:"Pen-wan",h:"'pen' + 'won'"},{t:"ที่ดี",m:"Tee-dee",h:"'tea' + 'D'"}]},
  "welcome": {t:"ยินดีต้อนรับ", p:"yin dee tawn rap", s:[{t:"ยินดี",m:"Yin-dee",h:"'yin' like 'yin-yang' + 'D'"},{t:"ต้อนรับ",m:"Tawn-rap",h:"'torn' + 'wrap'"}]},
  "what is your name?": {t:"คุณชื่ออะไร", p:"khun cheu a-rai", s:[{t:"คุณ",m:"Khun",h:"like 'coon' but shorter"},{t:"ชื่อ",m:"Cheu",h:"like 'chew'"},{t:"อะไร",m:"A-rai",h:"'uh' + 'rye'"}]},
  "my name is...": {t:"ผมชื่อ...", p:"phom cheu...", s:[{t:"ผม",m:"Phom",h:"like 'palm' without the 'l'"},{t:"ชื่อ",m:"Cheu",h:"like 'chew'"}]},

  // ===== 2. YES / NO / BASICS (10) =====
  "yes": {t:"ใช่", p:"chai", s:[{t:"ใช่",m:"Chai",h:"like 'chai' tea"}]},
  "no": {t:"ไม่", p:"mai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"}]},
  "yes (polite, male)": {t:"ครับ", p:"khrap", s:[{t:"ครับ",m:"Khrap",h:"like 'cup' with a 'kr'"}]},
  "yes (polite, female)": {t:"ค่ะ", p:"kha", s:[{t:"ค่ะ",m:"Kha",h:"like 'car' without the 'r'"}]},
  "not / no": {t:"ไม่ใช่", p:"mai chai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"ใช่",m:"Chai",h:"like 'chai' tea"}]},
  "I don't know": {t:"ไม่รู้", p:"mai roo", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"รู้",m:"Roo",h:"the word 'rue'"}]},
  "I understand": {t:"เข้าใจ", p:"khao jai", s:[{t:"เข้า",m:"Khao",h:"like 'cow'"},{t:"ใจ",m:"Jai",h:"like 'j' + 'eye'"}]},
  "I don't understand": {t:"ไม่เข้าใจ", p:"mai khao jai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"เข้า",m:"Khao",h:"like 'cow'"},{t:"ใจ",m:"Jai",h:"like 'j' + 'eye'"}]},
  "can / is able to": {t:"ได้", p:"dai", s:[{t:"ได้",m:"Dai",h:"the word 'die'"}]},
  "cannot": {t:"ไม่ได้", p:"mai dai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"ได้",m:"Dai",h:"the word 'die'"}]},

  // ===== 3. EMERGENCY & SAFETY (15) =====
  "help!": {t:"ช่วยด้วย", p:"chuay duay", s:[{t:"ช่วย",m:"Chuay",h:"like 'chew' + 'eye'"},{t:"ด้วย",m:"Duay",h:"like 'do' + 'eye'"}]},
  "call the police": {t:"เรียกตำรวจ", p:"riak tam-ruat", s:[{t:"เรียก",m:"Riak",h:"like 'ree' + 'ak'"},{t:"ตำรวจ",m:"Tam-ruat",h:"'tum' + 'rue' + 'at'"}]},
  "call an ambulance": {t:"เรียกรถพยาบาล", p:"riak rot pha-yaa-baan", s:[{t:"เรียก",m:"Riak",h:"like 'ree' + 'ak'"},{t:"รถ",m:"Rot",h:"the word 'rot'"},{t:"พยาบาล",m:"Pha-yaa-baan",h:"'pa' + 'ya' + 'barn'"}]},
  "I need a doctor": {t:"ต้องการหมอ", p:"tawng gaan maw", s:[{t:"ต้อง",m:"Tawng",h:"like 'tongue'"},{t:"การ",m:"Gaan",h:"the word 'gone'"},{t:"หมอ",m:"Maw",h:"like 'more' without the 'r'"}]},
  "fire!": {t:"ไฟไหม้", p:"fai mai", s:[{t:"ไฟ",m:"Fai",h:"like 'fie' in 'fie upon you'"},{t:"ไหม้",m:"Mai",h:"the word 'my'"}]},
  "danger": {t:"อันตราย", p:"an-ta-raai", s:[{t:"อัน",m:"An",h:"the word 'un'"},{t:"ตราย",m:"Ta-raai",h:"'ta' + 'rye'"}]},
  "be careful": {t:"ระวัง", p:"ra-wang", s:[{t:"ระ",m:"Ra",h:"like 'ruh'"},{t:"วัง",m:"Wang",h:"the word 'wrong' without the 'r'"}]},
  "I'm lost": {t:"หลงทาง", p:"long taang", s:[{t:"หลง",m:"Long",h:"the word 'long'"},{t:"ทาง",m:"Taang",h:"like 'tongue'"}]},
  "hospital": {t:"โรงพยาบาล", p:"rong pha-yaa-baan", s:[{t:"โรง",m:"Rong",h:"like 'wrong'"},{t:"พยาบาล",m:"Pha-yaa-baan",h:"'pa' + 'ya' + 'barn'"}]},
  "police station": {t:"สถานีตำรวจ", p:"sa-taa-nee tam-ruat", s:[{t:"สถานี",m:"Sa-taa-nee",h:"'suh' + 'tar' + 'knee'"},{t:"ตำรวจ",m:"Tam-ruat",h:"'tum' + 'rue' + 'at'"}]},
  "stop!": {t:"หยุด", p:"yut", s:[{t:"หยุด",m:"Yut",h:"like 'yoot' said quickly"}]},
  "I'm allergic to...": {t:"แพ้...", p:"phae...", s:[{t:"แพ้",m:"Phae",h:"like 'pair' without the 'r'"}]},
  "thief!": {t:"ขโมย", p:"kha-moy", s:[{t:"ขโมย",m:"Kha-moy",h:"'ka' + 'moy' like 'boy'"}]},
  "embassy": {t:"สถานทูต", p:"sa-taan-toot", s:[{t:"สถาน",m:"Sa-taan",h:"'suh' + 'tan'"},{t:"ทูต",m:"Toot",h:"like 'toot' a horn"}]},
  "emergency": {t:"ฉุกเฉิน", p:"chuk-chern", s:[{t:"ฉุก",m:"Chuk",h:"like 'chuck'"},{t:"เฉิน",m:"Chern",h:"like 'churn'"}]},

  // ===== 4. NUMBERS (15) =====
  "zero": {t:"ศูนย์", p:"soon", s:[{t:"ศูนย์",m:"Soon",h:"the word 'soon'"}]},
  "one": {t:"หนึ่ง", p:"neung", s:[{t:"หนึ่ง",m:"Neung",h:"like 'nung' in 'young'"}]},
  "two": {t:"สอง", p:"sawng", s:[{t:"สอง",m:"Sawng",h:"the word 'song'"}]},
  "three": {t:"สาม", p:"saam", s:[{t:"สาม",m:"Saam",h:"the word 'psalm'"}]},
  "four": {t:"สี่", p:"see", s:[{t:"สี่",m:"See",h:"the word 'see'"}]},
  "five": {t:"ห้า", p:"haa", s:[{t:"ห้า",m:"Haa",h:"like 'ha' as in laughter"}]},
  "six": {t:"หก", p:"hok", s:[{t:"หก",m:"Hok",h:"like 'hawk' said quickly"}]},
  "seven": {t:"เจ็ด", p:"jet", s:[{t:"เจ็ด",m:"Jet",h:"the word 'jet'"}]},
  "eight": {t:"แปด", p:"bpaet", s:[{t:"แปด",m:"Bpaet",h:"like 'pet' with a 'b' start"}]},
  "nine": {t:"เก้า", p:"gao", s:[{t:"เก้า",m:"Gao",h:"like 'cow' with a 'g'"}]},
  "ten": {t:"สิบ", p:"sip", s:[{t:"สิบ",m:"Sip",h:"the word 'sip'"}]},
  "twenty": {t:"ยี่สิบ", p:"yee sip", s:[{t:"ยี่",m:"Yee",h:"like 'yee-haw'"},{t:"สิบ",m:"Sip",h:"the word 'sip'"}]},
  "fifty": {t:"ห้าสิบ", p:"haa sip", s:[{t:"ห้า",m:"Haa",h:"like 'ha' as in laughter"},{t:"สิบ",m:"Sip",h:"the word 'sip'"}]},
  "one hundred": {t:"หนึ่งร้อย", p:"neung roi", s:[{t:"หนึ่ง",m:"Neung",h:"like 'nung' in 'young'"},{t:"ร้อย",m:"Roi",h:"like 'roy'"}]},
  "one thousand": {t:"หนึ่งพัน", p:"neung phan", s:[{t:"หนึ่ง",m:"Neung",h:"like 'nung' in 'young'"},{t:"พัน",m:"Phan",h:"the word 'pun'"}]},

  // ===== 5. FOOD & DRINK (30) =====
  "water": {t:"น้ำ", p:"nam", s:[{t:"น้ำ",m:"Nam",h:"the word 'nom'"}]},
  "rice": {t:"ข้าว", p:"khao", s:[{t:"ข้าว",m:"Khao",h:"like 'cow'"}]},
  "fried rice": {t:"ข้าวผัด", p:"khao phat", s:[{t:"ข้าว",m:"Khao",h:"like 'cow'"},{t:"ผัด",m:"Phat",h:"like 'pat'"}]},
  "pad thai": {t:"ผัดไทย", p:"phat thai", s:[{t:"ผัด",m:"Phat",h:"like 'pat'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"}]},
  "chicken": {t:"ไก่", p:"gai", s:[{t:"ไก่",m:"Gai",h:"the word 'guy'"}]},
  "pork": {t:"หมู", p:"moo", s:[{t:"หมู",m:"Moo",h:"the word 'moo'"}]},
  "beef": {t:"เนื้อ", p:"neua", s:[{t:"เนื้อ",m:"Neua",h:"like 'new' + 'ah'"}]},
  "shrimp": {t:"กุ้ง", p:"gung", s:[{t:"กุ้ง",m:"Gung",h:"like 'gung-ho'"}]},
  "fish": {t:"ปลา", p:"bplaa", s:[{t:"ปลา",m:"Bplaa",h:"like 'blah'"}]},
  "egg": {t:"ไข่", p:"khai", s:[{t:"ไข่",m:"Khai",h:"the word 'kite' without the 't'"}]},
  "vegetables": {t:"ผัก", p:"phak", s:[{t:"ผัก",m:"Phak",h:"like 'pack'"}]},
  "fruit": {t:"ผลไม้", p:"phon-la-mai", s:[{t:"ผล",m:"Phon",h:"like 'phone' without the 'e'"},{t:"ไม้",m:"La-mai",h:"'la' + 'my'"}]},
  "spicy": {t:"เผ็ด", p:"phet", s:[{t:"เผ็ด",m:"Phet",h:"the word 'pet'"}]},
  "not spicy": {t:"ไม่เผ็ด", p:"mai phet", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"เผ็ด",m:"Phet",h:"the word 'pet'"}]},
  "delicious": {t:"อร่อย", p:"a-roi", s:[{t:"อร่อย",m:"A-roi",h:"'uh' + 'roy'"}]},
  "sweet": {t:"หวาน", p:"waan", s:[{t:"หวาน",m:"Waan",h:"the word 'wan'"}]},
  "sour": {t:"เปรี้ยว", p:"bpriao", s:[{t:"เปรี้ยว",m:"Bpriao",h:"like 'pre' + 'ow'"}]},
  "salty": {t:"เค็ม", p:"khem", s:[{t:"เค็ม",m:"Khem",h:"the word 'kem' like 'hem'"}]},
  "bitter": {t:"ขม", p:"khom", s:[{t:"ขม",m:"Khom",h:"like 'come'"}]},
  "coffee": {t:"กาแฟ", p:"gaa-fae", s:[{t:"กา",m:"Gaa",h:"like 'ga' in 'garden'"},{t:"แฟ",m:"Fae",h:"like 'fair' without the 'r'"}]},
  "tea": {t:"ชา", p:"chaa", s:[{t:"ชา",m:"Chaa",h:"like 'cha-cha'"}]},
  "beer": {t:"เบียร์", p:"bia", s:[{t:"เบียร์",m:"Bia",h:"like 'beer' without the 'r'"}]},
  "ice": {t:"น้ำแข็ง", p:"nam khaeng", s:[{t:"น้ำ",m:"Nam",h:"the word 'nom'"},{t:"แข็ง",m:"Khaeng",h:"like 'cane'"}]},
  "milk": {t:"นม", p:"nom", s:[{t:"นม",m:"Nom",h:"the word 'gnome' without the 'e'"}]},
  "soup": {t:"ซุป", p:"sup", s:[{t:"ซุป",m:"Sup",h:"the word 'soup'"}]},
  "noodles": {t:"ก๋วยเตี๋ยว", p:"guay tiao", s:[{t:"ก๋วย",m:"Guay",h:"like 'goo' + 'ay'"},{t:"เตี๋ยว",m:"Tiao",h:"like 'tee' + 'ow'"}]},
  "som tam (papaya salad)": {t:"ส้มตำ", p:"som tam", s:[{t:"ส้ม",m:"Som",h:"the word 'some'"},{t:"ตำ",m:"Tam",h:"the word 'tum'"}]},
  "tom yum": {t:"ต้มยำ", p:"tom yam", s:[{t:"ต้ม",m:"Tom",h:"the word 'Tom'"},{t:"ยำ",m:"Yam",h:"the word 'yum'"}]},
  "green curry": {t:"แกงเขียวหวาน", p:"gaeng khiao waan", s:[{t:"แกง",m:"Gaeng",h:"the word 'gang'"},{t:"เขียว",m:"Khiao",h:"like 'key' + 'ow'"},{t:"หวาน",m:"Waan",h:"the word 'wan'"}]},
  "mango sticky rice": {t:"ข้าวเหนียวมะม่วง", p:"khao niao ma-muang", s:[{t:"ข้าว",m:"Khao",h:"like 'cow'"},{t:"เหนียว",m:"Niao",h:"like 'knee' + 'ow'"},{t:"มะม่วง",m:"Ma-muang",h:"'ma' + 'moo' + 'ung'"}]},

  // ===== 6. RESTAURANT (15) =====
  "I'm hungry": {t:"หิว", p:"hiu", s:[{t:"หิว",m:"Hiu",h:"like 'he' + 'you' said fast"}]},
  "I'm thirsty": {t:"หิวน้ำ", p:"hiu nam", s:[{t:"หิว",m:"Hiu",h:"like 'he' + 'you' said fast"},{t:"น้ำ",m:"Nam",h:"the word 'nom'"}]},
  "menu please": {t:"ขอเมนูหน่อย", p:"khaw may-noo noi", s:[{t:"ขอ",m:"Khaw",h:"like 'core' without the 'r'"},{t:"เมนู",m:"May-noo",h:"the word 'menu'"},{t:"หน่อย",m:"Noi",h:"like 'noy' in 'annoy'"}]},
  "I'd like to order": {t:"สั่งอาหาร", p:"sang aa-haan", s:[{t:"สั่ง",m:"Sang",h:"the word 'sung'"},{t:"อาหาร",m:"Aa-haan",h:"'ah' + 'harn'"}]},
  "this one please": {t:"เอาอันนี้", p:"ao an nee", s:[{t:"เอา",m:"Ao",h:"like 'ow'"},{t:"อัน",m:"An",h:"the word 'un'"},{t:"นี้",m:"Nee",h:"the word 'knee'"}]},
  "bill please": {t:"เช็คบิล", p:"chek bin", s:[{t:"เช็ค",m:"Chek",h:"the word 'check'"},{t:"บิล",m:"Bin",h:"the word 'bin'"}]},
  "is this spicy?": {t:"อันนี้เผ็ดไหม", p:"an nee phet mai", s:[{t:"อัน",m:"An",h:"the word 'un'"},{t:"นี้",m:"Nee",h:"the word 'knee'"},{t:"เผ็ด",m:"Phet",h:"the word 'pet'"},{t:"ไหม",m:"Mai",h:"the word 'my'"}]},
  "a little spicy": {t:"เผ็ดนิดหน่อย", p:"phet nit noi", s:[{t:"เผ็ด",m:"Phet",h:"the word 'pet'"},{t:"นิด",m:"Nit",h:"the word 'knit'"},{t:"หน่อย",m:"Noi",h:"like 'noy' in 'annoy'"}]},
  "no sugar": {t:"ไม่ใส่น้ำตาล", p:"mai sai nam-taan", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"ใส่",m:"Sai",h:"like 'sigh'"},{t:"น้ำตาล",m:"Nam-taan",h:"'nom' + 'tan'"}]},
  "vegetarian": {t:"เจ", p:"jay", s:[{t:"เจ",m:"Jay",h:"the letter 'J'"}]},
  "it's very delicious": {t:"อร่อยมาก", p:"a-roi maak", s:[{t:"อร่อย",m:"A-roi",h:"'uh' + 'roy'"},{t:"มาก",m:"Maak",h:"like 'mark' without the 'r'"}]},
  "I'm full": {t:"อิ่มแล้ว", p:"im laew", s:[{t:"อิ่ม",m:"Im",h:"the word 'im' like 'him' without 'h'"},{t:"แล้ว",m:"Laew",h:"like 'la' + 'ew'"}]},
  "one more please": {t:"ขออีกหนึ่ง", p:"khaw eek neung", s:[{t:"ขอ",m:"Khaw",h:"like 'core' without the 'r'"},{t:"อีก",m:"Eek",h:"like 'geek' without the 'g'"},{t:"หนึ่ง",m:"Neung",h:"like 'nung' in 'young'"}]},
  "take away": {t:"กลับบ้าน", p:"glap baan", s:[{t:"กลับ",m:"Glap",h:"like 'gulp' reversed"},{t:"บ้าน",m:"Baan",h:"the word 'barn' without the 'r'"}]},
  "eat here": {t:"ทานที่นี่", p:"taan tee nee", s:[{t:"ทาน",m:"Taan",h:"the word 'tan'"},{t:"ที่",m:"Tee",h:"the word 'tea'"},{t:"นี่",m:"Nee",h:"the word 'knee'"}]},

  // ===== 7. SHOPPING & MONEY (20) =====
  "how much?": {t:"เท่าไหร่", p:"tao rai", s:[{t:"เท่า",m:"Tao",h:"like 'tao' in 'Taoism'"},{t:"ไหร่",m:"Rai",h:"like 'rye' bread"}]},
  "expensive": {t:"แพง", p:"phaeng", s:[{t:"แพง",m:"Phaeng",h:"like 'pang'"}]},
  "cheap": {t:"ถูก", p:"took", s:[{t:"ถูก",m:"Took",h:"the word 'took'"}]},
  "can you reduce the price?": {t:"ลดราคาได้ไหม", p:"lot raa-kaa dai mai", s:[{t:"ลด",m:"Lot",h:"the word 'lot'"},{t:"ราคา",m:"Raa-kaa",h:"'ra' + 'car'"},{t:"ได้ไหม",m:"Dai-mai",h:"'die' + 'my'"}]},
  "I want to buy": {t:"อยากซื้อ", p:"yaak seu", s:[{t:"อยาก",m:"Yaak",h:"like 'yak'"},{t:"ซื้อ",m:"Seu",h:"like 'sue'"}]},
  "I'm just looking": {t:"ดูเฉยๆ", p:"doo choey choey", s:[{t:"ดู",m:"Doo",h:"the word 'do'"},{t:"เฉยๆ",m:"Choey-choey",h:"'choy' said twice"}]},
  "do you have...?": {t:"มี...ไหม", p:"mee...mai", s:[{t:"มี",m:"Mee",h:"the word 'me'"},{t:"ไหม",m:"Mai",h:"the word 'my'"}]},
  "big": {t:"ใหญ่", p:"yai", s:[{t:"ใหญ่",m:"Yai",h:"like 'yai' in 'bonsai'"}]},
  "small": {t:"เล็ก", p:"lek", s:[{t:"เล็ก",m:"Lek",h:"the word 'leg' with a 'k'"}]},
  "money": {t:"เงิน", p:"ngern", s:[{t:"เงิน",m:"Ngern",h:"like 'ng' + 'urn'"}]},
  "baht (Thai currency)": {t:"บาท", p:"baat", s:[{t:"บาท",m:"Baat",h:"like 'bot' with a long 'a'"}]},
  "credit card": {t:"บัตรเครดิต", p:"bat khray-dit", s:[{t:"บัตร",m:"Bat",h:"the word 'bat'"},{t:"เครดิต",m:"Khray-dit",h:"the word 'credit'"}]},
  "cash": {t:"เงินสด", p:"ngern sot", s:[{t:"เงิน",m:"Ngern",h:"like 'ng' + 'urn'"},{t:"สด",m:"Sot",h:"the word 'sot'"}]},
  "receipt": {t:"ใบเสร็จ", p:"bai set", s:[{t:"ใบ",m:"Bai",h:"the word 'buy'"},{t:"เสร็จ",m:"Set",h:"the word 'set'"}]},
  "bag": {t:"ถุง", p:"tung", s:[{t:"ถุง",m:"Tung",h:"the word 'tongue'"}]},
  "market": {t:"ตลาด", p:"ta-laat", s:[{t:"ตลาด",m:"Ta-laat",h:"'ta' + 'lot'"}]},
  "shop / store": {t:"ร้าน", p:"raan", s:[{t:"ร้าน",m:"Raan",h:"like 'run' with a long 'a'"}]},
  "too expensive": {t:"แพงเกินไป", p:"phaeng gern bpai", s:[{t:"แพง",m:"Phaeng",h:"like 'pang'"},{t:"เกินไป",m:"Gern-bpai",h:"'gurn' + 'bye'"}]},
  "I'll take it": {t:"เอา", p:"ao", s:[{t:"เอา",m:"Ao",h:"like 'ow'"}]},
  "beautiful": {t:"สวย", p:"suay", s:[{t:"สวย",m:"Suay",h:"like 'sue' + 'ay'"}]},

  // ===== 8. DIRECTIONS & TRANSPORTATION (25) =====
  "where is...?": {t:"...อยู่ที่ไหน", p:"...yoo tee nai", s:[{t:"อยู่",m:"Yoo",h:"the word 'you'"},{t:"ที่ไหน",m:"Tee-nai",h:"'tea' + 'nigh'"}]},
  "left": {t:"ซ้าย", p:"saai", s:[{t:"ซ้าย",m:"Saai",h:"like 'sigh'"}]},
  "right": {t:"ขวา", p:"khwaa", s:[{t:"ขวา",m:"Khwaa",h:"like 'qua' in 'quality'"}]},
  "straight ahead": {t:"ตรงไป", p:"dtrong bpai", s:[{t:"ตรง",m:"Dtrong",h:"like 'strong' without the 's'"},{t:"ไป",m:"Bpai",h:"like 'buy'"}]},
  "stop here": {t:"จอดที่นี่", p:"jot tee nee", s:[{t:"จอด",m:"Jot",h:"the word 'jot'"},{t:"ที่",m:"Tee",h:"the word 'tea'"},{t:"นี่",m:"Nee",h:"the word 'knee'"}]},
  "far": {t:"ไกล", p:"glai", s:[{t:"ไกล",m:"Glai",h:"like 'g' + 'lie'"}]},
  "near": {t:"ใกล้", p:"glai", s:[{t:"ใกล้",m:"Glai",h:"like 'g' + 'lie' (falling tone)"}]},
  "taxi": {t:"แท็กซี่", p:"thaek-see", s:[{t:"แท็กซี่",m:"Thaek-see",h:"the word 'taxi'"}]},
  "tuk-tuk": {t:"ตุ๊กตุ๊ก", p:"tuk-tuk", s:[{t:"ตุ๊กตุ๊ก",m:"Tuk-tuk",h:"like 'took-took'"}]},
  "bus": {t:"รถเมล์", p:"rot may", s:[{t:"รถ",m:"Rot",h:"the word 'rot'"},{t:"เมล์",m:"May",h:"the word 'may'"}]},
  "train": {t:"รถไฟ", p:"rot fai", s:[{t:"รถ",m:"Rot",h:"the word 'rot'"},{t:"ไฟ",m:"Fai",h:"like 'fie'"}]},
  "BTS (skytrain)": {t:"รถไฟฟ้า", p:"rot fai faa", s:[{t:"รถไฟ",m:"Rot-fai",h:"'rot' + 'fie'"},{t:"ฟ้า",m:"Faa",h:"the word 'far' without the 'r'"}]},
  "airport": {t:"สนามบิน", p:"sa-naam bin", s:[{t:"สนาม",m:"Sa-naam",h:"'suh' + 'gnome'"},{t:"บิน",m:"Bin",h:"the word 'bin'"}]},
  "boat": {t:"เรือ", p:"reua", s:[{t:"เรือ",m:"Reua",h:"like 'roo' + 'ah'"}]},
  "motorcycle taxi": {t:"มอเตอร์ไซค์", p:"maw-ter-sai", s:[{t:"มอเตอร์",m:"Maw-ter",h:"like 'motor'"},{t:"ไซค์",m:"Sai",h:"like 'sigh'"}]},
  "how do I get to...?": {t:"ไป...ยังไง", p:"bpai...yang-ngai", s:[{t:"ไป",m:"Bpai",h:"like 'buy'"},{t:"ยังไง",m:"Yang-ngai",h:"'yung' + 'ngai'"}]},
  "turn left": {t:"เลี้ยวซ้าย", p:"liao saai", s:[{t:"เลี้ยว",m:"Liao",h:"like 'lee' + 'ow'"},{t:"ซ้าย",m:"Saai",h:"like 'sigh'"}]},
  "turn right": {t:"เลี้ยวขวา", p:"liao khwaa", s:[{t:"เลี้ยว",m:"Liao",h:"like 'lee' + 'ow'"},{t:"ขวา",m:"Khwaa",h:"like 'qua' in 'quality'"}]},
  "go": {t:"ไป", p:"bpai", s:[{t:"ไป",m:"Bpai",h:"like 'buy'"}]},
  "come": {t:"มา", p:"maa", s:[{t:"มา",m:"Maa",h:"the word 'ma'"}]},
  "map": {t:"แผนที่", p:"phaen-tee", s:[{t:"แผน",m:"Phaen",h:"like 'pan'"},{t:"ที่",m:"Tee",h:"the word 'tea'"}]},
  "I want to go to...": {t:"อยากไป...", p:"yaak bpai...", s:[{t:"อยาก",m:"Yaak",h:"like 'yak'"},{t:"ไป",m:"Bpai",h:"like 'buy'"}]},
  "how long does it take?": {t:"ใช้เวลานานเท่าไหร่", p:"chai way-laa naan tao rai", s:[{t:"ใช้",m:"Chai",h:"like 'chai' tea"},{t:"เวลา",m:"Way-laa",h:"'way' + 'la'"},{t:"นาน",m:"Naan",h:"like 'naan' bread"},{t:"เท่าไหร่",m:"Tao-rai",h:"'tao' + 'rye'"}]},
  "ferry": {t:"เรือข้ามฟาก", p:"reua khaam faak", s:[{t:"เรือ",m:"Reua",h:"like 'roo' + 'ah'"},{t:"ข้าม",m:"Khaam",h:"like 'calm'"},{t:"ฟาก",m:"Faak",h:"like 'fork' without the 'r'"}]},
  "intersection": {t:"แยก", p:"yaek", s:[{t:"แยก",m:"Yaek",h:"like 'yak' with an 'e'"}]},

  // ===== 9. ACCOMMODATION (15) =====
  "hotel": {t:"โรงแรม", p:"rong raem", s:[{t:"โรง",m:"Rong",h:"like 'wrong'"},{t:"แรม",m:"Raem",h:"like 'ram'"}]},
  "room": {t:"ห้อง", p:"hawng", s:[{t:"ห้อง",m:"Hawng",h:"like 'hong'"}]},
  "do you have a room?": {t:"มีห้องว่างไหม", p:"mee hawng waang mai", s:[{t:"มี",m:"Mee",h:"the word 'me'"},{t:"ห้อง",m:"Hawng",h:"like 'hong'"},{t:"ว่าง",m:"Waang",h:"like 'wrong' without the 'r'"},{t:"ไหม",m:"Mai",h:"the word 'my'"}]},
  "one night": {t:"หนึ่งคืน", p:"neung keun", s:[{t:"หนึ่ง",m:"Neung",h:"like 'nung' in 'young'"},{t:"คืน",m:"Keun",h:"like 'kern'"}]},
  "how much per night?": {t:"คืนละเท่าไหร่", p:"keun la tao rai", s:[{t:"คืน",m:"Keun",h:"like 'kern'"},{t:"ละ",m:"La",h:"the word 'la'"},{t:"เท่าไหร่",m:"Tao-rai",h:"'tao' + 'rye'"}]},
  "key": {t:"กุญแจ", p:"gun-jae", s:[{t:"กุญ",m:"Gun",h:"the word 'gun'"},{t:"แจ",m:"Jae",h:"like 'jay'"}]},
  "air conditioning": {t:"แอร์", p:"ae", s:[{t:"แอร์",m:"Ae",h:"the word 'air'"}]},
  "bathroom": {t:"ห้องน้ำ", p:"hawng nam", s:[{t:"ห้อง",m:"Hawng",h:"like 'hong'"},{t:"น้ำ",m:"Nam",h:"the word 'nom'"}]},
  "towel": {t:"ผ้าเช็ดตัว", p:"phaa chet tua", s:[{t:"ผ้า",m:"Phaa",h:"like 'pa'"},{t:"เช็ด",m:"Chet",h:"like 'chet'"},{t:"ตัว",m:"Tua",h:"like 'too' + 'ah'"}]},
  "check in": {t:"เช็คอิน", p:"chek in", s:[{t:"เช็ค",m:"Chek",h:"the word 'check'"},{t:"อิน",m:"In",h:"the word 'in'"}]},
  "check out": {t:"เช็คเอาท์", p:"chek ao", s:[{t:"เช็ค",m:"Chek",h:"the word 'check'"},{t:"เอาท์",m:"Ao",h:"the word 'out'"}]},
  "wifi password": {t:"รหัสไวไฟ", p:"ra-hat wai-fai", s:[{t:"รหัส",m:"Ra-hat",h:"'ruh' + 'hut'"},{t:"ไวไฟ",m:"Wai-fai",h:"the word 'wifi'"}]},
  "hot water": {t:"น้ำร้อน", p:"nam rawn", s:[{t:"น้ำ",m:"Nam",h:"the word 'nom'"},{t:"ร้อน",m:"Rawn",h:"like 'Ron'"}]},
  "cold water": {t:"น้ำเย็น", p:"nam yen", s:[{t:"น้ำ",m:"Nam",h:"the word 'nom'"},{t:"เย็น",m:"Yen",h:"the word 'yen'"}]},
  "blanket": {t:"ผ้าห่ม", p:"phaa hom", s:[{t:"ผ้า",m:"Phaa",h:"like 'pa'"},{t:"ห่ม",m:"Hom",h:"the word 'home' without the 'e'"}]},

  // ===== 10. COMMUNICATION (15) =====
  "do you speak English?": {t:"พูดภาษาอังกฤษได้ไหม", p:"phoot phaa-saa ang-grit dai mai", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"ภาษา",m:"Phaa-saa",h:"'pa' + 'sa'"},{t:"อังกฤษ",m:"Ang-grit",h:"like 'English' in Thai"},{t:"ได้ไหม",m:"Dai-mai",h:"'die' + 'my'"}]},
  "I don't speak Thai": {t:"พูดไทยไม่ได้", p:"phoot thai mai dai", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"},{t:"ไม่ได้",m:"Mai-dai",h:"'my' + 'die'"}]},
  "please speak slowly": {t:"พูดช้าหน่อย", p:"phoot chaa noi", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"ช้า",m:"Chaa",h:"like 'cha'"},{t:"หน่อย",m:"Noi",h:"like 'noy' in 'annoy'"}]},
  "please say that again": {t:"พูดอีกทีได้ไหม", p:"phoot eek tee dai mai", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"อีกที",m:"Eek-tee",h:"'eek' + 'tea'"},{t:"ได้ไหม",m:"Dai-mai",h:"'die' + 'my'"}]},
  "what does this mean?": {t:"นี่แปลว่าอะไร", p:"nee bplae waa a-rai", s:[{t:"นี่",m:"Nee",h:"the word 'knee'"},{t:"แปล",m:"Bplae",h:"like 'play' without the 'y'"},{t:"ว่า",m:"Waa",h:"the word 'wa'"},{t:"อะไร",m:"A-rai",h:"'uh' + 'rye'"}]},
  "telephone": {t:"โทรศัพท์", p:"toh-ra-sap", s:[{t:"โทร",m:"Toh",h:"like 'toe'"},{t:"ศัพท์",m:"Ra-sap",h:"'ruh' + 'sup'"}]},
  "internet": {t:"อินเทอร์เน็ต", p:"in-ter-net", s:[{t:"อินเทอร์เน็ต",m:"In-ter-net",h:"the word 'internet'"}]},
  "what is this?": {t:"นี่คืออะไร", p:"nee keu a-rai", s:[{t:"นี่",m:"Nee",h:"the word 'knee'"},{t:"คือ",m:"Keu",h:"like 'ker'"},{t:"อะไร",m:"A-rai",h:"'uh' + 'rye'"}]},
  "how do you say...?": {t:"...พูดว่าอะไร", p:"...phoot waa a-rai", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"ว่า",m:"Waa",h:"the word 'wa'"},{t:"อะไร",m:"A-rai",h:"'uh' + 'rye'"}]},
  "write it down please": {t:"เขียนให้หน่อย", p:"khian hai noi", s:[{t:"เขียน",m:"Khian",h:"like 'key' + 'un'"},{t:"ให้",m:"Hai",h:"the word 'hi'"},{t:"หน่อย",m:"Noi",h:"like 'noy' in 'annoy'"}]},
  "I speak a little Thai": {t:"พูดไทยได้นิดหน่อย", p:"phoot thai dai nit noi", s:[{t:"พูด",m:"Phoot",h:"like 'put'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"},{t:"ได้",m:"Dai",h:"the word 'die'"},{t:"นิดหน่อย",m:"Nit-noi",h:"'knit' + 'noy'"}]},
  "translate": {t:"แปล", p:"bplae", s:[{t:"แปล",m:"Bplae",h:"like 'play' without the 'y'"}]},
  "English": {t:"ภาษาอังกฤษ", p:"phaa-saa ang-grit", s:[{t:"ภาษา",m:"Phaa-saa",h:"'pa' + 'sa'"},{t:"อังกฤษ",m:"Ang-grit",h:"like 'English' in Thai"}]},
  "Thai language": {t:"ภาษาไทย", p:"phaa-saa thai", s:[{t:"ภาษา",m:"Phaa-saa",h:"'pa' + 'sa'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"}]},
  "what?": {t:"อะไร", p:"a-rai", s:[{t:"อะไร",m:"A-rai",h:"'uh' + 'rye'"}]},

  // ===== 11. HEALTH (10) =====
  "I'm sick": {t:"ไม่สบาย", p:"mai sa-baai", s:[{t:"ไม่",m:"Mai",h:"the word 'my'"},{t:"สบาย",m:"Sa-baai",h:"'suh' + 'buy'"}]},
  "headache": {t:"ปวดหัว", p:"bpuat hua", s:[{t:"ปวด",m:"Bpuat",h:"like 'boot' with a 'pw'"},{t:"หัว",m:"Hua",h:"like 'who' + 'ah'"}]},
  "stomachache": {t:"ปวดท้อง", p:"bpuat tawng", s:[{t:"ปวด",m:"Bpuat",h:"like 'boot' with a 'pw'"},{t:"ท้อง",m:"Tawng",h:"like 'tongue'"}]},
  "fever": {t:"มีไข้", p:"mee khai", s:[{t:"มี",m:"Mee",h:"the word 'me'"},{t:"ไข้",m:"Khai",h:"the word 'kite' without the 't'"}]},
  "pharmacy": {t:"ร้านขายยา", p:"raan khaai yaa", s:[{t:"ร้าน",m:"Raan",h:"like 'run' with a long 'a'"},{t:"ขาย",m:"Khaai",h:"like 'kite' without the 't'"},{t:"ยา",m:"Yaa",h:"the word 'ya'"}]},
  "medicine": {t:"ยา", p:"yaa", s:[{t:"ยา",m:"Yaa",h:"the word 'ya'"}]},
  "it hurts here": {t:"เจ็บตรงนี้", p:"jep dtrong nee", s:[{t:"เจ็บ",m:"Jep",h:"like 'jab' with an 'e'"},{t:"ตรง",m:"Dtrong",h:"like 'strong' without the 's'"},{t:"นี้",m:"Nee",h:"the word 'knee'"}]},
  "I have diarrhea": {t:"ท้องเสีย", p:"tawng sia", s:[{t:"ท้อง",m:"Tawng",h:"like 'tongue'"},{t:"เสีย",m:"Sia",h:"like 'see' + 'ah'"}]},
  "I need medicine": {t:"ต้องการยา", p:"tawng gaan yaa", s:[{t:"ต้อง",m:"Tawng",h:"like 'tongue'"},{t:"การ",m:"Gaan",h:"the word 'gone'"},{t:"ยา",m:"Yaa",h:"the word 'ya'"}]},
  "doctor": {t:"หมอ", p:"maw", s:[{t:"หมอ",m:"Maw",h:"like 'more' without the 'r'"}]},

  // ===== 12. TIME (10) =====
  "today": {t:"วันนี้", p:"wan nee", s:[{t:"วัน",m:"Wan",h:"the word 'won'"},{t:"นี้",m:"Nee",h:"the word 'knee'"}]},
  "tomorrow": {t:"พรุ่งนี้", p:"phrung nee", s:[{t:"พรุ่ง",m:"Phrung",h:"like 'prung'"},{t:"นี้",m:"Nee",h:"the word 'knee'"}]},
  "yesterday": {t:"เมื่อวาน", p:"meua waan", s:[{t:"เมื่อ",m:"Meua",h:"like 'moo' + 'ah'"},{t:"วาน",m:"Waan",h:"the word 'wan'"}]},
  "now": {t:"ตอนนี้", p:"tawn nee", s:[{t:"ตอน",m:"Tawn",h:"like 'torn'"},{t:"นี้",m:"Nee",h:"the word 'knee'"}]},
  "later": {t:"ทีหลัง", p:"tee lang", s:[{t:"ที",m:"Tee",h:"the word 'tea'"},{t:"หลัง",m:"Lang",h:"the word 'lung'"}]},
  "what time is it?": {t:"กี่โมงแล้ว", p:"gee mong laew", s:[{t:"กี่",m:"Gee",h:"the word 'gee'"},{t:"โมง",m:"Mong",h:"like 'mong'"},{t:"แล้ว",m:"Laew",h:"like 'la' + 'ew'"}]},
  "morning": {t:"เช้า", p:"chao", s:[{t:"เช้า",m:"Chao",h:"like 'chow'"}]},
  "afternoon": {t:"บ่าย", p:"baai", s:[{t:"บ่าย",m:"Baai",h:"like 'buy'"}]},
  "evening / night": {t:"กลางคืน", p:"glaang keun", s:[{t:"กลาง",m:"Glaang",h:"like 'g' + 'long'"},{t:"คืน",m:"Keun",h:"like 'kern'"}]},
  "minute": {t:"นาที", p:"naa-tee", s:[{t:"นา",m:"Naa",h:"the word 'nah'"},{t:"ที",m:"Tee",h:"the word 'tea'"}]},

  // ===== 13. WEATHER & MISC (10) =====
  "hot (weather)": {t:"ร้อน", p:"rawn", s:[{t:"ร้อน",m:"Rawn",h:"like 'Ron'"}]},
  "cold (weather)": {t:"หนาว", p:"naao", s:[{t:"หนาว",m:"Naao",h:"like 'now'"}]},
  "rain": {t:"ฝน", p:"fon", s:[{t:"ฝน",m:"Fon",h:"the word 'phone' without the 'e'"}]},
  "it's raining": {t:"ฝนตก", p:"fon tok", s:[{t:"ฝน",m:"Fon",h:"the word 'phone' without the 'e'"},{t:"ตก",m:"Tok",h:"like 'talk' without the 'l'"}]},
  "sunny": {t:"แดดออก", p:"daet awk", s:[{t:"แดด",m:"Daet",h:"like 'dad' with a long 'a'"},{t:"ออก",m:"Awk",h:"like 'awk-ward'"}]},
  "Thailand": {t:"ประเทศไทย", p:"bpra-tet thai", s:[{t:"ประเทศ",m:"Bpra-tet",h:"'bra' + 'tet'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"}]},
  "Thai person": {t:"คนไทย", p:"khon thai", s:[{t:"คน",m:"Khon",h:"like 'con'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"}]},
  "foreigner": {t:"ฝรั่ง", p:"fa-rang", s:[{t:"ฝรั่ง",m:"Fa-rang",h:"like 'fur' + 'rung'"}]},
  "fun": {t:"สนุก", p:"sa-nuk", s:[{t:"สนุก",m:"Sa-nuk",h:"'suh' + 'nook'"}]},
  "I love Thailand": {t:"รักเมืองไทย", p:"rak meuang thai", s:[{t:"รัก",m:"Rak",h:"the word 'ruck'"},{t:"เมือง",m:"Meuang",h:"like 'moo' + 'ung'"},{t:"ไทย",m:"Thai",h:"the word 'tie'"}]}
};
