var DICT_FR = {

  // ============ GREETINGS (20) ============

  "hello": {t:"bonjour", s:[{t:"bon",m:"Bon",h:"nasal 'bon' as in 'bon' voyage"},{t:"jour",m:"Joor",h:"'joo' + guttural R"}]},
  "good evening": {t:"bonsoir", s:[{t:"bon",m:"Bon",h:"nasal 'bon' as in 'bon' voyage"},{t:"soir",m:"Swahr",h:"'swah' + guttural R"}]},
  "goodbye": {t:"au revoir", s:[{t:"au",m:"Oh",h:"like 'oh'"},{t:"re",m:"Ruh",h:"guttural R + 'uh'"},{t:"voir",m:"Vwahr",h:"'vwah' + guttural R"}]},
  "good night": {t:"bonne nuit", s:[{t:"bonne",m:"Bun",h:"like 'bun' the bread"},{t:"nuit",m:"Nwee",h:"'n' + 'we' as in 'week'"}]},
  "see you later": {t:"à plus tard", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"plus",m:"Plew",h:"'plew' with pursed lips"},{t:"tard",m:"Tahr",h:"'tah' + guttural R, silent D"}]},
  "see you soon": {t:"à bientôt", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"tôt",m:"Toe",h:"like 'toe', silent T"}]},
  "how are you": {t:"comment allez-vous", s:[{t:"co",m:"Cuh",h:"like 'come' without the M"},{t:"mment",m:"Mon",h:"nasal 'mon'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"llez",m:"Lay",h:"like 'lay'"},{t:"vous",m:"Voo",h:"like 'voo' in voodoo"}]},
  "I'm fine": {t:"je vais bien", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"vais",m:"Vay",h:"like 'vay' in survey"},{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"}]},
  "please": {t:"s'il vous plaît", s:[{t:"s'il",m:"Seal",h:"like 'seal'"},{t:"vous",m:"Voo",h:"like 'voo' in voodoo"},{t:"plaît",m:"Play",h:"like 'play', silent T"}]},
  "thank you": {t:"merci", s:[{t:"mer",m:"Mare",h:"like 'mare' the horse"},{t:"ci",m:"See",h:"like 'see'"}]},
  "thank you very much": {t:"merci beaucoup", s:[{t:"mer",m:"Mare",h:"like 'mare'"},{t:"ci",m:"See",h:"like 'see'"},{t:"beau",m:"Bow",h:"like 'bow' of a ship"},{t:"coup",m:"Coo",h:"like 'coo' a pigeon makes"}]},
  "you're welcome": {t:"de rien", s:[{t:"de",m:"Duh",h:"like 'duh'"},{t:"rien",m:"Ree-en",h:"nasal 'ree-en', guttural R"}]},
  "excuse me": {t:"excusez-moi", s:[{t:"ex",m:"Ex",h:"like 'ex'"},{t:"cu",m:"Kew",h:"'kew' with pursed lips"},{t:"sez",m:"Zay",h:"like 'zay'"},{t:"moi",m:"Mwah",h:"like 'mwah' a kiss"}]},
  "sorry": {t:"pardon", s:[{t:"par",m:"Par",h:"like 'par' in golf, guttural R"},{t:"don",m:"Don",h:"nasal 'don', like 'don' a coat"}]},
  "I'm sorry": {t:"je suis désolé", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"suis",m:"Swee",h:"'s' + 'we' as in 'week'"},{t:"dé",m:"Day",h:"like 'day'"},{t:"so",m:"Zoh",h:"like 'zone' without the N"},{t:"lé",m:"Lay",h:"like 'lay'"}]},
  "nice to meet you": {t:"enchanté", s:[{t:"en",m:"On",h:"nasal 'on'"},{t:"chan",m:"Shon",h:"nasal 'shon'"},{t:"té",m:"Tay",h:"like 'tay' in stay"}]},
  "my name is": {t:"je m'appelle", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"m'a",m:"Mah",h:"like 'ma'"},{t:"ppelle",m:"Pell",h:"like 'pell' in compel"}]},
  "what is your name": {t:"comment vous appelez-vous", s:[{t:"co",m:"Cuh",h:"like 'come' without the M"},{t:"mment",m:"Mon",h:"nasal 'mon'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ppe",m:"Play",h:"like 'play'"},{t:"lez",m:"Lay",h:"like 'lay'"},{t:"vous",m:"Voo",h:"like 'voo'"}]},
  "good morning": {t:"bonjour", s:[{t:"bon",m:"Bon",h:"nasal 'bon' as in 'bon' voyage"},{t:"jour",m:"Joor",h:"'joo' + guttural R"}]},
  "welcome": {t:"bienvenue", s:[{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"ve",m:"Vuh",h:"like 'vug' without the G"},{t:"nue",m:"New",h:"like 'new' with pursed lips"}]},

  // ============ YES/NO/BASICS (10) ============

  "yes": {t:"oui", s:[{t:"oui",m:"We",h:"like 'we'"}]},
  "no": {t:"non", s:[{t:"non",m:"Non",h:"nasal 'non', like 'known' without the K"}]},
  "maybe": {t:"peut-être", s:[{t:"peut",m:"Puh",h:"like 'push' without the SH"},{t:"ê",m:"Eh",h:"like 'eh'"},{t:"tre",m:"Truh",h:"'tr' + 'uh', guttural R"}]},
  "of course": {t:"bien sûr", s:[{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"sûr",m:"Sewer",h:"'s' + pursed lips 'ewer'"}]},
  "I don't understand": {t:"je ne comprends pas", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"ne",m:"Nuh",h:"like 'nub' without the B"},{t:"com",m:"Con",h:"nasal 'con'"},{t:"prends",m:"Pron",h:"nasal 'pron', guttural R"},{t:"pas",m:"Pah",h:"like 'pa', silent S"}]},
  "I understand": {t:"je comprends", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"com",m:"Con",h:"nasal 'con'"},{t:"prends",m:"Pron",h:"nasal 'pron', guttural R"}]},
  "do you speak English": {t:"parlez-vous anglais", s:[{t:"par",m:"Par",h:"like 'par', guttural R"},{t:"lez",m:"Lay",h:"like 'lay'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"an",m:"On",h:"nasal 'on'"},{t:"glais",m:"Glay",h:"like 'glay' in 'play' with G"}]},
  "I don't speak French": {t:"je ne parle pas français", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"ne",m:"Nuh",h:"like 'nub' without the B"},{t:"parle",m:"Parl",h:"like 'par' + L, guttural R"},{t:"pas",m:"Pah",h:"like 'pa', silent S"},{t:"fran",m:"Fron",h:"nasal 'fron', guttural R"},{t:"çais",m:"Say",h:"like 'say'"}]},
  "I speak a little French": {t:"je parle un peu français", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"parle",m:"Parl",h:"like 'par' + L"},{t:"un",m:"Un",h:"nasal 'un', pursed lips"},{t:"peu",m:"Puh",h:"pursed lips 'puh'"},{t:"fran",m:"Fron",h:"nasal 'fron'"},{t:"çais",m:"Say",h:"like 'say'"}]},
  "can you repeat that": {t:"pouvez-vous répéter", s:[{t:"pou",m:"Poo",h:"like 'pooh'"},{t:"vez",m:"Vay",h:"like 'vay'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"ré",m:"Ray",h:"like 'ray'"},{t:"pé",m:"Pay",h:"like 'pay'"},{t:"ter",m:"Tay",h:"like 'tay', silent R in casual speech"}]},

  // ============ EMERGENCY (15) ============

  "help": {t:"au secours", s:[{t:"au",m:"Oh",h:"like 'oh'"},{t:"se",m:"Suh",h:"like 'sub' without the B"},{t:"cours",m:"Coor",h:"like 'coor' in 'courier'"}]},
  "call the police": {t:"appelez la police", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"ppe",m:"Play",h:"like 'play'"},{t:"lez",m:"Lay",h:"like 'lay'"},{t:"la",m:"Lah",h:"like 'la' in music"},{t:"po",m:"Poh",h:"like 'poe'"},{t:"lice",m:"Lease",h:"like 'lease'"}]},
  "call an ambulance": {t:"appelez une ambulance", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"ppe",m:"Play",h:"like 'play'"},{t:"lez",m:"Lay",h:"like 'lay'"},{t:"une",m:"Oon",h:"like 'oon' in moon"},{t:"am",m:"On",h:"nasal 'on'"},{t:"bu",m:"Bew",h:"'b' + pursed lips 'ew'"},{t:"lance",m:"Lons",h:"nasal 'lons'"}]},
  "I need a doctor": {t:"j'ai besoin d'un médecin", s:[{t:"j'ai",m:"Jay",h:"like 'jay' the bird"},{t:"be",m:"Buh",h:"like 'but' without the T"},{t:"soin",m:"Swan",h:"nasal 'swan'"},{t:"d'un",m:"Done",h:"nasal 'done'"},{t:"mé",m:"May",h:"like 'may'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"cin",m:"San",h:"nasal 'san'"}]},
  "fire": {t:"au feu", s:[{t:"au",m:"Oh",h:"like 'oh'"},{t:"feu",m:"Fuh",h:"'f' + pursed lips, like 'fur' without the R"}]},
  "I'm lost": {t:"je suis perdu", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"suis",m:"Swee",h:"'s' + 'we'"},{t:"per",m:"Pair",h:"like 'pair', guttural R"},{t:"du",m:"Dew",h:"'d' + pursed lips 'ew'"}]},
  "danger": {t:"danger", s:[{t:"dan",m:"Don",h:"nasal 'don'"},{t:"ger",m:"Jay",h:"like 'jay', silent R"}]},
  "stop": {t:"arrêtez", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"rrê",m:"Reh",h:"guttural R + 'eh'"},{t:"tez",m:"Tay",h:"like 'tay'"}]},
  "I've been robbed": {t:"on m'a volé", s:[{t:"on",m:"On",h:"nasal 'on'"},{t:"m'a",m:"Mah",h:"like 'ma'"},{t:"vo",m:"Voh",h:"like 'vow' without the W"},{t:"lé",m:"Lay",h:"like 'lay'"}]},
  "emergency": {t:"urgence", s:[{t:"ur",m:"Ewer",h:"pursed lips 'ewer', guttural R"},{t:"gence",m:"Johns",h:"like 'johns', nasal ending"}]},
  "I need help": {t:"j'ai besoin d'aide", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"be",m:"Buh",h:"like 'but' without the T"},{t:"soin",m:"Swan",h:"nasal 'swan'"},{t:"d'aide",m:"Dead",h:"like 'dead'"}]},
  "where is the hospital": {t:"où est l'hôpital", s:[{t:"où",m:"Oo",h:"like 'oo' in 'ooze'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"l'hô",m:"Low",h:"like 'low'"},{t:"pi",m:"Pee",h:"like 'pee'"},{t:"tal",m:"Tal",h:"like 'tall'"}]},
  "I'm hurt": {t:"je suis blessé", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"suis",m:"Swee",h:"'s' + 'we'"},{t:"ble",m:"Bless",h:"like 'bless'"},{t:"ssé",m:"Say",h:"like 'say'"}]},
  "it's an emergency": {t:"c'est une urgence", s:[{t:"c'est",m:"Set",h:"like 'set'"},{t:"une",m:"Oon",h:"like 'oon' in moon"},{t:"ur",m:"Ewer",h:"pursed lips 'ewer'"},{t:"gence",m:"Johns",h:"like 'johns'"}]},
  "thief": {t:"au voleur", s:[{t:"au",m:"Oh",h:"like 'oh'"},{t:"vo",m:"Voh",h:"like 'vow' without the W"},{t:"leur",m:"Lure",h:"like 'lure', guttural R"}]},

  // ============ NUMBERS (15) ============

  "zero": {t:"zéro", s:[{t:"zé",m:"Zay",h:"like 'zay'"},{t:"ro",m:"Row",h:"guttural R + 'oh'"}]},
  "one": {t:"un", s:[{t:"un",m:"Un",h:"nasal 'un', pursed lips"}]},
  "two": {t:"deux", s:[{t:"deux",m:"Duh",h:"'d' + pursed lips, like 'duh' with rounded lips"}]},
  "three": {t:"trois", s:[{t:"trois",m:"Twah",h:"guttural R, 'twah'"}]},
  "four": {t:"quatre", s:[{t:"qua",m:"Cat",h:"like 'cat'"},{t:"tre",m:"Truh",h:"'tr' + 'uh', guttural R"}]},
  "five": {t:"cinq", s:[{t:"cinq",m:"Sank",h:"like 'sank' a ship"}]},
  "six": {t:"six", s:[{t:"six",m:"Cease",h:"like 'cease'"}]},
  "seven": {t:"sept", s:[{t:"sept",m:"Set",h:"like 'set', silent PT"}]},
  "eight": {t:"huit", s:[{t:"huit",m:"Wheat",h:"like 'wheat'"}]},
  "nine": {t:"neuf", s:[{t:"neuf",m:"Nuff",h:"like 'nuff' in enough"}]},
  "ten": {t:"dix", s:[{t:"dix",m:"Deece",h:"like 'deece' in fleece with D"}]},
  "twenty": {t:"vingt", s:[{t:"vingt",m:"Van",h:"nasal 'van', silent GT"}]},
  "fifty": {t:"cinquante", s:[{t:"cin",m:"San",h:"nasal 'san'"},{t:"quante",m:"Cont",h:"nasal 'cont'"}]},
  "one hundred": {t:"cent", s:[{t:"cent",m:"Son",h:"nasal 'son', like 'son'"}]},
  "one thousand": {t:"mille", s:[{t:"mille",m:"Meal",h:"like 'meal'"}]},

  // ============ FOOD & DRINK (30) ============

  "water": {t:"de l'eau", s:[{t:"de",m:"Duh",h:"like 'duh'"},{t:"l'eau",m:"Low",h:"like 'low'"}]},
  "coffee": {t:"café", s:[{t:"ca",m:"Cah",h:"like 'car' without the R"},{t:"fé",m:"Fay",h:"like 'fay'"}]},
  "tea": {t:"thé", s:[{t:"thé",m:"Tay",h:"like 'tay' in stay"}]},
  "beer": {t:"bière", s:[{t:"bi",m:"Bee",h:"like 'bee'"},{t:"ère",m:"Air",h:"like 'air'"}]},
  "wine": {t:"vin", s:[{t:"vin",m:"Van",h:"nasal 'van'"}]},
  "red wine": {t:"vin rouge", s:[{t:"vin",m:"Van",h:"nasal 'van'"},{t:"rouge",m:"Rooj",h:"guttural R + 'ooj'"}]},
  "white wine": {t:"vin blanc", s:[{t:"vin",m:"Van",h:"nasal 'van'"},{t:"blanc",m:"Blon",h:"nasal 'blon', silent C"}]},
  "bread": {t:"pain", s:[{t:"pain",m:"Pan",h:"nasal 'pan'"}]},
  "cheese": {t:"fromage", s:[{t:"fro",m:"Froh",h:"guttural R + 'oh'"},{t:"mage",m:"Mahj",h:"like 'mahj' in mahjong"}]},
  "meat": {t:"viande", s:[{t:"vi",m:"Vee",h:"like 'vee'"},{t:"ande",m:"Ond",h:"nasal 'ond'"}]},
  "chicken": {t:"poulet", s:[{t:"pou",m:"Pooh",h:"like 'pooh'"},{t:"let",m:"Lay",h:"like 'lay', silent T"}]},
  "fish": {t:"poisson", s:[{t:"poi",m:"Pwah",h:"'oi' = 'wah'"},{t:"sson",m:"Son",h:"nasal 'son'"}]},
  "vegetables": {t:"légumes", s:[{t:"lé",m:"Lay",h:"like 'lay'"},{t:"gumes",m:"Goom",h:"like 'goom' in mushroom"}]},
  "fruit": {t:"fruits", s:[{t:"fruits",m:"Frwee",h:"guttural R + 'wee', silent TS"}]},
  "salad": {t:"salade", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"lade",m:"Lad",h:"like 'lad'"}]},
  "soup": {t:"soupe", s:[{t:"soupe",m:"Soup",h:"like 'soup'"}]},
  "egg": {t:"œuf", s:[{t:"œuf",m:"Uff",h:"like 'uff' in 'huff'"}]},
  "butter": {t:"beurre", s:[{t:"beurre",m:"Burr",h:"like 'burr', guttural R"}]},
  "milk": {t:"lait", s:[{t:"lait",m:"Lay",h:"like 'lay', silent T"}]},
  "sugar": {t:"sucre", s:[{t:"su",m:"Sew",h:"'s' + pursed lips 'ew'"},{t:"cre",m:"Cruh",h:"'cr' + 'uh', guttural R"}]},
  "salt": {t:"sel", s:[{t:"sel",m:"Sell",h:"like 'sell'"}]},
  "pepper": {t:"poivre", s:[{t:"poi",m:"Pwah",h:"'oi' = 'wah'"},{t:"vre",m:"Vruh",h:"'vr' + 'uh', guttural R"}]},
  "ice cream": {t:"glace", s:[{t:"glace",m:"Glass",h:"like 'glass'"}]},
  "cake": {t:"gâteau", s:[{t:"gâ",m:"Gah",h:"like 'gas' without the S"},{t:"teau",m:"Toe",h:"like 'toe', 'eau' = 'oh'"}]},
  "I'm hungry": {t:"j'ai faim", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"faim",m:"Fan",h:"nasal 'fan'"}]},
  "I'm thirsty": {t:"j'ai soif", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"soif",m:"Swahf",h:"'swah' + F"}]},
  "a glass of": {t:"un verre de", s:[{t:"un",m:"Un",h:"nasal 'un'"},{t:"verre",m:"Vair",h:"like 'fair' with V, guttural R"},{t:"de",m:"Duh",h:"like 'duh'"}]},
  "a bottle of": {t:"une bouteille de", s:[{t:"une",m:"Oon",h:"like 'oon' in moon"},{t:"bou",m:"Boo",h:"like 'boo'"},{t:"teille",m:"Tay",h:"like 'tay'"},{t:"de",m:"Duh",h:"like 'duh'"}]},
  "orange juice": {t:"jus d'orange", s:[{t:"jus",m:"Jew",h:"'j' + pursed lips 'ew'"},{t:"d'o",m:"Door",h:"like 'door'"},{t:"range",m:"Ronj",h:"nasal 'ronj'"}]},
  "croissant": {t:"croissant", s:[{t:"croi",m:"Kwah",h:"guttural R, 'oi' = 'wah'"},{t:"ssant",m:"Son",h:"nasal 'son', silent T"}]},

  // ============ RESTAURANT (15) ============

  "a table for two": {t:"une table pour deux", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"table",m:"Tahbl",h:"like 'table' with 'ah'"},{t:"pour",m:"Poor",h:"like 'poor'"},{t:"deux",m:"Duh",h:"'d' + pursed lips"}]},
  "the menu please": {t:"la carte s'il vous plaît", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"carte",m:"Cart",h:"like 'cart', guttural R"},{t:"s'il",m:"Seal",h:"like 'seal'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"plaît",m:"Play",h:"like 'play'"}]},
  "I would like": {t:"je voudrais", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"vou",m:"Voo",h:"like 'voo'"},{t:"drais",m:"Dray",h:"guttural R + 'ay'"}]},
  "the bill please": {t:"l'addition s'il vous plaît", s:[{t:"l'a",m:"Lah",h:"like 'la'"},{t:"ddi",m:"Dee",h:"like 'dee'"},{t:"tion",m:"See-on",h:"'see' + nasal 'on'"},{t:"s'il",m:"Seal",h:"like 'seal'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"plaît",m:"Play",h:"like 'play'"}]},
  "is service included": {t:"le service est compris", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"ser",m:"Sair",h:"like 'sair'"},{t:"vice",m:"Veece",h:"like 'fleece' with V"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"com",m:"Con",h:"nasal 'con'"},{t:"pris",m:"Pree",h:"like 'preen' without the N"}]},
  "I'm vegetarian": {t:"je suis végétarien", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"suis",m:"Swee",h:"'s' + 'we'"},{t:"vé",m:"Vay",h:"like 'vay'"},{t:"gé",m:"Jay",h:"like 'jay'"},{t:"ta",m:"Tah",h:"like 'ta'"},{t:"rien",m:"Ree-en",h:"nasal 'ree-en'"}]},
  "no meat": {t:"sans viande", s:[{t:"sans",m:"Son",h:"nasal 'son'"},{t:"vi",m:"Vee",h:"like 'vee'"},{t:"ande",m:"Ond",h:"nasal 'ond'"}]},
  "rare": {t:"saignant", s:[{t:"sai",m:"Sen",h:"nasal 'sen'"},{t:"gnant",m:"Nyon",h:"'ny' + nasal 'on'"}]},
  "medium": {t:"à point", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"point",m:"Pwan",h:"nasal 'pwan'"}]},
  "well done": {t:"bien cuit", s:[{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"cuit",m:"Kwee",h:"like 'kwee'"}]},
  "delicious": {t:"délicieux", s:[{t:"dé",m:"Day",h:"like 'day'"},{t:"li",m:"Lee",h:"like 'lee'"},{t:"cieux",m:"See-uh",h:"'see' + pursed 'uh'"}]},
  "a reservation": {t:"une réservation", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"ré",m:"Ray",h:"like 'ray'"},{t:"ser",m:"Zair",h:"like 'zair'"},{t:"va",m:"Vah",h:"like 'va'"},{t:"tion",m:"See-on",h:"'see' + nasal 'on'"}]},
  "waiter": {t:"monsieur", s:[{t:"mon",m:"Muh",h:"nasal, like 'muh'"},{t:"sieur",m:"See-uh",h:"'see' + 'uh'"}]},
  "more bread please": {t:"encore du pain s'il vous plaît", s:[{t:"en",m:"On",h:"nasal 'on'"},{t:"core",m:"Core",h:"like 'core'"},{t:"du",m:"Dew",h:"pursed lips 'dew'"},{t:"pain",m:"Pan",h:"nasal 'pan'"},{t:"s'il",m:"Seal",h:"like 'seal'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"plaît",m:"Play",h:"like 'play'"}]},
  "for here or to go": {t:"sur place ou à emporter", s:[{t:"sur",m:"Sewer",h:"pursed lips 'sewer'"},{t:"place",m:"Plass",h:"like 'plass'"},{t:"ou",m:"Oo",h:"like 'oo'"},{t:"à",m:"Ah",h:"like 'ah'"},{t:"em",m:"On",h:"nasal 'on'"},{t:"por",m:"Pour",h:"like 'pour'"},{t:"ter",m:"Tay",h:"like 'tay'"}]},

  // ============ SHOPPING (20) ============

  "how much does this cost": {t:"combien ça coûte", s:[{t:"com",m:"Con",h:"nasal 'con'"},{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"ça",m:"Sah",h:"like 'saw'"},{t:"coûte",m:"Coot",h:"like 'coot' the bird"}]},
  "too expensive": {t:"trop cher", s:[{t:"trop",m:"Trow",h:"guttural R + 'oh'"},{t:"cher",m:"Share",h:"like 'share', guttural R"}]},
  "cheap": {t:"bon marché", s:[{t:"bon",m:"Bon",h:"nasal 'bon'"},{t:"mar",m:"Mar",h:"like 'mar', guttural R"},{t:"ché",m:"Shay",h:"like 'shay'"}]},
  "I'm looking for": {t:"je cherche", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"cherche",m:"Shairsh",h:"'share' + SH, guttural R"}]},
  "do you have": {t:"avez-vous", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"vez",m:"Vay",h:"like 'vay'"},{t:"vous",m:"Voo",h:"like 'voo'"}]},
  "I'll take it": {t:"je le prends", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"prends",m:"Pron",h:"nasal 'pron', guttural R"}]},
  "can I try this on": {t:"puis-je essayer", s:[{t:"puis",m:"Pwee",h:"'pw' + 'ee'"},{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"e",m:"Eh",h:"like 'eh'"},{t:"ssay",m:"Say",h:"like 'say'"},{t:"er",m:"Ay",h:"like 'ay'"}]},
  "what size": {t:"quelle taille", s:[{t:"quelle",m:"Kell",h:"like 'kell'"},{t:"taille",m:"Tie",h:"like 'tie'"}]},
  "bigger": {t:"plus grand", s:[{t:"plus",m:"Plew",h:"pursed lips 'plew'"},{t:"grand",m:"Gron",h:"nasal 'gron', guttural R, silent D"}]},
  "smaller": {t:"plus petit", s:[{t:"plus",m:"Plew",h:"pursed lips 'plew'"},{t:"pe",m:"Puh",h:"like 'push' without the SH"},{t:"tit",m:"Tee",h:"like 'tee', silent T"}]},
  "I'm just looking": {t:"je regarde", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"re",m:"Ruh",h:"guttural R + 'uh'"},{t:"garde",m:"Gard",h:"like 'guard'"}]},
  "where is the market": {t:"où est le marché", s:[{t:"où",m:"Oo",h:"like 'oo'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"mar",m:"Mar",h:"like 'mar', guttural R"},{t:"ché",m:"Shay",h:"like 'shay'"}]},
  "receipt": {t:"le reçu", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"re",m:"Ruh",h:"guttural R + 'uh'"},{t:"çu",m:"Sew",h:"'s' + pursed lips 'ew'"}]},
  "cash": {t:"espèces", s:[{t:"es",m:"Eh",h:"like 'eh'"},{t:"pè",m:"Pess",h:"like 'pess' in pessimist"},{t:"ces",m:"Suh",h:"like 'sub' without the B"}]},
  "credit card": {t:"carte de crédit", s:[{t:"carte",m:"Cart",h:"like 'cart'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"cré",m:"Cray",h:"guttural R + 'ay'"},{t:"dit",m:"Dee",h:"like 'dee', silent T"}]},
  "open": {t:"ouvert", s:[{t:"ou",m:"Oo",h:"like 'oo'"},{t:"vert",m:"Vair",h:"like 'fair' with V, silent T"}]},
  "closed": {t:"fermé", s:[{t:"fer",m:"Fair",h:"like 'fair', guttural R"},{t:"mé",m:"May",h:"like 'may'"}]},
  "pharmacy": {t:"pharmacie", s:[{t:"phar",m:"Far",h:"like 'far', guttural R"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"cie",m:"See",h:"like 'see'"}]},
  "supermarket": {t:"supermarché", s:[{t:"su",m:"Sew",h:"pursed lips 'sew'"},{t:"per",m:"Pair",h:"like 'pair'"},{t:"mar",m:"Mar",h:"like 'mar', guttural R"},{t:"ché",m:"Shay",h:"like 'shay'"}]},
  "a gift": {t:"un cadeau", s:[{t:"un",m:"Un",h:"nasal 'un'"},{t:"ca",m:"Cah",h:"like 'car' without the R"},{t:"deau",m:"Doe",h:"like 'doe', 'eau' = 'oh'"}]},

  // ============ DIRECTIONS (25) ============

  "where is": {t:"où est", s:[{t:"où",m:"Oo",h:"like 'oo'"},{t:"est",m:"Ay",h:"like 'ay'"}]},
  "left": {t:"à gauche", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"gauche",m:"Gohsh",h:"like 'gosh' with a long O"}]},
  "right": {t:"à droite", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"droite",m:"Dwat",h:"guttural R, 'oi' = 'wah' + T"}]},
  "straight ahead": {t:"tout droit", s:[{t:"tout",m:"Too",h:"like 'too'"},{t:"droit",m:"Dwah",h:"guttural R, 'oi' = 'wah', silent T"}]},
  "near": {t:"près", s:[{t:"près",m:"Pray",h:"like 'pray', guttural R, silent S"}]},
  "far": {t:"loin", s:[{t:"loin",m:"Lwan",h:"nasal 'lwan'"}]},
  "here": {t:"ici", s:[{t:"i",m:"Ee",h:"like 'ee'"},{t:"ci",m:"See",h:"like 'see'"}]},
  "there": {t:"là-bas", s:[{t:"là",m:"Lah",h:"like 'la'"},{t:"bas",m:"Bah",h:"like 'bah', silent S"}]},
  "the street": {t:"la rue", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"rue",m:"Rew",h:"guttural R + pursed lips 'ew'"}]},
  "the bridge": {t:"le pont", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"pont",m:"Pon",h:"nasal 'pon', silent T"}]},
  "the station": {t:"la gare", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"gare",m:"Gar",h:"like 'gar' in garlic, guttural R"}]},
  "the airport": {t:"l'aéroport", s:[{t:"l'a",m:"Lah",h:"like 'la'"},{t:"é",m:"Ay",h:"like 'ay'"},{t:"ro",m:"Row",h:"guttural R + 'oh'"},{t:"port",m:"Pour",h:"like 'pour', silent T"}]},
  "the bus stop": {t:"l'arrêt de bus", s:[{t:"l'a",m:"Lah",h:"like 'la'"},{t:"rrêt",m:"Ray",h:"guttural R + 'ay', silent T"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"bus",m:"Booze",h:"like 'booze'"}]},
  "the metro": {t:"le métro", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"mé",m:"May",h:"like 'may'"},{t:"tro",m:"Trow",h:"guttural R + 'oh'"}]},
  "a taxi": {t:"un taxi", s:[{t:"un",m:"Un",h:"nasal 'un'"},{t:"ta",m:"Tah",h:"like 'ta'"},{t:"xi",m:"Ksee",h:"like 'ksee'"}]},
  "the museum": {t:"le musée", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"mu",m:"Mew",h:"'m' + pursed lips 'ew'"},{t:"sée",m:"Zay",h:"like 'zay'"}]},
  "the church": {t:"l'église", s:[{t:"l'é",m:"Lay",h:"like 'lay'"},{t:"glise",m:"Gleez",h:"like 'gleeze'"}]},
  "the bathroom": {t:"les toilettes", s:[{t:"les",m:"Lay",h:"like 'lay'"},{t:"toi",m:"Twah",h:"'oi' = 'wah'"},{t:"lettes",m:"Let",h:"like 'let'"}]},
  "across from": {t:"en face de", s:[{t:"en",m:"On",h:"nasal 'on'"},{t:"face",m:"Fass",h:"like 'fuss' with A"},{t:"de",m:"Duh",h:"like 'duh'"}]},
  "next to": {t:"à côté de", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"cô",m:"Coh",h:"like 'co'"},{t:"té",m:"Tay",h:"like 'tay'"},{t:"de",m:"Duh",h:"like 'duh'"}]},
  "behind": {t:"derrière", s:[{t:"de",m:"Duh",h:"like 'duh'"},{t:"rri",m:"Ree",h:"guttural R + 'ee'"},{t:"ère",m:"Air",h:"like 'air'"}]},
  "in front of": {t:"devant", s:[{t:"de",m:"Duh",h:"like 'duh'"},{t:"vant",m:"Von",h:"nasal 'von', silent T"}]},
  "the corner": {t:"le coin", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"coin",m:"Kwan",h:"nasal 'kwan'"}]},
  "how far is it": {t:"c'est loin", s:[{t:"c'est",m:"Say",h:"like 'say'"},{t:"loin",m:"Lwan",h:"nasal 'lwan'"}]},
  "I'm looking for this address": {t:"je cherche cette adresse", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"cherche",m:"Shairsh",h:"'share' + SH"},{t:"cette",m:"Set",h:"like 'set'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"dresse",m:"Dress",h:"like 'dress'"}]},

  // ============ ACCOMMODATION (15) ============

  "I have a reservation": {t:"j'ai une réservation", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"une",m:"Oon",h:"like 'oon'"},{t:"ré",m:"Ray",h:"like 'ray'"},{t:"ser",m:"Zair",h:"like 'zair'"},{t:"va",m:"Vah",h:"like 'va'"},{t:"tion",m:"See-on",h:"'see' + nasal 'on'"}]},
  "a single room": {t:"une chambre simple", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"cham",m:"Shon",h:"nasal 'shon'"},{t:"bre",m:"Bruh",h:"'br' + 'uh'"},{t:"simple",m:"San-pl",h:"nasal 'san' + 'pl'"}]},
  "a double room": {t:"une chambre double", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"cham",m:"Shon",h:"nasal 'shon'"},{t:"bre",m:"Bruh",h:"'br' + 'uh'"},{t:"double",m:"Doobl",h:"like 'double' with 'oo'"}]},
  "how much per night": {t:"combien par nuit", s:[{t:"com",m:"Con",h:"nasal 'con'"},{t:"bien",m:"Bee-en",h:"nasal 'bee-en'"},{t:"par",m:"Par",h:"like 'par', guttural R"},{t:"nuit",m:"Nwee",h:"'n' + 'we'"}]},
  "breakfast included": {t:"petit-déjeuner inclus", s:[{t:"pe",m:"Puh",h:"like 'push' without the SH"},{t:"tit",m:"Tee",h:"like 'tee'"},{t:"dé",m:"Day",h:"like 'day'"},{t:"jeu",m:"Juh",h:"pursed lips 'juh'"},{t:"ner",m:"Nay",h:"like 'nay'"},{t:"in",m:"An",h:"nasal 'an'"},{t:"clus",m:"Clew",h:"pursed lips 'clew'"}]},
  "the key": {t:"la clé", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"clé",m:"Clay",h:"like 'clay'"}]},
  "air conditioning": {t:"la climatisation", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"cli",m:"Clee",h:"like 'clean' without the N"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ti",m:"Tee",h:"like 'tee'"},{t:"sa",m:"Zah",h:"like 'za'"},{t:"tion",m:"See-on",h:"'see' + nasal 'on'"}]},
  "what time is checkout": {t:"à quelle heure est le départ", s:[{t:"à",m:"Ah",h:"like 'ah'"},{t:"quelle",m:"Kell",h:"like 'kell'"},{t:"heure",m:"Ur",h:"pursed lips 'ur'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"dé",m:"Day",h:"like 'day'"},{t:"part",m:"Par",h:"like 'par', silent T"}]},
  "the elevator": {t:"l'ascenseur", s:[{t:"l'a",m:"Lah",h:"like 'la'"},{t:"scen",m:"Son",h:"nasal 'son'"},{t:"seur",m:"Sir",h:"pursed lips 'sir'"}]},
  "the floor": {t:"l'étage", s:[{t:"l'é",m:"Lay",h:"like 'lay'"},{t:"tage",m:"Tahj",h:"like 'tahj' in Taj Mahal"}]},
  "the wifi password": {t:"le mot de passe wifi", s:[{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"mot",m:"Mow",h:"like 'mow', silent T"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"passe",m:"Pass",h:"like 'pass'"},{t:"wi",m:"Wee",h:"like 'wee'"},{t:"fi",m:"Fee",h:"like 'fee'"}]},
  "hot water": {t:"l'eau chaude", s:[{t:"l'eau",m:"Low",h:"like 'low'"},{t:"chaude",m:"Shode",h:"like 'showed'"}]},
  "the shower": {t:"la douche", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"douche",m:"Doosh",h:"like 'doosh'"}]},
  "towel": {t:"une serviette", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"ser",m:"Sair",h:"like 'sair'"},{t:"vi",m:"Vee",h:"like 'vee'"},{t:"ette",m:"Et",h:"like 'et'"}]},
  "could you wake me at": {t:"pouvez-vous me réveiller à", s:[{t:"pou",m:"Poo",h:"like 'pooh'"},{t:"vez",m:"Vay",h:"like 'vay'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"me",m:"Muh",h:"like 'mug' without the G"},{t:"ré",m:"Ray",h:"like 'ray'"},{t:"vei",m:"Vay",h:"like 'vay'"},{t:"ller",m:"Yay",h:"like 'yay'"},{t:"à",m:"Ah",h:"like 'ah'"}]},

  // ============ COMMUNICATION (15) ============

  "do you have wifi": {t:"avez-vous le wifi", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"vez",m:"Vay",h:"like 'vay'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"wi",m:"Wee",h:"like 'wee'"},{t:"fi",m:"Fee",h:"like 'fee'"}]},
  "what is the password": {t:"quel est le mot de passe", s:[{t:"quel",m:"Kell",h:"like 'kell'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"le",m:"Luh",h:"like 'lug' without the G"},{t:"mot",m:"Mow",h:"like 'mow'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"passe",m:"Pass",h:"like 'pass'"}]},
  "I need to make a call": {t:"je dois téléphoner", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"dois",m:"Dwah",h:"'oi' = 'wah'"},{t:"té",m:"Tay",h:"like 'tay'"},{t:"lé",m:"Lay",h:"like 'lay'"},{t:"pho",m:"Foh",h:"like 'foe'"},{t:"ner",m:"Nay",h:"like 'nay'"}]},
  "can I charge my phone": {t:"puis-je charger mon téléphone", s:[{t:"puis",m:"Pwee",h:"'pw' + 'ee'"},{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"char",m:"Shar",h:"like 'shar' in shark, guttural R"},{t:"ger",m:"Jay",h:"like 'jay'"},{t:"mon",m:"Mon",h:"nasal 'mon'"},{t:"té",m:"Tay",h:"like 'tay'"},{t:"lé",m:"Lay",h:"like 'lay'"},{t:"phone",m:"Fun",h:"like 'fun'"}]},
  "email": {t:"courriel", s:[{t:"cou",m:"Coo",h:"like 'coo'"},{t:"rri",m:"Ree",h:"guttural R + 'ee'"},{t:"el",m:"Ell",h:"like 'ell'"}]},
  "I don't have signal": {t:"je n'ai pas de réseau", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"n'ai",m:"Nay",h:"like 'nay'"},{t:"pas",m:"Pah",h:"like 'pa'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"ré",m:"Ray",h:"like 'ray'"},{t:"seau",m:"Zoh",h:"like 'zone' without the N, 'eau' = 'oh'"}]},
  "a stamp": {t:"un timbre", s:[{t:"un",m:"Un",h:"nasal 'un'"},{t:"tim",m:"Tan",h:"nasal 'tan'"},{t:"bre",m:"Bruh",h:"'br' + 'uh'"}]},
  "a postcard": {t:"une carte postale", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"carte",m:"Cart",h:"like 'cart'"},{t:"pos",m:"Paws",h:"like 'paws'"},{t:"tale",m:"Tal",h:"like 'tall'"}]},
  "the post office": {t:"la poste", s:[{t:"la",m:"Lah",h:"like 'la'"},{t:"poste",m:"Post",h:"like 'post'"}]},
  "a phone card": {t:"une carte téléphonique", s:[{t:"une",m:"Oon",h:"like 'oon'"},{t:"carte",m:"Cart",h:"like 'cart'"},{t:"té",m:"Tay",h:"like 'tay'"},{t:"lé",m:"Lay",h:"like 'lay'"},{t:"pho",m:"Foh",h:"like 'foe'"},{t:"nique",m:"Neek",h:"like 'geek' with N"}]},
  "where is an ATM": {t:"où est un distributeur", s:[{t:"où",m:"Oo",h:"like 'oo'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"un",m:"Un",h:"nasal 'un'"},{t:"di",m:"Dee",h:"like 'dee'"},{t:"stri",m:"Stree",h:"like 'stree' in street"},{t:"bu",m:"Bew",h:"pursed lips 'bew'"},{t:"teur",m:"Tur",h:"pursed lips 'tur'"}]},
  "can you write it down": {t:"pouvez-vous l'écrire", s:[{t:"pou",m:"Poo",h:"like 'pooh'"},{t:"vez",m:"Vay",h:"like 'vay'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"l'é",m:"Lay",h:"like 'lay'"},{t:"crire",m:"Creer",h:"guttural R + 'eer'"}]},
  "slowly please": {t:"lentement s'il vous plaît", s:[{t:"len",m:"Lon",h:"nasal 'lon'"},{t:"te",m:"Tuh",h:"like 'tug' without the G"},{t:"ment",m:"Mon",h:"nasal 'mon'"},{t:"s'il",m:"Seal",h:"like 'seal'"},{t:"vous",m:"Voo",h:"like 'voo'"},{t:"plaît",m:"Play",h:"like 'play'"}]},
  "what does this mean": {t:"qu'est-ce que ça veut dire", s:[{t:"qu'est",m:"Kess",h:"like 'kess'"},{t:"ce",m:"Suh",h:"like 'sub' without the B"},{t:"que",m:"Kuh",h:"like 'could' without the LD"},{t:"ça",m:"Sah",h:"like 'saw'"},{t:"veut",m:"Vuh",h:"pursed lips 'vuh'"},{t:"dire",m:"Deer",h:"like 'deer', guttural R"}]},
  "how do you say": {t:"comment dit-on", s:[{t:"co",m:"Cuh",h:"like 'come' without the M"},{t:"mment",m:"Mon",h:"nasal 'mon'"},{t:"dit",m:"Dee",h:"like 'dee'"},{t:"on",m:"On",h:"nasal 'on'"}]},

  // ============ HEALTH (10) ============

  "I feel sick": {t:"je me sens mal", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"me",m:"Muh",h:"like 'mug' without the G"},{t:"sens",m:"Son",h:"nasal 'son'"},{t:"mal",m:"Mal",h:"like 'mal' in malice"}]},
  "I have a headache": {t:"j'ai mal à la tête", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"mal",m:"Mal",h:"like 'mal'"},{t:"à",m:"Ah",h:"like 'ah'"},{t:"la",m:"Lah",h:"like 'la'"},{t:"tête",m:"Tet",h:"like 'tet', silent final E"}]},
  "I have a fever": {t:"j'ai de la fièvre", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"la",m:"Lah",h:"like 'la'"},{t:"fi",m:"Fee",h:"like 'fee'"},{t:"èvre",m:"Evruh",h:"like 'ever' + 'uh'"}]},
  "I'm allergic to": {t:"je suis allergique à", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"suis",m:"Swee",h:"'s' + 'we'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ller",m:"Lair",h:"like 'lair'"},{t:"gique",m:"Jeek",h:"like 'geek' with J"},{t:"à",m:"Ah",h:"like 'ah'"}]},
  "I need medicine": {t:"j'ai besoin de médicaments", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"be",m:"Buh",h:"like 'but' without the T"},{t:"soin",m:"Swan",h:"nasal 'swan'"},{t:"de",m:"Duh",h:"like 'duh'"},{t:"mé",m:"May",h:"like 'may'"},{t:"di",m:"Dee",h:"like 'dee'"},{t:"ca",m:"Cah",h:"like 'car' without the R"},{t:"ments",m:"Mon",h:"nasal 'mon'"}]},
  "it hurts here": {t:"j'ai mal ici", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"mal",m:"Mal",h:"like 'mal'"},{t:"i",m:"Ee",h:"like 'ee'"},{t:"ci",m:"See",h:"like 'see'"}]},
  "I have a stomachache": {t:"j'ai mal au ventre", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"mal",m:"Mal",h:"like 'mal'"},{t:"au",m:"Oh",h:"like 'oh'"},{t:"ventre",m:"Von-truh",h:"nasal 'von' + 'truh'"}]},
  "where is the nearest pharmacy": {t:"où est la pharmacie la plus proche", s:[{t:"où",m:"Oo",h:"like 'oo'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"la",m:"Lah",h:"like 'la'"},{t:"phar",m:"Far",h:"like 'far'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"cie",m:"See",h:"like 'see'"},{t:"la",m:"Lah",h:"like 'la'"},{t:"plus",m:"Plew",h:"pursed lips 'plew'"},{t:"proche",m:"Prosh",h:"guttural R + 'osh'"}]},
  "I have insurance": {t:"j'ai une assurance", s:[{t:"j'ai",m:"Jay",h:"like 'jay'"},{t:"une",m:"Oon",h:"like 'oon'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"ssu",m:"Sew",h:"pursed lips 'sew'"},{t:"rance",m:"Rons",h:"nasal 'rons'"}]},
  "I can't breathe": {t:"je ne peux pas respirer", s:[{t:"je",m:"Juh",h:"like 'jug' without the G"},{t:"ne",m:"Nuh",h:"like 'nub' without the B"},{t:"peux",m:"Puh",h:"pursed lips 'puh'"},{t:"pas",m:"Pah",h:"like 'pa'"},{t:"res",m:"Ress",h:"like 'rest' without the T"},{t:"pi",m:"Pee",h:"like 'pee'"},{t:"rer",m:"Ray",h:"guttural R + 'ay'"}]},

  // ============ TIME (10) ============

  "what time is it": {t:"quelle heure est-il", s:[{t:"quelle",m:"Kell",h:"like 'kell'"},{t:"heure",m:"Ur",h:"pursed lips 'ur'"},{t:"est",m:"Ay",h:"like 'ay'"},{t:"il",m:"Eel",h:"like 'eel'"}]},
  "today": {t:"aujourd'hui", s:[{t:"au",m:"Oh",h:"like 'oh'"},{t:"jour",m:"Joor",h:"'joo' + guttural R"},{t:"d'hui",m:"Dwee",h:"'dw' + 'ee'"}]},
  "tomorrow": {t:"demain", s:[{t:"de",m:"Duh",h:"like 'duh'"},{t:"main",m:"Man",h:"nasal 'man'"}]},
  "yesterday": {t:"hier", s:[{t:"hier",m:"Ee-air",h:"'ee' + 'air'"}]},
  "morning": {t:"matin", s:[{t:"ma",m:"Mah",h:"like 'ma'"},{t:"tin",m:"Tan",h:"nasal 'tan'"}]},
  "afternoon": {t:"après-midi", s:[{t:"a",m:"Ah",h:"like 'ah'"},{t:"près",m:"Pray",h:"guttural R + 'ay'"},{t:"mi",m:"Mee",h:"like 'me'"},{t:"di",m:"Dee",h:"like 'dee'"}]},
  "evening": {t:"soir", s:[{t:"soir",m:"Swahr",h:"'swah' + guttural R"}]},
  "now": {t:"maintenant", s:[{t:"main",m:"Man",h:"nasal 'man'"},{t:"te",m:"Tuh",h:"like 'tug' without the G"},{t:"nant",m:"Non",h:"nasal 'non'"}]},
  "later": {t:"plus tard", s:[{t:"plus",m:"Plew",h:"pursed lips 'plew'"},{t:"tard",m:"Tar",h:"like 'tar', guttural R, silent D"}]},
  "early": {t:"tôt", s:[{t:"tôt",m:"Toe",h:"like 'toe', silent final T"}]},

  // ============ WEATHER (10) ============

  "what is the weather like": {t:"quel temps fait-il", s:[{t:"quel",m:"Kell",h:"like 'kell'"},{t:"temps",m:"Ton",h:"nasal 'ton', silent PS"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"il",m:"Eel",h:"like 'eel'"}]},
  "it's hot": {t:"il fait chaud", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"chaud",m:"Show",h:"like 'show', silent D"}]},
  "it's cold": {t:"il fait froid", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"froid",m:"Fwah",h:"guttural R, 'oi' = 'wah', silent D"}]},
  "it's raining": {t:"il pleut", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"pleut",m:"Pluh",h:"pursed lips 'pluh'"}]},
  "it's sunny": {t:"il fait beau", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"beau",m:"Bow",h:"like 'bow' of a ship, 'eau' = 'oh'"}]},
  "it's windy": {t:"il y a du vent", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"y",m:"Ee",h:"like 'ee'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"du",m:"Dew",h:"pursed lips 'dew'"},{t:"vent",m:"Von",h:"nasal 'von', silent T"}]},
  "it's snowing": {t:"il neige", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"neige",m:"Nej",h:"like 'edge' with N"}]},
  "umbrella": {t:"parapluie", s:[{t:"pa",m:"Pah",h:"like 'pa'"},{t:"ra",m:"Rah",h:"guttural R + 'ah'"},{t:"pluie",m:"Plwee",h:"'pl' + 'wee'"}]},
  "it's cloudy": {t:"il fait nuageux", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"nu",m:"New",h:"pursed lips 'new'"},{t:"a",m:"Ah",h:"like 'ah'"},{t:"geux",m:"Juh",h:"pursed lips 'juh'"}]},
  "it's nice out": {t:"il fait bon", s:[{t:"il",m:"Eel",h:"like 'eel'"},{t:"fait",m:"Fay",h:"like 'fay'"},{t:"bon",m:"Bon",h:"nasal 'bon'"}]}

};
