// dict-ru.js — Russian phrase dictionary (210+ entries)
// Auto-generated for HowDoISay app
var DICT_RU = {
  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"привет", p:"privet", s:[{t:"при",m:"Pree",h:"like 'free' with P"},{t:"вет",m:"Vet",h:"the word 'vet'"}]},
  "good morning": {t:"доброе утро", p:"dobroye utro", s:[{t:"до",m:"Doh",h:"the note 'doh'"},{t:"бро",m:"Bra",h:"like 'bra'"},{t:"е",m:"Yeh",h:"like 'yeah'"},{t:"у",m:"Oo",h:"like 'ooh'"},{t:"тро",m:"Tro",h:"like 'troll' without L"}]},
  "good afternoon": {t:"добрый день", p:"dobryy den'", s:[{t:"до",m:"Doh",h:"the note 'doh'"},{t:"брый",m:"Bree",h:"like 'breezy' without Z"},{t:"день",m:"Den",h:"the word 'den' said softly"}]},
  "good evening": {t:"добрый вечер", p:"dobryy vecher", s:[{t:"до",m:"Doh",h:"the note 'doh'"},{t:"брый",m:"Bree",h:"like 'breezy' without Z"},{t:"ве",m:"Veh",h:"like 'vest' without ST"},{t:"чер",m:"Chair",h:"the word 'chair'"}]},
  "good night": {t:"спокойной ночи", p:"spokoynoy nochi", s:[{t:"спо",m:"Spa",h:"like 'spa'"},{t:"кой",m:"Coy",h:"the word 'coy'"},{t:"ной",m:"Noy",h:"like 'annoy' without A"},{t:"но",m:"No",h:"the word 'no'"},{t:"чи",m:"Chee",h:"like 'cheese' without S"}]},
  "goodbye": {t:"до свидания", p:"do svidaniya", s:[{t:"до",m:"Dah",h:"like 'da' in Russian"},{t:"сви",m:"Svee",h:"'see' with V"},{t:"да",m:"Dah",h:"the word 'da'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"я",m:"Ya",h:"the word 'ya'"}]},
  "see you later": {t:"увидимся", p:"uvidimsya", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"дим",m:"Dim",h:"the word 'dim'"},{t:"ся",m:"Sya",h:"'see' + 'ya'"}]},
  "thank you": {t:"спасибо", p:"spasibo", s:[{t:"спа",m:"Spa",h:"like 'spa'"},{t:"си",m:"See",h:"the word 'see'"},{t:"бо",m:"Bah",h:"the word 'bah'"}]},
  "thank you very much": {t:"большое спасибо", p:"bol'shoye spasibo", s:[{t:"боль",m:"Ball",h:"the word 'ball'"},{t:"шо",m:"Show",h:"the word 'show'"},{t:"е",m:"Yeh",h:"like 'yeah'"},{t:"спа",m:"Spa",h:"like 'spa'"},{t:"си",m:"See",h:"the word 'see'"},{t:"бо",m:"Bah",h:"the word 'bah'"}]},
  "you're welcome": {t:"пожалуйста", p:"pozhaluysta", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"жа",m:"Zha",h:"like 'jar' without R"},{t:"луй",m:"Loo",h:"like 'loom' without M"},{t:"ста",m:"Sta",h:"like 'star' without R"}]},
  "excuse me": {t:"извините", p:"izvinite", s:[{t:"из",m:"Eez",h:"like 'ease' with Z"},{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"}]},
  "i'm sorry": {t:"мне жаль", p:"mne zhal'", s:[{t:"мне",m:"Mn-yeh",h:"'M' + 'yeah'"},{t:"жаль",m:"Zhal",h:"like 'shall' with ZH"}]},
  "please": {t:"пожалуйста", p:"pozhaluysta", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"жа",m:"Zha",h:"like 'jar' without R"},{t:"луй",m:"Loo",h:"like 'loom' without M"},{t:"ста",m:"Sta",h:"like 'star' without R"}]},
  "nice to meet you": {t:"приятно познакомиться", p:"priyatno poznakomit'sya", s:[{t:"при",m:"Pree",h:"like 'free' with P"},{t:"ят",m:"Yat",h:"like 'yacht'"},{t:"но",m:"Na",h:"like 'nah'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"зна",m:"Zna",h:"'Z' + 'nah'"},{t:"ко",m:"Koh",h:"like 'co-' in 'coat'"},{t:"мить",m:"Meet",h:"the word 'meet'"},{t:"ся",m:"Sya",h:"'see' + 'ya'"}]},
  "how are you": {t:"как дела", p:"kak dela", s:[{t:"как",m:"Kak",h:"like 'cuckoo' first syllable"},{t:"де",m:"Dye",h:"the word 'dye'"},{t:"ла",m:"La",h:"the note 'la'"}]},
  "i'm fine": {t:"я в порядке", p:"ya v poryadke", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"в",m:"V",h:"the letter 'V'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"ряд",m:"Ryad",h:"'R' + 'yard'"},{t:"ке",m:"Kye",h:"like 'kayak' first syllable"}]},
  "what is your name": {t:"как вас зовут", p:"kak vas zovut", s:[{t:"как",m:"Kak",h:"like 'cuckoo' first syllable"},{t:"вас",m:"Vas",h:"the word 'vase' without E"},{t:"зо",m:"Za",h:"like 'za' in pizza"},{t:"вут",m:"Voot",h:"like 'boot' with V"}]},
  "my name is": {t:"меня зовут", p:"menya zovut", s:[{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"зо",m:"Za",h:"like 'za' in pizza"},{t:"вут",m:"Voot",h:"like 'boot' with V"}]},
  "pleased to meet you": {t:"рад познакомиться", p:"rad poznakomit'sya", s:[{t:"рад",m:"Rod",h:"like 'rod' with rolled R"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"зна",m:"Zna",h:"'Z' + 'nah'"},{t:"ко",m:"Koh",h:"like 'co-' in 'coat'"},{t:"мить",m:"Meet",h:"the word 'meet'"},{t:"ся",m:"Sya",h:"'see' + 'ya'"}]},
  "congratulations": {t:"поздравляю", p:"pozdravlyayu", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"здра",m:"Zdra",h:"'Z' + 'draw'"},{t:"вля",m:"Vlya",h:"'V' + 'la'"},{t:"ю",m:"You",h:"the word 'you'"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"да", p:"da", s:[{t:"да",m:"Da",h:"like 'da' father"}]},
  "no": {t:"нет", p:"nyet", s:[{t:"нет",m:"Nyet",h:"like 'net' with Y"}]},
  "ok": {t:"хорошо", p:"khorosho", s:[{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"ро",m:"Ra",h:"like 'rah' with rolled R"},{t:"шо",m:"Show",h:"the word 'show'"}]},
  "i understand": {t:"я понимаю", p:"ya ponimayu", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ма",m:"Ma",h:"the word 'ma'"},{t:"ю",m:"You",h:"the word 'you'"}]},
  "i don't understand": {t:"я не понимаю", p:"ya ne ponimayu", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ма",m:"Ma",h:"the word 'ma'"},{t:"ю",m:"You",h:"the word 'you'"}]},
  "do you speak english": {t:"вы говорите по-английски", p:"vy govorite po-angliyski", s:[{t:"вы",m:"Vee",h:"like the letter 'V'"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"ри",m:"Ree",h:"like 'reef' without F"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"ан",m:"An",h:"the word 'an'"},{t:"глий",m:"Glee",h:"the word 'glee'"},{t:"ски",m:"Ski",h:"the word 'ski'"}]},
  "slowly please": {t:"помедленнее пожалуйста", p:"pomedlenneye pozhaluysta", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"мед",m:"Med",h:"the word 'med'"},{t:"лен",m:"Len",h:"the name 'Len'"},{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "can you help me": {t:"вы можете мне помочь", p:"vy mozhete mne pomoch'", s:[{t:"вы",m:"Vee",h:"like the letter 'V'"},{t:"мо",m:"Mah",h:"like 'ma'"},{t:"же",m:"Zheh",h:"like 'measure' middle sound"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"мне",m:"Mn-yeh",h:"'M' + 'yeah'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"мочь",m:"Moch",h:"like 'mocha' without A"}]},
  "where is": {t:"где", p:"gde", s:[{t:"где",m:"G-dyeh",h:"'G' + 'day'"}]},
  "how much": {t:"сколько", p:"skol'ko", s:[{t:"сколь",m:"Skull",h:"the word 'skull'"},{t:"ко",m:"Ka",h:"like 'ka' in karate"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"помогите", p:"pomogite", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"мо",m:"Ma",h:"like 'ma'"},{t:"ги",m:"Gee",h:"the word 'gee'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"}]},
  "emergency": {t:"экстренный случай", p:"ekstrennyy sluchay", s:[{t:"эк",m:"Ek",h:"like 'echo' first syllable"},{t:"стрен",m:"Stren",h:"like 'strength' without GTH"},{t:"ный",m:"Nee",h:"like 'knee'"},{t:"слу",m:"Sloo",h:"like 'slew'"},{t:"чай",m:"Chai",h:"the word 'chai' tea"}]},
  "call the police": {t:"вызовите полицию", p:"vyzovite politsiyu", s:[{t:"вы",m:"Vee",h:"like the letter 'V'"},{t:"зо",m:"Za",h:"like 'za' in pizza"},{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"ли",m:"Lee",h:"the name 'Lee'"},{t:"ци",m:"Tsee",h:"'T' + 'see'"},{t:"ю",m:"You",h:"the word 'you'"}]},
  "call the doctor": {t:"вызовите врача", p:"vyzovite vracha", s:[{t:"вы",m:"Vee",h:"like the letter 'V'"},{t:"зо",m:"Za",h:"like 'za' in pizza"},{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"вра",m:"Vra",h:"'V' + 'rah'"},{t:"ча",m:"Cha",h:"like 'cha-cha'"}]},
  "hospital": {t:"больница", p:"bol'nitsa", s:[{t:"боль",m:"Ball",h:"the word 'ball'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ца",m:"Tsa",h:"'T' + 'sah'"}]},
  "fire": {t:"пожар", p:"pozhar", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"жар",m:"Zhar",h:"like 'jar' with ZH"}]},
  "danger": {t:"опасность", p:"opasnost'", s:[{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"пас",m:"Pas",h:"the word 'pass'"},{t:"ность",m:"Nast",h:"like 'nasty' without Y"}]},
  "watch out": {t:"осторожно", p:"ostorozhno", s:[{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"сто",m:"Sta",h:"like 'star' without R"},{t:"рож",m:"Rozh",h:"like 'rogue' with ZH"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "i'm lost": {t:"я заблудился", p:"ya zabludilsya", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"за",m:"Za",h:"like 'za' in pizza"},{t:"блу",m:"Bloo",h:"like 'blue'"},{t:"дил",m:"Deal",h:"the word 'deal'"},{t:"ся",m:"Sya",h:"'see' + 'ya'"}]},
  "i'm sick": {t:"мне плохо", p:"mne plokho", s:[{t:"мне",m:"Mn-yeh",h:"'M' + 'yeah'"},{t:"пло",m:"Plah",h:"like 'plot' without T"},{t:"хо",m:"Kha",h:"like 'ha' with K"}]},
  "call an ambulance": {t:"вызовите скорую", p:"vyzovite skoruyu", s:[{t:"вы",m:"Vee",h:"like the letter 'V'"},{t:"зо",m:"Za",h:"like 'za' in pizza"},{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"ско",m:"Ska",h:"like 'scar' without R"},{t:"ру",m:"Roo",h:"like 'roo' in kangaroo"},{t:"ю",m:"You",h:"the word 'you'"}]},
  "i need a doctor": {t:"мне нужен врач", p:"mne nuzhen vrach", s:[{t:"мне",m:"Mn-yeh",h:"'M' + 'yeah'"},{t:"ну",m:"Noo",h:"like 'noon' without last N"},{t:"жен",m:"Zhen",h:"like 'Zen' with ZH"},{t:"врач",m:"Vrach",h:"'V' + 'rotch'"}]},
  "passport": {t:"паспорт", p:"pasport", s:[{t:"пас",m:"Pas",h:"the word 'pass'"},{t:"порт",m:"Port",h:"the word 'port'"}]},
  "visa": {t:"виза", p:"viza", s:[{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"за",m:"Za",h:"like 'za' in pizza"}]},
  "police station": {t:"полицейский участок", p:"politseyskiy uchastok", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"ли",m:"Lee",h:"the name 'Lee'"},{t:"цей",m:"Tsay",h:"'T' + 'say'"},{t:"ский",m:"Ski",h:"the word 'ski'"},{t:"у",m:"Oo",h:"like 'ooh'"},{t:"час",m:"Chas",h:"like 'chasm' without M"},{t:"ток",m:"Tok",h:"like 'talk'"}]},

  // ===== NUMBERS (15) =====
  "zero": {t:"ноль", p:"nol'", s:[{t:"ноль",m:"Nol",h:"like 'knoll'"}]},
  "one": {t:"один", p:"odin", s:[{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"дин",m:"Dean",h:"the name 'Dean'"}]},
  "two": {t:"два", p:"dva", s:[{t:"два",m:"Dva",h:"like 'divan' first part"}]},
  "three": {t:"три", p:"tri", s:[{t:"три",m:"Tree",h:"the word 'tree'"}]},
  "four": {t:"четыре", p:"chetyre", s:[{t:"че",m:"Cheh",h:"like 'check' without CK"},{t:"ты",m:"Ti",h:"like 'tick' without CK"},{t:"ре",m:"Rye",h:"the word 'rye'"}]},
  "five": {t:"пять", p:"pyat'", s:[{t:"пять",m:"Pyat",h:"'P' + 'yacht'"}]},
  "six": {t:"шесть", p:"shest'", s:[{t:"шесть",m:"Shest",h:"like 'chest' with SH"}]},
  "seven": {t:"семь", p:"sem'", s:[{t:"семь",m:"Sem",h:"like 'stem' without T"}]},
  "eight": {t:"восемь", p:"vosem'", s:[{t:"во",m:"Voh",h:"like 'vote' without TE"},{t:"семь",m:"Sem",h:"like 'stem' without T"}]},
  "nine": {t:"девять", p:"devyat'", s:[{t:"де",m:"Dye",h:"the word 'dye'"},{t:"вять",m:"Vyat",h:"'V' + 'yacht'"}]},
  "ten": {t:"десять", p:"desyat'", s:[{t:"де",m:"Dye",h:"the word 'dye'"},{t:"сять",m:"Syat",h:"'S' + 'yacht'"}]},
  "twenty": {t:"двадцать", p:"dvadtsat'", s:[{t:"двад",m:"Dvad",h:"'D' + 'vat'"},{t:"цать",m:"Tsat",h:"'T' + 'sat'"}]},
  "fifty": {t:"пятьдесят", p:"pyat'desyat", s:[{t:"пять",m:"Pyat",h:"'P' + 'yacht'"},{t:"де",m:"Dee",h:"the word 'dee'"},{t:"сят",m:"Syat",h:"'S' + 'yacht'"}]},
  "one hundred": {t:"сто", p:"sto", s:[{t:"сто",m:"Sto",h:"like 'stow'"}]},
  "one thousand": {t:"тысяча", p:"tysyacha", s:[{t:"ты",m:"Ti",h:"like 'tick' without CK"},{t:"ся",m:"Sya",h:"'see' + 'ya'"},{t:"ча",m:"Cha",h:"like 'cha-cha'"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"вода", p:"voda", s:[{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "coffee": {t:"кофе", p:"kofe", s:[{t:"ко",m:"Koh",h:"like 'co-' in 'coat'"},{t:"фе",m:"Feh",h:"like 'fed' without D"}]},
  "tea": {t:"чай", p:"chay", s:[{t:"чай",m:"Chai",h:"the word 'chai' tea"}]},
  "beer": {t:"пиво", p:"pivo", s:[{t:"пи",m:"Pee",h:"the letter 'P'"},{t:"во",m:"Va",h:"like 'vault' without LT"}]},
  "wine": {t:"вино", p:"vino", s:[{t:"ви",m:"Vee",h:"like the letter 'V'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "juice": {t:"сок", p:"sok", s:[{t:"сок",m:"Sock",h:"the word 'sock'"}]},
  "milk": {t:"молоко", p:"moloko", s:[{t:"мо",m:"Ma",h:"like 'ma'"},{t:"ло",m:"La",h:"the note 'la'"},{t:"ко",m:"Ko",h:"like 'co-' in 'coat'"}]},
  "bread": {t:"хлеб", p:"khleb", s:[{t:"хлеб",m:"Khleb",h:"'K' + 'leb' like 'celeb'"}]},
  "meat": {t:"мясо", p:"myaso", s:[{t:"мя",m:"Mya",h:"'M' + 'ya'"},{t:"со",m:"Sa",h:"like 'saw'"}]},
  "chicken": {t:"курица", p:"kuritsa", s:[{t:"ку",m:"Koo",h:"like 'coo' of a dove"},{t:"ри",m:"Ree",h:"like 'reef' without F"},{t:"ца",m:"Tsa",h:"'T' + 'sah'"}]},
  "fish": {t:"рыба", p:"ryba", s:[{t:"ры",m:"Ri",h:"like 'rib' without B"},{t:"ба",m:"Ba",h:"like 'baa' of a sheep"}]},
  "rice": {t:"рис", p:"ris", s:[{t:"рис",m:"Rees",h:"the name 'Reese'"}]},
  "vegetables": {t:"овощи", p:"ovoshchi", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"щи",m:"Shee",h:"the word 'she'"}]},
  "fruit": {t:"фрукты", p:"frukty", s:[{t:"фрук",m:"Frook",h:"like 'fruit' without T"},{t:"ты",m:"Ti",h:"like 'tick' without CK"}]},
  "soup": {t:"суп", p:"sup", s:[{t:"суп",m:"Soup",h:"the word 'soup'"}]},
  "salad": {t:"салат", p:"salat", s:[{t:"са",m:"Sa",h:"like 'saw'"},{t:"лат",m:"Lot",h:"the word 'lot'"}]},
  "egg": {t:"яйцо", p:"yaytso", s:[{t:"яй",m:"Yai",h:"like 'yikes' first part"},{t:"цо",m:"Tso",h:"'T' + 'so'"}]},
  "cheese": {t:"сыр", p:"syr", s:[{t:"сыр",m:"Sir",h:"the word 'sir'"}]},
  "butter": {t:"масло", p:"maslo", s:[{t:"мас",m:"Mas",h:"like 'mass'"},{t:"ло",m:"La",h:"the note 'la'"}]},
  "sugar": {t:"сахар", p:"sakhar", s:[{t:"са",m:"Sa",h:"like 'saw'"},{t:"хар",m:"Khar",h:"like 'car' with KH"}]},
  "salt": {t:"соль", p:"sol'", s:[{t:"соль",m:"Sol",h:"the name 'Sol'"}]},
  "pepper": {t:"перец", p:"perets", s:[{t:"пе",m:"Peh",h:"like 'pet' without T"},{t:"рец",m:"Rets",h:"like 'rets' in 'frets'"}]},
  "ice cream": {t:"мороженое", p:"morozhenoye", s:[{t:"мо",m:"Ma",h:"like 'ma'"},{t:"ро",m:"Roh",h:"like 'row' with rolled R"},{t:"же",m:"Zheh",h:"like 'measure' middle sound"},{t:"но",m:"Na",h:"like 'nah'"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "cake": {t:"торт", p:"tort", s:[{t:"торт",m:"Tort",h:"the word 'tort'"}]},
  "chocolate": {t:"шоколад", p:"shokolad", s:[{t:"шо",m:"Shaw",h:"the name 'Shaw'"},{t:"ко",m:"Ka",h:"like 'ka' in karate"},{t:"лад",m:"Lad",h:"the word 'lad'"}]},
  "i'm hungry": {t:"я голоден", p:"ya goloden", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"ло",m:"La",h:"the note 'la'"},{t:"ден",m:"Den",h:"the word 'den'"}]},
  "i'm thirsty": {t:"я хочу пить", p:"ya khochu pit'", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"чу",m:"Choo",h:"like 'chew'"},{t:"пить",m:"Peet",h:"like 'peat'"}]},
  "delicious": {t:"вкусно", p:"vkusno", s:[{t:"вкус",m:"Vkoos",h:"'V' + 'goose' without G"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "i'm vegetarian": {t:"я вегетарианец", p:"ya vegetarianets", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"ве",m:"Veh",h:"like 'vest' without ST"},{t:"ге",m:"Geh",h:"like 'get' without T"},{t:"та",m:"Ta",h:"like 'ta' in British English"},{t:"ри",m:"Ree",h:"like 'reef' without F"},{t:"а",m:"Ah",h:"the sound 'ah'"},{t:"нец",m:"Nets",h:"the word 'nets'"}]},
  "i don't eat meat": {t:"я не ем мясо", p:"ya ne yem myaso", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"ем",m:"Yem",h:"like 'gem' with Y"},{t:"мя",m:"Mya",h:"'M' + 'ya'"},{t:"со",m:"Sa",h:"like 'saw'"}]},

  // ===== RESTAURANT (15) =====
  "menu": {t:"меню", p:"menyu", s:[{t:"ме",m:"Mee",h:"like 'me'"},{t:"ню",m:"Nyoo",h:"the word 'new'"}]},
  "table for two": {t:"столик на двоих", p:"stolik na dvoikh", s:[{t:"сто",m:"Sta",h:"like 'star' without R"},{t:"лик",m:"Leek",h:"the word 'leek'"},{t:"на",m:"Na",h:"like 'nah'"},{t:"двo",m:"Dva",h:"like 'divan' first part"},{t:"их",m:"Eekh",h:"like 'each' with KH"}]},
  "the check please": {t:"счёт пожалуйста", p:"schyot pozhaluysta", s:[{t:"счёт",m:"Shyot",h:"'SH' + 'yacht'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"жа",m:"Zha",h:"like 'jar' without R"},{t:"луй",m:"Loo",h:"like 'loom' without M"},{t:"ста",m:"Sta",h:"like 'star' without R"}]},
  "i would like": {t:"я бы хотел", p:"ya by khotel", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"бы",m:"Bi",h:"like 'big' without G"},{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"тел",m:"Tel",h:"the word 'tell'"}]},
  "breakfast": {t:"завтрак", p:"zavtrak", s:[{t:"зав",m:"Zahv",h:"like 'salve' with Z"},{t:"трак",m:"Track",h:"the word 'track'"}]},
  "lunch": {t:"обед", p:"obed", s:[{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"бед",m:"Byed",h:"like 'bed' with Y"}]},
  "dinner": {t:"ужин", p:"uzhin", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"жин",m:"Zheen",h:"like 'jean' with ZH"}]},
  "waiter": {t:"официант", p:"ofitsiant", s:[{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"фи",m:"Fee",h:"the word 'fee'"},{t:"ци",m:"Tsee",h:"'T' + 'see'"},{t:"ант",m:"Ant",h:"the word 'ant'"}]},
  "reservation": {t:"бронирование", p:"bronirovaniye", s:[{t:"бро",m:"Bra",h:"like 'bra'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ро",m:"Roh",h:"like 'row' with rolled R"},{t:"ва",m:"Va",h:"like 'vault' without LT"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "with ice": {t:"со льдом", p:"so l'dom", s:[{t:"со",m:"Sa",h:"like 'saw'"},{t:"льдом",m:"Ldom",h:"'L' + 'dome'"}]},
  "without ice": {t:"без льда", p:"bez l'da", s:[{t:"без",m:"Bez",h:"like 'best' without T"},{t:"льда",m:"Lda",h:"'L' + 'dah'"}]},
  "spicy": {t:"острое", p:"ostroye", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"стро",m:"Stra",h:"like 'straw'"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "not spicy": {t:"не острое", p:"ne ostroye", s:[{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"о",m:"Oh",h:"the word 'oh'"},{t:"стро",m:"Stra",h:"like 'straw'"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "more water please": {t:"ещё воды пожалуйста", p:"yeshchyo vody pozhaluysta", s:[{t:"е",m:"Yeh",h:"like 'yeah'"},{t:"щё",m:"Shyo",h:"'SH' + 'yo'"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"ды",m:"Di",h:"like 'did' without last D"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"жа",m:"Zha",h:"like 'jar' without R"},{t:"луй",m:"Loo",h:"like 'loom' without M"},{t:"ста",m:"Sta",h:"like 'star' without R"}]},
  "it was delicious": {t:"было очень вкусно", p:"bylo ochen' vkusno", s:[{t:"бы",m:"Bi",h:"like 'big' without G"},{t:"ло",m:"La",h:"the note 'la'"},{t:"о",m:"Oh",h:"the word 'oh'"},{t:"чень",m:"Chen",h:"like 'Chen' the name"},{t:"вкус",m:"Vkoos",h:"'V' + 'goose' without G"},{t:"но",m:"Na",h:"like 'nah'"}]},

  // ===== SHOPPING (20) =====
  "how much does this cost": {t:"сколько это стоит", p:"skol'ko eto stoit", s:[{t:"сколь",m:"Skull",h:"the word 'skull'"},{t:"ко",m:"Ka",h:"like 'ka' in karate"},{t:"э",m:"Eh",h:"the sound 'eh'"},{t:"то",m:"Ta",h:"like 'ta' in British English"},{t:"сто",m:"Stoh",h:"like 'stow'"},{t:"ит",m:"Eet",h:"like 'eat'"}]},
  "too expensive": {t:"слишком дорого", p:"slishkom dorogo", s:[{t:"слиш",m:"Sleesh",h:"like 'leash' with S"},{t:"ком",m:"Come",h:"the word 'come'"},{t:"до",m:"Doh",h:"the note 'doh'"},{t:"ро",m:"Ra",h:"like 'rah' with rolled R"},{t:"го",m:"Ga",h:"like 'got' without T"}]},
  "cheap": {t:"дёшево", p:"dyoshevo", s:[{t:"дё",m:"Dyo",h:"like 'dew' with yo"},{t:"ше",m:"Sheh",h:"like 'shed' without D"},{t:"во",m:"Va",h:"like 'vault' without LT"}]},
  "discount": {t:"скидка", p:"skidka", s:[{t:"скид",m:"Skid",h:"the word 'skid'"},{t:"ка",m:"Ka",h:"like 'ka' in karate"}]},
  "i want to buy": {t:"я хочу купить", p:"ya khochu kupit'", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"чу",m:"Choo",h:"like 'chew'"},{t:"ку",m:"Koo",h:"like 'coo' of a dove"},{t:"пить",m:"Peet",h:"like 'peat'"}]},
  "i'm just looking": {t:"я просто смотрю", p:"ya prosto smotryu", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"про",m:"Pra",h:"like 'pram' without M"},{t:"сто",m:"Sta",h:"like 'star' without R"},{t:"смо",m:"Sma",h:"'S' + 'ma'"},{t:"трю",m:"True",h:"the word 'true'"}]},
  "do you have": {t:"у вас есть", p:"u vas yest'", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"вас",m:"Vas",h:"the word 'vase' without E"},{t:"есть",m:"Yest",h:"like 'yest' in 'yester'"}]},
  "bigger": {t:"побольше", p:"pobol'she", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"боль",m:"Ball",h:"the word 'ball'"},{t:"ше",m:"Sheh",h:"like 'shed' without D"}]},
  "smaller": {t:"поменьше", p:"pomen'she", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"мень",m:"Men",h:"the word 'men'"},{t:"ше",m:"Sheh",h:"like 'shed' without D"}]},
  "can i try this on": {t:"можно примерить", p:"mozhno primerit'", s:[{t:"мож",m:"Mozh",h:"like 'mosh' with ZH"},{t:"но",m:"Na",h:"like 'nah'"},{t:"при",m:"Pree",h:"like 'free' with P"},{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"рить",m:"Reet",h:"like 'reef' without F"}]},
  "cash": {t:"наличные", p:"nalichnye", s:[{t:"на",m:"Na",h:"like 'nah'"},{t:"лич",m:"Leech",h:"the word 'leech'"},{t:"ны",m:"Ni",h:"like 'nick' without CK"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "credit card": {t:"кредитная карта", p:"kreditnaya karta", s:[{t:"кре",m:"Kreh",h:"like 'credit' first part"},{t:"дит",m:"Deet",h:"like 'deed' + T"},{t:"на",m:"Na",h:"like 'nah'"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"кар",m:"Car",h:"the word 'car'"},{t:"та",m:"Ta",h:"like 'ta' in British English"}]},
  "receipt": {t:"чек", p:"chek", s:[{t:"чек",m:"Check",h:"the word 'check'"}]},
  "bag": {t:"пакет", p:"paket", s:[{t:"па",m:"Pa",h:"like 'pa'"},{t:"кет",m:"Ket",h:"like 'ket' in 'racket'"}]},
  "size": {t:"размер", p:"razmer", s:[{t:"раз",m:"Raz",h:"like 'razzle' first part"},{t:"мер",m:"Mehr",h:"like 'mare'"}]},
  "open": {t:"открыто", p:"otkryto", s:[{t:"от",m:"At",h:"the word 'at'"},{t:"кры",m:"Kri",h:"like 'cry'"},{t:"то",m:"Ta",h:"like 'ta' in British English"}]},
  "closed": {t:"закрыто", p:"zakryto", s:[{t:"за",m:"Za",h:"like 'za' in pizza"},{t:"кры",m:"Kri",h:"like 'cry'"},{t:"то",m:"Ta",h:"like 'ta' in British English"}]},
  "market": {t:"рынок", p:"rynok", s:[{t:"ры",m:"Ri",h:"like 'rib' without B"},{t:"нок",m:"Nok",h:"like 'knock'"}]},
  "pharmacy": {t:"аптека", p:"apteka", s:[{t:"ап",m:"Ap",h:"like 'app'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"ка",m:"Ka",h:"like 'ka' in karate"}]},
  "souvenir": {t:"сувенир", p:"suvenir", s:[{t:"су",m:"Soo",h:"the word 'sue'"},{t:"ве",m:"Veh",h:"like 'vest' without ST"},{t:"нир",m:"Near",h:"the word 'near'"}]},

  // ===== DIRECTIONS (25) =====
  "where is the bathroom": {t:"где туалет", p:"gde tualet", s:[{t:"где",m:"G-dyeh",h:"'G' + 'day'"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"а",m:"Ah",h:"the sound 'ah'"},{t:"лет",m:"Let",h:"the word 'let'"}]},
  "left": {t:"налево", p:"nalevo", s:[{t:"на",m:"Na",h:"like 'nah'"},{t:"ле",m:"Lyeh",h:"like 'let' without T"},{t:"во",m:"Va",h:"like 'vault' without LT"}]},
  "right": {t:"направо", p:"napravo", s:[{t:"на",m:"Na",h:"like 'nah'"},{t:"пра",m:"Pra",h:"like 'pram' without M"},{t:"во",m:"Va",h:"like 'vault' without LT"}]},
  "straight ahead": {t:"прямо", p:"pryamo", s:[{t:"пря",m:"Prya",h:"'P' + 'R' + 'ya'"},{t:"мо",m:"Ma",h:"like 'ma'"}]},
  "stop": {t:"стоп", p:"stop", s:[{t:"стоп",m:"Stop",h:"the word 'stop'"}]},
  "near": {t:"рядом", p:"ryadom", s:[{t:"ря",m:"Rya",h:"'R' + 'ya'"},{t:"дом",m:"Dome",h:"the word 'dome'"}]},
  "far": {t:"далеко", p:"daleko", s:[{t:"да",m:"Da",h:"the word 'da'"},{t:"ле",m:"Lee",h:"the name 'Lee'"},{t:"ко",m:"Ko",h:"like 'co-' in 'coat'"}]},
  "here": {t:"здесь", p:"zdes'", s:[{t:"здесь",m:"Zdyes",h:"'Z' + 'yes'"}]},
  "there": {t:"там", p:"tam", s:[{t:"там",m:"Tom",h:"the name 'Tom'"}]},
  "map": {t:"карта", p:"karta", s:[{t:"кар",m:"Car",h:"the word 'car'"},{t:"та",m:"Ta",h:"like 'ta' in British English"}]},
  "taxi": {t:"такси", p:"taksi", s:[{t:"так",m:"Tack",h:"the word 'tack'"},{t:"си",m:"See",h:"the word 'see'"}]},
  "bus": {t:"автобус", p:"avtobus", s:[{t:"ав",m:"Ahv",h:"like 'have' without H"},{t:"то",m:"Ta",h:"like 'ta' in British English"},{t:"бус",m:"Bus",h:"the word 'bus'"}]},
  "train": {t:"поезд", p:"poyezd", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"езд",m:"Yezd",h:"'yes' + 'D'"}]},
  "airport": {t:"аэропорт", p:"aeroport", s:[{t:"а",m:"Ah",h:"the sound 'ah'"},{t:"э",m:"Eh",h:"the sound 'eh'"},{t:"ро",m:"Ra",h:"like 'rah' with rolled R"},{t:"порт",m:"Port",h:"the word 'port'"}]},
  "train station": {t:"вокзал", p:"vokzal", s:[{t:"вок",m:"Vok",h:"like 'vogue' without UE"},{t:"зал",m:"Zal",h:"like 'pal' with Z"}]},
  "metro": {t:"метро", p:"metro", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"тро",m:"Tro",h:"like 'troll' without L"}]},
  "entrance": {t:"вход", p:"vkhod", s:[{t:"вход",m:"Vkhod",h:"'V' + 'hod'"}]},
  "exit": {t:"выход", p:"vykhod", s:[{t:"вы",m:"Vi",h:"like the letter 'V'"},{t:"ход",m:"Khod",h:"'hod' with K"}]},
  "street": {t:"улица", p:"ulitsa", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ли",m:"Lee",h:"the name 'Lee'"},{t:"ца",m:"Tsa",h:"'T' + 'sah'"}]},
  "bridge": {t:"мост", p:"most", s:[{t:"мост",m:"Most",h:"the word 'most'"}]},
  "center": {t:"центр", p:"tsentr", s:[{t:"центр",m:"Tsentr",h:"'T' + 'centre'"}]},
  "how do i get to": {t:"как добраться до", p:"kak dobrat'sya do", s:[{t:"как",m:"Kak",h:"like 'cuckoo' first syllable"},{t:"до",m:"Da",h:"like 'da'"},{t:"брать",m:"Brat",h:"the word 'brat'"},{t:"ся",m:"Sya",h:"'see' + 'ya'"},{t:"до",m:"Doh",h:"the note 'doh'"}]},
  "is it far from here": {t:"это далеко отсюда", p:"eto daleko otsyuda", s:[{t:"э",m:"Eh",h:"the sound 'eh'"},{t:"то",m:"Ta",h:"like 'ta' in British English"},{t:"да",m:"Da",h:"the word 'da'"},{t:"ле",m:"Lee",h:"the name 'Lee'"},{t:"ко",m:"Ko",h:"like 'co-' in 'coat'"},{t:"от",m:"At",h:"the word 'at'"},{t:"сю",m:"Sue",h:"the name 'Sue'"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "behind": {t:"позади", p:"pozadi", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"за",m:"Za",h:"like 'za' in pizza"},{t:"ди",m:"Dee",h:"the word 'dee'"}]},
  "in front of": {t:"впереди", p:"vperedi", s:[{t:"впе",m:"Vpeh",h:"'V' + 'peh'"},{t:"ре",m:"Rye",h:"the word 'rye'"},{t:"ди",m:"Dee",h:"the word 'dee'"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"гостиница", p:"gostinitsa", s:[{t:"гос",m:"Gas",h:"like 'gust' without T"},{t:"ти",m:"Tee",h:"the word 'tea'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ца",m:"Tsa",h:"'T' + 'sah'"}]},
  "room": {t:"комната", p:"komnata", s:[{t:"ком",m:"Come",h:"the word 'come'"},{t:"на",m:"Na",h:"like 'nah'"},{t:"та",m:"Ta",h:"like 'ta' in British English"}]},
  "i have a reservation": {t:"у меня бронирование", p:"u menya bronirovaniye", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"бро",m:"Bra",h:"like 'bra'"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"ро",m:"Roh",h:"like 'row' with rolled R"},{t:"ва",m:"Va",h:"like 'vault' without LT"},{t:"ни",m:"Knee",h:"the word 'knee'"},{t:"е",m:"Yeh",h:"like 'yeah'"}]},
  "check in": {t:"регистрация", p:"registratsiya", s:[{t:"ре",m:"Reh",h:"like 'red' without D"},{t:"гис",m:"Gees",h:"like 'geese'"},{t:"тра",m:"Tra",h:"like 'tram' without M"},{t:"ци",m:"Tsee",h:"'T' + 'see'"},{t:"я",m:"Ya",h:"the word 'ya'"}]},
  "check out": {t:"выезд", p:"vyyezd", s:[{t:"вы",m:"Vi",h:"like the letter 'V'"},{t:"езд",m:"Yezd",h:"'yes' + 'D'"}]},
  "key": {t:"ключ", p:"klyuch", s:[{t:"ключ",m:"Klyooch",h:"'K' + 'L' + 'ouch'"}]},
  "bed": {t:"кровать", p:"krovat'", s:[{t:"кро",m:"Kra",h:"like 'crawl' without L"},{t:"вать",m:"Vat",h:"the word 'vat'"}]},
  "shower": {t:"душ", p:"dush", s:[{t:"душ",m:"Doosh",h:"like 'douche'"}]},
  "towel": {t:"полотенце", p:"polotentse", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"ло",m:"La",h:"the note 'la'"},{t:"тен",m:"Ten",h:"the word 'ten'"},{t:"це",m:"Tse",h:"'T' + 'se'"}]},
  "wifi": {t:"вай-фай", p:"vay-fay", s:[{t:"вай",m:"Vai",h:"like 'vine' without NE"},{t:"фай",m:"Fai",h:"like 'fine' without NE"}]},
  "wifi password": {t:"пароль от вай-фай", p:"parol' ot vay-fay", s:[{t:"па",m:"Pa",h:"like 'pa'"},{t:"роль",m:"Roll",h:"the word 'roll'"},{t:"от",m:"At",h:"the word 'at'"},{t:"вай",m:"Vai",h:"like 'vine' without NE"},{t:"фай",m:"Fai",h:"like 'fine' without NE"}]},
  "air conditioning": {t:"кондиционер", p:"konditsioner", s:[{t:"кон",m:"Con",h:"the word 'con'"},{t:"ди",m:"Dee",h:"the word 'dee'"},{t:"ци",m:"Tsee",h:"'T' + 'see'"},{t:"о",m:"Ah",h:"the sound 'ah'"},{t:"нер",m:"Nair",h:"the word 'nair'"}]},
  "hot water": {t:"горячая вода", p:"goryachaya voda", s:[{t:"го",m:"Ga",h:"like 'got' without T"},{t:"ря",m:"Rya",h:"'R' + 'ya'"},{t:"ча",m:"Cha",h:"like 'cha-cha'"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "cold water": {t:"холодная вода", p:"kholodnaya voda", s:[{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"лод",m:"Lod",h:"like 'lodge' without GE"},{t:"на",m:"Na",h:"like 'nah'"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "quiet": {t:"тихо", p:"tikho", s:[{t:"ти",m:"Tee",h:"the word 'tea'"},{t:"хо",m:"Kha",h:"like 'ha' with K"}]},

  // ===== COMMUNICATION (15) =====
  "i speak a little russian": {t:"я немного говорю по-русски", p:"ya nemnogo govoryu po-russki", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"мно",m:"Mno",h:"'M' + 'no'"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"рю",m:"Ryoo",h:"'R' + 'you'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"рус",m:"Roos",h:"like 'roost' without T"},{t:"ски",m:"Ski",h:"the word 'ski'"}]},
  "what does this mean": {t:"что это значит", p:"chto eto znachit", s:[{t:"что",m:"Shto",h:"like 'show' + T"},{t:"э",m:"Eh",h:"the sound 'eh'"},{t:"то",m:"Ta",h:"like 'ta' in British English"},{t:"зна",m:"Zna",h:"'Z' + 'nah'"},{t:"чит",m:"Cheet",h:"like 'cheat'"}]},
  "how do you say": {t:"как сказать", p:"kak skazat'", s:[{t:"как",m:"Kak",h:"like 'cuckoo' first syllable"},{t:"ска",m:"Ska",h:"like 'scar' without R"},{t:"зать",m:"Zat",h:"like 'zap' without P"}]},
  "can you write it down": {t:"можете написать", p:"mozhete napisat'", s:[{t:"мо",m:"Ma",h:"like 'ma'"},{t:"же",m:"Zheh",h:"like 'measure' middle sound"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"на",m:"Na",h:"like 'nah'"},{t:"пи",m:"Pee",h:"the letter 'P'"},{t:"сать",m:"Sat",h:"the word 'sat'"}]},
  "repeat please": {t:"повторите пожалуйста", p:"povtorite pozhaluysta", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"вто",m:"Fta",h:"like 'after' middle"},{t:"ри",m:"Ree",h:"like 'reef' without F"},{t:"те",m:"Tyeh",h:"like 'check' without CK"}]},
  "phone number": {t:"номер телефона", p:"nomer telefona", s:[{t:"но",m:"No",h:"the word 'no'"},{t:"мер",m:"Mehr",h:"like 'mare'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"ле",m:"Lee",h:"the name 'Lee'"},{t:"фо",m:"Foh",h:"like 'foe'"},{t:"на",m:"Na",h:"like 'nah'"}]},
  "internet": {t:"интернет", p:"internet", s:[{t:"ин",m:"Een",h:"like 'keen' without K"},{t:"тер",m:"Ter",h:"like 'tear'"},{t:"нет",m:"Net",h:"the word 'net'"}]},
  "email": {t:"электронная почта", p:"elektronnaya pochta", s:[{t:"э",m:"Eh",h:"the sound 'eh'"},{t:"лек",m:"Lek",h:"like 'wreck' with L"},{t:"трон",m:"Tron",h:"like 'Tron' the movie"},{t:"на",m:"Na",h:"like 'nah'"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"поч",m:"Poch",h:"like 'posh' with CH"},{t:"та",m:"Ta",h:"like 'ta' in British English"}]},
  "can i make a call": {t:"можно позвонить", p:"mozhno pozvonit'", s:[{t:"мож",m:"Mozh",h:"like 'mosh' with ZH"},{t:"но",m:"Na",h:"like 'nah'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"зво",m:"Zva",h:"'Z' + 'va'"},{t:"нить",m:"Neet",h:"like 'neat'"}]},
  "i don't speak russian": {t:"я не говорю по-русски", p:"ya ne govoryu po-russki", s:[{t:"я",m:"Ya",h:"the word 'ya'"},{t:"не",m:"Nyeh",h:"like 'net' without T"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"во",m:"Va",h:"like 'vault' without LT"},{t:"рю",m:"Ryoo",h:"'R' + 'you'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"рус",m:"Roos",h:"like 'roost' without T"},{t:"ски",m:"Ski",h:"the word 'ski'"}]},
  "translate": {t:"перевести", p:"perevesti", s:[{t:"пе",m:"Peh",h:"like 'pet' without T"},{t:"ре",m:"Reh",h:"like 'red' without D"},{t:"вес",m:"Vyes",h:"like 'vest' without T"},{t:"ти",m:"Tee",h:"the word 'tea'"}]},
  "what": {t:"что", p:"chto", s:[{t:"что",m:"Shto",h:"like 'show' + T"}]},
  "when": {t:"когда", p:"kogda", s:[{t:"ког",m:"Kahg",h:"like 'cog'"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "why": {t:"почему", p:"pochemu", s:[{t:"по",m:"Pa",h:"like 'pa'"},{t:"че",m:"Cheh",h:"like 'check' without CK"},{t:"му",m:"Moo",h:"like a cow's 'moo'"}]},
  "who": {t:"кто", p:"kto", s:[{t:"кто",m:"Kto",h:"'K' + 'tow'"}]},

  // ===== HEALTH (10) =====
  "i need medicine": {t:"мне нужно лекарство", p:"mne nuzhno lekarstvo", s:[{t:"мне",m:"Mn-yeh",h:"'M' + 'yeah'"},{t:"нуж",m:"Noozh",h:"like 'rouge' with N"},{t:"но",m:"Na",h:"like 'nah'"},{t:"ле",m:"Lee",h:"the name 'Lee'"},{t:"кар",m:"Car",h:"the word 'car'"},{t:"ство",m:"Stva",h:"'S' + 'tva'"}]},
  "i have a headache": {t:"у меня болит голова", p:"u menya bolit golova", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"бо",m:"Ba",h:"like 'bah'"},{t:"лит",m:"Leet",h:"like 'leet'"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"ло",m:"La",h:"the note 'la'"},{t:"ва",m:"Va",h:"like 'vault' without LT"}]},
  "i have a fever": {t:"у меня температура", p:"u menya temperatura", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"тем",m:"Tyem",h:"like 'them' with Y"},{t:"пе",m:"Peh",h:"like 'pet' without T"},{t:"ра",m:"Ra",h:"like 'rah' with rolled R"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"ра",m:"Ra",h:"like 'rah' with rolled R"}]},
  "i'm allergic to": {t:"у меня аллергия на", p:"u menya allergiya na", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"ал",m:"Al",h:"the name 'Al'"},{t:"лер",m:"Lehr",h:"like 'lair'"},{t:"ги",m:"Gee",h:"the word 'gee'"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"на",m:"Na",h:"like 'nah'"}]},
  "it hurts here": {t:"здесь болит", p:"zdes' bolit", s:[{t:"здесь",m:"Zdyes",h:"'Z' + 'yes'"},{t:"бо",m:"Ba",h:"like 'bah'"},{t:"лит",m:"Leet",h:"like 'leet'"}]},
  "dentist": {t:"зубной врач", p:"zubnoy vrach", s:[{t:"зуб",m:"Zoob",h:"like 'zoo' + B"},{t:"ной",m:"Noy",h:"like 'annoy' without A"},{t:"врач",m:"Vrach",h:"'V' + 'rotch'"}]},
  "pharmacy": {t:"аптека", p:"apteka", s:[{t:"ап",m:"Ap",h:"like 'app'"},{t:"те",m:"Tyeh",h:"like 'check' without CK"},{t:"ка",m:"Ka",h:"like 'ka' in karate"}]},
  "i have diabetes": {t:"у меня диабет", p:"u menya diabet", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"ди",m:"Dee",h:"the word 'dee'"},{t:"а",m:"Ah",h:"the sound 'ah'"},{t:"бет",m:"Bet",h:"the word 'bet'"}]},
  "pain": {t:"боль", p:"bol'", s:[{t:"боль",m:"Ball",h:"the word 'ball'"}]},
  "i feel dizzy": {t:"у меня кружится голова", p:"u menya kruzhitsya golova", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"ме",m:"Mee",h:"like 'me'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"},{t:"кру",m:"Kroo",h:"like 'cruise' without SE"},{t:"жит",m:"Zheet",h:"like 'sheet' with ZH"},{t:"ся",m:"Sya",h:"'see' + 'ya'"},{t:"го",m:"Ga",h:"like 'got' without T"},{t:"ло",m:"La",h:"the note 'la'"},{t:"ва",m:"Va",h:"like 'vault' without LT"}]},

  // ===== TIME (10) =====
  "what time is it": {t:"который час", p:"kotoryy chas", s:[{t:"ко",m:"Ka",h:"like 'ka' in karate"},{t:"то",m:"Toh",h:"like 'toe'"},{t:"рый",m:"Ri",h:"like 'rip' without P"},{t:"час",m:"Chas",h:"like 'chasm' without M"}]},
  "today": {t:"сегодня", p:"segodnya", s:[{t:"се",m:"See",h:"the word 'see'"},{t:"год",m:"God",h:"the word 'God'"},{t:"ня",m:"Nya",h:"'knee' + 'ya'"}]},
  "tomorrow": {t:"завтра", p:"zavtra", s:[{t:"зав",m:"Zahv",h:"like 'salve' with Z"},{t:"тра",m:"Tra",h:"like 'tram' without M"}]},
  "yesterday": {t:"вчера", p:"vchera", s:[{t:"вче",m:"Fcheh",h:"'F' + 'check' without CK"},{t:"ра",m:"Ra",h:"like 'rah' with rolled R"}]},
  "morning": {t:"утро", p:"utro", s:[{t:"у",m:"Oo",h:"like 'ooh'"},{t:"тро",m:"Tro",h:"like 'troll' without L"}]},
  "afternoon": {t:"день", p:"den'", s:[{t:"день",m:"Den",h:"the word 'den' said softly"}]},
  "evening": {t:"вечер", p:"vecher", s:[{t:"ве",m:"Veh",h:"like 'vest' without ST"},{t:"чер",m:"Chair",h:"the word 'chair'"}]},
  "night": {t:"ночь", p:"noch'", s:[{t:"ночь",m:"Noch",h:"like 'notch'"}]},
  "hour": {t:"час", p:"chas", s:[{t:"час",m:"Chas",h:"like 'chasm' without M"}]},
  "minute": {t:"минута", p:"minuta", s:[{t:"ми",m:"Mee",h:"like 'me'"},{t:"ну",m:"Noo",h:"like 'noon' without last N"},{t:"та",m:"Ta",h:"like 'ta' in British English"}]},

  // ===== WEATHER (10) =====
  "what is the weather like": {t:"какая погода", p:"kakaya pogoda", s:[{t:"ка",m:"Ka",h:"like 'ka' in karate"},{t:"ка",m:"Ka",h:"like 'ka' in karate"},{t:"я",m:"Ya",h:"the word 'ya'"},{t:"по",m:"Pa",h:"like 'pa'"},{t:"го",m:"Go",h:"the word 'go'"},{t:"да",m:"Da",h:"the word 'da'"}]},
  "it's cold": {t:"холодно", p:"kholodno", s:[{t:"хо",m:"Kha",h:"like 'ha' with K"},{t:"лод",m:"Lod",h:"like 'lodge' without GE"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "it's hot": {t:"жарко", p:"zharko", s:[{t:"жар",m:"Zhar",h:"like 'jar' with ZH"},{t:"ко",m:"Ka",h:"like 'ka' in karate"}]},
  "it's raining": {t:"идёт дождь", p:"idyot dozhd'", s:[{t:"и",m:"Ee",h:"the letter 'E'"},{t:"дёт",m:"Dyot",h:"like 'yacht' with D"},{t:"дождь",m:"Dozh-d",h:"like 'dodge' with ZH"}]},
  "it's snowing": {t:"идёт снег", p:"idyot sneg", s:[{t:"и",m:"Ee",h:"the letter 'E'"},{t:"дёт",m:"Dyot",h:"like 'yacht' with D"},{t:"снег",m:"Snyeg",h:"'S' + 'neck' with G"}]},
  "sunny": {t:"солнечно", p:"solnechno", s:[{t:"сол",m:"Sol",h:"the name 'Sol'"},{t:"неч",m:"Nyech",h:"like 'neck' with Y"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "cloudy": {t:"облачно", p:"oblachno", s:[{t:"об",m:"Ob",h:"like 'obvious' first part"},{t:"лач",m:"Lach",h:"like 'latch'"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "windy": {t:"ветрено", p:"vetreno", s:[{t:"вет",m:"Vet",h:"the word 'vet'"},{t:"ре",m:"Rye",h:"the word 'rye'"},{t:"но",m:"Na",h:"like 'nah'"}]},
  "temperature": {t:"температура", p:"temperatura", s:[{t:"тем",m:"Tyem",h:"like 'them' with Y"},{t:"пе",m:"Peh",h:"like 'pet' without T"},{t:"ра",m:"Ra",h:"like 'rah' with rolled R"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"ра",m:"Ra",h:"like 'rah' with rolled R"}]},
  "umbrella": {t:"зонт", p:"zont", s:[{t:"зонт",m:"Zont",h:"like 'font' with Z"}]}
};
