var DICT_PTBR = {

  // ============ GREETINGS (20) ============

  "hello": {t:"olá", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"lá",m:"Lah",h:"like 'la' the musical note"}]},
  "good morning": {t:"bom dia", s:[{t:"bom",m:"Bone",h:"like 'bone' without the e"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "good afternoon": {t:"boa tarde", s:[{t:"bo",m:"Bow",h:"like 'bow' of a ship"},{t:"ah",m:"Ah",h:"the word 'ah'"},{t:"tar",m:"Tar",h:"the word 'tar'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "good evening": {t:"boa noite", s:[{t:"bo",m:"Bow",h:"like 'bow' of a ship"},{t:"ah",m:"Ah",h:"the word 'ah'"},{t:"noy",m:"Noy",h:"like 'boy' with an N"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "goodbye": {t:"tchau", s:[{t:"tchau",m:"Chow",h:"the word 'chow'"}]},
  "see you later": {t:"até logo", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"té",m:"Teh",h:"like 'ten' without the n"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "see you tomorrow": {t:"até amanhã", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"té",m:"Teh",h:"like 'ten' without the n"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyah",m:"Nyah",h:"like 'nyah'"}]},
  "how are you?": {t:"como você está?", s:[{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"mo",m:"Moo",h:"the word 'moo'"},{t:"vo",m:"Voh",h:"like 'vo' in vote"},{t:"cê",m:"Say",h:"the word 'say'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"tá",m:"Tah",h:"like 'ta' in taco"}]},
  "I'm fine": {t:"estou bem", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"bem",m:"Bang",h:"like 'bang' with a nasal sound"}]},
  "nice to meet you": {t:"prazer em conhecê-lo", s:[{t:"pra",m:"Prah",h:"like 'pra' in practice"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"em",m:"Ang",h:"like 'ang' nasal"},{t:"co",m:"Co",h:"like 'co' in cone"},{t:"nye",m:"Nyeh",h:"like 'nye'"},{t:"say",m:"Say",h:"the word 'say'"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "my name is...": {t:"meu nome é...", s:[{t:"meu",m:"May",h:"like 'may' + 'oo'"},{t:"no",m:"No",h:"the word 'no'"},{t:"mee",m:"Me",h:"the word 'me'"},{t:"eh",m:"Eh",h:"the word 'eh'"}]},
  "what is your name?": {t:"qual é o seu nome?", s:[{t:"qual",m:"Kwow",h:"like 'cow' with a KW"},{t:"é",m:"Eh",h:"the word 'eh'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"seu",m:"Say",h:"like 'say' + 'oo'"},{t:"no",m:"No",h:"the word 'no'"},{t:"mee",m:"Me",h:"the word 'me'"}]},
  "please": {t:"por favor", s:[{t:"por",m:"Poor",h:"the word 'poor'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"vor",m:"Vor",h:"like 'vor' in divorce"}]},
  "thank you": {t:"obrigado", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"bri",m:"Bree",h:"like 'bree' in breeze"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "thank you (female)": {t:"obrigada", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"bri",m:"Bree",h:"like 'bree' in breeze"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "you're welcome": {t:"de nada", s:[{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "excuse me": {t:"com licença", s:[{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"sen",m:"Sen",h:"like 'sen' in send"},{t:"sa",m:"Sah",h:"like 'sa' in saga"}]},
  "sorry": {t:"desculpe", s:[{t:"des",m:"Des",h:"like 'des' in desk"},{t:"cul",m:"Cool",h:"the word 'cool'"},{t:"pee",m:"Pee",h:"the word 'pee'"}]},
  "welcome": {t:"bem-vindo", s:[{t:"bem",m:"Bang",h:"like 'bang' nasal"},{t:"vin",m:"Veen",h:"like 'keen' with a V"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "have a nice day": {t:"tenha um bom dia", s:[{t:"te",m:"Teh",h:"like 'ten' without the n"},{t:"nya",m:"Nyah",h:"like 'nyah'"},{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"bom",m:"Bone",h:"like 'bone' without the e"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},

  // ============ YES/NO/BASICS (10) ============

  "yes": {t:"sim", s:[{t:"sim",m:"Sing",h:"like 'sing' nasal"}]},
  "no": {t:"não", s:[{t:"não",m:"Now",h:"like 'now' nasal"}]},
  "maybe": {t:"talvez", s:[{t:"tal",m:"Tow",h:"like 'tow'"},{t:"vez",m:"Vays",h:"like 'vase' with a Z"}]},
  "I don't understand": {t:"eu não entendo", s:[{t:"eu",m:"Ay",h:"like 'ay' + 'oo'"},{t:"não",m:"Now",h:"like 'now' nasal"},{t:"en",m:"En",h:"like 'en' in enter"},{t:"ten",m:"Ten",h:"the word 'ten'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "I don't speak Portuguese": {t:"eu não falo português", s:[{t:"eu",m:"Ay",h:"like 'ay' + 'oo'"},{t:"não",m:"Now",h:"like 'now' nasal"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"lo",m:"Low",h:"the word 'low'"},{t:"por",m:"Poor",h:"the word 'poor'"},{t:"tu",m:"Too",h:"the word 'too'"},{t:"gays",m:"Gaze",h:"the word 'gaze'"}]},
  "do you speak English?": {t:"você fala inglês?", s:[{t:"vo",m:"Voh",h:"like 'vo' in vote"},{t:"cê",m:"Say",h:"the word 'say'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"la",m:"Lah",h:"like 'la' the musical note"},{t:"in",m:"In",h:"the word 'in'"},{t:"glays",m:"Glaze",h:"like 'glaze'"}]},
  "please speak slowly": {t:"fale devagar, por favor", s:[{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"lee",m:"Lee",h:"the word 'lee'"},{t:"de",m:"Jee",h:"the word 'gee'"},{t:"va",m:"Vah",h:"like 'va' in vase"},{t:"gar",m:"Gar",h:"like 'gar' in garden"},{t:"poor",m:"Poor",h:"the word 'poor'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"vor",m:"Vor",h:"like 'vor' in divorce"}]},
  "can you repeat that?": {t:"pode repetir?", s:[{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"pe",m:"Peh",h:"like 'pen' without the n"},{t:"cheer",m:"Cheer",h:"the word 'cheer'"}]},
  "I understand": {t:"eu entendo", s:[{t:"eu",m:"Ay",h:"like 'ay' + 'oo'"},{t:"en",m:"En",h:"like 'en' in enter"},{t:"ten",m:"Ten",h:"the word 'ten'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "of course": {t:"claro", s:[{t:"cla",m:"Clah",h:"like 'cla' in clan"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},

  // ============ EMERGENCY (15) ============

  "help!": {t:"socorro!", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"ho",m:"Ho",h:"the word 'ho'"}]},
  "call the police": {t:"chame a polícia", s:[{t:"sha",m:"Shah",h:"the word 'shah'"},{t:"mee",m:"Me",h:"the word 'me'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"lee",m:"Lee",h:"the word 'lee'"},{t:"see",m:"See",h:"the word 'see'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "call an ambulance": {t:"chame uma ambulância", s:[{t:"sha",m:"Shah",h:"the word 'shah'"},{t:"mee",m:"Me",h:"the word 'me'"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"am",m:"Am",h:"the word 'am'"},{t:"bu",m:"Boo",h:"the word 'boo'"},{t:"lan",m:"Lan",h:"like 'lan' in land"},{t:"see",m:"See",h:"the word 'see'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "I need a doctor": {t:"preciso de um médico", s:[{t:"pre",m:"Preh",h:"like 'pre' in press"},{t:"see",m:"See",h:"the word 'see'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"meh",m:"Meh",h:"the word 'meh'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"co",m:"Co",h:"like 'co' in coat"}]},
  "I'm lost": {t:"estou perdido", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"per",m:"Per",h:"the word 'per'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "fire!": {t:"fogo!", s:[{t:"fo",m:"Foh",h:"like 'fo' in four"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "danger": {t:"perigo", s:[{t:"pe",m:"Peh",h:"like 'pen' without the n"},{t:"ree",m:"Ree",h:"like 'ree' in reed"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "I've been robbed": {t:"fui assaltado", s:[{t:"fwee",m:"Free",h:"like 'free' with a W"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"sal",m:"Sal",h:"the word 'sal'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "where is the hospital?": {t:"onde fica o hospital?", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"fee",m:"Fee",h:"the word 'fee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"os",m:"Os",h:"like 'os' in boss"},{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"tow",m:"Tow",h:"the word 'tow'"}]},
  "where is the pharmacy?": {t:"onde fica a farmácia?", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"fee",m:"Fee",h:"the word 'fee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"far",m:"Far",h:"the word 'far'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"see",m:"See",h:"the word 'see'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "stop!": {t:"pare!", s:[{t:"pa",m:"Pah",h:"like 'pa' in party"},{t:"ree",m:"Ree",h:"like 'ree' in reed"}]},
  "be careful": {t:"cuidado", s:[{t:"kwee",m:"Key",h:"like 'key' with a W"},{t:"da",m:"Dah",h:"like 'da' in dance"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "I'm allergic to...": {t:"tenho alergia a...", s:[{t:"te",m:"Teh",h:"like 'ten' without the n"},{t:"nyo",m:"Nyo",h:"like 'nyo'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ler",m:"Lair",h:"the word 'lair'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "it's an emergency": {t:"é uma emergência", s:[{t:"eh",m:"Eh",h:"the word 'eh'"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"e",m:"Eh",h:"the word 'eh'"},{t:"mer",m:"Mer",h:"like 'mer' in mercy"},{t:"jen",m:"Jen",h:"the name 'Jen'"},{t:"see",m:"See",h:"the word 'see'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "I need help": {t:"preciso de ajuda", s:[{t:"pre",m:"Preh",h:"like 'pre' in press"},{t:"see",m:"See",h:"the word 'see'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"joo",m:"Jew",h:"like 'Jew'"},{t:"dah",m:"Dah",h:"like 'da' in dance"}]},

  // ============ NUMBERS (15) ============

  "zero": {t:"zero", s:[{t:"ze",m:"Zeh",h:"like 'ze' in zest"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},
  "one": {t:"um", s:[{t:"um",m:"Oom",h:"like 'oom' in room"}]},
  "two": {t:"dois", s:[{t:"dois",m:"Doys",h:"like 'toys' with a D"}]},
  "three": {t:"três", s:[{t:"trays",m:"Trays",h:"the word 'trays'"}]},
  "four": {t:"quatro", s:[{t:"kwa",m:"Ква",h:"like 'qua' in quarter"},{t:"tro",m:"True",h:"like 'true' with an O"}]},
  "five": {t:"cinco", s:[{t:"sin",m:"Sin",h:"the word 'sin'"},{t:"co",m:"Co",h:"like 'co' in coat"}]},
  "six": {t:"seis", s:[{t:"says",m:"Says",h:"the word 'says'"}]},
  "seven": {t:"sete", s:[{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "eight": {t:"oito", s:[{t:"oy",m:"Oy",h:"the word 'oy'"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "nine": {t:"nove", s:[{t:"no",m:"No",h:"the word 'no'"},{t:"vee",m:"Vee",h:"the letter 'V'"}]},
  "ten": {t:"dez", s:[{t:"days",m:"Days",h:"the word 'days'"}]},
  "twenty": {t:"vinte", s:[{t:"vin",m:"Veen",h:"like 'keen' with a V"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "fifty": {t:"cinquenta", s:[{t:"sin",m:"Sin",h:"the word 'sin'"},{t:"kwen",m:"Ken",h:"like 'ken' with a W"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},
  "one hundred": {t:"cem", s:[{t:"sem",m:"Sang",h:"like 'sang' nasal"}]},
  "one thousand": {t:"mil", s:[{t:"mil",m:"Meal",h:"the word 'meal'"}]},

  // ============ FOOD & DRINK (30) ============

  "water": {t:"água", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gwa",m:"Gwa",h:"like 'gwa' in guava"}]},
  "coffee": {t:"café", s:[{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"feh",m:"Feh",h:"like 'fair' without the r"}]},
  "beer": {t:"cerveja", s:[{t:"ser",m:"Sir",h:"the word 'sir'"},{t:"ve",m:"Veh",h:"like 'vet' without the t"},{t:"ja",m:"Jah",h:"like 'ja' in jar"}]},
  "wine": {t:"vinho", s:[{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"nyo",m:"Nyo",h:"like 'nyo'"}]},
  "juice": {t:"suco", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"co",m:"Co",h:"like 'co' in coat"}]},
  "milk": {t:"leite", s:[{t:"lay",m:"Lay",h:"the word 'lay'"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "tea": {t:"chá", s:[{t:"sha",m:"Shah",h:"the word 'shah'"}]},
  "bread": {t:"pão", s:[{t:"pow",m:"Pow",h:"the word 'pow' nasal"}]},
  "rice": {t:"arroz", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"hoys",m:"Joys",h:"like 'joys' with an H"}]},
  "beans": {t:"feijão", s:[{t:"fay",m:"Fay",h:"the name 'Fay'"},{t:"jow",m:"Jow",h:"like 'now' with a J, nasal"}]},
  "chicken": {t:"frango", s:[{t:"fran",m:"Fran",h:"the name 'Fran'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "beef": {t:"carne", s:[{t:"car",m:"Car",h:"the word 'car'"},{t:"nee",m:"Knee",h:"the word 'knee'"}]},
  "fish": {t:"peixe", s:[{t:"pay",m:"Pay",h:"the word 'pay'"},{t:"shee",m:"She",h:"the word 'she'"}]},
  "egg": {t:"ovo", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"vo",m:"Voh",h:"like 'vo' in vote"}]},
  "cheese": {t:"queijo", s:[{t:"kay",m:"Kay",h:"the name 'Kay'"},{t:"jo",m:"Joe",h:"the name 'Joe'"}]},
  "fruit": {t:"fruta", s:[{t:"fru",m:"Frew",h:"like 'brew' with an F"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},
  "salad": {t:"salada", s:[{t:"sa",m:"Sah",h:"like 'sa' in saga"},{t:"la",m:"Lah",h:"like 'la' the musical note"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "soup": {t:"sopa", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"pa",m:"Pah",h:"like 'pa' in party"}]},
  "cake": {t:"bolo", s:[{t:"bo",m:"Bow",h:"like 'bow' of a ship"},{t:"lo",m:"Low",h:"the word 'low'"}]},
  "ice cream": {t:"sorvete", s:[{t:"sor",m:"Sor",h:"like 'sor' in sort"},{t:"ve",m:"Veh",h:"like 'vet' without the t"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "sugar": {t:"açúcar", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"car",m:"Car",h:"the word 'car'"}]},
  "salt": {t:"sal", s:[{t:"sal",m:"Sal",h:"the word 'sal'"}]},
  "pepper": {t:"pimenta", s:[{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"men",m:"Men",h:"the word 'men'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},
  "I'm hungry": {t:"estou com fome", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"fo",m:"Foh",h:"like 'fo' in four"},{t:"mee",m:"Me",h:"the word 'me'"}]},
  "I'm thirsty": {t:"estou com sede", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "a snack": {t:"um lanche", s:[{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"lan",m:"Lan",h:"like 'lan' in land"},{t:"shee",m:"She",h:"the word 'she'"}]},
  "sparkling water": {t:"água com gás", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gwa",m:"Gwa",h:"like 'gwa' in guava"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"gas",m:"Gaz",h:"like 'gaz' in gaze"}]},
  "still water": {t:"água sem gás", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gwa",m:"Gwa",h:"like 'gwa' in guava"},{t:"sem",m:"Sang",h:"like 'sang' nasal"},{t:"gas",m:"Gaz",h:"like 'gaz' in gaze"}]},
  "orange juice": {t:"suco de laranja", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"co",m:"Co",h:"like 'co' in coat"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"la",m:"Lah",h:"like 'la' the musical note"},{t:"ran",m:"Han",h:"like 'han' with a soft R"},{t:"ja",m:"Jah",h:"like 'ja' in jar"}]},
  "coconut water": {t:"água de coco", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gwa",m:"Gwa",h:"like 'gwa' in guava"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"co",m:"Co",h:"like 'co' in coat"},{t:"co",m:"Co",h:"like 'co' in coat"}]},

  // ============ RESTAURANT (15) ============

  "a table for two, please": {t:"uma mesa para dois, por favor", s:[{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"me",m:"Meh",h:"the word 'meh'"},{t:"za",m:"Zah",h:"like 'za' in plaza"},{t:"pa",m:"Pah",h:"like 'pa' in party"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"doys",m:"Toys",h:"like 'toys' with a D"},{t:"poor",m:"Poor",h:"the word 'poor'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"vor",m:"Vor",h:"like 'vor' in divorce"}]},
  "the menu, please": {t:"o cardápio, por favor", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"car",m:"Car",h:"the word 'car'"},{t:"da",m:"Dah",h:"like 'da' in dance"},{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"poor",m:"Poor",h:"the word 'poor'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"vor",m:"Vor",h:"like 'vor' in divorce"}]},
  "I would like...": {t:"eu gostaria de...", s:[{t:"eu",m:"Ay",h:"like 'ay' + 'oo'"},{t:"gos",m:"Gos",h:"like 'gos' in ghost"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ree",m:"Ree",h:"like 'ree' in reed"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "the bill, please": {t:"a conta, por favor", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"con",m:"Kong",h:"like 'kong' nasal"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"poor",m:"Poor",h:"the word 'poor'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"vor",m:"Vor",h:"like 'vor' in divorce"}]},
  "is service included?": {t:"a gorjeta está incluída?", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gor",m:"Gor",h:"like 'gor' in gorge"},{t:"je",m:"Jeh",h:"like 'jet' without the t"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"in",m:"In",h:"the word 'in'"},{t:"clu",m:"Clue",h:"the word 'clue'"},{t:"ee",m:"Ee",h:"like 'ee' in see"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "what do you recommend?": {t:"o que você recomenda?", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"kee",m:"Key",h:"the word 'key'"},{t:"vo",m:"Voh",h:"like 'vo' in vote"},{t:"say",m:"Say",h:"the word 'say'"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"co",m:"Co",h:"like 'co' in coat"},{t:"men",m:"Men",h:"the word 'men'"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "I'm vegetarian": {t:"sou vegetariano", s:[{t:"soh",m:"So",h:"the word 'so'"},{t:"ve",m:"Veh",h:"like 'vet' without the t"},{t:"je",m:"Jeh",h:"like 'jet' without the t"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ree",m:"Ree",h:"like 'ree' in reed"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "no meat": {t:"sem carne", s:[{t:"sem",m:"Sang",h:"like 'sang' nasal"},{t:"car",m:"Car",h:"the word 'car'"},{t:"nee",m:"Knee",h:"the word 'knee'"}]},
  "delicious": {t:"delicioso", s:[{t:"de",m:"Jeh",h:"like 'jet' without the t"},{t:"li",m:"Lee",h:"the word 'lee'"},{t:"see",m:"See",h:"the word 'see'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"}]},
  "too spicy": {t:"muito picante", s:[{t:"mween",m:"Mean",h:"the word 'mean' with W"},{t:"to",m:"Too",h:"the word 'too'"},{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"kan",m:"Can",h:"the word 'can'"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "a glass of wine": {t:"uma taça de vinho", s:[{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"sa",m:"Sah",h:"like 'sa' in saga"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"nyo",m:"Nyo",h:"like 'nyo'"}]},
  "a bottle of water": {t:"uma garrafa de água", s:[{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"ha",m:"Hah",h:"like 'ha'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"gwa",m:"Gwa",h:"like 'gwa' in guava"}]},
  "breakfast": {t:"café da manhã", s:[{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"feh",m:"Feh",h:"like 'fair' without the r"},{t:"da",m:"Dah",h:"like 'da' in dance"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyah",m:"Nyah",h:"like 'nyah'"}]},
  "lunch": {t:"almoço", s:[{t:"al",m:"Al",h:"the name 'Al'"},{t:"mo",m:"Moh",h:"like 'mo' in mole"},{t:"so",m:"So",h:"the word 'so'"}]},
  "dinner": {t:"jantar", s:[{t:"jan",m:"Jan",h:"the name 'Jan'"},{t:"tar",m:"Tar",h:"the word 'tar'"}]},

  // ============ SHOPPING (20) ============

  "how much does this cost?": {t:"quanto custa isso?", s:[{t:"kwan",m:"Wan",h:"like 'wan' with a K"},{t:"to",m:"Too",h:"the word 'too'"},{t:"coos",m:"Coos",h:"like 'coos' in cozy"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ee",m:"Ee",h:"like 'ee' in see"},{t:"so",m:"So",h:"the word 'so'"}]},
  "too expensive": {t:"muito caro", s:[{t:"mween",m:"Mean",h:"the word 'mean' with W"},{t:"to",m:"Too",h:"the word 'too'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},
  "do you have...?": {t:"você tem...?", s:[{t:"vo",m:"Voh",h:"like 'vo' in vote"},{t:"say",m:"Say",h:"the word 'say'"},{t:"tang",m:"Tang",h:"the word 'tang' nasal"}]},
  "I want to buy...": {t:"quero comprar...", s:[{t:"ke",m:"Keh",h:"like 'ket' without the t"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"prar",m:"Prar",h:"like 'pra' in practice + R"}]},
  "can I pay by card?": {t:"posso pagar com cartão?", s:[{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"so",m:"So",h:"the word 'so'"},{t:"pa",m:"Pah",h:"like 'pa' in party"},{t:"gar",m:"Gar",h:"like 'gar' in garden"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"car",m:"Car",h:"the word 'car'"},{t:"tow",m:"Tow",h:"the word 'tow' nasal"}]},
  "cash": {t:"dinheiro", s:[{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"nyay",m:"Nay",h:"like 'nay' with NY"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},
  "receipt": {t:"recibo", s:[{t:"he",m:"Heh",h:"like 'heh'"},{t:"see",m:"See",h:"the word 'see'"},{t:"bo",m:"Bow",h:"like 'bow' of a ship"}]},
  "bigger": {t:"maior", s:[{t:"ma",m:"My",h:"like 'my'"},{t:"yor",m:"Yor",h:"like 'your'"}]},
  "smaller": {t:"menor", s:[{t:"me",m:"Meh",h:"the word 'meh'"},{t:"nor",m:"Nor",h:"the word 'nor'"}]},
  "this one": {t:"este", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "that one": {t:"aquele", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ke",m:"Keh",h:"like 'ket' without the t"},{t:"lee",m:"Lee",h:"the word 'lee'"}]},
  "a bag": {t:"uma sacola", s:[{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"sa",m:"Sah",h:"like 'sa' in saga"},{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"la",m:"Lah",h:"like 'la' the musical note"}]},
  "open": {t:"aberto", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ber",m:"Bare",h:"the word 'bare'"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "closed": {t:"fechado", s:[{t:"fe",m:"Feh",h:"like 'fair' without the r"},{t:"sha",m:"Shah",h:"the word 'shah'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "discount": {t:"desconto", s:[{t:"des",m:"Des",h:"like 'des' in desk"},{t:"con",m:"Kong",h:"like 'kong' nasal"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "can you lower the price?": {t:"pode fazer um desconto?", s:[{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"des",m:"Des",h:"like 'des' in desk"},{t:"con",m:"Kong",h:"like 'kong' nasal"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "I'm just looking": {t:"estou só olhando", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"so",m:"So",h:"the word 'so'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"lyan",m:"Lyon",h:"like 'Lyon' the city"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "what size?": {t:"qual tamanho?", s:[{t:"kwow",m:"Cow",h:"like 'cow' with a KW"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyo",m:"Nyo",h:"like 'nyo'"}]},
  "do you accept credit card?": {t:"aceita cartão de crédito?", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"say",m:"Say",h:"the word 'say'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"car",m:"Car",h:"the word 'car'"},{t:"tow",m:"Tow",h:"the word 'tow' nasal"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"cre",m:"Creh",h:"like 'cre' in credit"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "where is the market?": {t:"onde fica o mercado?", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"fee",m:"Fee",h:"the word 'fee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"mer",m:"Mer",h:"like 'mer' in mercy"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"do",m:"Doo",h:"the word 'do'"}]},

  // ============ DIRECTIONS (25) ============

  "where is...?": {t:"onde fica...?", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"fee",m:"Fee",h:"the word 'fee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"}]},
  "turn left": {t:"vire à esquerda", s:[{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"ree",m:"Ree",h:"like 'ree' in reed"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"ker",m:"Care",h:"the word 'care'"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "turn right": {t:"vire à direita", s:[{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"ree",m:"Ree",h:"like 'ree' in reed"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ray",m:"Ray",h:"the word 'ray'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},
  "go straight": {t:"siga em frente", s:[{t:"see",m:"See",h:"the word 'see'"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"em",m:"Ang",h:"like 'ang' nasal"},{t:"fren",m:"Fren",h:"like 'fren' in French"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "near": {t:"perto", s:[{t:"per",m:"Per",h:"the word 'per'"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "far": {t:"longe", s:[{t:"lon",m:"Long",h:"the word 'long'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "here": {t:"aqui", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"key",m:"Key",h:"the word 'key'"}]},
  "there": {t:"ali", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"lee",m:"Lee",h:"the word 'lee'"}]},
  "street": {t:"rua", s:[{t:"hu",m:"Who",h:"the word 'who'"},{t:"ah",m:"Ah",h:"the word 'ah'"}]},
  "avenue": {t:"avenida", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ve",m:"Veh",h:"like 'vet' without the t"},{t:"nee",m:"Knee",h:"the word 'knee'"},{t:"da",m:"Dah",h:"like 'da' in dance"}]},
  "bus stop": {t:"ponto de ônibus", s:[{t:"pon",m:"Pong",h:"like 'pong' nasal"},{t:"to",m:"Too",h:"the word 'too'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"oh",m:"Oh",h:"the word 'oh'"},{t:"nee",m:"Knee",h:"the word 'knee'"},{t:"bus",m:"Boos",h:"like 'boos'"}]},
  "taxi": {t:"táxi", s:[{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ksee",m:"See",h:"the word 'see' with K"}]},
  "subway": {t:"metrô", s:[{t:"me",m:"Meh",h:"the word 'meh'"},{t:"tro",m:"Trow",h:"like 'throw'"}]},
  "airport": {t:"aeroporto", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"e",m:"Eh",h:"the word 'eh'"},{t:"ro",m:"Hoh",h:"like 'hoe'"},{t:"por",m:"Poor",h:"the word 'poor'"},{t:"to",m:"Too",h:"the word 'too'"}]},
  "train station": {t:"estação de trem", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"sow",m:"Sow",h:"the word 'sow' nasal"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"trang",m:"Trang",h:"like 'trang' nasal"}]},
  "beach": {t:"praia", s:[{t:"pra",m:"Pry",h:"like 'pry' + 'ah'"},{t:"ya",m:"Ya",h:"the word 'ya'"}]},
  "on the corner": {t:"na esquina", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"kee",m:"Key",h:"the word 'key'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "next to": {t:"ao lado de", s:[{t:"ow",m:"Ow",h:"the word 'ow'"},{t:"la",m:"Lah",h:"like 'la' the musical note"},{t:"do",m:"Doo",h:"the word 'do'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "in front of": {t:"na frente de", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"fren",m:"Fren",h:"like 'fren' in French"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "behind": {t:"atrás de", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"tras",m:"Traz",h:"like 'traz'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "how do I get to...?": {t:"como chego a...?", s:[{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"mo",m:"Moo",h:"the word 'moo'"},{t:"she",m:"She",h:"the word 'she'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"a",m:"Ah",h:"the word 'ah'"}]},
  "is it far from here?": {t:"é longe daqui?", s:[{t:"eh",m:"Eh",h:"the word 'eh'"},{t:"lon",m:"Long",h:"the word 'long'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"da",m:"Dah",h:"like 'da' in dance"},{t:"key",m:"Key",h:"the word 'key'"}]},
  "I need a taxi": {t:"preciso de um táxi", s:[{t:"pre",m:"Preh",h:"like 'pre' in press"},{t:"see",m:"See",h:"the word 'see'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"ksee",m:"See",h:"the word 'see' with K"}]},
  "take me to...": {t:"me leve para...", s:[{t:"mee",m:"Me",h:"the word 'me'"},{t:"le",m:"Leh",h:"like 'let' without the t"},{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"pa",m:"Pah",h:"like 'pa' in party"},{t:"ra",m:"Rah",h:"like 'rah'"}]},
  "how long does it take?": {t:"quanto tempo demora?", s:[{t:"kwan",m:"Wan",h:"like 'wan' with a K"},{t:"to",m:"Too",h:"the word 'too'"},{t:"tem",m:"Tang",h:"like 'tang' nasal"},{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"de",m:"Jeh",h:"like 'jet' without the t"},{t:"mo",m:"Moh",h:"like 'mo' in mole"},{t:"ra",m:"Rah",h:"like 'rah'"}]},

  // ============ ACCOMMODATION (15) ============

  "do you have a room?": {t:"tem quarto disponível?", s:[{t:"tang",m:"Tang",h:"the word 'tang' nasal"},{t:"kwar",m:"Car",h:"like 'car' with KW"},{t:"to",m:"Too",h:"the word 'too'"},{t:"jees",m:"Geez",h:"the word 'geez'"},{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"nee",m:"Knee",h:"the word 'knee'"},{t:"vel",m:"Vow",h:"like 'vow'"}]},
  "a single room": {t:"um quarto de solteiro", s:[{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"kwar",m:"Car",h:"like 'car' with KW"},{t:"to",m:"Too",h:"the word 'too'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"sol",m:"Sol",h:"the word 'sol'"},{t:"tay",m:"Tay",h:"like 'tay'"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},
  "a double room": {t:"um quarto de casal", s:[{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"kwar",m:"Car",h:"like 'car' with KW"},{t:"to",m:"Too",h:"the word 'too'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"zal",m:"Zow",h:"like 'zow'"}]},
  "how much per night?": {t:"quanto custa por noite?", s:[{t:"kwan",m:"Wan",h:"like 'wan' with a K"},{t:"to",m:"Too",h:"the word 'too'"},{t:"coos",m:"Coos",h:"like 'coos' in cozy"},{t:"ta",m:"Tah",h:"like 'ta' in taco"},{t:"poor",m:"Poor",h:"the word 'poor'"},{t:"noy",m:"Noy",h:"like 'boy' with an N"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "I have a reservation": {t:"tenho uma reserva", s:[{t:"te",m:"Teh",h:"like 'ten' without the n"},{t:"nyo",m:"Nyo",h:"like 'nyo'"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"va",m:"Vah",h:"like 'va' in vase"}]},
  "check-in": {t:"fazer o check-in", s:[{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"check",m:"Check",h:"the word 'check'"},{t:"in",m:"In",h:"the word 'in'"}]},
  "check-out": {t:"fazer o check-out", s:[{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"check",m:"Check",h:"the word 'check'"},{t:"out",m:"Out",h:"the word 'out'"}]},
  "the key": {t:"a chave", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"sha",m:"Shah",h:"the word 'shah'"},{t:"vee",m:"Vee",h:"the letter 'V'"}]},
  "air conditioning": {t:"ar-condicionado", s:[{t:"ar",m:"Ar",h:"like 'ar' in are"},{t:"con",m:"Kong",h:"like 'kong' nasal"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"see",m:"See",h:"the word 'see'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "Wi-Fi password": {t:"senha do Wi-Fi", s:[{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"nya",m:"Nyah",h:"like 'nyah'"},{t:"do",m:"Doo",h:"the word 'do'"},{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fi",h:"like 'fi' in file"}]},
  "towel": {t:"toalha", s:[{t:"to",m:"Too",h:"the word 'too'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"lya",m:"Lyah",h:"like 'lya'"}]},
  "bathroom": {t:"banheiro", s:[{t:"ba",m:"Bah",h:"like 'ba' in bar"},{t:"nyay",m:"Nay",h:"like 'nay' with NY"},{t:"ro",m:"Hoo",h:"like 'who' with a soft R"}]},
  "swimming pool": {t:"piscina", s:[{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"see",m:"See",h:"the word 'see'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "elevator": {t:"elevador", s:[{t:"e",m:"Eh",h:"the word 'eh'"},{t:"le",m:"Leh",h:"like 'let' without the t"},{t:"va",m:"Vah",h:"like 'va' in vase"},{t:"dor",m:"Door",h:"the word 'door'"}]},
  "is breakfast included?": {t:"o café da manhã está incluído?", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"feh",m:"Feh",h:"like 'fair' without the r"},{t:"da",m:"Dah",h:"like 'da' in dance"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyah",m:"Nyah",h:"like 'nyah'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"in",m:"In",h:"the word 'in'"},{t:"clu",m:"Clue",h:"the word 'clue'"},{t:"ee",m:"Ee",h:"like 'ee' in see"},{t:"do",m:"Doo",h:"the word 'do'"}]},

  // ============ COMMUNICATION (15) ============

  "phone": {t:"telefone", s:[{t:"te",m:"Teh",h:"like 'ten' without the n"},{t:"le",m:"Leh",h:"like 'let' without the t"},{t:"fo",m:"Foh",h:"like 'fo' in four"},{t:"nee",m:"Knee",h:"the word 'knee'"}]},
  "internet": {t:"internet", s:[{t:"in",m:"In",h:"the word 'in'"},{t:"ter",m:"Ter",h:"like 'ter' in term"},{t:"ne",m:"Neh",h:"like 'net' without the t"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "can I use the Wi-Fi?": {t:"posso usar o Wi-Fi?", s:[{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"so",m:"So",h:"the word 'so'"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"zar",m:"Zar",h:"like 'tsar'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fi",h:"like 'fi' in file"}]},
  "what is the Wi-Fi password?": {t:"qual é a senha do Wi-Fi?", s:[{t:"kwow",m:"Cow",h:"like 'cow' with a KW"},{t:"eh",m:"Eh",h:"the word 'eh'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"nya",m:"Nyah",h:"like 'nyah'"},{t:"do",m:"Doo",h:"the word 'do'"},{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fi",h:"like 'fi' in file"}]},
  "email": {t:"e-mail", s:[{t:"ee",m:"Ee",h:"like 'ee' in see"},{t:"may",m:"May",h:"the word 'may'"},{t:"ol",m:"Ol",h:"like 'ol' in old"}]},
  "message": {t:"mensagem", s:[{t:"men",m:"Men",h:"the word 'men'"},{t:"sa",m:"Sah",h:"like 'sa' in saga"},{t:"jang",m:"Jang",h:"like 'jang' nasal"}]},
  "I don't have signal": {t:"não tenho sinal", s:[{t:"now",m:"Now",h:"like 'now' nasal"},{t:"te",m:"Teh",h:"like 'ten' without the n"},{t:"nyo",m:"Nyo",h:"like 'nyo'"},{t:"see",m:"See",h:"the word 'see'"},{t:"now",m:"Now",h:"the word 'now'"}]},
  "can I make a call?": {t:"posso fazer uma ligação?", s:[{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"so",m:"So",h:"the word 'so'"},{t:"fa",m:"Fah",h:"like 'fa' the musical note"},{t:"zer",m:"Zer",h:"like 'zer' in zero"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"lee",m:"Lee",h:"the word 'lee'"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"sow",m:"Sow",h:"the word 'sow' nasal"}]},
  "where can I charge my phone?": {t:"onde posso carregar meu celular?", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"po",m:"Poh",h:"like 'po' in pole"},{t:"so",m:"So",h:"the word 'so'"},{t:"ca",m:"Kah",h:"like 'ka' in karate"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"gar",m:"Gar",h:"like 'gar' in garden"},{t:"meu",m:"May",h:"like 'may' + 'oo'"},{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"lu",m:"Loo",h:"like 'loo'"},{t:"lar",m:"Lar",h:"the word 'lar'"}]},
  "letter": {t:"carta", s:[{t:"car",m:"Car",h:"the word 'car'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},
  "post office": {t:"correio", s:[{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"hay",m:"Hay",h:"the word 'hay'"},{t:"o",m:"Oh",h:"the word 'oh'"}]},
  "I need to send a message": {t:"preciso enviar uma mensagem", s:[{t:"pre",m:"Preh",h:"like 'pre' in press"},{t:"see",m:"See",h:"the word 'see'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"},{t:"en",m:"En",h:"like 'en' in enter"},{t:"vee",m:"Vee",h:"the letter 'V'"},{t:"ar",m:"Ar",h:"like 'ar' in are"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"men",m:"Men",h:"the word 'men'"},{t:"sa",m:"Sah",h:"like 'sa' in saga"},{t:"jang",m:"Jang",h:"like 'jang' nasal"}]},
  "SIM card": {t:"chip de celular", s:[{t:"ship",m:"Ship",h:"the word 'ship'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"lu",m:"Loo",h:"like 'loo'"},{t:"lar",m:"Lar",h:"the word 'lar'"}]},
  "do you have a charger?": {t:"você tem um carregador?", s:[{t:"vo",m:"Voh",h:"like 'vo' in vote"},{t:"say",m:"Say",h:"the word 'say'"},{t:"tang",m:"Tang",h:"the word 'tang' nasal"},{t:"um",m:"Oom",h:"like 'oom' in room"},{t:"ca",m:"Kah",h:"like 'ka' in karate"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"ga",m:"Gah",h:"like 'ga' in garden"},{t:"dor",m:"Door",h:"the word 'door'"}]},
  "translate": {t:"traduzir", s:[{t:"tra",m:"Trah",h:"like 'tra' in track"},{t:"du",m:"Doo",h:"the word 'do'"},{t:"zeer",m:"Zeer",h:"like 'seer' with a Z"}]},

  // ============ HEALTH (10) ============

  "I feel sick": {t:"estou passando mal", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"pa",m:"Pah",h:"like 'pa' in party"},{t:"san",m:"San",h:"the name 'San'"},{t:"do",m:"Doo",h:"the word 'do'"},{t:"mow",m:"Mow",h:"the word 'mow'"}]},
  "I have a headache": {t:"estou com dor de cabeça", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"dor",m:"Door",h:"the word 'door'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ka",m:"Kah",h:"like 'ka' in karate"},{t:"be",m:"Beh",h:"like 'bet' without the t"},{t:"sa",m:"Sah",h:"like 'sa' in saga"}]},
  "I have a fever": {t:"estou com febre", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"toh",m:"Toe",h:"the word 'toe'"},{t:"com",m:"Kong",h:"like 'kong' nasal"},{t:"feh",m:"Feh",h:"like 'fair' without the r"},{t:"bree",m:"Bree",h:"like 'bree' in breeze"}]},
  "I need medicine": {t:"preciso de remédio", s:[{t:"pre",m:"Preh",h:"like 'pre' in press"},{t:"see",m:"See",h:"the word 'see'"},{t:"zo",m:"Zoo",h:"the word 'zoo'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"he",m:"Heh",h:"like 'heh'"},{t:"meh",m:"Meh",h:"the word 'meh'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"o",m:"Oh",h:"the word 'oh'"}]},
  "it hurts here": {t:"dói aqui", s:[{t:"doy",m:"Toy",h:"like 'toy' with a D"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"key",m:"Key",h:"the word 'key'"}]},
  "stomach pain": {t:"dor de estômago", s:[{t:"dor",m:"Door",h:"the word 'door'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "I'm diabetic": {t:"sou diabético", s:[{t:"soh",m:"So",h:"the word 'so'"},{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"a",m:"Ah",h:"the word 'ah'"},{t:"beh",m:"Beh",h:"like 'bet' without the t"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"},{t:"co",m:"Co",h:"like 'co' in coat"}]},
  "I can't breathe": {t:"não consigo respirar", s:[{t:"now",m:"Now",h:"like 'now' nasal"},{t:"con",m:"Kong",h:"like 'kong' nasal"},{t:"see",m:"See",h:"the word 'see'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"hes",m:"Hes",h:"like 'hes' in hesitate"},{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"rar",m:"Har",h:"like 'har'"}]},
  "hospital": {t:"hospital", s:[{t:"os",m:"Os",h:"like 'os' in boss"},{t:"pee",m:"Pee",h:"the word 'pee'"},{t:"tow",m:"Tow",h:"the word 'tow'"}]},
  "dentist": {t:"dentista", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"chees",m:"Cheese",h:"the word 'cheese'"},{t:"ta",m:"Tah",h:"like 'ta' in taco"}]},

  // ============ TIME (10) ============

  "what time is it?": {t:"que horas são?", s:[{t:"kee",m:"Key",h:"the word 'key'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ras",m:"Ras",h:"like 'ras' in rascal"},{t:"sow",m:"Sow",h:"the word 'sow' nasal"}]},
  "today": {t:"hoje", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "tomorrow": {t:"amanhã", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyah",m:"Nyah",h:"like 'nyah'"}]},
  "yesterday": {t:"ontem", s:[{t:"on",m:"Own",h:"the word 'own'"},{t:"tang",m:"Tang",h:"the word 'tang' nasal"}]},
  "now": {t:"agora", s:[{t:"a",m:"Ah",h:"the word 'ah'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"ra",m:"Rah",h:"like 'rah'"}]},
  "later": {t:"mais tarde", s:[{t:"mice",m:"Mice",h:"the word 'mice'"},{t:"tar",m:"Tar",h:"the word 'tar'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "morning": {t:"manhã", s:[{t:"ma",m:"Mah",h:"like 'ma'"},{t:"nyah",m:"Nyah",h:"like 'nyah'"}]},
  "afternoon": {t:"tarde", s:[{t:"tar",m:"Tar",h:"the word 'tar'"},{t:"jee",m:"Gee",h:"the word 'gee'"}]},
  "night": {t:"noite", s:[{t:"noy",m:"Noy",h:"like 'boy' with an N"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "week": {t:"semana", s:[{t:"se",m:"Seh",h:"like 'set' without the t"},{t:"ma",m:"Mah",h:"like 'ma'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},

  // ============ WEATHER (10) ============

  "what's the weather like?": {t:"como está o tempo?", s:[{t:"co",m:"Coh",h:"like 'co' in coat"},{t:"mo",m:"Moo",h:"the word 'moo'"},{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"tem",m:"Tang",h:"like 'tang' nasal"},{t:"po",m:"Poh",h:"like 'po' in pole"}]},
  "it's hot": {t:"está quente", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"ken",m:"Ken",h:"the name 'Ken'"},{t:"chee",m:"Chee",h:"like 'cheese' without the se"}]},
  "it's cold": {t:"está frio", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"free",m:"Free",h:"the word 'free'"},{t:"o",m:"Oh",h:"the word 'oh'"}]},
  "it's raining": {t:"está chovendo", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"sho",m:"Show",h:"the word 'show'"},{t:"ven",m:"Ven",h:"like 'ven' in vent"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "sunny": {t:"ensolarado", s:[{t:"en",m:"En",h:"like 'en' in enter"},{t:"so",m:"So",h:"the word 'so'"},{t:"la",m:"Lah",h:"like 'la' the musical note"},{t:"ra",m:"Rah",h:"like 'rah'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "cloudy": {t:"nublado", s:[{t:"noo",m:"New",h:"the word 'new'"},{t:"bla",m:"Blah",h:"the word 'blah'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "windy": {t:"ventando", s:[{t:"ven",m:"Ven",h:"like 'ven' in vent"},{t:"tan",m:"Tan",h:"the word 'tan'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "it's humid": {t:"está úmido", s:[{t:"es",m:"Es",h:"like 'es' in best"},{t:"tah",m:"Tah",h:"like 'ta' in taco"},{t:"oo",m:"Ooh",h:"the word 'ooh'"},{t:"mee",m:"Me",h:"the word 'me'"},{t:"do",m:"Doo",h:"the word 'do'"}]},
  "is it going to rain?": {t:"vai chover?", s:[{t:"vai",m:"Vie",h:"like 'vie'"},{t:"sho",m:"Show",h:"the word 'show'"},{t:"ver",m:"Vair",h:"like 'vair'"}]},
  "beautiful day": {t:"dia lindo", s:[{t:"jee",m:"Gee",h:"the word 'gee'"},{t:"ah",m:"Ah",h:"the word 'ah'"},{t:"lin",m:"Lean",h:"the word 'lean'"},{t:"do",m:"Doo",h:"the word 'do'"}]}
};
