// dict-ja.js — Japanese phrase dictionary (200+ entries)
// Auto-generated for HowDoISay app
var DICT_JA = {
  // === 1. GREETINGS & COURTESY (20) ===
  "hello": {t:"こんにちは", p:"konnichiwa", s:[{t:"kon",m:"Con",h:"the word 'con'"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"wa",m:"Wah",h:"the word 'wah'"}]},
  "good morning": {t:"おはようございます", p:"ohayou gozaimasu", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"zai",m:"Zai",h:"like 'sigh' with Z"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "good afternoon": {t:"こんにちは", p:"konnichiwa", s:[{t:"kon",m:"Con",h:"the word 'con'"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"wa",m:"Wah",h:"the word 'wah'"}]},
  "good evening": {t:"こんばんは", p:"konbanwa", s:[{t:"kon",m:"Con",h:"the word 'con'"},{t:"ban",m:"Ban",h:"the word 'ban'"},{t:"wa",m:"Wah",h:"the word 'wah'"}]},
  "good night": {t:"おやすみなさい", p:"oyasumi nasai", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "goodbye": {t:"さようなら", p:"sayounara", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ra",m:"Rah",h:"the word 'rah'"}]},
  "see you later": {t:"またね", p:"mata ne", s:[{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ne",m:"Neh",h:"'net' without T"}]},
  "thank you": {t:"ありがとう", p:"arigatou", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"u",m:"Oo",h:"like 'ooh'"}]},
  "thank you very much": {t:"ありがとうございます", p:"arigatou gozaimasu", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"zai",m:"Zai",h:"like 'sigh' with Z"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "you're welcome": {t:"どういたしまして", p:"dou itashimashite", s:[{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"te",m:"Teh",h:"'ten' without N"}]},
  "excuse me": {t:"すみません", p:"sumimasen", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"sen",m:"Sen",h:"the word 'send' without D"}]},
  "i'm sorry": {t:"ごめんなさい", p:"gomen nasai", s:[{t:"go",m:"Go",h:"the word 'go'"},{t:"men",m:"Men",h:"the word 'men'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "please": {t:"お願いします", p:"onegai shimasu", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ne",m:"Neh",h:"'net' without T"},{t:"gai",m:"Guy",h:"the word 'guy'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "nice to meet you": {t:"はじめまして", p:"hajimemashite", s:[{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"ji",m:"Gee",h:"like 'gee whiz'"},{t:"me",m:"Meh",h:"like 'met' without T"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"te",m:"Teh",h:"'ten' without N"}]},
  "how are you": {t:"お元気ですか", p:"ogenki desu ka", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"gen",m:"Gen",h:"the name 'Gen'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "i'm fine": {t:"元気です", p:"genki desu", s:[{t:"gen",m:"Gen",h:"the name 'Gen'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "what is your name": {t:"お名前は何ですか", p:"onamae wa nan desu ka", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"nan",m:"Non",h:"like 'none'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "my name is": {t:"私の名前は", p:"watashi no namae wa", s:[{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"shi",m:"She",h:"the word 'she'"},{t:"no",m:"No",h:"the word 'no'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"wa",m:"Wah",h:"the word 'wah'"}]},
  "congratulations": {t:"おめでとうございます", p:"omedetou gozaimasu", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"me",m:"Meh",h:"like 'met' without T"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"zai",m:"Zai",h:"like 'sigh' with Z"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "happy birthday": {t:"お誕生日おめでとう", p:"otanjoubi omedetou", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"tan",m:"Ton",h:"the word 'ton'"},{t:"jo",m:"Joe",h:"the name 'Joe'"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"me",m:"Meh",h:"like 'met' without T"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"to",m:"Toe",h:"the word 'toe'"}]},

  // === 2. YES/NO/BASICS (10) ===
  "yes": {t:"はい", p:"hai", s:[{t:"hai",m:"Hi",h:"the word 'hi'"}]},
  "no": {t:"いいえ", p:"iie", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"e",m:"Eh",h:"the sound 'eh'"}]},
  "okay": {t:"大丈夫", p:"daijoubu", s:[{t:"dai",m:"Die",h:"the word 'die'"},{t:"jo",m:"Joe",h:"the name 'Joe'"},{t:"bu",m:"Boo",h:"like 'boo!'"}]},
  "i understand": {t:"わかりました", p:"wakarimashita", s:[{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "i don't understand": {t:"わかりません", p:"wakarimasen", s:[{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"sen",m:"Sen",h:"the word 'send' without D"}]},
  "do you speak english": {t:"英語を話せますか", p:"eigo o hanasemasu ka", s:[{t:"ei",m:"A",h:"the letter 'A'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"se",m:"Seh",h:"like 'set' without T"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "slowly please": {t:"ゆっくりお願いします", p:"yukkuri onegai shimasu", s:[{t:"yuk",m:"Yuck",h:"the word 'yuck'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ne",m:"Neh",h:"'net' without T"},{t:"gai",m:"Guy",h:"the word 'guy'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "can you help me": {t:"助けてもらえますか", p:"tasukete moraemasu ka", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ke",m:"Keh",h:"like 'kept' without PT"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "where is": {t:"どこですか", p:"doko desu ka", s:[{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "how much": {t:"いくらですか", p:"ikura desu ka", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},

  // === 3. EMERGENCY & SAFETY (15) ===
  "help": {t:"助けて", p:"tasukete", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ke",m:"Keh",h:"like 'kept' without PT"},{t:"te",m:"Teh",h:"'ten' without N"}]},
  "emergency": {t:"緊急", p:"kinkyuu", s:[{t:"kin",m:"Kin",h:"the word 'kin'"},{t:"kyu",m:"Cue",h:"the word 'cue'"}]},
  "call the police": {t:"警察を呼んでください", p:"keisatsu o yonde kudasai", s:[{t:"kei",m:"Kay",h:"the name 'Kay'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"yon",m:"Yon",h:"the word 'yawn'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "call a doctor": {t:"医者を呼んでください", p:"isha o yonde kudasai", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"sha",m:"Shah",h:"like 'Shah' title"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"yon",m:"Yon",h:"the word 'yawn'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "hospital": {t:"病院", p:"byouin", s:[{t:"byo",m:"Bio",h:"like 'bio' in biology"},{t:"in",m:"Een",h:"like 'keen' without K"}]},
  "fire": {t:"火事", p:"kaji", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ji",m:"Gee",h:"like 'gee whiz'"}]},
  "danger": {t:"危険", p:"kiken", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"ken",m:"Ken",h:"the name 'Ken'"}]},
  "watch out": {t:"気をつけて", p:"ki o tsukete", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"ke",m:"Keh",h:"like 'kept' without PT"},{t:"te",m:"Teh",h:"'ten' without N"}]},
  "i'm lost": {t:"道に迷いました", p:"michi ni mayoimashita", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "i'm sick": {t:"気分が悪いです", p:"kibun ga warui desu", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"bun",m:"Bun",h:"the word 'bun'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ru",m:"Roo",h:"like 'rude' without D"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "call an ambulance": {t:"救急車を呼んでください", p:"kyuukyuusha o yonde kudasai", s:[{t:"kyu",m:"Cue",h:"the word 'cue'"},{t:"kyu",m:"Cue",h:"the word 'cue'"},{t:"sha",m:"Shah",h:"like 'Shah' title"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"yon",m:"Yon",h:"the word 'yawn'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "i need a doctor": {t:"医者が必要です", p:"isha ga hitsuyou desu", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"sha",m:"Shah",h:"like 'Shah' title"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"hi",m:"He",h:"the word 'he'"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "passport": {t:"パスポート", p:"pasupooto", s:[{t:"pa",m:"Pah",h:"like 'pa'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"po",m:"Poe",h:"the name 'Poe'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "police station": {t:"交番", p:"kouban", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"ban",m:"Ban",h:"the word 'ban'"}]},
  "earthquake": {t:"地震", p:"jishin", s:[{t:"ji",m:"Gee",h:"like 'gee whiz'"},{t:"shin",m:"Shin",h:"the word 'shin'"}]},

  // === 4. NUMBERS 0-10, 20, 50, 100, 1000 (15) ===
  "zero": {t:"零", p:"rei", s:[{t:"rei",m:"Ray",h:"the name 'Ray'"}]},
  "one": {t:"一", p:"ichi", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"}]},
  "two": {t:"二", p:"ni", s:[{t:"ni",m:"Knee",h:"the word 'knee'"}]},
  "three": {t:"三", p:"san", s:[{t:"san",m:"San",h:"like 'sun'"}]},
  "four": {t:"四", p:"shi", s:[{t:"shi",m:"She",h:"the word 'she'"}]},
  "five": {t:"五", p:"go", s:[{t:"go",m:"Go",h:"the word 'go'"}]},
  "six": {t:"六", p:"roku", s:[{t:"ro",m:"Row",h:"the word 'row'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "seven": {t:"七", p:"nana", s:[{t:"na",m:"Nah",h:"the word 'nah'"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "eight": {t:"八", p:"hachi", s:[{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"}]},
  "nine": {t:"九", p:"kyuu", s:[{t:"kyu",m:"Cue",h:"the word 'cue'"}]},
  "ten": {t:"十", p:"juu", s:[{t:"juu",m:"Jew",h:"like 'juice' without CE"}]},
  "twenty": {t:"二十", p:"nijuu", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"juu",m:"Jew",h:"like 'juice' without CE"}]},
  "fifty": {t:"五十", p:"gojuu", s:[{t:"go",m:"Go",h:"the word 'go'"},{t:"juu",m:"Jew",h:"like 'juice' without CE"}]},
  "one hundred": {t:"百", p:"hyaku", s:[{t:"hya",m:"Hah",h:"like 'hah!' exclamation"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "one thousand": {t:"千", p:"sen", s:[{t:"sen",m:"Sen",h:"the word 'send' without D"}]},

  // === 5. FOOD & DRINK (30) ===
  "water": {t:"水", p:"mizu", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"zu",m:"Zoo",h:"the word 'zoo'"}]},
  "coffee": {t:"コーヒー", p:"koohii", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"hii",m:"He",h:"the word 'he'"}]},
  "tea": {t:"お茶", p:"ocha", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"cha",m:"Cha",h:"like 'cha-cha' dance"}]},
  "green tea": {t:"緑茶", p:"ryokucha", s:[{t:"ryo",m:"Rio",h:"like 'Rio' the city"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"cha",m:"Cha",h:"like 'cha-cha' dance"}]},
  "beer": {t:"ビール", p:"biiru", s:[{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"ru",m:"Roo",h:"like 'rude' without D"}]},
  "wine": {t:"ワイン", p:"wain", s:[{t:"wai",m:"Why",h:"the word 'why'"},{t:"n",m:"N",h:"the letter 'N'"}]},
  "sake": {t:"日本酒", p:"nihonshu", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"hon",m:"Hon",h:"the word 'hon'"},{t:"shu",m:"Shoe",h:"the word 'shoe'"}]},
  "rice": {t:"ご飯", p:"gohan", s:[{t:"go",m:"Go",h:"the word 'go'"},{t:"han",m:"Han",h:"like 'Han' Solo"}]},
  "bread": {t:"パン", p:"pan", s:[{t:"pan",m:"Pan",h:"the word 'pan'"}]},
  "noodles": {t:"麺", p:"men", s:[{t:"men",m:"Men",h:"the word 'men'"}]},
  "ramen": {t:"ラーメン", p:"raamen", s:[{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"men",m:"Men",h:"the word 'men'"}]},
  "sushi": {t:"寿司", p:"sushi", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "meat": {t:"肉", p:"niku", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "chicken": {t:"鶏肉", p:"toriniku", s:[{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "beef": {t:"牛肉", p:"gyuuniku", s:[{t:"gyu",m:"Gyoo",h:"like 'goo' with Y"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "pork": {t:"豚肉", p:"butaniku", s:[{t:"bu",m:"Boo",h:"like 'boo!'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "fish": {t:"魚", p:"sakana", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"na",m:"Nah",h:"the word 'nah'"}]},
  "egg": {t:"卵", p:"tamago", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "vegetable": {t:"野菜", p:"yasai", s:[{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "fruit": {t:"果物", p:"kudamono", s:[{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"no",m:"No",h:"the word 'no'"}]},
  "milk": {t:"牛乳", p:"gyuunyuu", s:[{t:"gyu",m:"Gyoo",h:"like 'goo' with Y"},{t:"nyu",m:"New",h:"the word 'new'"}]},
  "juice": {t:"ジュース", p:"juusu", s:[{t:"juu",m:"Jew",h:"like 'juice' without CE"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "soup": {t:"スープ", p:"suupu", s:[{t:"suu",m:"Sue",h:"the name 'Sue'"},{t:"pu",m:"Poo",h:"like 'pool' without L"}]},
  "salad": {t:"サラダ", p:"sarada", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"da",m:"Dah",h:"the word 'duh'"}]},
  "tofu": {t:"豆腐", p:"toufu", s:[{t:"to",m:"Toe",h:"the word 'toe'"},{t:"fu",m:"Foo",h:"like 'food' without D"}]},
  "tempura": {t:"天ぷら", p:"tenpura", s:[{t:"ten",m:"Ten",h:"the number 'ten'"},{t:"pu",m:"Poo",h:"like 'pool' without L"},{t:"ra",m:"Rah",h:"the word 'rah'"}]},
  "soy sauce": {t:"醤油", p:"shouyu", s:[{t:"sho",m:"Show",h:"the word 'show'"},{t:"yu",m:"You",h:"the word 'you'"}]},
  "hot (spicy)": {t:"辛い", p:"karai", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"rai",m:"Rye",h:"the bread 'rye'"}]},
  "sweet": {t:"甘い", p:"amai", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"mai",m:"My",h:"the word 'my'"}]},
  "delicious": {t:"美味しい", p:"oishii", s:[{t:"oi",m:"Oy",h:"like 'oi!'"},{t:"shi",m:"She",h:"the word 'she'"}]},

  // === 6. RESTAURANT (15) ===
  "restaurant": {t:"レストラン", p:"resutoran", s:[{t:"re",m:"Reh",h:"like 'red' without D"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ran",m:"Run",h:"the word 'run'"}]},
  "menu": {t:"メニュー", p:"menyuu", s:[{t:"me",m:"Meh",h:"like 'met' without T"},{t:"nyu",m:"New",h:"the word 'new'"}]},
  "i'd like this": {t:"これをお願いします", p:"kore o onegai shimasu", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ne",m:"Neh",h:"'net' without T"},{t:"gai",m:"Guy",h:"the word 'guy'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "the check please": {t:"お会計お願いします", p:"okaikei onegai shimasu", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"kai",m:"Kai",h:"the name 'Kai'"},{t:"kei",m:"Kay",h:"the name 'Kay'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ne",m:"Neh",h:"'net' without T"},{t:"gai",m:"Guy",h:"the word 'guy'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "table for two": {t:"二人です", p:"futari desu", s:[{t:"fu",m:"Foo",h:"like 'food' without D"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "reservation": {t:"予約", p:"yoyaku", s:[{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "i have a reservation": {t:"予約があります", p:"yoyaku ga arimasu", s:[{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "no smoking": {t:"禁煙", p:"kin'en", s:[{t:"kin",m:"Kin",h:"the word 'kin'"},{t:"en",m:"En",h:"like 'end' without D"}]},
  "is this seat taken": {t:"この席は空いていますか", p:"kono seki wa aiteimasu ka", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"no",m:"No",h:"the word 'no'"},{t:"se",m:"Seh",h:"like 'set' without T"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ai",m:"Eye",h:"the word 'eye'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "i'm vegetarian": {t:"私はベジタリアンです", p:"watashi wa bejitarian desu", s:[{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"shi",m:"She",h:"the word 'she'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"be",m:"Beh",h:"like 'bed' without D"},{t:"ji",m:"Gee",h:"like 'gee whiz'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"an",m:"Ahn",h:"like 'on'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "i'm allergic to": {t:"アレルギーがあります", p:"arerugii ga arimasu", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"ru",m:"Roo",h:"like 'rude' without D"},{t:"gi",m:"Gee",h:"like 'gee whiz'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "more water please": {t:"水をもっとください", p:"mizu o motto kudasai", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"zu",m:"Zoo",h:"the word 'zoo'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"mot",m:"Moat",h:"the word 'moat'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "it was delicious": {t:"ごちそうさまでした", p:"gochisousama deshita", s:[{t:"go",m:"Go",h:"the word 'go'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"so",m:"So",h:"the word 'so'"},{t:"sa",m:"Sah",h:"like 'saw'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "chopsticks": {t:"箸", p:"hashi", s:[{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "spoon": {t:"スプーン", p:"supuun", s:[{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"puu",m:"Poo",h:"like 'pool' without L"},{t:"n",m:"N",h:"the letter 'N'"}]},

  // === 7. SHOPPING & MONEY (20) ===
  "how much is this": {t:"これはいくらですか", p:"kore wa ikura desu ka", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "too expensive": {t:"高すぎます", p:"takasugimasu", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"gi",m:"Gee",h:"like 'gee whiz'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "cheap": {t:"安い", p:"yasui", s:[{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"i",m:"Ee",h:"the letter 'E'"}]},
  "can you give a discount": {t:"値引きできますか", p:"nebiki dekimasu ka", s:[{t:"ne",m:"Neh",h:"'net' without T"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "i'll take it": {t:"これにします", p:"kore ni shimasu", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "do you accept credit cards": {t:"クレジットカードは使えますか", p:"kurejitto kaado wa tsukaemasu ka", s:[{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"jit",m:"Jit",h:"like 'jitter' start"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "cash": {t:"現金", p:"genkin", s:[{t:"gen",m:"Gen",h:"the name 'Gen'"},{t:"kin",m:"Kin",h:"the word 'kin'"}]},
  "receipt": {t:"レシート", p:"reshiito", s:[{t:"re",m:"Reh",h:"like 'red' without D"},{t:"shi",m:"She",h:"the word 'she'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "bag": {t:"袋", p:"fukuro", s:[{t:"fu",m:"Foo",h:"like 'food' without D"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "big": {t:"大きい", p:"ookii", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ki",m:"Key",h:"the word 'key'"}]},
  "small": {t:"小さい", p:"chiisai", s:[{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "this one": {t:"これ", p:"kore", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"}]},
  "that one": {t:"それ", p:"sore", s:[{t:"so",m:"So",h:"the word 'so'"},{t:"re",m:"Reh",h:"like 'red' without D"}]},
  "different color": {t:"違う色", p:"chigau iro", s:[{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"gau",m:"Gow",h:"like 'cow' with G"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "souvenir": {t:"お土産", p:"omiyage", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"ge",m:"Geh",h:"like 'get' without T"}]},
  "tax free": {t:"免税", p:"menzei", s:[{t:"men",m:"Men",h:"the word 'men'"},{t:"zei",m:"Zay",h:"like 'say' with Z"}]},
  "just looking": {t:"見ているだけです", p:"miteiru dake desu", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ru",m:"Roo",h:"like 'rude' without D"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"ke",m:"Keh",h:"like 'kept' without PT"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "convenience store": {t:"コンビニ", p:"konbini", s:[{t:"kon",m:"Con",h:"the word 'con'"},{t:"bi",m:"Bee",h:"the word 'bee'"},{t:"ni",m:"Knee",h:"the word 'knee'"}]},
  "department store": {t:"デパート", p:"depaato", s:[{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"pa",m:"Pah",h:"like 'pa'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "where can i buy": {t:"どこで買えますか", p:"doko de kaemasu ka", s:[{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},

  // === 8. DIRECTIONS & TRANSPORTATION (25) ===
  "where is the station": {t:"駅はどこですか", p:"eki wa doko desu ka", s:[{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"ki",m:"Key",h:"the word 'key'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "train": {t:"電車", p:"densha", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"sha",m:"Shah",h:"like 'Shah' title"}]},
  "bus": {t:"バス", p:"basu", s:[{t:"ba",m:"Bah",h:"the word 'bah'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "taxi": {t:"タクシー", p:"takushii", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "subway": {t:"地下鉄", p:"chikatetsu", s:[{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"}]},
  "airport": {t:"空港", p:"kuukou", s:[{t:"kuu",m:"Koo",h:"like 'cool' without L"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"}]},
  "ticket": {t:"切符", p:"kippu", s:[{t:"kip",m:"Kip",h:"the word 'kip'"},{t:"pu",m:"Poo",h:"like 'pool' without L"}]},
  "one ticket please": {t:"切符を一枚ください", p:"kippu o ichimai kudasai", s:[{t:"kip",m:"Kip",h:"the word 'kip'"},{t:"pu",m:"Poo",h:"like 'pool' without L"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"mai",m:"My",h:"the word 'my'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "left": {t:"左", p:"hidari", s:[{t:"hi",m:"He",h:"the word 'he'"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"ri",m:"Ree",h:"like 'reef' without F"}]},
  "right": {t:"右", p:"migi", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"gi",m:"Gee",h:"like 'gee whiz'"}]},
  "straight ahead": {t:"まっすぐ", p:"massugu", s:[{t:"mas",m:"Moss",h:"the word 'moss'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"gu",m:"Goo",h:"like 'goo'"}]},
  "stop here please": {t:"ここで止めてください", p:"koko de tomete kudasai", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"me",m:"Meh",h:"like 'met' without T"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "entrance": {t:"入口", p:"iriguchi", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"gu",m:"Goo",h:"like 'goo'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"}]},
  "exit": {t:"出口", p:"deguchi", s:[{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"gu",m:"Goo",h:"like 'goo'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"}]},
  "near": {t:"近い", p:"chikai", s:[{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"kai",m:"Kai",h:"the name 'Kai'"}]},
  "far": {t:"遠い", p:"tooi", s:[{t:"to",m:"Toe",h:"the word 'toe'"},{t:"i",m:"Ee",h:"the letter 'E'"}]},
  "north": {t:"北", p:"kita", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "south": {t:"南", p:"minami", s:[{t:"mi",m:"Me",h:"the word 'me'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"mi",m:"Me",h:"the word 'me'"}]},
  "east": {t:"東", p:"higashi", s:[{t:"hi",m:"He",h:"the word 'he'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "west": {t:"西", p:"nishi", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "map": {t:"地図", p:"chizu", s:[{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"zu",m:"Zoo",h:"the word 'zoo'"}]},
  "bullet train": {t:"新幹線", p:"shinkansen", s:[{t:"shin",m:"Shin",h:"the word 'shin'"},{t:"kan",m:"Con",h:"the word 'con'"},{t:"sen",m:"Sen",h:"the word 'send' without D"}]},
  "platform": {t:"ホーム", p:"hoomu", s:[{t:"ho",m:"Ho",h:"like 'hope' without PE"},{t:"mu",m:"Moo",h:"like a cow's 'moo'"}]},
  "next stop": {t:"次の停車", p:"tsugi no teisha", s:[{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"gi",m:"Gee",h:"like 'gee whiz'"},{t:"no",m:"No",h:"the word 'no'"},{t:"tei",m:"Tay",h:"like 'today' without -day"},{t:"sha",m:"Shah",h:"like 'Shah' title"}]},
  "transfer": {t:"乗り換え", p:"norikae", s:[{t:"no",m:"No",h:"the word 'no'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"e",m:"Eh",h:"the sound 'eh'"}]},

  // === 9. ACCOMMODATION (15) ===
  "hotel": {t:"ホテル", p:"hoteru", s:[{t:"ho",m:"Ho",h:"like 'hope' without PE"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ru",m:"Roo",h:"like 'rude' without D"}]},
  "room": {t:"部屋", p:"heya", s:[{t:"he",m:"Heh",h:"like 'help' without LP"},{t:"ya",m:"Yah",h:"the word 'yah'"}]},
  "i have a reservation": {t:"予約しています", p:"yoyaku shiteimasu", s:[{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"shi",m:"She",h:"the word 'she'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "check in": {t:"チェックイン", p:"chekkuin", s:[{t:"chek",m:"Check",h:"the word 'check'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"in",m:"In",h:"the word 'in'"}]},
  "check out": {t:"チェックアウト", p:"chekkuauto", s:[{t:"chek",m:"Check",h:"the word 'check'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"au",m:"Ow",h:"like 'ouch' without CH"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "key": {t:"鍵", p:"kagi", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"gi",m:"Gee",h:"like 'gee whiz'"}]},
  "air conditioning": {t:"エアコン", p:"eakon", s:[{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"kon",m:"Con",h:"the word 'con'"}]},
  "wifi": {t:"ワイファイ", p:"waifai", s:[{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fie",h:"like 'fire' without R"}]},
  "wifi password": {t:"ワイファイのパスワード", p:"waifai no pasuwaado", s:[{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fie",h:"like 'fire' without R"},{t:"no",m:"No",h:"the word 'no'"},{t:"pa",m:"Pah",h:"like 'pa'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"do",m:"Doe",h:"like a 'doe' deer"}]},
  "bathroom": {t:"お風呂", p:"ofuro", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"fu",m:"Foo",h:"like 'food' without D"},{t:"ro",m:"Row",h:"the word 'row'"}]},
  "toilet": {t:"トイレ", p:"toire", s:[{t:"toi",m:"Toy",h:"the word 'toy'"},{t:"re",m:"Reh",h:"like 'red' without D"}]},
  "towel": {t:"タオル", p:"taoru", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ru",m:"Roo",h:"like 'rude' without D"}]},
  "blanket": {t:"毛布", p:"moufu", s:[{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"fu",m:"Foo",h:"like 'food' without D"}]},
  "quiet please": {t:"静かにしてください", p:"shizuka ni shite kudasai", s:[{t:"shi",m:"She",h:"the word 'she'"},{t:"zu",m:"Zoo",h:"the word 'zoo'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "laundry": {t:"洗濯", p:"sentaku", s:[{t:"sen",m:"Sen",h:"the word 'send' without D"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},

  // === 10. COMMUNICATION (15) ===
  "phone": {t:"電話", p:"denwa", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"wa",m:"Wah",h:"the word 'wah'"}]},
  "internet": {t:"インターネット", p:"intaanetto", s:[{t:"in",m:"In",h:"the word 'in'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"net",m:"Net",h:"the word 'net'"},{t:"to",m:"Toe",h:"the word 'toe'"}]},
  "email": {t:"メール", p:"meeru", s:[{t:"me",m:"Meh",h:"like 'met' without T"},{t:"ru",m:"Roo",h:"like 'rude' without D"}]},
  "i don't speak japanese": {t:"日本語が話せません", p:"nihongo ga hanasemasen", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"hon",m:"Hon",h:"the word 'hon'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"se",m:"Seh",h:"like 'set' without T"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"sen",m:"Sen",h:"the word 'send' without D"}]},
  "please say that again": {t:"もう一度言ってください", p:"mou ichido itte kudasai", s:[{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"chi",m:"Chee",h:"like 'cheese' without S"},{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"it",m:"It",h:"the word 'it'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "please write it down": {t:"書いてください", p:"kaite kudasai", s:[{t:"kai",m:"Kai",h:"the name 'Kai'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"da",m:"Dah",h:"the word 'duh'"},{t:"sai",m:"Sigh",h:"the word 'sigh'"}]},
  "what does this mean": {t:"これはどういう意味ですか", p:"kore wa douiu imi desu ka", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"u",m:"Oo",h:"like 'ooh'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"mi",m:"Me",h:"the word 'me'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "is there someone who speaks english": {t:"英語が話せる人はいますか", p:"eigo ga hanaseru hito wa imasu ka", s:[{t:"ei",m:"A",h:"the letter 'A'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"ha",m:"Ha",h:"the word 'ha'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"se",m:"Seh",h:"like 'set' without T"},{t:"ru",m:"Roo",h:"like 'rude' without D"},{t:"hi",m:"He",h:"the word 'he'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "how do you say this in japanese": {t:"これは日本語で何と言いますか", p:"kore wa nihongo de nan to iimasu ka", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"hon",m:"Hon",h:"the word 'hon'"},{t:"go",m:"Go",h:"the word 'go'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"nan",m:"Non",h:"like 'none'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "can i use your phone": {t:"電話を借りてもいいですか", p:"denwa o karitemo ii desu ka", s:[{t:"den",m:"Den",h:"the word 'den'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "translator": {t:"翻訳者", p:"hon'yakusha", s:[{t:"hon",m:"Hon",h:"the word 'hon'"},{t:"ya",m:"Yah",h:"the word 'yah'"},{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"sha",m:"Shah",h:"like 'Shah' title"}]},
  "i am american": {t:"私はアメリカ人です", p:"watashi wa amerikajin desu", s:[{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"shi",m:"She",h:"the word 'she'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"me",m:"Meh",h:"like 'met' without T"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"jin",m:"Gin",h:"like the drink 'gin'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "what is the wifi password": {t:"ワイファイのパスワードは何ですか", p:"waifai no pasuwaado wa nan desu ka", s:[{t:"wai",m:"Why",h:"the word 'why'"},{t:"fai",m:"Fie",h:"like 'fire' without R"},{t:"no",m:"No",h:"the word 'no'"},{t:"pa",m:"Pah",h:"like 'pa'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"do",m:"Doe",h:"like a 'doe' deer"},{t:"wa",m:"Wah",h:"the word 'wah'"},{t:"nan",m:"Non",h:"like 'none'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "photo": {t:"写真", p:"shashin", s:[{t:"sha",m:"Shah",h:"like 'Shah' title"},{t:"shin",m:"Shin",h:"the word 'shin'"}]},
  "can you take my photo": {t:"写真を撮ってもらえますか", p:"shashin o tottemoraemasu ka", s:[{t:"sha",m:"Shah",h:"like 'Shah' title"},{t:"shin",m:"Shin",h:"the word 'shin'"},{t:"o",m:"Oh",h:"the word 'oh'"},{t:"tot",m:"Tot",h:"the word 'tot'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"mo",m:"Mo",h:"like 'mow' the lawn"},{t:"ra",m:"Rah",h:"the word 'rah'"},{t:"e",m:"Eh",h:"the sound 'eh'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},

  // === 11. HEALTH (10) ===
  "pharmacy": {t:"薬局", p:"yakkyoku", s:[{t:"yak",m:"Yak",h:"the animal 'yak'"},{t:"kyo",m:"Kyo",h:"like 'Kyo' name"},{t:"ku",m:"Koo",h:"like 'cool' without L"}]},
  "medicine": {t:"薬", p:"kusuri", s:[{t:"ku",m:"Koo",h:"like 'cool' without L"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ri",m:"Ree",h:"like 'reef' without F"}]},
  "i have a headache": {t:"頭が痛いです", p:"atama ga itai desu", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"tai",m:"Tie",h:"the word 'tie'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "i have a fever": {t:"熱があります", p:"netsu ga arimasu", s:[{t:"ne",m:"Neh",h:"'net' without T"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"ri",m:"Ree",h:"like 'reef' without F"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "stomach ache": {t:"お腹が痛い", p:"onaka ga itai", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"na",m:"Nah",h:"the word 'nah'"},{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"tai",m:"Tie",h:"the word 'tie'"}]},
  "cold (illness)": {t:"風邪", p:"kaze", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"ze",m:"Zeh",h:"like 'zest' without ST"}]},
  "it hurts here": {t:"ここが痛いです", p:"koko ga itai desu", s:[{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"ko",m:"Ko",h:"like 'co-' in co-pilot"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"i",m:"Ee",h:"the letter 'E'"},{t:"tai",m:"Tie",h:"the word 'tie'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"}]},
  "allergy": {t:"アレルギー", p:"arerugii", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"re",m:"Reh",h:"like 'red' without D"},{t:"ru",m:"Roo",h:"like 'rude' without D"},{t:"gi",m:"Gee",h:"like 'gee whiz'"}]},
  "dentist": {t:"歯医者", p:"haisha", s:[{t:"hai",m:"Hi",h:"the word 'hi'"},{t:"sha",m:"Shah",h:"like 'Shah' title"}]},
  "insurance": {t:"保険", p:"hoken", s:[{t:"ho",m:"Ho",h:"like 'hope' without PE"},{t:"ken",m:"Ken",h:"the name 'Ken'"}]},

  // === 12. TIME (10) ===
  "what time is it": {t:"今何時ですか", p:"ima nanji desu ka", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"},{t:"nan",m:"Non",h:"like 'none'"},{t:"ji",m:"Gee",h:"like 'gee whiz'"},{t:"de",m:"Deh",h:"like 'desk' without SK"},{t:"su",m:"Sue",h:"the name 'Sue'"},{t:"ka",m:"Kah",h:"like 'car' without R"}]},
  "today": {t:"今日", p:"kyou", s:[{t:"kyo",m:"Kyo",h:"like 'Kyo' name"}]},
  "tomorrow": {t:"明日", p:"ashita", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"shi",m:"She",h:"the word 'she'"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "yesterday": {t:"昨日", p:"kinou", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"no",m:"No",h:"the word 'no'"}]},
  "morning": {t:"朝", p:"asa", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "afternoon": {t:"午後", p:"gogo", s:[{t:"go",m:"Go",h:"the word 'go'"},{t:"go",m:"Go",h:"the word 'go'"}]},
  "evening": {t:"夕方", p:"yuugata", s:[{t:"yuu",m:"You",h:"the word 'you'"},{t:"ga",m:"Gah",h:"like 'got' without T"},{t:"ta",m:"Tah",h:"like 'ta' in British English"}]},
  "night": {t:"夜", p:"yoru", s:[{t:"yo",m:"Yo",h:"the word 'yo'"},{t:"ru",m:"Roo",h:"like 'rude' without D"}]},
  "now": {t:"今", p:"ima", s:[{t:"i",m:"Ee",h:"the letter 'E'"},{t:"ma",m:"Ma",h:"the word 'ma'"}]},
  "later": {t:"後で", p:"ato de", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"to",m:"Toe",h:"the word 'toe'"},{t:"de",m:"Deh",h:"like 'desk' without SK"}]},

  // === 13. WEATHER & MISC (10) ===
  "hot (weather)": {t:"暑い", p:"atsui", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"tsu",m:"Tsoo",h:"like 'tsunami' start"},{t:"i",m:"Ee",h:"the letter 'E'"}]},
  "cold (weather)": {t:"寒い", p:"samui", s:[{t:"sa",m:"Sah",h:"like 'saw'"},{t:"mu",m:"Moo",h:"like a cow's 'moo'"},{t:"i",m:"Ee",h:"the letter 'E'"}]},
  "rain": {t:"雨", p:"ame", s:[{t:"a",m:"Ah",h:"the sound 'ah'"},{t:"me",m:"Meh",h:"like 'met' without T"}]},
  "umbrella": {t:"傘", p:"kasa", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"sa",m:"Sah",h:"like 'saw'"}]},
  "beautiful": {t:"きれい", p:"kirei", s:[{t:"ki",m:"Key",h:"the word 'key'"},{t:"rei",m:"Ray",h:"the name 'Ray'"}]},
  "fun": {t:"楽しい", p:"tanoshii", s:[{t:"ta",m:"Tah",h:"like 'ta' in British English"},{t:"no",m:"No",h:"the word 'no'"},{t:"shi",m:"She",h:"the word 'she'"}]},
  "cute": {t:"可愛い", p:"kawaii", s:[{t:"ka",m:"Kah",h:"like 'car' without R"},{t:"wai",m:"Why",h:"the word 'why'"},{t:"i",m:"Ee",h:"the letter 'E'"}]},
  "japan": {t:"日本", p:"nihon", s:[{t:"ni",m:"Knee",h:"the word 'knee'"},{t:"hon",m:"Hon",h:"the word 'hon'"}]},
  "temple": {t:"お寺", p:"otera", s:[{t:"o",m:"Oh",h:"the word 'oh'"},{t:"te",m:"Teh",h:"'ten' without N"},{t:"ra",m:"Rah",h:"the word 'rah'"}]},
  "shrine": {t:"神社", p:"jinja", s:[{t:"jin",m:"Gin",h:"like the drink 'gin'"},{t:"ja",m:"Jah",h:"like 'jar' without R"}]}
};
