// dict-uk.js — Ukrainian phrase dictionary (210 entries)
// Auto-generated for HowDoISay app
var DICT_UK = {

  // ===== GREETINGS & COURTESY (20) =====
  "hello": {t:"привіт", p:"pryvit", s:[{t:"при",m:"Pre",h:"like 'pre-' in preview"},{t:"віт",m:"Veet",h:"like 'feet' with V"}]},
  "good morning": {t:"добрий ранок", p:"dobryi ranok", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"брий",m:"Bree",h:"the word 'bree' like breeze"},{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"нок",m:"Nok",h:"the word 'knock'"}]},
  "good afternoon": {t:"добрий день", p:"dobryi den", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"брий",m:"Bree",h:"the word 'bree' like breeze"},{t:"день",m:"Den",h:"the word 'den'"}]},
  "good evening": {t:"добрий вечір", p:"dobryi vechir", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"брий",m:"Bree",h:"the word 'bree' like breeze"},{t:"ве",m:"Veh",h:"like 'veh' in veteran"},{t:"чір",m:"Cheer",h:"the word 'cheer'"}]},
  "good night": {t:"на добраніч", p:"na dobranich", s:[{t:"на",m:"Nah",h:"the word 'nah'"},{t:"до",m:"Doh",h:"the word 'dough'"},{t:"бра",m:"Brah",h:"like 'bra'"},{t:"ніч",m:"Neech",h:"like 'beach' with N"}]},
  "goodbye": {t:"до побачення", p:"do pobachennya", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"ба",m:"Bah",h:"the word 'bah'"},{t:"чен",m:"Chen",h:"the name 'Chen'"},{t:"ня",m:"Nya",h:"like 'nyah'"}]},
  "thank you": {t:"дякую", p:"dyakuyu", s:[{t:"дя",m:"Dya",h:"'D' + 'yah'"},{t:"ку",m:"Koo",h:"the word 'coo'"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "thank you very much": {t:"дуже дякую", p:"duzhe dyakuyu", s:[{t:"ду",m:"Doo",h:"like 'do'"},{t:"же",m:"Zheh",h:"like 'je' in French"},{t:"дя",m:"Dya",h:"'D' + 'yah'"},{t:"ку",m:"Koo",h:"the word 'coo'"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "you're welcome": {t:"будь ласка", p:"bud laska", s:[{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "excuse me": {t:"перепрошую", p:"pereproshuyu", s:[{t:"пе",m:"Peh",h:"like 'peh' in pen"},{t:"ре",m:"Reh",h:"like 'ray'"},{t:"про",m:"Pro",h:"the word 'pro'"},{t:"шу",m:"Shoo",h:"the word 'shoo'"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "i'm sorry": {t:"вибачте", p:"vybachte", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"бач",m:"Bach",h:"like 'Bach' the composer"},{t:"те",m:"Teh",h:"like 'teh' in tech"}]},
  "please": {t:"будь ласка", p:"bud laska", s:[{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "nice to meet you": {t:"приємно познайомитися", p:"pryyemno poznayomytysya", s:[{t:"при",m:"Pre",h:"like 'pre-' in preview"},{t:"єм",m:"Yem",h:"like 'yam'"},{t:"но",m:"No",h:"the word 'no'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"знай",m:"Znai",h:"'Z' + the word 'nigh'"},{t:"о",m:"Oh",h:"the word 'oh'"},{t:"ми",m:"My",h:"the word 'me'"},{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"}]},
  "how are you": {t:"як справи", p:"yak spravy", s:[{t:"як",m:"Yak",h:"the animal 'yak'"},{t:"спра",m:"Sprah",h:"like 'spa' with R"},{t:"ви",m:"Vy",h:"like 'vee'"}]},
  "i'm fine": {t:"я в порядку", p:"ya v poryadku", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"в",m:"V",h:"the letter 'V'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"ряд",m:"Ryad",h:"'R' + 'yad'"},{t:"ку",m:"Koo",h:"the word 'coo'"}]},
  "what is your name": {t:"як вас звати", p:"yak vas zvaty", s:[{t:"як",m:"Yak",h:"the animal 'yak'"},{t:"вас",m:"Vas",h:"like 'vase' without E"},{t:"зва",m:"Zvah",h:"'Z' + 'vah'"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "my name is": {t:"мене звати", p:"mene zvaty", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"зва",m:"Zvah",h:"'Z' + 'vah'"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "pleased to meet you": {t:"радий вас бачити", p:"radyi vas bachyty", s:[{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"дий",m:"Dee",h:"the word 'dee'"},{t:"вас",m:"Vas",h:"like 'vase' without E"},{t:"ба",m:"Bah",h:"the word 'bah'"},{t:"чи",m:"Chee",h:"like 'chi' the Greek letter"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "congratulations": {t:"вітаю", p:"vitayu", s:[{t:"ві",m:"Vee",h:"the word 'vee'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "happy birthday": {t:"з днем народження", p:"z dnem narodzhennya", s:[{t:"з",m:"Z",h:"the letter 'Z'"},{t:"днем",m:"Dnem",h:"'D' + 'nem'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"джен",m:"Jen",h:"the name 'Jen'"},{t:"ня",m:"Nya",h:"like 'nyah'"}]},
  "welcome": {t:"ласкаво просимо", p:"laskavo prosymo", s:[{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"про",m:"Pro",h:"the word 'pro'"},{t:"си",m:"Sy",h:"like 'see'"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"}]},

  // ===== YES/NO/BASICS (10) =====
  "yes": {t:"так", p:"tak", s:[{t:"так",m:"Tack",h:"the word 'tack'"}]},
  "no": {t:"ні", p:"ni", s:[{t:"ні",m:"Knee",h:"the word 'knee'"}]},
  "ok": {t:"добре", p:"dobre", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"бре",m:"Breh",h:"like 'bread' without D"}]},
  "i understand": {t:"я розумію", p:"ya rozumiyu", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"зу",m:"Zoo",h:"the word 'zoo'"},{t:"мі",m:"Mee",h:"the word 'me'"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "i don't understand": {t:"я не розумію", p:"ya ne rozumiyu", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"зу",m:"Zoo",h:"the word 'zoo'"},{t:"мі",m:"Mee",h:"the word 'me'"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "do you speak english": {t:"ви розмовляєте англійською", p:"vy rozmovlyayete anhliyskoyu", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"роз",m:"Roz",h:"the name 'Roz'"},{t:"мов",m:"Mov",h:"like 'move' without E"},{t:"ля",m:"Lya",h:"like 'lia'"},{t:"є",m:"Yeh",h:"the word 'yeah'"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"ан",m:"An",h:"the word 'an'"},{t:"глій",m:"Hlee",h:"'H' + 'lee'"},{t:"ською",m:"Skoyu",h:"'sko' + 'you'"}]},
  "slowly please": {t:"повільніше будь ласка", p:"povilnishe bud laska", s:[{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"віль",m:"Veel",h:"like 'feel' with V"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"ше",m:"Sheh",h:"like 'shed' without D"},{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "can you help me": {t:"ви можете мені допомогти", p:"vy mozhete meni dopomohty", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"же",m:"Zheh",h:"like 'je' in French"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"до",m:"Doh",h:"the word 'dough'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"мог",m:"Moh",h:"like 'mow' the lawn"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "where is": {t:"де знаходиться", p:"de znakhodytsya", s:[{t:"де",m:"Deh",h:"like 'day'"},{t:"зна",m:"Znah",h:"'Z' + 'nah'"},{t:"хо",m:"Kho",h:"like 'ho'"},{t:"дить",m:"Deets",h:"like 'deeds'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"}]},
  "how much": {t:"скільки коштує", p:"skilky koshtuye", s:[{t:"скіль",m:"Skeel",h:"'ski' + 'L'"},{t:"ки",m:"Ky",h:"like 'key'"},{t:"кош",m:"Kosh",h:"like 'gosh' with K"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"є",m:"Yeh",h:"the word 'yeah'"}]},

  // ===== EMERGENCY & SAFETY (15) =====
  "help": {t:"допоможіть", p:"dopomozhit", s:[{t:"до",m:"Doh",h:"the word 'dough'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"жіть",m:"Zheet",h:"like 'sheet' with ZH"}]},
  "emergency": {t:"надзвичайна ситуація", p:"nadzvychaina sytuatsiya", s:[{t:"над",m:"Nad",h:"like 'nod'"},{t:"зви",m:"Zvy",h:"'Z' + 'vee'"},{t:"чай",m:"Chai",h:"the word 'chai' tea"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"си",m:"Sy",h:"like 'see'"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"а",m:"Ah",h:"the word 'ah'"},{t:"ці",m:"Tsee",h:"like 'sea' with TS"},{t:"я",m:"Ya",h:"the word 'yah'"}]},
  "call the police": {t:"викликайте поліцію", p:"vyklykajte politsiyu", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"кли",m:"Kly",h:"'K' + 'lee'"},{t:"кай",m:"Kai",h:"like 'kai'"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"ці",m:"Tsee",h:"like 'sea' with TS"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "call the doctor": {t:"викликайте лікаря", p:"vyklykajte likarya", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"кли",m:"Kly",h:"'K' + 'lee'"},{t:"кай",m:"Kai",h:"like 'kai'"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"ря",m:"Rya",h:"'R' + 'yah'"}]},
  "hospital": {t:"лікарня", p:"likarnya", s:[{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"кар",m:"Kar",h:"like 'car'"},{t:"ня",m:"Nya",h:"like 'nyah'"}]},
  "fire": {t:"пожежа", p:"pozhezha", s:[{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"же",m:"Zheh",h:"like 'je' in French"},{t:"жа",m:"Zhah",h:"like 'shah' with ZH"}]},
  "danger": {t:"небезпека", p:"nebezpeka", s:[{t:"не",m:"Neh",h:"like 'net' without T"},{t:"без",m:"Bez",h:"like 'Bez'"},{t:"пе",m:"Peh",h:"like 'peh' in pen"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "watch out": {t:"обережно", p:"oberezhno", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"бе",m:"Beh",h:"like 'bed' without D"},{t:"реж",m:"Rezh",h:"like 'fresh' without F"},{t:"но",m:"No",h:"the word 'no'"}]},
  "i'm lost": {t:"я загубився", p:"ya zahubyvsya", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"гу",m:"Hoo",h:"like 'who'"},{t:"бив",m:"Byv",h:"like 'biv'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"}]},
  "i'm sick": {t:"мені погано", p:"meni pohano", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"га",m:"Hah",h:"like 'ha'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "call an ambulance": {t:"викликайте швидку", p:"vyklykajte shvydku", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"кли",m:"Kly",h:"'K' + 'lee'"},{t:"кай",m:"Kai",h:"like 'kai'"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"швид",m:"Shvyd",h:"'sh' + 'vid'"},{t:"ку",m:"Koo",h:"the word 'coo'"}]},
  "i need a doctor": {t:"мені потрібен лікар", p:"meni potriben likar", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"трі",m:"Tree",h:"the word 'tree'"},{t:"бен",m:"Ben",h:"the name 'Ben'"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"кар",m:"Kar",h:"like 'car'"}]},
  "passport": {t:"паспорт", p:"pasport", s:[{t:"пас",m:"Pas",h:"like 'pass'"},{t:"порт",m:"Port",h:"the word 'port'"}]},
  "pharmacy": {t:"аптека", p:"apteka", s:[{t:"ап",m:"Ap",h:"like 'app'"},{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "police station": {t:"відділення поліції", p:"viddilennya politsiyi", s:[{t:"від",m:"Veed",h:"like 'feed' with V"},{t:"ді",m:"Dee",h:"the letter 'D'"},{t:"лен",m:"Len",h:"the name 'Len'"},{t:"ня",m:"Nya",h:"like 'nyah'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"ці",m:"Tsee",h:"like 'sea' with TS"},{t:"ї",m:"Yee",h:"like 'yee'"}]},

  // ===== NUMBERS 0-10, 20, 50, 100, 1000 (15) =====
  "zero": {t:"нуль", p:"nul", s:[{t:"нуль",m:"Nool",h:"like 'pool' with N"}]},
  "one": {t:"один", p:"odyn", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"дин",m:"Dyn",h:"like 'din'"}]},
  "two": {t:"два", p:"dva", s:[{t:"два",m:"Dvah",h:"'D' + 'vah'"}]},
  "three": {t:"три", p:"try", s:[{t:"три",m:"Tree",h:"the word 'tree'"}]},
  "four": {t:"чотири", p:"chotyry", s:[{t:"чо",m:"Cho",h:"like 'cho' in chocolate"},{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ри",m:"Ry",h:"like 'ree'"}]},
  "five": {t:"п'ять", p:"pyat", s:[{t:"п'ять",m:"Pyat",h:"'P' + 'yat'"}]},
  "six": {t:"шість", p:"shist", s:[{t:"шість",m:"Sheest",h:"like 'she' + 'st'"}]},
  "seven": {t:"сім", p:"sim", s:[{t:"сім",m:"Seem",h:"the word 'seem'"}]},
  "eight": {t:"вісім", p:"visim", s:[{t:"ві",m:"Vee",h:"the word 'vee'"},{t:"сім",m:"Seem",h:"the word 'seem'"}]},
  "nine": {t:"дев'ять", p:"devyat", s:[{t:"де",m:"Deh",h:"like 'day'"},{t:"в'ять",m:"Vyat",h:"'V' + 'yat'"}]},
  "ten": {t:"десять", p:"desyat", s:[{t:"де",m:"Deh",h:"like 'day'"},{t:"сять",m:"Syat",h:"'S' + 'yat'"}]},
  "twenty": {t:"двадцять", p:"dvadtsyat", s:[{t:"двад",m:"Dvad",h:"'D' + 'vad'"},{t:"цять",m:"Tsyat",h:"'TS' + 'yat'"}]},
  "fifty": {t:"п'ятдесят", p:"pyatdesyat", s:[{t:"п'ят",m:"Pyat",h:"'P' + 'yat'"},{t:"де",m:"Deh",h:"like 'day'"},{t:"сят",m:"Syat",h:"'S' + 'yat'"}]},
  "one hundred": {t:"сто", p:"sto", s:[{t:"сто",m:"Stoh",h:"like 'stow'"}]},
  "one thousand": {t:"тисяча", p:"tysyacha", s:[{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"},{t:"ча",m:"Cha",h:"like 'cha' for tea"}]},

  // ===== FOOD & DRINK (30) =====
  "water": {t:"вода", p:"voda", s:[{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"да",m:"Dah",h:"the word 'dah'"}]},
  "coffee": {t:"кава", p:"kava", s:[{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"ва",m:"Vah",h:"like 'va' in valet"}]},
  "tea": {t:"чай", p:"chai", s:[{t:"чай",m:"Chai",h:"the word 'chai' tea"}]},
  "beer": {t:"пиво", p:"pyvo", s:[{t:"пи",m:"Py",h:"like 'pea'"},{t:"во",m:"Voh",h:"like 'vow' without W"}]},
  "wine": {t:"вино", p:"vyno", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "rice": {t:"рис", p:"rys", s:[{t:"рис",m:"Rys",h:"like 'riss'"}]},
  "bread": {t:"хліб", p:"khlib", s:[{t:"хліб",m:"Khleeb",h:"like 'sleep' with KHL"}]},
  "meat": {t:"м'ясо", p:"myaso", s:[{t:"м'я",m:"Mya",h:"'M' + 'yah'"},{t:"со",m:"Soh",h:"like 'sew'"}]},
  "chicken": {t:"курка", p:"kurka", s:[{t:"кур",m:"Koor",h:"like 'cure'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "fish": {t:"риба", p:"ryba", s:[{t:"ри",m:"Ry",h:"like 'ree'"},{t:"ба",m:"Bah",h:"the word 'bah'"}]},
  "pork": {t:"свинина", p:"svynyna", s:[{t:"сви",m:"Svy",h:"'S' + 'vee'"},{t:"ни",m:"Ny",h:"like 'knee'"},{t:"на",m:"Nah",h:"the word 'nah'"}]},
  "beef": {t:"яловичина", p:"yalovychyna", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"ло",m:"Loh",h:"like 'low'"},{t:"ви",m:"Vy",h:"like 'vee'"},{t:"чи",m:"Chee",h:"like 'chi' the Greek letter"},{t:"на",m:"Nah",h:"the word 'nah'"}]},
  "vegetables": {t:"овочі", p:"ovochi", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"чі",m:"Chee",h:"like 'chi' the Greek letter"}]},
  "fruit": {t:"фрукти", p:"frukty", s:[{t:"фрук",m:"Frook",h:"like 'fluke' with R"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "soup": {t:"суп", p:"sup", s:[{t:"суп",m:"Soup",h:"the word 'soup'"}]},
  "salad": {t:"салат", p:"salat", s:[{t:"са",m:"Sah",h:"like 'sah'"},{t:"лат",m:"Lat",h:"the word 'lat'"}]},
  "borshch": {t:"борщ", p:"borshch", s:[{t:"борщ",m:"Borshch",h:"like 'bore' + 'sh' + 'ch'"}]},
  "varenyky": {t:"вареники", p:"varenyky", s:[{t:"ва",m:"Vah",h:"like 'va' in valet"},{t:"ре",m:"Reh",h:"like 'ray'"},{t:"ни",m:"Ny",h:"like 'knee'"},{t:"ки",m:"Ky",h:"like 'key'"}]},
  "egg": {t:"яйце", p:"yaytse", s:[{t:"яй",m:"Yai",h:"like 'yai'"},{t:"це",m:"Tseh",h:"like 'tseh'"}]},
  "milk": {t:"молоко", p:"moloko", s:[{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"ло",m:"Loh",h:"like 'low'"},{t:"ко",m:"Koh",h:"like 'co' in company"}]},
  "butter": {t:"масло", p:"maslo", s:[{t:"мас",m:"Mas",h:"like 'mass'"},{t:"ло",m:"Loh",h:"like 'low'"}]},
  "cheese": {t:"сир", p:"syr", s:[{t:"сир",m:"Seer",h:"like 'seer'"}]},
  "sugar": {t:"цукор", p:"tsukor", s:[{t:"цу",m:"Tsoo",h:"'TS' + 'oo'"},{t:"кор",m:"Kor",h:"like 'core'"}]},
  "salt": {t:"сіль", p:"sil", s:[{t:"сіль",m:"Seel",h:"like 'seal'"}]},
  "pepper": {t:"перець", p:"perets", s:[{t:"пе",m:"Peh",h:"like 'peh' in pen"},{t:"рець",m:"Rets",h:"like 'wets' with R"}]},
  "juice": {t:"сік", p:"sik", s:[{t:"сік",m:"Seek",h:"the word 'seek'"}]},
  "ice cream": {t:"морозиво", p:"morozyvo", s:[{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"зи",m:"Zy",h:"like 'zee'"},{t:"во",m:"Voh",h:"like 'vow' without W"}]},
  "cake": {t:"торт", p:"tort", s:[{t:"торт",m:"Tort",h:"the word 'tort'"}]},
  "chocolate": {t:"шоколад", p:"shokolad", s:[{t:"шо",m:"Sho",h:"like 'show'"},{t:"ко",m:"Koh",h:"like 'co' in company"},{t:"лад",m:"Lad",h:"the word 'lad'"}]},
  "i'm hungry": {t:"я голодний", p:"ya holodnyi", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"лод",m:"Lod",h:"like 'laud'"},{t:"ний",m:"Nyi",h:"like 'knee'"}]},

  // ===== RESTAURANT (15) =====
  "menu": {t:"меню", p:"menyu", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ню",m:"Nyu",h:"like 'new'"}]},
  "i would like": {t:"я хотів би", p:"ya khotiv by", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"хо",m:"Kho",h:"like 'ho'"},{t:"тів",m:"Teev",h:"like 'teeth' without TH"},{t:"би",m:"By",h:"the word 'by'"}]},
  "the bill please": {t:"рахунок будь ласка", p:"rakhunok bud laska", s:[{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"ху",m:"Khoo",h:"like 'who'"},{t:"нок",m:"Nok",h:"the word 'knock'"},{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "table for two": {t:"столик на двох", p:"stolyk na dvokh", s:[{t:"сто",m:"Stoh",h:"like 'stow'"},{t:"лик",m:"Lyk",h:"like 'lick'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"двох",m:"Dvokh",h:"'D' + 'vokh'"}]},
  "breakfast": {t:"сніданок", p:"snidanok", s:[{t:"сні",m:"Snee",h:"like 'sneeze' without ZE"},{t:"да",m:"Dah",h:"the word 'dah'"},{t:"нок",m:"Nok",h:"the word 'knock'"}]},
  "lunch": {t:"обід", p:"obid", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"бід",m:"Beed",h:"like 'bead'"}]},
  "dinner": {t:"вечеря", p:"vecherya", s:[{t:"ве",m:"Veh",h:"like 'veh' in veteran"},{t:"че",m:"Cheh",h:"like 'check' without CK"},{t:"ря",m:"Rya",h:"'R' + 'yah'"}]},
  "delicious": {t:"смачно", p:"smachno", s:[{t:"смач",m:"Smach",h:"like 'smash' with CH"},{t:"но",m:"No",h:"the word 'no'"}]},
  "spicy": {t:"гостре", p:"hostre", s:[{t:"гос",m:"Hos",h:"like 'host' without T"},{t:"тре",m:"Treh",h:"like 'tray'"}]},
  "vegetarian": {t:"вегетаріанське", p:"vehetarianske", s:[{t:"ве",m:"Veh",h:"like 'veh' in veteran"},{t:"ге",m:"Heh",h:"like 'heh'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"},{t:"рі",m:"Ree",h:"like 'ree'"},{t:"ан",m:"An",h:"the word 'an'"},{t:"ське",m:"Skeh",h:"like 'sketch' without TCH"}]},
  "more water please": {t:"ще води будь ласка", p:"shche vody bud laska", s:[{t:"ще",m:"Shcheh",h:"like 'shed' without D, with CH"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"ди",m:"Dy",h:"like 'dee'"},{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "no sugar": {t:"без цукру", p:"bez tsukru", s:[{t:"без",m:"Bez",h:"like 'Bez'"},{t:"цук",m:"Tsook",h:"'TS' + 'ook'"},{t:"ру",m:"Roo",h:"like 'roo' in kangaroo"}]},
  "with milk": {t:"з молоком", p:"z molokom", s:[{t:"з",m:"Z",h:"the letter 'Z'"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"ло",m:"Loh",h:"like 'low'"},{t:"ком",m:"Kom",h:"like 'com' in company"}]},
  "i'm allergic to": {t:"у мене алергія на", p:"u mene alerhiya na", s:[{t:"у",m:"Oo",h:"like 'oo' in moon"},{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"а",m:"Ah",h:"the word 'ah'"},{t:"лер",m:"Ler",h:"like 'lair'"},{t:"гі",m:"Hee",h:"like 'he'"},{t:"я",m:"Ya",h:"the word 'yah'"},{t:"на",m:"Nah",h:"the word 'nah'"}]},
  "waiter": {t:"офіціант", p:"ofitsiant", s:[{t:"о",m:"Oh",h:"the word 'oh'"},{t:"фі",m:"Fee",h:"the word 'fee'"},{t:"ці",m:"Tsee",h:"like 'sea' with TS"},{t:"ант",m:"Ant",h:"the word 'ant'"}]},

  // ===== SHOPPING (20) =====
  "how much does this cost": {t:"скільки це коштує", p:"skilky tse koshtuye", s:[{t:"скіль",m:"Skeel",h:"'ski' + 'L'"},{t:"ки",m:"Ky",h:"like 'key'"},{t:"це",m:"Tseh",h:"like 'tseh'"},{t:"кош",m:"Kosh",h:"like 'gosh' with K"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"є",m:"Yeh",h:"the word 'yeah'"}]},
  "too expensive": {t:"занадто дорого", p:"zanadto doroho", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"над",m:"Nad",h:"like 'nod'"},{t:"то",m:"Toh",h:"like 'toe'"},{t:"до",m:"Doh",h:"the word 'dough'"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"го",m:"Hoh",h:"like 'hoe'"}]},
  "cheap": {t:"дешево", p:"deshevo", s:[{t:"де",m:"Deh",h:"like 'day'"},{t:"ше",m:"Sheh",h:"like 'shed' without D"},{t:"во",m:"Voh",h:"like 'vow' without W"}]},
  "discount": {t:"знижка", p:"znyzhka", s:[{t:"зниж",m:"Znyzhk",h:"'Z' + 'knee' + 'ZH'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "i want to buy": {t:"я хочу купити", p:"ya khochu kupyty", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"хо",m:"Kho",h:"like 'ho'"},{t:"чу",m:"Choo",h:"like 'chew'"},{t:"ку",m:"Koo",h:"the word 'coo'"},{t:"пи",m:"Py",h:"like 'pea'"},{t:"ти",m:"Ty",h:"like 'tea'"}]},
  "do you have": {t:"у вас є", p:"u vas ye", s:[{t:"у",m:"Oo",h:"like 'oo' in moon"},{t:"вас",m:"Vas",h:"like 'vase' without E"},{t:"є",m:"Yeh",h:"the word 'yeah'"}]},
  "this one": {t:"ось це", p:"os tse", s:[{t:"ось",m:"Os",h:"like 'oss'"},{t:"це",m:"Tseh",h:"like 'tseh'"}]},
  "bigger": {t:"більший", p:"bilshyi", s:[{t:"біль",m:"Beel",h:"like 'feel' with B"},{t:"ший",m:"Shyi",h:"like 'she'"}]},
  "smaller": {t:"менший", p:"menshyi", s:[{t:"мен",m:"Men",h:"the word 'men'"},{t:"ший",m:"Shyi",h:"like 'she'"}]},
  "different color": {t:"інший колір", p:"inshyi kolir", s:[{t:"ін",m:"Een",h:"like 'keen' without K"},{t:"ший",m:"Shyi",h:"like 'she'"},{t:"ко",m:"Koh",h:"like 'co' in company"},{t:"лір",m:"Leer",h:"like 'leer'"}]},
  "cash": {t:"готівка", p:"hotivka", s:[{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"тів",m:"Teev",h:"like 'teeth' without TH"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "credit card": {t:"кредитна картка", p:"kredytna kartka", s:[{t:"кре",m:"Kreh",h:"like 'cred'"},{t:"дит",m:"Dyt",h:"like 'dit'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"карт",m:"Kart",h:"the word 'cart'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "receipt": {t:"чек", p:"chek", s:[{t:"чек",m:"Check",h:"the word 'check'"}]},
  "open": {t:"відчинено", p:"vidchyneno", s:[{t:"від",m:"Veed",h:"like 'feed' with V"},{t:"чи",m:"Chee",h:"like 'chi' the Greek letter"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"но",m:"No",h:"the word 'no'"}]},
  "closed": {t:"зачинено", p:"zachyneno", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"чи",m:"Chee",h:"like 'chi' the Greek letter"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"но",m:"No",h:"the word 'no'"}]},
  "market": {t:"ринок", p:"rynok", s:[{t:"ри",m:"Ry",h:"like 'ree'"},{t:"нок",m:"Nok",h:"the word 'knock'"}]},
  "supermarket": {t:"супермаркет", p:"supermarket", s:[{t:"су",m:"Soo",h:"the word 'Sue'"},{t:"пер",m:"Per",h:"the word 'per'"},{t:"мар",m:"Mar",h:"the word 'mar'"},{t:"кет",m:"Ket",h:"like 'ket' in market"}]},
  "bag": {t:"пакет", p:"paket", s:[{t:"па",m:"Pah",h:"like 'pa'"},{t:"кет",m:"Ket",h:"like 'ket' in market"}]},
  "souvenir": {t:"сувенір", p:"suvenir", s:[{t:"су",m:"Soo",h:"the word 'Sue'"},{t:"ве",m:"Veh",h:"like 'veh' in veteran"},{t:"нір",m:"Neer",h:"like 'near'"}]},
  "try on": {t:"приміряти", p:"prymeryaty", s:[{t:"при",m:"Pre",h:"like 'pre-' in preview"},{t:"мі",m:"Mee",h:"the word 'me'"},{t:"ря",m:"Rya",h:"'R' + 'yah'"},{t:"ти",m:"Ty",h:"like 'tea'"}]},

  // ===== DIRECTIONS (25) =====
  "left": {t:"ліворуч", p:"livoruch", s:[{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"руч",m:"Rooch",h:"like 'pooch' with R"}]},
  "right": {t:"праворуч", p:"pravoruch", s:[{t:"пра",m:"Prah",h:"like 'pra'"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"руч",m:"Rooch",h:"like 'pooch' with R"}]},
  "straight ahead": {t:"прямо", p:"pryamo", s:[{t:"пря",m:"Prya",h:"'P' + 'R' + 'yah'"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"}]},
  "stop": {t:"стоп", p:"stop", s:[{t:"стоп",m:"Stop",h:"the word 'stop'"}]},
  "here": {t:"тут", p:"tut", s:[{t:"тут",m:"Toot",h:"the word 'toot'"}]},
  "there": {t:"там", p:"tam", s:[{t:"там",m:"Tom",h:"the name 'Tom'"}]},
  "near": {t:"близько", p:"blyzko", s:[{t:"близь",m:"Blyz",h:"like 'bliss' with Z"},{t:"ко",m:"Koh",h:"like 'co' in company"}]},
  "far": {t:"далеко", p:"daleko", s:[{t:"да",m:"Dah",h:"the word 'dah'"},{t:"ле",m:"Leh",h:"like 'let' without T"},{t:"ко",m:"Koh",h:"like 'co' in company"}]},
  "map": {t:"карта", p:"karta", s:[{t:"кар",m:"Kar",h:"like 'car'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"}]},
  "street": {t:"вулиця", p:"vulytsya", s:[{t:"ву",m:"Voo",h:"like 'voo' in voodoo"},{t:"ли",m:"Ly",h:"like 'lee'"},{t:"ця",m:"Tsya",h:"'TS' + 'yah'"}]},
  "intersection": {t:"перехрестя", p:"perekhrestya", s:[{t:"пе",m:"Peh",h:"like 'peh' in pen"},{t:"ре",m:"Reh",h:"like 'ray'"},{t:"хрес",m:"Khres",h:"like 'crest' without T"},{t:"тя",m:"Tya",h:"'T' + 'yah'"}]},
  "bridge": {t:"міст", p:"mist", s:[{t:"міст",m:"Meest",h:"like 'feast' with M"}]},
  "river": {t:"річка", p:"richka", s:[{t:"річ",m:"Reech",h:"like 'reach'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "bus stop": {t:"зупинка автобуса", p:"zupynka avtobusa", s:[{t:"зу",m:"Zoo",h:"the word 'zoo'"},{t:"пин",m:"Pyn",h:"like 'pin'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"ав",m:"Av",h:"like 'av' in have"},{t:"то",m:"Toh",h:"like 'toe'"},{t:"бу",m:"Boo",h:"the word 'boo'"},{t:"са",m:"Sah",h:"like 'sah'"}]},
  "train station": {t:"залізничний вокзал", p:"zaliznychnyi vokzal", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"ліз",m:"Leez",h:"like 'lease'"},{t:"нич",m:"Nych",h:"like 'niche'"},{t:"ний",m:"Nyi",h:"like 'knee'"},{t:"вок",m:"Vok",h:"like 'voc' in vocal"},{t:"зал",m:"Zal",h:"like 'pal' with Z"}]},
  "airport": {t:"аеропорт", p:"aeroport", s:[{t:"а",m:"Ah",h:"the word 'ah'"},{t:"е",m:"Eh",h:"the word 'eh'"},{t:"ро",m:"Roh",h:"like 'row'"},{t:"порт",m:"Port",h:"the word 'port'"}]},
  "taxi": {t:"таксі", p:"taksi", s:[{t:"так",m:"Tack",h:"the word 'tack'"},{t:"сі",m:"See",h:"the word 'see'"}]},
  "metro": {t:"метро", p:"metro", s:[{t:"мет",m:"Met",h:"the word 'met'"},{t:"ро",m:"Roh",h:"like 'row'"}]},
  "how do i get to": {t:"як дістатися до", p:"yak distatysya do", s:[{t:"як",m:"Yak",h:"the animal 'yak'"},{t:"діс",m:"Dees",h:"like 'this' with D"},{t:"та",m:"Tah",h:"like 'ta' for thanks"},{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"},{t:"до",m:"Doh",h:"the word 'dough'"}]},
  "i'm looking for": {t:"я шукаю", p:"ya shukayu", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"шу",m:"Shoo",h:"the word 'shoo'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"ю",m:"Yu",h:"the word 'you'"}]},
  "turn left": {t:"поверніть ліворуч", p:"povernit livoruch", s:[{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"вер",m:"Ver",h:"like 'ver' in very"},{t:"ніть",m:"Neet",h:"like 'neat'"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"руч",m:"Rooch",h:"like 'pooch' with R"}]},
  "turn right": {t:"поверніть праворуч", p:"povernit pravoruch", s:[{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"вер",m:"Ver",h:"like 'ver' in very"},{t:"ніть",m:"Neet",h:"like 'neat'"},{t:"пра",m:"Prah",h:"like 'pra'"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"руч",m:"Rooch",h:"like 'pooch' with R"}]},
  "entrance": {t:"вхід", p:"vkhid", s:[{t:"вхід",m:"Vkheed",h:"'V' + 'heed'"}]},
  "exit": {t:"вихід", p:"vykhid", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"хід",m:"Kheed",h:"like 'heed'"}]},
  "ticket": {t:"квиток", p:"kvytok", s:[{t:"кви",m:"Kvy",h:"'K' + 'vee'"},{t:"ток",m:"Tok",h:"like 'talk' without L"}]},

  // ===== ACCOMMODATION (15) =====
  "hotel": {t:"готель", p:"hotel", s:[{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"тель",m:"Tel",h:"like 'tell'"}]},
  "room": {t:"кімната", p:"kimnata", s:[{t:"кім",m:"Keem",h:"like 'seem' with K"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"}]},
  "bed": {t:"ліжко", p:"lizhko", s:[{t:"ліж",m:"Leezh",h:"like 'lease' with ZH"},{t:"ко",m:"Koh",h:"like 'co' in company"}]},
  "bathroom": {t:"ванна кімната", p:"vanna kimnata", s:[{t:"ван",m:"Van",h:"the word 'van'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"кім",m:"Keem",h:"like 'seem' with K"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"}]},
  "key": {t:"ключ", p:"klyuch", s:[{t:"ключ",m:"Klyooch",h:"'K' + 'L' + 'ooch'"}]},
  "reservation": {t:"бронювання", p:"bronyuvannya", s:[{t:"бро",m:"Broh",h:"like 'bro'"},{t:"ню",m:"Nyu",h:"like 'new'"},{t:"ван",m:"Van",h:"the word 'van'"},{t:"ня",m:"Nya",h:"like 'nyah'"}]},
  "check in": {t:"заселитися", p:"zaselytysya", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"се",m:"Seh",h:"like 'set' without T"},{t:"ли",m:"Ly",h:"like 'lee'"},{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"}]},
  "check out": {t:"виселитися", p:"vyselytysya", s:[{t:"ви",m:"Vy",h:"like 'vee'"},{t:"се",m:"Seh",h:"like 'set' without T"},{t:"ли",m:"Ly",h:"like 'lee'"},{t:"ти",m:"Ty",h:"like 'tea'"},{t:"ся",m:"Sya",h:"'S' + 'yah'"}]},
  "hot water": {t:"гаряча вода", p:"haryacha voda", s:[{t:"га",m:"Hah",h:"like 'ha'"},{t:"ря",m:"Rya",h:"'R' + 'yah'"},{t:"ча",m:"Cha",h:"like 'cha' for tea"},{t:"во",m:"Voh",h:"like 'vow' without W"},{t:"да",m:"Dah",h:"the word 'dah'"}]},
  "towel": {t:"рушник", p:"rushnyk", s:[{t:"руш",m:"Roosh",h:"like 'push' with R"},{t:"ник",m:"Nyk",h:"like 'nick'"}]},
  "air conditioning": {t:"кондиціонер", p:"kondytsioner", s:[{t:"кон",m:"Kon",h:"like 'con'"},{t:"ди",m:"Dy",h:"like 'dee'"},{t:"ці",m:"Tsee",h:"like 'sea' with TS"},{t:"о",m:"Oh",h:"the word 'oh'"},{t:"нер",m:"Ner",h:"like 'nerd' without D"}]},
  "wifi": {t:"вай-фай", p:"vai-fai", s:[{t:"вай",m:"Vai",h:"like 'vie'"},{t:"фай",m:"Fai",h:"like 'fie'"}]},
  "elevator": {t:"ліфт", p:"lift", s:[{t:"ліфт",m:"Leeft",h:"the word 'lift'"}]},
  "floor": {t:"поверх", p:"poverkh", s:[{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"верх",m:"Verkh",h:"like 'verse' without SE"}]},
  "one night": {t:"одна ніч", p:"odna nich", s:[{t:"од",m:"Od",h:"like 'odd'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"ніч",m:"Neech",h:"like 'beach' with N"}]},

  // ===== COMMUNICATION (15) =====
  "i don't speak ukrainian": {t:"я не розмовляю українською", p:"ya ne rozmovlyayu ukrayinskoyu", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"роз",m:"Roz",h:"the name 'Roz'"},{t:"мов",m:"Mov",h:"like 'move' without E"},{t:"ля",m:"Lya",h:"like 'lia'"},{t:"ю",m:"Yu",h:"the word 'you'"},{t:"у",m:"Oo",h:"like 'oo' in moon"},{t:"кра",m:"Krah",h:"like 'cra' in craft"},{t:"їн",m:"Yeen",h:"like 'keen' with Y"},{t:"ською",m:"Skoyu",h:"'sko' + 'you'"}]},
  "repeat please": {t:"повторіть будь ласка", p:"povtorit bud laska", s:[{t:"пов",m:"Pov",h:"like 'pov'"},{t:"то",m:"Toh",h:"like 'toe'"},{t:"ріть",m:"Reet",h:"like 'meet' with R"},{t:"будь",m:"Bood",h:"like 'good' with B"},{t:"лас",m:"Las",h:"like 'Las' Vegas"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "write it down": {t:"запишіть це", p:"zapyshit tse", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"пи",m:"Py",h:"like 'pea'"},{t:"шіть",m:"Sheet",h:"the word 'sheet'"},{t:"це",m:"Tseh",h:"like 'tseh'"}]},
  "what does this mean": {t:"що це означає", p:"shcho tse oznachaye", s:[{t:"що",m:"Shcho",h:"like 'show' + 'cho'"},{t:"це",m:"Tseh",h:"like 'tseh'"},{t:"о",m:"Oh",h:"the word 'oh'"},{t:"зна",m:"Znah",h:"'Z' + 'nah'"},{t:"ча",m:"Cha",h:"like 'cha' for tea"},{t:"є",m:"Yeh",h:"the word 'yeah'"}]},
  "telephone": {t:"телефон", p:"telefon", s:[{t:"те",m:"Teh",h:"like 'teh' in tech"},{t:"ле",m:"Leh",h:"like 'let' without T"},{t:"фон",m:"Fon",h:"the word 'phone'"}]},
  "internet": {t:"інтернет", p:"internet", s:[{t:"ін",m:"Een",h:"like 'keen' without K"},{t:"тер",m:"Ter",h:"like 'tear'"},{t:"нет",m:"Net",h:"the word 'net'"}]},
  "email": {t:"електронна пошта", p:"elektronna poshta", s:[{t:"е",m:"Eh",h:"the word 'eh'"},{t:"лек",m:"Lek",h:"like 'leck'"},{t:"трон",m:"Tron",h:"like 'Tron'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"пош",m:"Posh",h:"the word 'posh'"},{t:"та",m:"Tah",h:"like 'ta' for thanks"}]},
  "i need help": {t:"мені потрібна допомога", p:"meni potribna dopomoha", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"тріб",m:"Treeb",h:"like 'tree' + 'B'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"до",m:"Doh",h:"the word 'dough'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"га",m:"Hah",h:"like 'ha'"}]},
  "what time is it": {t:"котра година", p:"kotra hodyna", s:[{t:"кот",m:"Kot",h:"like 'cot'"},{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"ди",m:"Dy",h:"like 'dee'"},{t:"на",m:"Nah",h:"the word 'nah'"}]},
  "today": {t:"сьогодні", p:"sohodni", s:[{t:"сьо",m:"Syo",h:"like 'so' with Y"},{t:"год",m:"Hod",h:"like 'hod'"},{t:"ні",m:"Knee",h:"the word 'knee'"}]},
  "tomorrow": {t:"завтра", p:"zavtra", s:[{t:"зав",m:"Zav",h:"like 'have' with Z"},{t:"тра",m:"Trah",h:"like 'tra' in travel"}]},
  "yesterday": {t:"вчора", p:"vchora", s:[{t:"вчо",m:"Vcho",h:"'V' + 'cho'"},{t:"ра",m:"Rah",h:"the word 'rah'"}]},
  "wait": {t:"зачекайте", p:"zachekajte", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"че",m:"Cheh",h:"like 'check' without CK"},{t:"кай",m:"Kai",h:"like 'kai'"},{t:"те",m:"Teh",h:"like 'teh' in tech"}]},
  "come here": {t:"ідіть сюди", p:"idit syudy", s:[{t:"і",m:"Ee",h:"the letter 'E'"},{t:"діть",m:"Deet",h:"like 'deed' with T"},{t:"сю",m:"Syu",h:"'S' + 'you'"},{t:"ди",m:"Dy",h:"like 'dee'"}]},
  "i am a tourist": {t:"я турист", p:"ya turyst", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"рист",m:"Ryst",h:"like 'wrist'"}]},

  // ===== HEALTH (10) =====
  "i have a headache": {t:"у мене болить голова", p:"u mene bolyt holova", s:[{t:"у",m:"Oo",h:"like 'oo' in moon"},{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"бо",m:"Boh",h:"like 'bow'"},{t:"лить",m:"Lyt",h:"like 'lit'"},{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"ло",m:"Loh",h:"like 'low'"},{t:"ва",m:"Vah",h:"like 'va' in valet"}]},
  "i have a fever": {t:"у мене температура", p:"u mene temperatura", s:[{t:"у",m:"Oo",h:"like 'oo' in moon"},{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"не",m:"Neh",h:"like 'net' without T"},{t:"тем",m:"Tem",h:"like 'tem' in tempo"},{t:"пе",m:"Peh",h:"like 'peh' in pen"},{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"ту",m:"Too",h:"the word 'too'"},{t:"ра",m:"Rah",h:"the word 'rah'"}]},
  "i need medicine": {t:"мені потрібні ліки", p:"meni potribni liky", s:[{t:"ме",m:"Meh",h:"like 'met' without T"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"тріб",m:"Treeb",h:"like 'tree' + 'B'"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"ки",m:"Ky",h:"like 'key'"}]},
  "dentist": {t:"стоматолог", p:"stomatoloh", s:[{t:"сто",m:"Stoh",h:"like 'stow'"},{t:"ма",m:"Mah",h:"like 'ma'"},{t:"то",m:"Toh",h:"like 'toe'"},{t:"лог",m:"Loh",h:"like 'log'"}]},
  "allergic": {t:"алергія", p:"alerhiya", s:[{t:"а",m:"Ah",h:"the word 'ah'"},{t:"лер",m:"Ler",h:"like 'lair'"},{t:"гі",m:"Hee",h:"like 'he'"},{t:"я",m:"Ya",h:"the word 'yah'"}]},
  "it hurts here": {t:"тут болить", p:"tut bolyt", s:[{t:"тут",m:"Toot",h:"the word 'toot'"},{t:"бо",m:"Boh",h:"like 'bow'"},{t:"лить",m:"Lyt",h:"like 'lit'"}]},
  "medicine": {t:"ліки", p:"liky", s:[{t:"лі",m:"Lee",h:"the name 'Lee'"},{t:"ки",m:"Ky",h:"like 'key'"}]},
  "i'm pregnant": {t:"я вагітна", p:"ya vahitna", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"ва",m:"Vah",h:"like 'va' in valet"},{t:"гіт",m:"Heet",h:"like 'heat'"},{t:"на",m:"Nah",h:"the word 'nah'"}]},
  "hospital emergency": {t:"невідкладна допомога", p:"nevidkladna dopomoha", s:[{t:"не",m:"Neh",h:"like 'net' without T"},{t:"від",m:"Veed",h:"like 'feed' with V"},{t:"клад",m:"Klad",h:"like 'clad'"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"до",m:"Doh",h:"the word 'dough'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"мо",m:"Moh",h:"like 'mow' the lawn"},{t:"га",m:"Hah",h:"like 'ha'"}]},
  "insurance": {t:"страхування", p:"strakhuvannya", s:[{t:"стра",m:"Strah",h:"like 'stra' in strap"},{t:"ху",m:"Khoo",h:"like 'who'"},{t:"ван",m:"Van",h:"the word 'van'"},{t:"ня",m:"Nya",h:"like 'nyah'"}]},

  // ===== TIME (10) =====
  "morning": {t:"ранок", p:"ranok", s:[{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"нок",m:"Nok",h:"the word 'knock'"}]},
  "afternoon": {t:"день", p:"den", s:[{t:"день",m:"Den",h:"the word 'den'"}]},
  "evening": {t:"вечір", p:"vechir", s:[{t:"ве",m:"Veh",h:"like 'veh' in veteran"},{t:"чір",m:"Cheer",h:"the word 'cheer'"}]},
  "night": {t:"ніч", p:"nich", s:[{t:"ніч",m:"Neech",h:"like 'beach' with N"}]},
  "now": {t:"зараз", p:"zaraz", s:[{t:"за",m:"Zah",h:"'Z' + 'ah'"},{t:"раз",m:"Raz",h:"like 'raz' in raspberry"}]},
  "later": {t:"пізніше", p:"piznishe", s:[{t:"піз",m:"Peez",h:"like 'peas' with Z"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"ше",m:"Sheh",h:"like 'shed' without D"}]},
  "early": {t:"рано", p:"rano", s:[{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "late": {t:"пізно", p:"pizno", s:[{t:"піз",m:"Peez",h:"like 'peas' with Z"},{t:"но",m:"No",h:"the word 'no'"}]},
  "what day is today": {t:"який сьогодні день", p:"yakyi sohodni den", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"кий",m:"Kyi",h:"like 'key'"},{t:"сьо",m:"Syo",h:"like 'so' with Y"},{t:"год",m:"Hod",h:"like 'hod'"},{t:"ні",m:"Knee",h:"the word 'knee'"},{t:"день",m:"Den",h:"the word 'den'"}]},
  "week": {t:"тиждень", p:"tyzhden", s:[{t:"тиж",m:"Tyzh",h:"like 'tish' with ZH"},{t:"день",m:"Den",h:"the word 'den'"}]},

  // ===== WEATHER (10) =====
  "it's hot": {t:"спекотно", p:"spekotno", s:[{t:"спе",m:"Speh",h:"like 'spell' without LL"},{t:"кот",m:"Kot",h:"like 'cot'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "it's cold": {t:"холодно", p:"kholodno", s:[{t:"хо",m:"Kho",h:"like 'ho'"},{t:"лод",m:"Lod",h:"like 'laud'"},{t:"но",m:"No",h:"the word 'no'"}]},
  "rain": {t:"дощ", p:"doshch", s:[{t:"дощ",m:"Doshch",h:"like 'dose' + 'ch'"}]},
  "snow": {t:"сніг", p:"snih", s:[{t:"сніг",m:"Sneeh",h:"like 'sneeze' without ZE"}]},
  "sun": {t:"сонце", p:"sontse", s:[{t:"сон",m:"Son",h:"the word 'son'"},{t:"це",m:"Tseh",h:"like 'tseh'"}]},
  "wind": {t:"вітер", p:"viter", s:[{t:"ві",m:"Vee",h:"the word 'vee'"},{t:"тер",m:"Ter",h:"like 'tear'"}]},
  "cloudy": {t:"хмарно", p:"khmarno", s:[{t:"хмар",m:"Khmar",h:"like 'mar' with KH"},{t:"но",m:"No",h:"the word 'no'"}]},
  "umbrella": {t:"парасолька", p:"parasolka", s:[{t:"па",m:"Pah",h:"like 'pa'"},{t:"ра",m:"Rah",h:"the word 'rah'"},{t:"соль",m:"Sol",h:"like 'sol' the note"},{t:"ка",m:"Kah",h:"like 'ka' in karate"}]},
  "what's the weather like": {t:"яка погода", p:"yaka pohoda", s:[{t:"я",m:"Ya",h:"the word 'yah'"},{t:"ка",m:"Kah",h:"like 'ka' in karate"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"да",m:"Dah",h:"the word 'dah'"}]},
  "beautiful weather": {t:"гарна погода", p:"harna pohoda", s:[{t:"гар",m:"Har",h:"like 'har' in harbor"},{t:"на",m:"Nah",h:"the word 'nah'"},{t:"по",m:"Poh",h:"like 'Po' the river"},{t:"го",m:"Hoh",h:"like 'hoe'"},{t:"да",m:"Dah",h:"the word 'dah'"}]}
};
